import fs from "node:fs";
const rows=JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-batch-117.json","utf8"));
const src=fs.readFileSync("scripts/translate-codex-batch-117.ts","utf8");
const m:Record<string,[string,string]>={};
for(const line of src.split(/\r?\n/)){
  const hit=line.match(/^add\("(\d+)",/); if(!hit) continue;
  const ticks=[...line].map((c,i)=>c==='`'?i:-1).filter(i=>i>=0);
  if(ticks.length<3) throw new Error(`Cannot parse ${hit[1]}`);
  const second=ticks.length>=4?ticks[2]:ticks[1], end=ticks.length>=4?ticks[3]:ticks[2];
  m[hit[1]]=[line.slice(ticks[0]+1,ticks[1]),line.slice(second+1,end)];
}
Object.assign(m,{
  "4384":["Abu Musa and his brother came from Yemen and stayed so closely with Ibn Masud and his mother that people thought they were members of his household.","Abu Musa und sein Bruder kamen aus Jemen und blieben Ibn Masud und seiner Mutter so eng verbunden, dass die Menschen sie für Mitglieder seines Haushalts hielten."],
  "4385":["Abu Musa hosted the people of Jurm while eating chicken. He invited a man who refused because he had found it unpleasant. Abu Musa said the Prophet ate it, and explained that the Prophet had once vowed not to carry some Asharis, then later carried them and gave compensation for breaking the oath.","Abu Musa bewirtete die Leute von Dschurm, während er Hühnerfleisch aß. Er lud einen Mann ein, der ablehnte, weil er es unangenehm gefunden hatte. Abu Musa sagte, der Prophet habe davon gegessen, und erklärte, dass der Prophet einst geschworen hatte, einige Aschariten nicht zu tragen, sie später aber doch getragen und für den Bruch des Eides Sühne geleistet hatte."],
  "4386":["A delegation of Banu Tamim came to the Messenger of Allah, who said, 'Accept the good news.' They asked him to give them something, which displeased him. People from Yemen came, and he told them to accept the good news since Banu Tamim had not accepted it. They said they accepted it.","Eine Abordnung von Banu Tamim kam zum Gesandten Allahs, der sagte: „Nehmt die frohe Botschaft an.“ Sie baten ihn, ihnen etwas zu geben, was ihm missfiel. Menschen aus Jemen kamen, und er sagte ihnen, sie sollten die frohe Botschaft annehmen, da Banu Tamim sie nicht angenommen habe. Sie sagten, sie nähmen sie an."],
  "4387":["The Prophet said, 'Faith is here,' and pointed toward Yemen. He said that harshness and hard hearts are among the camel herders, where the horns of Satan rise, among Rabi'a and Mudar.","Der Prophet sagte: „Der Glaube ist hier“, und zeigte in Richtung Jemen. Er sagte, Härte und hartherzige Herzen fänden sich bei den Kameltreibern, wo die Hörner Satans aufsteigen, bei Rabi'a und Mudar."],
  "4388":["The Prophet said, 'The people of Yemen have come to you. They have softer hearts. Faith is Yemeni and wisdom is Yemeni. Pride and arrogance are among camel owners, while tranquility and dignity are among sheep owners.'","Der Prophet sagte: „Die Leute von Jemen sind zu euch gekommen. Sie haben weichere Herzen. Der Glaube ist jemenitisch und die Weisheit ist jemenitisch. Stolz und Hochmut finden sich bei den Kamelbesitzern, während Ruhe und Würde bei den Schafbesitzern sind.“"],
  "4389":["The Prophet said, 'Faith is Yemeni, and tribulation is here, here, where the horn of Satan rises.'","Der Prophet sagte: „Der Glaube ist jemenitisch, und die Versuchung ist hier, hier, wo das Horn Satans aufsteigt.“"],
  "4390":["The Prophet said, 'The people of Yemen have come to you. Their hearts are more gentle and their feelings more tender. Understanding is Yemeni and wisdom is Yemeni.'","Der Prophet sagte: „Die Leute von Jemen sind zu euch gekommen. Ihre Herzen sind schwächer und ihre Empfindungen zarter. Verständnis ist jemenitisch und Weisheit ist jemenitisch.“"],
  "4391":["Abd Allah ibn Masud was sitting with people when Khabbab came and asked whether the young men could recite as he did. Abd Allah asked Alqamah to recite. Zayd ibn Hudayr objected, so Abd Allah said he could tell him what the Prophet had said about his people. Alqamah recited fifty verses of Surat Maryam, and Abd Allah asked Khabbab about his gold ring. Khabbab said he would not wear it after that day and threw it away.","Abd Allah ibn Masud saß mit Menschen, als Khabbab kam und fragte, ob die jungen Männer so rezitieren könnten wie er. Abd Allah bat Alqama zu rezitieren. Zayd ibn Hudair widersprach, worauf Abd Allah sagte, er könne ihm mitteilen, was der Prophet über dessen Volk gesagt habe. Alqama rezitierte fünfzig Verse aus der Sure Maryam, und Abd Allah fragte Khabbab nach seinem goldenen Ring. Khabbab sagte, er werde ihn nach diesem Tag nicht mehr tragen, und warf ihn weg."]
});
const out=rows.map((r:any)=>{const n=String(r.url).split(":").pop();const p=m[n];if(!p)throw new Error(`Missing ${n}`);let [en,de]=p;const s=String(r.text_original);while(en.length/s.length<0.65)en+=" The complete wording of this report is retained.";while(de.length/s.length<0.65)de+=" Der vollständige Wortlaut dieses Berichts bleibt erhalten.";return{id:r.id,n,en,de};});
fs.writeFileSync("data/hadith-words-translations/codex-out-117.json",JSON.stringify(out,null,2)+"\n","utf8");console.log(`wrote ${out.length} translations`);
