import fs from "node:fs";
type Kind = "prophet_words" | "narration" | "companion_words" | "dialogue" | "reference_only" | "unclear";
const batch = JSON.parse(fs.readFileSync("data/hadith-split/batch-159.json", "utf8"));
const kinds: Kind[] = ["dialogue","dialogue","dialogue","prophet_words","prophet_words","dialogue","prophet_words","narration","dialogue","narration","companion_words","prophet_words","prophet_words","narration","prophet_words","prophet_words","prophet_words","narration","prophet_words","prophet_words","prophet_words","prophet_words","prophet_words","prophet_words","prophet_words","dialogue","prophet_words","prophet_words","dialogue","dialogue","prophet_words","prophet_words","dialogue","dialogue","companion_words","companion_words","dialogue","prophet_words","dialogue","dialogue","dialogue","dialogue","prophet_words","dialogue","prophet_words","dialogue","prophet_words","prophet_words","dialogue","prophet_words","companion_words","dialogue","dialogue","dialogue","prophet_words","dialogue","dialogue","dialogue","dialogue","dialogue"];
const marks:any[]=batch.map((x:any,i:number)=>({id:x.id,url:x.url,start:null as string|null,kind:kinds[i]}));
function cm(t:string){const c:string[]=[],m:number[]=[];for(let i=0;i<t.length;i++){if(/[\u064b-\u065f\u0670\u200e\u200f]/.test(t[i]))continue;c.push(t[i]);m.push(i)}return{c:c.join(""),m}}
const strip=(s:string)=>s.replace(/[\u064b-\u065f\u0670]/g,"");
function loc(t:string,n:string){const {c,m}=cm(t),p=c.indexOf(strip(n));if(p<0)throw new Error(`Could not locate: ${n}`);return t.slice(m[p],m[p]+Math.min(100,t.length-m[p]))}
function st(i:number,n:string){marks[i].start=loc(batch[i].text_original,n)}
function tail(i:number,n:string){marks[i].tail_start=loc(batch[i].text_original,n)}
function tailRe(i:number,r:RegExp){const m=strip(batch[i].text_original).match(r);if(!m)throw new Error(`Could not locate tail at ${i}`);tail(i,m[0])}
const s:Array<[number,string]> = [
 [0,"صاحب رسول الله صلى الله عليه وسلم"],[1,"أن عليا قال كانت لي شارف"],[2,"استأذنوا رسول الله صلى الله عليه وسلم"],[3,"قال قال رسول الله صلى الله عليه وسلم يوم بدر"],[4,"أن النبي صلى الله عليه وسلم قال في أسارى بدر"],[5,"قال بعث رسول الله صلى الله عليه وسلم إلى أبي رافع"],[6,"قال قال النبي صلى الله عليه وسلم يوم أحد"],[7,"قال صلى رسول الله صلى الله عليه وسلم على قتلى أحد"],[8,"قال قال رجل للنبي صلى الله عليه وسلم يوم أحد"],[9,"قال لما خرج النبي صلى الله عليه وسلم إلى أحد"],
 [10,"يقول نثل لي النبي صلى الله عليه وسلم كنانته"],[11,"لقد جمع لي رسول الله صلى الله عليه وسلم"],[12,"قال ما سمعت النبي صلى الله عليه وسلم جمع أبويه"],[13,"قالت لعروة يا ابن أختي"],[14,"طلع له أحد"],[15,"أن النبي صلى الله عليه وسلم خرج يوما"],[16,"قال قنت النبي صلى الله عليه وسلم بعد الركوع"],[17,"يقول خرج رسول الله صلى الله عليه وسلم إلى الخندق"],[18,"قال جعل المهاجرون والأنصار يحفرون الخندق"],[19,"قال قال النبي صلى الله عليه وسلم يوم الأحزاب"],
[20,"يقول سمعت النبي صلى الله عليه وسلم يقول"],[21,"عن النبي صلى الله عليه وسلم أنه قال يوم الخندق"],[22,"أن رسول الله صلى الله عليه وسلم كان يقول"],[23,"يقول دعا رسول الله صلى الله عليه وسلم على الأحزاب"],[24,"أن رسول الله صلى الله عليه وسلم كان إذا قفل"],[25,"قالت لما رجع النبي صلى الله عليه وسلم من الخندق"],[26,"قال قال النبي صلى الله عليه وسلم يوم الأحزاب"],[27,"قال قال النبي صلى الله عليه وسلم لحسان"],[28,"أنه قال دخلت المسجد"],[29,"قال غزونا مع رسول الله صلى الله عليه وسلم غزوة نجد"],
 [30,"قال ذهبت أسب حسان عند عائشة"],[31,"قال قال لنا رسول الله صلى الله عليه وسلم يوم الحديبية"],[32,"أن رسول الله صلى الله عليه وسلم رآه"],[33,"أن رسول الله صلى الله عليه وسلم كان يسير"],[34,"حدثنا موسى بن إسماعيل"],[35,"قال أتى على النبي صلى الله عليه وسلم زمن الحديبية"],[36,"قال كنا مع رسول الله صلى الله عليه وسلم بالحديبية"],[37,"يقول خرجت قبل أن يؤذن"],[38,"قال صلى النبي صلى الله عليه وسلم الصبح"],[39,"تخلف عن النبي صلى الله عليه وسلم في خيبر"],
[40,"قال قدمنا خيبر"],[41,"إلى النبي صلى الله عليه وسلم فقلنا أعطيت بني المطلب"],[42,"قال أمر رسول الله صلى الله عليه وسلم أسامة"],[43,"أن النبي صلى الله عليه وسلم نعى زيدا"],[44,"يقول بعثنا رسول الله صلى الله عليه وسلم إلى الحرقة"],[45,"قال قال رسول الله صلى الله عليه وسلم حين أراد حنينا"],[46,"أن النبي صلى الله عليه وسلم دخل مكة يوم الفتح"],[47,"قال دخل النبي صلى الله عليه وسلم مكة يوم الفتح"],[48,"قالت كان النبي صلى الله عليه وسلم يقول في ركوعه"],[49,"أنه قال لعمرو بن سعيد"],
[50,"أنه سمع رسول الله صلى الله عليه وسلم يقول عام الفتح"],[51,"قال قال لي أبو قلابة"],[52,"قال أما النبي صلى الله عليه وسلم فلا"],[53,"قال لما قسم النبي صلى الله عليه وسلم قسمة حنين"],[54,"قال لما كان يوم حنين آثر النبي صلى الله عليه وسلم"],[55,"قال بعث النبي صلى الله عليه وسلم خالد بن الوليد"],[56,"قال بعث النبي صلى الله عليه وسلم سرية"],[57,"قال بعث رسول الله صلى الله عليه وسلم أبا موسى"],[58,"قال قال رسول الله صلى الله عليه وسلم لمعاذ"],[59,"يقول غزونا جيش الخبط"]];
for(const [i,n] of s)st(i,n);
tailRe(0,/\u064a\u0631\u064a\u062f \u0627\u0644\u062a\u0645\u0627\u062b\u064a\u0644/);
tailRe(4,/\u0648\u0642\u0627\u0644 \u0627\u0644\u0644\u064a\u062b/);
tailRe(31,/\u062a\u0627\u0628\u0639\u0647 \u0627\u0644\u0623\u0639\u0645\u0634/);
tailRe(35,/\u0642\u0627\u0644 \u0623\u064a\u0648\u0628/);
tailRe(46,/\u0642\u0627\u0644 \u0645\u0627\u0644\u0643/);
tailRe(58,/\u0642\u0627\u0644 \u0623\u0628\u0648 \u0639\u0628\u062f \u0627\u0644\u0644\u0647/);
fs.writeFileSync("data/hadith-split/marks-159.json",JSON.stringify(marks,null,2)+"\n","utf8");console.log("Wrote 60 marks to data/hadith-split/marks-159.json");
