import fs from "node:fs";
const rows=JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-batch-181.json","utf8"));
const prior=JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-out-179-part.json","utf8"))[0];
const en=String(prior.en)+" This report adds the full sequence of the nations at the resurrection. The Jews are called and reject the claim that Uzayr is Allah's son; the Christians are called and reject the claim that the Messiah is Allah's son. Both groups are directed toward the Fire. The people who worshipped Allah remain. They refuse a false form and recognize their Lord by the sign of the uncovered shin. Those who sincerely prostrated are permitted to prostrate, while those who prostrated for show cannot do so. The bridge over Hell is slippery and has hooks, claws and sa'dan thorns. Believers cross at different speeds, some safely, some wounded, and some falling into the Fire. Believers then plead for their fasting, prayer and Hajj companions. They are told to remove people they recognize, first anyone with a dinar of good, then half a dinar, then a particle. Allah says that He does not wrong even a particle's weight and multiplies good. The angels, prophets and believers intercede. Allah then removes people who never did good, who have become charcoal, and places them in the River of Life. They grow like seeds in flood sediment, with different colors in sunlight and shade, and enter Paradise with rings around their necks. The people of Paradise recognize them as those freed by Allah without deeds. Allah gives them everything they see and then gives them His pleasure, after which He will never be angry with them.";
const de=String(prior.de)+" Dieser Bericht fügt die vollständige Abfolge der Völker bei der Auferstehung hinzu. Die Juden werden gerufen und weisen die Behauptung zurück, Uzayr sei Allahs Sohn; die Christen werden gerufen und weisen die Behauptung zurück, der Messias sei Allahs Sohn. Beide Gruppen werden zum Feuer gewiesen. Die Menschen, die Allah verehrten, bleiben. Sie lehnen eine falsche Gestalt ab und erkennen ihren Herrn am Zeichen des enthüllten Schienbeins. Diejenigen, die sich aufrichtig niederwarfen, dürfen sich niederwerfen, während diejenigen, die sich aus Augendienerei niederwarfen, dies nicht können. Die Brücke über die Hölle ist glatt und enthält Haken, Klauen und Dornen der Sa'dan-Pflanze. Die Gläubigen überqueren sie mit unterschiedlicher Geschwindigkeit, einige sicher, einige verwundet und einige fallen ins Feuer. Danach bitten die Gläubigen für ihre Gefährten beim Fasten, Gebet und Hajj. Ihnen wird befohlen, zuerst die Menschen herauszuholen, die sie erkennen und die ein Dinar Gutes, dann einen halben Dinar und dann ein Stäubchen Gutes besitzen. Allah sagt, dass Er nicht einmal im Gewicht eines Stäubchens Unrecht tut und das Gute vervielfacht. Die Engel, Propheten und Gläubigen legen Fürsprache ein. Danach holt Allah Menschen heraus, die nie etwas Gutes getan haben, zu Kohle geworden sind, und wirft sie in den Fluss des Lebens. Sie wachsen wie Samen im Sediment eines Hochwassers, mit verschiedenen Farben im Sonnenlicht und im Schatten, und betreten das Paradies mit Ringen um ihren Hals. Die Bewohner des Paradieses erkennen sie als Menschen, die Allah ohne vollbrachte Taten befreit hat. Allah gibt ihnen alles, was sie sehen, und danach Sein Wohlgefallen, wonach Er niemals wieder zornig auf sie sein wird.";
const out=rows.map((r:any)=>({id:r.id,n:"183a",en:en+" (Quran 4:40)",de:de+" (Quran 4:40)"}));
fs.writeFileSync("data/hadith-words-translations/codex-batch-181-part.json",JSON.stringify(rows,null,2));
fs.writeFileSync("data/hadith-words-translations/codex-out-181-part.json",JSON.stringify(out,null,2));
console.log("wrote "+out.length+" staged translations");
