import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-next.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:276a':{en:'Ishaq ibn Ibrahim al-Hanzali narrated to us. Abd al-Razzaq informed us. al-Thawri informed us, from Amr ibn Qays al-Mulai, from al-Hakam ibn Utayba, from al-Qasim ibn Mukhaimara, from Shurayh ibn Hani, who said: I came to Aisha to ask her about wiping over the leather socks. She said: You should ask Ibn Abi Talib, for he used to travel with the Messenger of Allah (peace be upon him). We asked him, and he said: The Messenger of Allah (peace be upon him) set three days and nights for the traveler, and one day and night for the resident. He said: Whenever Sufyan mentioned Amr, he praised him.',de:'Ishaq ibn Ibrahim al-Hanzali überlieferte uns. Abd al-Razzaq berichtete uns. al-Thawri berichtete uns, von Amr ibn Qays al-Mulai, von al-Hakam ibn Utayba, von al-Qasim ibn Mukhaimara, von Shurayh ibn Hani, der sagte: Ich kam zu Aisha, um sie über das Streichen über die Ledersocken zu fragen. Sie sagte: Du solltest Ibn Abi Talib fragen, denn er pflegte mit dem Gesandten Allahs (Friede sei auf ihm) zu reisen. Wir fragten ihn, und er sagte: Der Gesandte Allahs (Friede sei auf ihm) bestimmte für den Reisenden drei Tage und ihre Nächte und für den Ansässigen einen Tag und seine Nacht. Er sagte: Wenn Sufyan Amr erwähnte, lobte er ihn.'},
'https://sunnah.com/muslim:276b':{en:'Ishaq narrated to us. Zakariyya ibn Adi informed us, from Ubaydullah ibn Amr, from Zayd ibn Abi Unaysa, from al-Hakam, with this chain, with the same wording.',de:'Ishaq überlieferte uns. Zakariyya ibn Adi berichtete uns, von Ubaydullah ibn Amr, von Zayd ibn Abi Unaysa, von al-Hakam, mit dieser Überlieferungskette und demselben Wortlaut.'},
'https://sunnah.com/muslim:276c':{en:'Zuhayr ibn Harb narrated to me. Abu Muawiya narrated to us, from al-Amash, from al-Hakam, from al-Qasim ibn Mukhaimara, from Shurayh ibn Hani, who said: I asked Aisha about wiping over the leather socks. She said: Go to Ali, for he knows more about that than I do. I went to Ali, and he reported from the Prophet (peace be upon him) something like it.',de:'Zuhayr ibn Harb überlieferte mir. Abu Muawiya überlieferte uns, von al-Amash, von al-Hakam, von al-Qasim ibn Mukhaimara, von Shurayh ibn Hani, der sagte: Ich fragte Aisha über das Streichen über die Ledersocken. Sie sagte: Geh zu Ali, denn er weiß darüber mehr als ich. Ich ging zu Ali, und er berichtete vom Propheten (Friede sei auf ihm) etwas Ähnliches.'},
'https://sunnah.com/muslim:277':{en:'Muhammad ibn Abdullah ibn Numayr narrated to us. My father narrated to us. Sufyan narrated to us, from Alqama ibn Marthad. Muhammad ibn Hatim also narrated to me, and this is his wording: Yahya ibn Sa\'id narrated to us, from Sufyan, who said: Alqama ibn Marthad narrated to me, from Sulayman ibn Burayda, from his father, that the Prophet (peace be upon him) prayed the prayers on the day of the conquest with one wudu and wiped over his leather socks. Umar said to him: Today you have done something you did not used to do. He said: I did it deliberately, O Umar.',de:'Muhammad ibn Abdullah ibn Numayr überlieferte uns. Mein Vater überlieferte uns. Sufyan überlieferte uns, von Alqama ibn Marthad. Auch Muhammad ibn Hatim überlieferte mir, und dies ist sein Wortlaut: Yahya ibn Sa\'id überlieferte uns, von Sufyan, der sagte: Alqama ibn Marthad überlieferte mir, von Sulayman ibn Burayda, von dessen Vater, dass der Prophet (Friede sei auf ihm) am Tag der Eroberung die Gebete mit einer Wudu betete und über seine Ledersocken strich. Umar sagte zu ihm: Heute hast du etwas getan, was du sonst nicht zu tun pflegtest. Er sagte: Ich habe es absichtlich getan, o Umar.'},
'https://sunnah.com/muslim:278a':{en:'Nasr ibn Ali al-Jahdami and Hamid ibn Umar al-Bakrawi narrated to us. They said: Bishr ibn al-Mufaddal narrated to us, from Khalid, from Abdullah ibn Shaqiq, from Abu Hurayra, that the Prophet (peace be upon him) said: When one of you wakes from sleep, let him not dip his hand into the vessel until he washes it three times, for he does not know where his hand spent the night.',de:'Nasr ibn Ali al-Jahdami und Hamid ibn Umar al-Bakrawi überlieferten uns. Sie sagten: Bishr ibn al-Mufaddal überlieferte uns, von Khalid, von Abdullah ibn Shaqiq, von Abu Hurayra, dass der Prophet (Friede sei auf ihm) sagte: Wenn einer von euch aus dem Schlaf erwacht, soll er seine Hand nicht in das Gefäß tauchen, bevor er sie dreimal gewaschen hat, denn er weiß nicht, wo seine Hand die Nacht verbracht hat.'},
'https://sunnah.com/muslim:278b':{en:'Abu Kurayb and Abu Said al-Ashajj narrated to us. They said: Waki narrated to us. Abu Kurayb also narrated to us: Abu Muawiya narrated to us. Both narrated from al-Amash, from Abu Razin and Abu Salih, from Abu Hurayra. In the narration of Abu Muawiya it says: The Messenger of Allah (peace be upon him) said. In the narration of Waki it says: He attributed it to the Prophet, with the same wording.',de:'Abu Kurayb und Abu Said al-Ashajj überlieferten uns. Sie sagten: Waki überlieferte uns. Auch Abu Kurayb überlieferte uns: Abu Muawiya überlieferte uns. Beide überlieferten von al-Amash, von Abu Razin und Abu Salih, von Abu Hurayra. In der Überlieferung von Abu Muawiya heißt es: Der Gesandte Allahs (Friede sei auf ihm) sagte. In der Überlieferung von Waki heißt es: Er führte es auf den Propheten zurück, mit demselben Wortlaut.'},
'https://sunnah.com/muslim:278c':{en:'Abu Bakr ibn Abi Shayba, Amr al-Naqid, and Zuhayr ibn Harb narrated to us. They said: Sufyan ibn Uyayna narrated to us, from al-Zuhri, from Abu Salama. Muhammad ibn Rafi also narrated it to me: Abd al-Razzaq narrated to us. Ma\'mar informed us, from al-Zuhri, from Ibn al-Musayyab. Both narrated from Abu Hurayra, from the Prophet (peace be upon him), with the same wording.',de:'Abu Bakr ibn Abi Shayba, Amr al-Naqid und Zuhayr ibn Harb überlieferten uns. Sie sagten: Sufyan ibn Uyayna überlieferte uns, von al-Zuhri, von Abu Salama. Auch Muhammad ibn Rafi überlieferte ihn mir: Abd al-Razzaq überlieferte uns. Ma\'mar berichtete uns, von al-Zuhri, von Ibn al-Musayyab. Beide überlieferten von Abu Hurayra, vom Propheten (Friede sei auf ihm), mit demselben Wortlaut.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-211-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-211-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
