import fs from 'node:fs';

const rows: any[] = JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json', 'utf8'));
const tr: Record<string, { en: string; de: string }> = {
  'https://sunnah.com/muslim:340b': {
    en: 'Zuhayr ibn Harb narrated to us. Ruh ibn Ubada narrated to us. Zakariyya ibn Ishaq narrated to us. Amr ibn Dinar narrated to us. He said: I heard Jabir ibn Abdullah relate that the Messenger of Allah (peace be upon him) used to carry stones with them for the Kaaba, wearing his lower garment. His uncle Abbas said to him: O son of my brother, if you loosened your lower garment and put it on your shoulder under the stones. He said: So he loosened it and put it on his shoulder, and he fell unconscious. He said: After that day he was never seen naked.',
    de: 'Zuhayr ibn Harb überlieferte uns. Ruh ibn Ubada überlieferte uns. Zakariyya ibn Ishaq überlieferte uns. Amr ibn Dinar überlieferte uns. Er sagte: Ich hörte Jabir ibn Abdullah berichten, dass der Gesandte Allahs (Friede sei auf ihm) mit ihnen Steine für die Kaaba trug, während er sein Untergewand trug. Sein Onkel Abbas sagte zu ihm: O Sohn meines Bruders, wenn du dein Untergewand lösen und es unter den Steinen über deine Schulter legen würdest. Er sagte: Da löste er es und legte es über seine Schulter, worauf er ohnmächtig zu Boden fiel. Er sagte: Nach diesem Tag wurde er nie wieder nackt gesehen.'
  },
  'https://sunnah.com/muslim:341': {
    en: 'Said ibn Yahya al-Umawi narrated to us. My father narrated to me. Uthman ibn Hakim ibn Abbad ibn Hunayf al-Ansari narrated to us. Abu Umama ibn Sahl ibn Hunayf informed me, from al-Miswar ibn Makhrama, who said: I came carrying a heavy stone while I was wearing a light lower garment. My lower garment came loose while I had the stone with me, and I could not put it down until I had brought it to its place. The Messenger of Allah (peace be upon him) said: Go back to your garment, take it, and do not walk around naked.',
    de: 'Said ibn Yahya al-Umawi überlieferte uns. Mein Vater überlieferte mir. Uthman ibn Hakim ibn Abbad ibn Hunayf al-Ansari überlieferte uns. Abu Umama ibn Sahl ibn Hunayf berichtete mir, von al-Miswar ibn Makhrama, der sagte: Ich kam und trug einen schweren Stein, während ich ein leichtes Untergewand trug. Mein Untergewand löste sich, während ich den Stein bei mir hatte, und ich konnte ihn nicht ablegen, bis ich ihn an seinen Platz gebracht hatte. Der Gesandte Allahs (Friede sei auf ihm) sagte: Geh zu deinem Gewand zurück, nimm es, und geht nicht nackt umher.'
  },
  'https://sunnah.com/muslim:342': {
    en: 'Shayban ibn Farrukh and Abdullah ibn Muhammad ibn Asma al-Dubai narrated to us. They said: Mahdi, who was Ibn Maymun, narrated to us. Muhammad ibn Abdullah ibn Abi Yaqob narrated to us, from al-Hasan ibn Sad, the client of al-Hasan ibn Ali, from Abdullah ibn Jafar, who said: One day the Messenger of Allah (peace be upon him) seated me behind him and whispered a statement to me that I will not tell anyone. The thing he preferred to conceal himself behind when relieving himself was a target or a palm grove. Ibn Asma said in his hadith: He meant a palm wall.',
    de: 'Shayban ibn Farrukh und Abdullah ibn Muhammad ibn Asma al-Dubai überlieferten uns. Sie sagten: Mahdi, nämlich Ibn Maymun, überlieferte uns. Muhammad ibn Abdullah ibn Abi Yaqob überlieferte uns, von al-Hasan ibn Sad, dem Schutzbefohlenen von al-Hasan ibn Ali, von Abdullah ibn Jafar, der sagte: Eines Tages setzte mich der Gesandte Allahs (Friede sei auf ihm) hinter sich und flüsterte mir eine Aussage zu, die ich keinem Menschen erzählen werde. Das, hinter dem sich der Gesandte Allahs (Friede sei auf ihm) am liebsten verbarg, wenn er sich erleichterte, war ein Ziel oder ein Palmenhain. Ibn Asma sagte in seinem Hadith: Er meinte eine Palmenmauer.'
  },
  'https://sunnah.com/muslim:343a': {
    en: 'Yahya ibn Yahya, Yahya ibn Ayyub, Qutayba, and Ibn Hujr narrated to us. Yahya ibn Yahya said: He informed us, while the others said: Ismail, who was Ibn Jafar, narrated to us, from Sharik, meaning Ibn Abi Namir, from Abd al-Rahman ibn Abi Said al-Khudri, from his father, who said: I went out with the Messenger of Allah (peace be upon him) on Monday toward Quba. When we were in Banu Salim, the Messenger of Allah (peace be upon him) stopped at the door of Itban and called out to him. He came out dragging his lower garment. The Messenger of Allah (peace be upon him) said: We made the man hurry. Itban said: O Messenger of Allah, what do you say about a man who is made to hurry away from his wife but does not ejaculate? What is required of him? The Messenger of Allah (peace be upon him) said: Water is only due from water.',
    de: 'Yahya ibn Yahya, Yahya ibn Ayyub, Qutayba und Ibn Hujr überlieferten uns. Yahya ibn Yahya sagte: Er berichtete uns, während die anderen sagten: Ismail, nämlich Ibn Jafar, überlieferte uns, von Sharik, das heißt Ibn Abi Namir, von Abd al-Rahman ibn Abi Said al-Khudri, von dessen Vater, der sagte: Ich ging am Montag mit dem Gesandten Allahs (Friede sei auf ihm) nach Quba hinaus. Als wir bei den Banu Salim waren, blieb der Gesandte Allahs (Friede sei auf ihm) an der Tür von Itban stehen und rief ihn. Er kam heraus und schleifte sein Untergewand hinter sich her. Der Gesandte Allahs (Friede sei auf ihm) sagte: Wir haben den Mann zur Eile gebracht. Itban sagte: O Gesandter Allahs, was sagst du über einen Mann, der von seiner Frau weg zur Eile gebracht wird, aber nicht ejakuliert? Was ist ihm auferlegt? Der Gesandte Allahs (Friede sei auf ihm) sagte: Wasser ist nur aufgrund von Wasser erforderlich.'
  },
  'https://sunnah.com/muslim:343b': {
    en: 'Harun ibn Said al-Ayli narrated to us. Ibn Wahb narrated to us. Amr ibn al-Harith informed me, from Ibn Shihab, who related to him that Abu Salama ibn Abd al-Rahman related to him, from Abu Said al-Khudri, from the Prophet (peace be upon him), that he said: Water is only due from water.',
    de: 'Harun ibn Said al-Ayli überlieferte uns. Ibn Wahb überlieferte uns. Amr ibn al-Harith berichtete mir, von Ibn Shihab, der ihm überlieferte, dass Abu Salama ibn Abd al-Rahman ihm überlieferte, von Abu Said al-Khudri, vom Propheten (Friede sei auf ihm), dass er sagte: Wasser ist nur aufgrund von Wasser erforderlich.'
  },
  'https://sunnah.com/muslim:344': {
    en: 'Ubayd Allah ibn Muadh al-Anbari narrated to us. al-Mutamir narrated to us. My father narrated to us. Abu al-Ala ibn al-Shikhkhir narrated to us. He said: The Messenger of Allah (peace be upon him) used to abrogate some of his statements with others, just as the Quran abrogates some of its verses with others.',
    de: 'Ubayd Allah ibn Muadh al-Anbari überlieferte uns. al-Mutamir überlieferte uns. Mein Vater überlieferte uns. Abu al-Ala ibn al-Shikhkhir überlieferte uns. Er sagte: Der Gesandte Allahs (Friede sei auf ihm) pflegte manche seiner Aussagen durch andere aufzuheben, so wie der Quran manche seiner Verse durch andere aufhebt.'
  },
  'https://sunnah.com/muslim:345': {
    en: 'Abu Bakr ibn Abi Shaiba narrated to us. Ghundar narrated to us, from Shuba. And Muhammad ibn al-Muthanna and Ibn Bashshar narrated to us. They said: Muhammad ibn Jafar narrated to us. Shuba narrated to us, from al-Hakam, from Dhakwan, from Abu Said al-Khudri, that the Messenger of Allah (peace be upon him) passed by a man from the Ansar. He sent for him, and the man came out with water dripping from his head. He said: Perhaps we made you hurry. He said: Yes, O Messenger of Allah. He said: If you are made to hurry or if you are unable to ejaculate, then you do not have to perform ghusl, but you must perform wudu. Ibn Bashshar said: If you are made to hurry or if you are unable to ejaculate.',
    de: 'Abu Bakr ibn Abi Shaiba überlieferte uns. Ghundar überlieferte uns, von Shuba. Und Muhammad ibn al-Muthanna und Ibn Bashshar überlieferten uns. Sie sagten: Muhammad ibn Jafar überlieferte uns. Shuba überlieferte uns, von al-Hakam, von Dhakwan, von Abu Said al-Khudri, dass der Gesandte Allahs (Friede sei auf ihm) an einem Mann von den Ansar vorbeikam. Er ließ ihn rufen, und der Mann kam heraus, während Wasser von seinem Kopf tropfte. Er sagte: Vielleicht haben wir dich zur Eile gebracht. Er sagte: Ja, o Gesandter Allahs. Er sagte: Wenn du zur Eile gebracht wirst oder nicht ejakulierst, musst du keinen Ghusl verrichten, aber du musst Wudu verrichten. Ibn Bashshar sagte: Wenn du zur Eile gebracht wirst oder nicht ejakulierst.'
  }
};

const out = rows.filter((r) => tr[r.url]).map((r) => ({ ...r, ...tr[r.url] }));
if (out.length !== 7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-230-part.json', JSON.stringify(out, null, 2));
fs.writeFileSync('data/hadith-words-translations/codex-out-230-part.json', JSON.stringify(out, null, 2));
console.log(`wrote ${out.length} staged translations`);
