import fs from "node:fs";

type Raw = { id: string; url: string; text_original: string };
type Out = { id: string; n: number; en: string; de: string };

const input = "data/hadith-words-translations/codex-batch-026.json";
const output = "data/hadith-words-translations/codex-out-026.json";
const raw = JSON.parse(fs.readFileSync(input, "utf8")) as Raw[];

const translations: Record<number, [string, string]> = {
  2826: [
    "Abdullah ibn Yusuf narrated to us. Malik informed us, from Abu al-Zinad, from al-A'raj, from Abu Hurayra, may Allah be pleased with him, that the Messenger of Allah (peace be upon him) said: Allah laughs at two men, one of whom kills the other, yet both enter Paradise. One fights in the cause of Allah and is killed, then Allah accepts the killer's repentance and he is martyred.",
    "Abdullah ibn Yusuf überlieferte uns. Malik informierte uns, von Abu al-Zinad, von al-A'raj, von Abu Hurayra, möge Allah mit ihm zufrieden sein, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Allah lacht über zwei Männer, von denen einer den anderen tötet, während beide ins Paradies eintreten. Der eine kämpft auf Allahs Weg und wird getötet, dann nimmt Allah die Reue des Mörders an und dieser wird als Märtyrer getötet.",
  ],
  2827: [
    "Al-Humaydi narrated to us. Sufyan narrated to us. Al-Zuhri narrated to us. He said: Anbasa ibn Sa'id informed me, from Abu Hurayra, may Allah be pleased with him, who said: I came to the Messenger of Allah (peace be upon him) while he was at Khaybar, after they had conquered it, and I said: O Messenger of Allah, allot me a share. Some of Banu Sa'id ibn al-As said: Do not allot him a share, O Messenger of Allah. Abu Hurayra said: This is the killer of Ibn Qawqal. Ibn Sa'id ibn al-As said: How astonishing, a small creature dangling down upon us from a ram's chopping block, reproaching me for killing a Muslim man whom Allah honored by my hand and did not disgrace me by his hand. He said: I do not know whether he allotted him a share or did not allot him one. Sufyan said: Al-Sa'idi also narrated it to me, from his grandfather, from Abu Hurayra. Abu Abdullah said: Al-Sa'idi was Amr ibn Yahya ibn Sa'id ibn Amr ibn Sa'id ibn al-As.",
    "Al-Humaydi überlieferte uns. Sufyan überlieferte uns. Al-Zuhri überlieferte uns. Er sagte: Anbasa ibn Sa'id berichtete mir, von Abu Hurayra, möge Allah mit ihm zufrieden sein, der sagte: Ich kam zum Gesandten Allahs (Friede sei auf ihm), während er sich in Khaybar befand, nachdem sie es erobert hatten, und sagte: O Gesandter Allahs, teile mir einen Anteil zu. Einige von Banu Sa'id ibn al-As sagten: Teile ihm keinen Anteil zu, o Gesandter Allahs. Abu Hurayra sagte: Das ist der Mörder von Ibn Qawqal. Ibn Sa'id ibn al-As sagte: Wie erstaunlich, dass ein kleines Tier von einem Schafschlachtblock auf uns herabhängt und mich dafür tadelt, einen muslimischen Mann getötet zu haben, den Allah durch meine Hand ehrte und mich nicht durch seine Hand erniedrigte. Er sagte: Ich weiß nicht, ob er ihm einen Anteil zuteilte oder nicht. Sufyan sagte: Al-Sa'idi überlieferte es mir ebenfalls, von seinem Großvater, von Abu Hurayra. Abu Abdullah sagte: Al-Sa'idi war Amr ibn Yahya ibn Sa'id ibn Amr ibn Sa'id ibn al-As.",
  ],
  2828: [
    "Adam narrated to us. Shu'ba narrated to us. Thabit al-Bunani narrated to us. He said: I heard Anas ibn Malik, may Allah be pleased with him, say: During the time of the Prophet (peace be upon him), Abu Talha did not fast because of military expeditions. When the Prophet (peace be upon him) died, I never saw him not fasting except on Eid al-Fitr or Eid al-Adha.",
    "Adam überlieferte uns. Shu'ba überlieferte uns. Thabit al-Bunani überlieferte uns. Er sagte: Ich hörte Anas ibn Malik, möge Allah mit ihm zufrieden sein, sagen: Zur Zeit des Propheten (Friede sei auf ihm) fastete Abu Talha wegen der Feldzüge nicht. Als der Prophet (Friede sei auf ihm) starb, sah ich ihn nie nicht fasten, außer am Fest des Fastenbrechens oder am Opferfest.",
  ],
  2829: [
    "Abdullah ibn Yusuf narrated to us. Malik informed us, from Sumayy, from Abu Salih, from Abu Hurayra, may Allah be pleased with him, that the Messenger of Allah (peace be upon him) said: The martyrs are five: the one who dies from plague, the one who dies from an abdominal illness, the drowned person, the one killed beneath a collapsed building, and the martyr in the cause of Allah.",
    "Abdullah ibn Yusuf überlieferte uns. Malik informierte uns, von Sumayy, von Abu Salih, von Abu Hurayra, möge Allah mit ihm zufrieden sein, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Die Märtyrer sind fünf: der an einer Seuche Verstorbene, der an einer Bauchkrankheit Verstorbene, der Ertrunkene, der unter einem eingestürzten Gebäude Verstorbene und der Märtyrer auf Allahs Weg.",
  ],
  2830: [
    "Bishr ibn Muhammad informed us. Abdullah informed us. Asim informed us, from Hafsa bint Sirin, from Anas ibn Malik, may Allah be pleased with him, from the Prophet (peace be upon him), who said: Plague is martyrdom for every Muslim.",
    "Bishr ibn Muhammad informierte uns. Abdullah informierte uns. Asim informierte uns, von Hafsa bint Sirin, von Anas ibn Malik, möge Allah mit ihm zufrieden sein, vom Propheten (Friede sei auf ihm), der sagte: Die Pest ist Märtyrertum für jeden Muslim.",
  ],
  2831: [
    "Abu al-Walid narrated to us. Shu'ba narrated to us, from Abu Ishaq, who said: I heard al-Bara, may Allah be pleased with him, say: When (Quran 4:95) Those believers who sit back are not equal was revealed, the Messenger of Allah (peace be upon him) called for Zayd, who came with a shoulder blade and wrote it. Ibn Umm Maktum complained of his disability, and then (Quran 4:95) Those believers who sit back, except those who have an excuse was revealed.",
    "Abu al-Walid überlieferte uns. Shu'ba überlieferte uns, von Abu Ishaq, der sagte: Ich hörte al-Bara, möge Allah mit ihm zufrieden sein, sagen: Als (Quran 4:95) Diejenigen Gläubigen, die zurückbleiben, sind nicht gleich offenbart wurde, rief der Gesandte Allahs (Friede sei auf ihm) nach Zayd. Er kam mit einem Schulterblatt und schrieb es auf. Ibn Umm Maktum beklagte seine Behinderung, worauf (Quran 4:95) Diejenigen Gläubigen, die zurückbleiben, außer denjenigen, die eine Entschuldigung haben offenbart wurde.",
  ],
  2832: [
    "Abd al-Aziz ibn Abdullah narrated to us. Ibrahim ibn Sa'd al-Zuhri narrated to us. He said: Salih ibn Kaysan narrated to me, from Ibn Shihab, from Sahl ibn Sa'd al-Sa'idi, who said: I saw Marwan ibn al-Hakam sitting in the mosque, so I came and sat beside him. He informed us that Zayd ibn Thabit informed him that the Messenger of Allah (peace be upon him) dictated to him: Those believers who sit back are not equal to those who strive in the cause of Allah. He said: Ibn Umm Maktum came to him while he was dictating it to me and said: O Messenger of Allah, if I were able to strive, I would strive. He was a blind man. Then Allah, Blessed and Exalted is He, revealed to His Messenger (peace be upon him), while his thigh was on my thigh, and it became so heavy upon me that I feared it would crush my thigh. Then it was relieved from him, and Allah, Mighty and Majestic, revealed: (Quran 4:95) Except those who have an excuse.",
    "Abd al-Aziz ibn Abdullah überlieferte uns. Ibrahim ibn Sa'd al-Zuhri überlieferte uns. Er sagte: Salih ibn Kaysan berichtete mir, von Ibn Shihab, von Sahl ibn Sa'd al-Sa'idi, der sagte: Ich sah Marwan ibn al-Hakam in der Moschee sitzen, also kam ich und setzte mich neben ihn. Er berichtete uns, dass Zayd ibn Thabit ihm mitgeteilt hatte, dass der Gesandte Allahs (Friede sei auf ihm) ihm diktierte: Diejenigen Gläubigen, die zurückbleiben, sind nicht gleich denjenigen, die auf Allahs Weg streben. Er sagte: Ibn Umm Maktum kam zu ihm, während er es mir diktierte, und sagte: O Gesandter Allahs, wenn ich zum Streben fähig wäre, würde ich streben. Er war blind. Dann offenbarte Allah, Erhaben und Gepriesen sei Er, Seinem Gesandten (Friede sei auf ihm), während dessen Oberschenkel auf meinem Oberschenkel lag, und es wurde so schwer auf mir, dass ich fürchtete, es würde meinen Oberschenkel zerbrechen. Dann wurde es von ihm genommen, und Allah, der Mächtige und Majestätische, offenbarte: (Quran 4:95) Außer denjenigen, die eine Entschuldigung haben.",
  ],
  2833: [
    "Abdullah ibn Muhammad narrated to me. Muawiya ibn Amr narrated to us. Abu Ishaq narrated to us, from Musa ibn Uqba, from Salim Abu al-Nadr, that Abdullah ibn Abi Awfa wrote, and I read it: The Messenger of Allah (peace be upon him) said: When you meet them, be patient.",
    "Abdullah ibn Muhammad berichtete mir. Muawiya ibn Amr überlieferte uns. Abu Ishaq überlieferte uns, von Musa ibn Uqba, von Salim Abu al-Nadr, dass Abdullah ibn Abi Awfa schrieb, und ich las es: Der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn ihr auf sie trefft, dann seid standhaft.",
  ],
  2834: [
    "Abdullah ibn Muhammad narrated to us. Muawiya ibn Amr narrated to us. Abu Ishaq narrated to us, from Humayd, who said: I heard Anas, may Allah be pleased with him, say: The Messenger of Allah (peace be upon him) went out to the Trench, and the Emigrants and the Helpers were digging on a cold morning. They had no servants to do that for them. When he saw the exhaustion and hunger they were suffering, he said: O Allah, the true life is the life of the Hereafter, so forgive the Helpers and the Emigrants. They answered him: We are those who pledged allegiance to Muhammad to strive as long as we live, forever.",
    "Abdullah ibn Muhammad überlieferte uns. Muawiya ibn Amr überlieferte uns. Abu Ishaq überlieferte uns, von Humayd, der sagte: Ich hörte Anas, möge Allah mit ihm zufrieden sein, sagen: Der Gesandte Allahs (Friede sei auf ihm) zog zum Graben hinaus, und die Auswanderer und die Helfer gruben an einem kalten Morgen. Sie hatten keine Diener, die das für sie erledigten. Als er die Erschöpfung und den Hunger sah, unter denen sie litten, sagte er: O Allah, das wahre Leben ist das Leben des Jenseits, so vergib den Helfern und den Auswanderern. Sie antworteten ihm: Wir sind diejenigen, die Muhammad gelobt haben, zu streben, solange wir leben, für immer.",
  ],
  2835: [
    "Abu Ma'mar narrated to us. Abd al-Warith narrated to us. Abd al-Aziz narrated to us, from Anas, may Allah be pleased with him, who said: The Emigrants and the Helpers began digging the trench around Medina and carrying the soil on their backs, saying: We are those who pledged allegiance to Muhammad to remain upon Islam forever. The Prophet (peace be upon him) answered them, saying: O Allah, there is no good except the good of the Hereafter, so bless the Helpers and the Emigrants.",
    "Abu Ma'mar überlieferte uns. Abd al-Warith überlieferte uns. Abd al-Aziz überlieferte uns, von Anas, möge Allah mit ihm zufrieden sein, der sagte: Die Auswanderer und die Helfer begannen, den Graben um Medina auszuheben und die Erde auf ihren Rücken zu tragen. Sie sagten: Wir sind diejenigen, die Muhammad gelobt haben, für immer beim Islam zu bleiben. Der Prophet (Friede sei auf ihm) antwortete ihnen und sagte: O Allah, es gibt kein Gutes außer dem Guten des Jenseits, so segne die Helfer und die Auswanderer.",
  ],
  2836: [
    "Abu al-Walid narrated to us. Shu'ba narrated to us, from Abu Ishaq. I heard al-Bara, may Allah be pleased with him, say: The Prophet (peace be upon him) was carrying soil and saying: If not for You, we would not have been guided.",
    "Abu al-Walid überlieferte uns. Shu'ba überlieferte uns, von Abu Ishaq. Ich hörte al-Bara, möge Allah mit ihm zufrieden sein, sagen: Der Prophet (Friede sei auf ihm) trug Erde und sagte: Wenn nicht Du wärst, wären wir nicht rechtgeleitet worden.",
  ],
  2837: [
    "Hafs ibn Umar narrated to us. Shu'ba narrated to us, from Abu Ishaq, from al-Bara, may Allah be pleased with him, who said: I saw the Messenger of Allah (peace be upon him) on the day of the Confederates carrying soil, while the soil had covered the whiteness of his stomach, and he was saying: If not for You, we would not have been guided, nor given charity, nor prayed. Send tranquility down upon us and make our feet firm when we meet them. Those who transgressed against us, when they intend a trial, we refuse it.",
    "Hafs ibn Umar überlieferte uns. Shu'ba überlieferte uns, von Abu Ishaq, von al-Bara, möge Allah mit ihm zufrieden sein, der sagte: Ich sah den Gesandten Allahs (Friede sei auf ihm) am Tag der Verbündeten Erde tragen, wobei die Erde das Weiß seines Bauches bedeckte, und er sagte: Wenn nicht Du wärst, wären wir nicht rechtgeleitet worden, hätten keine Almosen gegeben und nicht gebetet. Sende Ruhe auf uns herab und festige unsere Füße, wenn wir ihnen begegnen. Diejenigen, die gegen uns frevelten, lehnen wir ab, wenn sie eine Versuchung wollen.",
  ],
  2838: [
    "Ahmad ibn Yunus narrated to us. Zuhayr narrated to us. Humayd narrated to us that Anas related to them: We returned from the expedition to Tabuk with the Prophet (peace be upon him).",
    "Ahmad ibn Yunus überlieferte uns. Zuhayr überlieferte uns. Humayd überlieferte uns, dass Anas ihnen berichtete: Wir kehrten mit dem Propheten (Friede sei auf ihm) vom Feldzug nach Tabuk zurück.",
  ],
  2839: [
    "Sulayman ibn Harb narrated to us. Hammad, meaning Ibn Zayd, narrated to us, from Humayd, from Anas, may Allah be pleased with him, that the Prophet (peace be upon him) was on an expedition and said: There are people in Medina behind us. We did not travel through a mountain pass or a valley without them being with us in it. An excuse held them back. Musa said: Hammad narrated to us, from Humayd, from Musa ibn Anas, from his father, who said: The Prophet (peace be upon him) said it. Abu Abdullah said: The first version is more authentic.",
    "Sulayman ibn Harb überlieferte uns. Hammad, also Ibn Zayd, überlieferte uns, von Humayd, von Anas, möge Allah mit ihm zufrieden sein, dass der Prophet (Friede sei auf ihm) bei einem Feldzug war und sagte: In Medina gibt es Menschen hinter uns. Wir durchquerten keinen Bergpass und kein Tal, ohne dass sie darin bei uns waren. Eine Entschuldigung hielt sie zurück. Musa sagte: Hammad überlieferte uns, von Humayd, von Musa ibn Anas, von seinem Vater, der sagte: Der Prophet (Friede sei auf ihm) sagte es. Abu Abdullah sagte: Die erste Fassung ist authentischer.",
  ],
  2840: [
    "Ishaq ibn Nasr narrated to us. Abd al-Razzaq narrated to us. Ibn Jurayj informed us. He said: Yahya ibn Sa'id and Suhayl ibn Abi Salih informed me that they heard al-Numan ibn Abi Ayyash, from Abu Sa'id, may Allah be pleased with him, who said: I heard the Prophet (peace be upon him) say: Whoever fasts one day in the cause of Allah, Allah distances his face from the Fire by seventy autumns.",
    "Ishaq ibn Nasr überlieferte uns. Abd al-Razzaq überlieferte uns. Ibn Jurayj informierte uns. Er sagte: Yahya ibn Sa'id und Suhayl ibn Abi Salih berichteten mir, dass sie al-Numan ibn Abi Ayyash von Abu Sa'id, möge Allah mit ihm zufrieden sein, hörten, der sagte: Ich hörte den Propheten (Friede sei auf ihm) sagen: Wer einen Tag auf Allahs Weg fastet, dessen Gesicht hält Allah siebzig Herbstzeiten vom Feuer fern.",
  ],
  2841: [
    "Sa'd ibn Hafs narrated to us. Shayban narrated to us, from Yahya, from Abu Salama, that he heard Abu Hurayra, may Allah be pleased with him, from the Prophet (peace be upon him), who said: Whoever spends a pair in the cause of Allah will be called by the keepers of Paradise: O servant of Allah, this is good. Every keeper has a gate. Abu Bakr said: O Messenger of Allah, that is the one who will have no loss. The Prophet (peace be upon him) said: I hope that you will be one of them.",
    "Sa'd ibn Hafs überlieferte uns. Shayban überlieferte uns, von Yahya, von Abu Salama, dass er Abu Hurayra, möge Allah mit ihm zufrieden sein, vom Propheten (Friede sei auf ihm) hörte, der sagte: Wer ein Paar auf Allahs Weg ausgibt, wird von den Hütern des Paradieses gerufen: O Diener Allahs, das ist gut. Jeder Hüter hat ein Tor. Abu Bakr sagte: O Gesandter Allahs, das ist derjenige, der keinen Verlust hat. Der Prophet (Friede sei auf ihm) sagte: Ich hoffe, dass du zu ihnen gehörst.",
  ],
  2842: [
    "Muhammad ibn Sinan narrated to us. Fulayh narrated to us. Hilal narrated to us, from Ata ibn Yasar, from Abu Sa'id al-Khudri, may Allah be pleased with him, that the Messenger of Allah (peace be upon him) stood on the pulpit and said: I only fear for you, after me, what will be opened for you of the blessings of the earth. Then he mentioned the splendor of the world. He began with one of them and followed with the other. A man stood and said: O Messenger of Allah, does good bring evil? The Prophet (peace be upon him) remained silent about him, and we said: Revelation is coming to him. The people remained silent as though birds were perched on their heads. Then he wiped the perspiration from his face and said: Where is the questioner just now? Is it good? Three times. Good brings only good. What spring vegetation grows can kill by overeating or nearly kill. Whenever an animal eats until its flanks are full, it faces the sun, defecates and urinates, then grazes again. This wealth is green and sweet. How excellent a companion it is for the Muslim who takes it rightfully and spends it in the cause of Allah, on orphans, and on the needy. Whoever does not take it rightfully is like one who eats but is never satisfied, and it will testify against him on the Day of Resurrection.",
    "Muhammad ibn Sinan überlieferte uns. Fulayh überlieferte uns. Hilal überlieferte uns, von Ata ibn Yasar, von Abu Sa'id al-Khudri, möge Allah mit ihm zufrieden sein, dass der Gesandte Allahs (Friede sei auf ihm) auf der Kanzel stand und sagte: Ich fürchte für euch nach mir nur das, was euch an Segnungen der Erde eröffnet werden wird. Dann erwähnte er den Glanz der Welt. Er begann mit dem einen und fügte das andere hinzu. Ein Mann stand auf und sagte: O Gesandter Allahs, bringt das Gute das Böse? Der Prophet (Friede sei auf ihm) schwieg ihm gegenüber, und wir sagten: Ihm wird offenbart. Die Menschen schwiegen, als säßen Vögel auf ihren Köpfen. Dann wischte er sich den Schweiß vom Gesicht und sagte: Wo ist derjenige, der soeben gefragt hat? Ist es gut? Dreimal. Das Gute bringt nur Gutes. Alles, was der Frühling wachsen lässt, kann durch Überfressen töten oder beinahe töten. Wenn ein Tier davon gefressen hat, bis seine Flanken voll sind, wendet es sich der Sonne zu, kotet und uriniert, und weidet dann wieder. Dieser Besitz ist grün und süß. Wie gut ist er als Begleiter für den Muslim, der ihn rechtmäßig nimmt und ihn auf Allahs Weg, für Waisen und Bedürftige einsetzt. Wer ihn nicht rechtmäßig nimmt, ist wie jemand, der isst, aber nicht satt wird, und er wird am Tag der Auferstehung gegen ihn zeugen.",
  ],
  2843: [
    "Abu Ma'mar narrated to us. Abd al-Warith narrated to us. al-Husayn narrated to us. He said: Yahya narrated to me. He said: Abu Salama narrated to me. He said: Busr ibn Sa'id narrated to me. He said: Zayd ibn Khalid, may Allah be pleased with him, narrated to me that the Messenger of Allah (peace be upon him) said: Whoever equips a fighter in the cause of Allah has fought, and whoever takes good care of a fighter's family in the cause of Allah has fought.",
    "Abu Ma'mar überlieferte uns. Abd al-Warith überlieferte uns. al-Husayn überlieferte uns. Er sagte: Yahya berichtete mir. Er sagte: Abu Salama berichtete mir. Er sagte: Busr ibn Sa'id berichtete mir. Er sagte: Zayd ibn Khalid, möge Allah mit ihm zufrieden sein, berichtete mir, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Wer einen Kämpfer auf Allahs Weg ausrüstet, hat gekämpft, und wer die Familie eines Kämpfers auf Allahs Weg gut versorgt, hat gekämpft.",
  ],
  2844: [
    "Musa narrated to us. Hammam narrated to us, from Ishaq ibn Abdullah, from Anas, may Allah be pleased with him, that the Prophet (peace be upon him) did not enter any house in Medina other than the house of Umm Sulaym, except the houses of his wives. He was asked about this, and he said: I show her mercy; her brother was killed alongside me.",
    "Musa überlieferte uns. Hammam überlieferte uns, von Ishaq ibn Abdullah, von Anas, möge Allah mit ihm zufrieden sein, dass der Prophet (Friede sei auf ihm) in Medina kein Haus außer dem Haus von Umm Sulaym betrat, außer den Häusern seiner Ehefrauen. Er wurde danach gefragt und sagte: Ich erweise ihr Barmherzigkeit; ihr Bruder wurde an meiner Seite getötet.",
  ],
  2845: [
    "Abdullah ibn Abd al-Wahhab narrated to us. Khalid ibn al-Harith narrated to us. Ibn Awn narrated to us, from Musa ibn Anas, who said: He mentioned the day of al-Yamama and said: Anas came to Thabit ibn Qays, who had uncovered his thighs and was applying embalming perfume. He said: O uncle, what is keeping you from coming? He said: Now, nephew. He continued applying the perfume, meaning the hanut, then came and sat down. The report mentioned that the people had fled, and he said: This is how you turn away from our faces until we fight the people? This is not how we used to act with the Messenger of Allah (peace be upon him). How badly you have trained your peers. Hammād narrated it from Thabit, from Anas.",
    "Abdullah ibn Abd al-Wahhab überlieferte uns. Khalid ibn al-Harith überlieferte uns. Ibn Awn überlieferte uns, von Musa ibn Anas, der sagte: Er erwähnte den Tag von al-Yamama und sagte: Anas kam zu Thabit ibn Qays, der seine Oberschenkel entblößt hatte und sich mit Einbalsamierungsduft einrieb. Er sagte: O Onkel, was hält dich davon ab zu kommen? Er sagte: Jetzt, Neffe. Er fuhr fort, sich mit dem Duft einzureiben, also dem Hanut, und kam dann und setzte sich. In der Überlieferung wurde erwähnt, dass die Menschen geflohen waren, und er sagte: So wendet ihr euch von unseren Gesichtern ab, bis wir gegen die Menschen kämpfen? So pflegten wir uns gegenüber dem Gesandten Allahs (Friede sei auf ihm) nicht zu verhalten. Wie schlecht habt ihr eure Gefährten erzogen. Hammad überlieferte dies von Thabit, von Anas.",
  ],
  2846: [
    "Abu Nu'aym narrated to us. Sufyan narrated to us, from Muhammad ibn al-Munkadir, from Jabir, may Allah be pleased with him, who said: The Prophet (peace be upon him) said: Who will bring me news of the people on the day of the Confederates? Al-Zubayr said: I will. Then he said: Who will bring me news of the people? Al-Zubayr said: I will. The Prophet (peace be upon him) said: Every prophet has a devoted helper, and al-Zubayr is my devoted helper.",
    "Abu Nu'aym überlieferte uns. Sufyan überlieferte uns, von Muhammad ibn al-Munkadir, von Jabir, möge Allah mit ihm zufrieden sein, der sagte: Der Prophet (Friede sei auf ihm) sagte: Wer bringt mir am Tag der Verbündeten Nachricht über die Menschen? Al-Zubayr sagte: Ich. Dann sagte er: Wer bringt mir Nachricht über die Menschen? Al-Zubayr sagte: Ich. Der Prophet (Friede sei auf ihm) sagte: Jeder Prophet hat einen ergebenen Helfer, und al-Zubayr ist mein ergebener Helfer.",
  ],
  2847: [
    "Sadaqa narrated to us. Ibn Uyayna informed us. Ibn al-Munkadir narrated to us. He heard Jabir ibn Abdullah, may Allah be pleased with them, say: The Prophet (peace be upon him) called the people to volunteer, I think Sadaqa said, on the day of the Trench, and al-Zubayr volunteered. Then he called again and al-Zubayr volunteered. Then he called the people, and al-Zubayr volunteered. The Prophet (peace be upon him) said: Every prophet has a devoted helper, and the devoted helper of al-Zubayr ibn al-Awwam is he.",
    "Sadaqa überlieferte uns. Ibn Uyayna informierte uns. Ibn al-Munkadir überlieferte uns. Er hörte Jabir ibn Abdullah, möge Allah mit ihnen zufrieden sein, sagen: Der Prophet (Friede sei auf ihm) rief die Menschen zur freiwilligen Meldung auf, so glaube ich, sagte Sadaqa, am Tag des Grabens, und al-Zubayr meldete sich. Dann rief er erneut, und al-Zubayr meldete sich. Dann rief er die Menschen, und al-Zubayr meldete sich. Der Prophet (Friede sei auf ihm) sagte: Jeder Prophet hat einen ergebenen Helfer, und der ergebene Helfer von al-Zubayr ibn al-Awwam ist er.",
  ],
  2848: [
    "Ahmad ibn Yunus narrated to us. Abu Shihab narrated to us, from Khalid al-Hadhdha, from Abu Qilaba, from Malik ibn al-Huwayrith, who said: I left the Prophet (peace be upon him), and he said to me and a companion of mine: Give the call to prayer and establish the prayer, and let the older of you lead you.",
    "Ahmad ibn Yunus überlieferte uns. Abu Shihab überlieferte uns, von Khalid al-Hadhdha, von Abu Qilaba, von Malik ibn al-Huwayrith, der sagte: Ich ging vom Propheten (Friede sei auf ihm) weg, und er sagte zu mir und einem Gefährten von mir: Ruft zum Gebet und verrichtet die Gebets­einleitung, und der Ältere von euch soll euch leiten.",
  ],
  2849: [
    "Abdullah ibn Maslama narrated to us. Malik narrated to us, from Nafi, from Abdullah ibn Umar, may Allah be pleased with them, who said: The Messenger of Allah (peace be upon him) said: Good is tied to the forelocks of horses until the Day of Resurrection.",
    "Abdullah ibn Maslama überlieferte uns. Malik überlieferte uns, von Nafi, von Abdullah ibn Umar, möge Allah mit ihnen zufrieden sein, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Das Gute ist bis zum Tag der Auferstehung an die Stirnlocken der Pferde gebunden.",
  ],
  2850: [
    "Hafs ibn Umar narrated to us. Shu'ba narrated to us, from Husayn and Ibn Abi al-Safar, from al-Sha'bi, from Urwa ibn al-Ja'd, from the Prophet (peace be upon him), who said: Good is tied to the forelocks of horses until the Day of Resurrection. Sulayman said: From Shu'ba, from Urwa ibn Abi al-Ja'd. Musaddad followed it from Hushaym, from Husayn, from al-Sha'bi, from Urwa ibn Abi al-Ja'd.",
    "Hafs ibn Umar überlieferte uns. Shu'ba überlieferte uns, von Husayn und Ibn Abi al-Safar, von al-Sha'bi, von Urwa ibn al-Ja'd, vom Propheten (Friede sei auf ihm), der sagte: Das Gute ist bis zum Tag der Auferstehung an die Stirnlocken der Pferde gebunden. Sulayman sagte: Von Shu'ba, von Urwa ibn Abi al-Ja'd. Musaddad überlieferte sie ebenfalls von Hushaym, von Husayn, von al-Sha'bi, von Urwa ibn Abi al-Ja'd.",
  ],
  2851: [
    "Musaddad narrated to us. Yahya narrated to us, from Shu'ba, from Abu al-Tayyah, from Anas ibn Malik, may Allah be pleased with him, who said: The Messenger of Allah (peace be upon him) said: Blessing is in the forelocks of horses.",
    "Musaddad überlieferte uns. Yahya überlieferte uns, von Shu'ba, von Abu al-Tayyah, von Anas ibn Malik, möge Allah mit ihm zufrieden sein, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Segen liegt in den Stirnlocken der Pferde.",
  ],
  2852: [
    "Abu Nu'aym narrated to us. Zakariya narrated to us, from Amir. Urwa al-Bariqi narrated to us that the Prophet (peace be upon him) said: Good is tied to the forelocks of horses until the Day of Resurrection: reward and spoils.",
    "Abu Nu'aym überlieferte uns. Zakariya überlieferte uns, von Amir. Urwa al-Bariqi überlieferte uns, dass der Prophet (Friede sei auf ihm) sagte: Das Gute ist bis zum Tag der Auferstehung an die Stirnlocken der Pferde gebunden: Belohnung und Beute.",
  ],
  2853: [
    "Ali ibn Hafs narrated to us. Ibn al-Mubarak narrated to us. Talha ibn Abi Sa'id informed us. He said: I heard Sa'id al-Maqburi relate that he heard Abu Hurayra, may Allah be pleased with him, say: The Prophet (peace be upon him) said: Whoever keeps a horse stationed in the cause of Allah, believing in Allah and affirming His promise, its feeding, watering, dung, and urine will be in his scale on the Day of Resurrection.",
    "Ali ibn Hafs überlieferte uns. Ibn al-Mubarak überlieferte uns. Talha ibn Abi Sa'id informierte uns. Er sagte: Ich hörte Sa'id al-Maqburi berichten, dass er Abu Hurayra, möge Allah mit ihm zufrieden sein, sagen hörte: Der Prophet (Friede sei auf ihm) sagte: Wer ein Pferd auf Allahs Weg bereithält, im Glauben an Allah und in der Bestätigung Seines Versprechens, dessen Futter, Trank, Mist und Urin werden am Tag der Auferstehung auf seiner Waage sein.",
  ],
  2854: [
    "Muhammad ibn Abi Bakr narrated to us. Fudayl ibn Sulayman narrated to us, from Abu Hazim, from Abdullah ibn Abi Qatada, from his father, that he went out with the Prophet (peace be upon him). Abu Qatada stayed behind with some of his companions, who were in a state of ihram, while he was not in ihram. They saw a wild donkey before he saw it, and when they saw it they left it until Abu Qatada saw it. He mounted a horse of his called al-Jarada and asked them to hand him his whip, but they refused. He took it himself, charged, and struck the donkey. Then he ate, and they ate. They regretted it, and when they caught up with the Prophet (peace be upon him), he said: Do you have any of it with you? He said: We have its leg. The Prophet (peace be upon him) took it and ate it.",
    "Muhammad ibn Abi Bakr überlieferte uns. Fudayl ibn Sulayman überlieferte uns, von Abu Hazim, von Abdullah ibn Abi Qatada, von seinem Vater, dass er mit dem Propheten (Friede sei auf ihm) auszog. Abu Qatada blieb mit einigen seiner Gefährten zurück, die sich im Ihram befanden, während er nicht im Ihram war. Sie sahen einen Wildesel, bevor er ihn sah, und als sie ihn sahen, ließen sie ihn, bis Abu Qatada ihn sah. Er bestieg ein Pferd von sich, das al-Jarada genannt wurde, und bat sie, ihm seine Peitsche zu reichen, doch sie weigerten sich. Er nahm sie selbst, stürmte vor und verletzte den Esel tödlich. Dann aß er, und sie aßen. Sie bereuten es, und als sie den Propheten (Friede sei auf ihm) einholten, sagte er: Habt ihr etwas davon bei euch? Er sagte: Wir haben sein Bein. Der Prophet (Friede sei auf ihm) nahm es und aß es.",
  ],
  2855: [
    "Ali ibn Abdullah ibn Ja'far narrated to us. Ma'n ibn Isa narrated to us. Ubayy ibn Abbas ibn Sahl narrated to us, from his father, from his grandfather, who said: The Prophet (peace be upon him) had a horse in our garden called al-Luhayf. Abu Abdullah said: Some of them called it al-Lukhayf.",
    "Ali ibn Abdullah ibn Ja'far überlieferte uns. Ma'n ibn Isa überlieferte uns. Ubayy ibn Abbas ibn Sahl überlieferte uns, von seinem Vater, von seinem Großvater, der sagte: Der Prophet (Friede sei auf ihm) hatte in unserem Garten ein Pferd, das al-Luhayf genannt wurde. Abu Abdullah sagte: Einige von ihnen nannten es al-Lukhayf.",
  ],
};

const out: Out[] = raw.map((row) => {
  const n = Number(row.url.split(":").pop());
  const pair = translations[n];
  if (!pair) throw new Error(`Missing translation for ${row.url}`);
  return { id: row.id, n, en: pair[0], de: pair[1] };
});

fs.writeFileSync(output, JSON.stringify(out, null, 2) + "\n", "utf8");
console.log(`wrote ${out.length} translations to ${output}`);
