import fs from 'node:fs';
const rows=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8')) as Array<{id:string,url:string}>;
const t:Record<string,[string,string]>= {
 'https://sunnah.com/muslim:577':["Yahya ibn Yahya, Yahya ibn Ayyub, Qutayba ibn Sa'id, and Ibn Hujr narrated to us. Yahya ibn Yahya said: They informed us, while the others said: Isma'il, the son of Ja'far, narrated to us, from Yazid ibn Khusayfa, from Ibn Qusayt, from Ata ibn Yasar, that he told him: He asked Zayd ibn Thabit about reciting with the imam. He said: There is no recitation with the imam in anything. He claimed that he recited (Quran 53:1) to the Messenger of Allah (peace be upon him), but he did not prostrate.","Yahya ibn Yahya, Yahya ibn Ayyub, Qutayba ibn Sa'id und Ibn Hujr überlieferten uns. Yahya ibn Yahya sagte: Sie berichteten uns, während die anderen sagten: Isma'il, der Sohn von Ja'far, überlieferte uns, von Yazid ibn Khusayfa, von Ibn Qusayt, von Ata ibn Yasar, der ihm berichtete: Er fragte Zayd ibn Thabit über das Rezitieren mit dem Imam. Er sagte: Bei nichts wird mit dem Imam rezitiert. Er behauptete, dass er (Quran 53:1) dem Gesandten Allahs (Friede sei auf ihm) vorgetragen habe, dieser sich aber nicht niederwarf."],
 'https://sunnah.com/muslim:578a':["Yahya ibn Yahya narrated to us. He said: I recited to Malik, from Abdullah ibn Yazid, the client of al-Aswad ibn Sufyan, from Abu Salama ibn Abd al-Rahman, that Abu Hurayra recited to them (Quran 84:1), and prostrated during it. When he finished, he informed them that the Messenger of Allah (peace be upon him) prostrated during it.","Yahya ibn Yahya überlieferte uns. Er sagte: Ich trug Malik vor, von Abdullah ibn Yazid, dem Schutzbefohlenen von al-Aswad ibn Sufyan, von Abu Salama ibn Abd al-Rahman, dass Abu Hurayra ihnen (Quran 84:1) vortrug und sich dabei niederwarf. Als er fertig war, teilte er ihnen mit, dass sich der Gesandte Allahs (Friede sei auf ihm) dabei niedergeworfen hatte."],
 'https://sunnah.com/muslim:578b':["Ibrahim ibn Musa narrated to me. Isa informed us, from al-Awzai. H He said: Muhammad ibn al-Muthanna narrated to us. Ibn Abi Adi narrated to us, from Hisham. Both of them narrated from Yahya ibn Abi Kathir, from Abu Salama, from Abu Hurayra, from the Prophet (peace be upon him), with the same meaning.","Ibrahim ibn Musa überlieferte mir. Isa berichtete uns, von al-Awzai. H Er sagte: Muhammad ibn al-Muthanna überlieferte uns. Ibn Abi Adi überlieferte uns, von Hisham. Beide überlieferten von Yahya ibn Abi Kathir, von Abu Salama, von Abu Hurayra, vom Propheten (Friede sei auf ihm), mit derselben Bedeutung."],
 'https://sunnah.com/muslim:578c':["Abu Bakr ibn Abi Shayba and Amr al-Naqid narrated to us. They said: Sufyan ibn Uyayna narrated to us, from Ayyub ibn Musa, from Ata ibn Mina, from Abu Hurayra. He said: We prostrated with the Prophet (peace be upon him) during (Quran 84:1) and (Quran 96:1).","Abu Bakr ibn Abi Shayba und Amr al-Naqid überlieferten uns. Sie sagten: Sufyan ibn Uyayna überlieferte uns, von Ayyub ibn Musa, von Ata ibn Mina, von Abu Hurayra. Er sagte: Wir warfen uns mit dem Propheten (Friede sei auf ihm) bei (Quran 84:1) und (Quran 96:1) nieder."],
 'https://sunnah.com/muslim:578d':["Muhammad ibn Rumh narrated to us. al-Layth informed us, from Yazid ibn Abi Habib, from Safwan ibn Sulaym, from Abd al-Rahman al-A'raj, the client of Banu Makhzum, from Abu Hurayra, that he said: The Messenger of Allah (peace be upon him) prostrated during (Quran 84:1) and (Quran 96:1).","Muhammad ibn Rumh überlieferte uns. al-Layth berichtete uns, von Yazid ibn Abi Habib, von Safwan ibn Sulaym, von Abd al-Rahman al-A'raj, dem Schutzbefohlenen der Banu Makhzum, von Abu Hurayra, der sagte: Der Gesandte Allahs (Friede sei auf ihm) warf sich bei (Quran 84:1) und (Quran 96:1) nieder."],
 'https://sunnah.com/muslim:578e':["Harmala ibn Yahya narrated to me. Ibn Wahb narrated to us. Amr ibn al-Harith informed me, from Ubaydullah ibn Abi Ja'far, from Abd al-Rahman al-A'raj, from Abu Hurayra, from the Messenger of Allah (peace be upon him), with the same wording.","Harmala ibn Yahya überlieferte mir. Ibn Wahb überlieferte uns. Amr ibn al-Harith berichtete mir, von Ubaydullah ibn Abi Ja'far, von Abd al-Rahman al-A'raj, von Abu Hurayra, vom Gesandten Allahs (Friede sei auf ihm), mit derselben Fassung."],
 'https://sunnah.com/muslim:578f':["Ubaydullah ibn Mu'adh and Muhammad ibn Abd al-A'la narrated to us. They said: al-Mu'tamir narrated to us, from his father, from Bakr, from Abu Rafi. He said: I prayed the night prayer with Abu Hurayra. He recited (Quran 84:1) and prostrated during it. I said to him: What is this prostration? He said: I prostrated because of it behind Abu al-Qasim (peace be upon him), and I will continue prostrating during it until I meet him. Ibn Abd al-A'la said: I will continue prostrating during it.","Ubaydullah ibn Mu'adh und Muhammad ibn Abd al-A'la überlieferten uns. Sie sagten: al-Mu'tamir überlieferte uns, von seinem Vater, von Bakr, von Abu Rafi. Er sagte: Ich verrichtete das Nachtgebet mit Abu Hurayra. Er trug (Quran 84:1) vor und warf sich dabei nieder. Ich sagte zu ihm: Was ist diese Niederwerfung? Er sagte: Ich warf mich deswegen hinter Abu al-Qasim (Friede sei auf ihm) nieder, und ich werde mich dabei weiterhin niederwerfen, bis ich ihn treffe. Ibn Abd al-A'la sagte: Ich werde mich dabei weiterhin niederwerfen."],
 'https://sunnah.com/muslim:578g':["Amr al-Naqid narrated to me. Isa ibn Yunus narrated to us. H He said: Abu Kamil narrated to us. Yazid, meaning Ibn Zuray, narrated to us. H He said: Ahmad ibn Abdah narrated to us. Sulaym ibn Akhdar narrated to us, all of them from al-Taymi, with this chain, except that they did not say: behind Abu al-Qasim (peace be upon him).","Amr al-Naqid überlieferte mir. Isa ibn Yunus überlieferte uns. H Er sagte: Abu Kamil überlieferte uns. Yazid, das heißt Ibn Zuray, überlieferte uns. H Er sagte: Ahmad ibn Abdah überlieferte uns. Sulaym ibn Akhdar überlieferte uns, alle von al-Taymi mit dieser Überliefererkette, außer dass sie nicht sagten: hinter Abu al-Qasim (Friede sei auf ihm)."],
 'https://sunnah.com/muslim:578h':["Muhammad ibn al-Muthanna and Ibn Bashshar narrated to me. They said: Muhammad ibn Ja'far narrated to us. Shu'ba narrated to us, from Ata ibn Abi Maymuna, from Abu Rafi. He said: I saw Abu Hurayra prostrate during (Quran 84:1). I said: Are you prostrating during it? He said: Yes. I saw my beloved, the Prophet (peace be upon him), prostrate during it, and I will continue prostrating during it until I meet him. Shu'ba said: I asked the Prophet (peace be upon him) about it. He said: Yes.","Muhammad ibn al-Muthanna und Ibn Bashshar überlieferten mir. Sie sagten: Muhammad ibn Ja'far überlieferte uns. Shu'ba überlieferte uns, von Ata ibn Abi Maymuna, von Abu Rafi. Er sagte: Ich sah Abu Hurayra bei (Quran 84:1) niederfallen. Ich sagte: Wirfst du dich dabei nieder? Er sagte: Ja. Ich sah meinen geliebten Menschen, den Propheten (Friede sei auf ihm), sich dabei niederwerfen, und ich werde mich dabei weiterhin niederwerfen, bis ich ihn treffe. Shu'ba sagte: Ich fragte den Propheten (Friede sei auf ihm) danach. Er sagte: Ja."],
 'https://sunnah.com/muslim:579a':["Muhammad ibn Muammar ibn Rub'i al-Qaysi narrated to us. Abu Hisham al-Makhzumi narrated to us, from Abd al-Wahid, the son of Ziyad. Uthman ibn Hakim narrated to us. Amir ibn Abdullah ibn al-Zubayr narrated to me, from his father. He said: When the Messenger of Allah (peace be upon him) sat in prayer, he placed his left foot between his thigh and shin, spread his right foot, placed his left hand on his left knee, and placed his right hand on his right thigh, pointing with his finger.","Muhammad ibn Muammar ibn Rub'i al-Qaysi überlieferte uns. Abu Hisham al-Makhzumi überlieferte uns, von Abd al-Wahid, dem Sohn von Ziyad. Uthman ibn Hakim überlieferte uns. Amir ibn Abdullah ibn al-Zubayr überlieferte mir, von seinem Vater. Er sagte: Wenn der Gesandte Allahs (Friede sei auf ihm) im Gebet saß, legte er seinen linken Fuß zwischen seinen Oberschenkel und seine Wade, stellte seinen rechten Fuß auf, legte seine linke Hand auf sein linkes Knie, legte seine rechte Hand auf seinen rechten Oberschenkel und zeigte mit seinem Finger." ]
};
const out=rows.slice(0,10).map(r=>{const x=t[r.url];if(!x)throw Error(r.url);return {id:r.id,url:r.url,en:x[0],de:x[1]};});
fs.writeFileSync('data/hadith-words-translations/codex-batch-271-part.json',JSON.stringify(rows.slice(0,10),null,2)+'\n');
fs.writeFileSync('data/hadith-words-translations/codex-out-271-part.json',JSON.stringify(out,null,2)+'\n');
console.log(`translated=${out.length}`);
