import fs from "node:fs";

const all = JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-batch-095.json", "utf8")) as { id: string; url: string }[];
const keep = new Set(["4010", "4011", "4012", "4014", "4015", "4016", "4018", "4019", "4020", "4021"]);
const raw = all.filter((row) => keep.has(row.url.split(":").pop()!));
fs.writeFileSync("data/hadith-words-translations/codex-batch-095.json", JSON.stringify(raw, null, 2) + "\n", "utf8");

const t: Record<string, { en: string; de: string }> = {
  "4010": { en: String.raw`Ahmad, meaning Ibn Salih, narrated to us. Anbasa narrated to us. Yunus narrated to us. Ibn Shihab said: Then I asked al-Husayn ibn Muhammad, one of Banu Salim and one of their leading men, about the report of Mahmud ibn al-Rabi from Itban ibn Malik, and he confirmed it.`, de: String.raw`Ahmad, das heißt Ibn Salih, überlieferte uns. Anbasa überlieferte uns. Yunus überlieferte uns. Ibn Schihab sagte: Dann fragte ich al-Husayn ibn Muhammad, einen der Banu Salim und einen ihrer Vornehmen, nach dem Bericht von Mahmud ibn ar-Rabi von Itban ibn Malik, und er bestätigte ihn.` },
  "4011": { en: String.raw`Abu al-Yaman narrated to us. Shuayb informed us, from al-Zuhri, who said: Abd Allah ibn Amir ibn Rabi'a informed me. He was one of the leading men of Banu Adi, and his father had witnessed Badr with the Prophet (peace be upon him), that Umar appointed Qudama ibn Mazun over Bahrain. He had witnessed Badr, and he was the maternal uncle of Abd Allah ibn Umar and Hafsa, may Allah be pleased with them.`, de: String.raw`Abu al-Yaman überlieferte uns. Schuayb berichtete uns, von az-Zuhri, der sagte: Abd Allah ibn Amir ibn Rabi'a berichtete mir, dass Umar Qudama ibn Mazun zum Statthalter über Bahrain ernannte. Er war einer der Vornehmen der Banu Adi, sein Vater hatte Badr mit dem Propheten (Friede sei auf ihm) miterlebt, und er war der mütterliche Onkel von Abd Allah ibn Umar und Hafsa, möge Allah mit ihnen zufrieden sein.` },
  "4012": { en: String.raw`Abd Allah ibn Muhammad ibn Asma narrated to us. Juwairiya narrated to us, from Malik, from al-Zuhri, that Salim ibn Abd Allah informed him: Rafi ibn Khadij told Abd Allah ibn Umar that his two uncles, who had witnessed Badr, informed him that the Messenger of Allah (peace be upon him) prohibited renting out farmland. I said to Salim: Do you rent it out? He said: Yes, for Rafi exaggerated against himself.`, de: String.raw`Abd Allah ibn Muhammad ibn Asma überlieferte uns. Dschuwairiya überlieferte uns, von Malik, von az-Zuhri, dass Salim ibn Abd Allah ihm berichtete: Rafi ibn Khadij teilte Abd Allah ibn Umar mit, dass seine beiden Onkel, die Badr miterlebt hatten, ihm berichtet hatten, dass der Gesandte Allahs (Friede sei auf ihm) das Verpachten von Ackerland untersagte. Ich sagte zu Salim: Verpachtest du es also? Er sagte: Ja, denn Rafi hat sich selbst gegenüber übertrieben.` },
  "4014": { en: String.raw`Adam narrated to us. Shu'ba narrated to us, from Husayn ibn Abd al-Rahman, who said: I heard Abd Allah ibn Shaddad ibn al-Had al-Laythi say: I saw Rifa'a ibn Rafi al-Ansari, who had witnessed Badr.`, de: String.raw`Adam überlieferte uns. Schu'ba überlieferte uns, von Husayn ibn Abd ar-Rahman, der sagte: Ich hörte Abd Allah ibn Schaddad ibn al-Had al-Laythi sagen: Ich sah Rifa'a ibn Rafi al-Ansari, der Badr miterlebt hatte.` },
  "4015": { en: String.raw`Abdan narrated to us. Abd Allah narrated to us. Ma'mar and Yunus narrated to us, from al-Zuhri, from Urwa ibn al-Zubayr, who informed him that al-Miswar ibn Makhrama informed him that Amr ibn Awf, an ally of Banu Amir ibn Luayy who had witnessed Badr with the Prophet (peace be upon him), said: The Messenger of Allah (peace be upon him) sent Abu Ubayda ibn al-Jarrah to Bahrain to bring its tribute. The Messenger of Allah (peace be upon him) had made peace with the people of Bahrain and appointed al-Ala ibn al-Hadrami over them. Abu Ubayda arrived with wealth from Bahrain. The Ansar heard of Abu Ubayda's arrival and came to the dawn prayer with the Prophet (peace be upon him). When he finished, they approached him. The Messenger of Allah (peace be upon him) smiled when he saw them and said: I suppose you have heard that Abu Ubayda has brought something. They said: Yes, O Messenger of Allah. He said: Rejoice and hope for what will please you. By Allah, I do not fear poverty for you, but I fear that the world will be spread out before you as it was spread out before those who came before you, and you will compete for it as they competed for it, and it will destroy you as it destroyed them.`, de: String.raw`Abdan überlieferte uns. Abd Allah überlieferte uns. Ma'mar und Yunus überlieferten uns, von az-Zuhri, von Urwa ibn az-Zubayr, der ihm berichtete, dass al-Miswar ibn Makhrama ihm mitteilte, dass Amr ibn Awf, ein Verbündeter der Banu Amir ibn Luayy, der Badr mit dem Propheten (Friede sei auf ihm) miterlebt hatte, sagte: Der Gesandte Allahs (Friede sei auf ihm) schickte Abu Ubayda ibn al-Dscharrah nach Bahrain, um dessen Tribut zu bringen. Der Gesandte Allahs (Friede sei auf ihm) hatte mit den Bewohnern von Bahrain Frieden geschlossen und al-Ala ibn al-Hadrami über sie eingesetzt. Abu Ubayda kam mit Vermögen aus Bahrain. Die Ansar hörten von Abu Ubaydas Ankunft und kamen mit dem Propheten (Friede sei auf ihm) zum Morgengebet. Als er fertig war, traten sie an ihn heran. Der Gesandte Allahs (Friede sei auf ihm) lächelte, als er sie sah, und sagte: Ich nehme an, ihr habt gehört, dass Abu Ubayda etwas gebracht hat. Sie sagten: Ja, o Gesandter Allahs. Er sagte: Freut euch und hofft auf das, was euch erfreuen wird. Bei Allah, ich fürchte für euch nicht die Armut, sondern ich fürchte, dass euch die Welt ausgebreitet wird, wie sie denen vor euch ausgebreitet wurde, und dass ihr um sie wetteifert, wie sie um sie wetteiferten, und dass sie euch zugrunde richtet, wie sie sie zugrunde richtete.` },
  "4016": { en: String.raw`Abu al-Numan narrated to us. Jarir ibn Hazim narrated to us, from Nafi, that Ibn Umar, may Allah be pleased with them both, used to kill every snake until Abu Lubaba al-Badri told him that the Prophet (peace be upon him) prohibited killing the house snakes. Then he stopped killing them.`, de: String.raw`Abu an-Numan überlieferte uns. Dscharir ibn Hazim überlieferte uns, von Nafi, dass Ibn Umar, möge Allah mit ihnen beiden zufrieden sein, jede Schlange zu töten pflegte, bis Abu Lubaba al-Badri ihm mitteilte, dass der Prophet (Friede sei auf ihm) das Töten der Hausschlangen untersagt hatte. Da hörte er auf, sie zu töten.` },
  "4018": { en: String.raw`Ibrahim ibn al-Mundhir narrated to me. Muhammad ibn Fulayh narrated to us, from Musa ibn Uqba. Ibn Shihab narrated to us that Anas ibn Malik said: Some men from the Ansar asked the Messenger of Allah (peace be upon him) for permission, saying: Permit us to waive the ransom of our nephew Abbas. He said: By Allah, you will not leave him even a dirham.`, de: String.raw`Ibrahim ibn al-Mundhir berichtete mir. Muhammad ibn Fulayh überlieferte uns, von Musa ibn Uqba. Ibn Schihab überlieferte uns, dass Anas ibn Malik sagte: Einige Männer der Ansar baten den Gesandten Allahs (Friede sei auf ihm) um Erlaubnis und sagten: Erlaube uns, auf das Lösegeld für unseren Neffen Abbas zu verzichten. Er sagte: Bei Allah, ihr werdet ihm nicht einmal einen Dirham erlassen.` },
  "4019": { en: String.raw`Abu Asim narrated to us, from Ibn Jurayj, from al-Zuhri, from Ata ibn Yazid, from Ubayd Allah ibn Adi, from al-Miqdad ibn al-Aswad. Ishaq narrated to me. Yaqub ibn Ibrahim ibn Sad narrated to us. The nephew of Ibn Shihab narrated to us, from his uncle, who said: Ata ibn Yazid al-Laythi, then al-Jundai, informed me that Ubayd Allah ibn Adi ibn al-Khiyar informed him that al-Miqdad ibn Amr al-Kindi, an ally of Banu Zuhra who had witnessed Badr with the Messenger of Allah (peace be upon him), told him: I said to the Messenger of Allah (peace be upon him): What do you think if I meet a disbeliever and we fight, and he strikes one of my hands with the sword and cuts it off, then takes refuge behind a tree from me and says: I submit to Allah? May I kill him, O Messenger of Allah, after he has said that? The Messenger of Allah (peace be upon him) said: Do not kill him. I said: O Messenger of Allah, he cut off one of my hands, then said that after cutting it off. The Messenger of Allah (peace be upon him) said: Do not kill him. If you kill him, he will have your status before you kill him, and you will have his status before he said the words he said.`, de: String.raw`Abu Asim überlieferte uns, von Ibn Dschuraidsch, von az-Zuhri, von Ata ibn Yazid, von Ubayd Allah ibn Adi, von al-Miqdad ibn al-Aswad. Ishaq berichtete mir. Yaqub ibn Ibrahim ibn Sad überlieferte uns. Der Neffe von Ibn Schihab überlieferte uns, von seinem Onkel, der sagte: Ata ibn Yazid al-Laythi, dann al-Dschundai, berichtete mir, dass Ubayd Allah ibn Adi ibn al-Khiyar ihm mitteilte, dass al-Miqdad ibn Amr al-Kindi, ein Verbündeter der Banu Zuhra, der Badr mit dem Gesandten Allahs (Friede sei auf ihm) miterlebt hatte, ihm berichtete: Ich sagte zum Gesandten Allahs (Friede sei auf ihm): Was meinst du, wenn ich einen Ungläubigen treffe und wir kämpfen, er eine meiner Hände mit dem Schwert schlägt und sie abschneidet, sich dann hinter einem Baum vor mir verbirgt und sagt: Ich ergebe mich Allah? Darf ich ihn töten, o Gesandter Allahs, nachdem er das gesagt hat? Der Gesandte Allahs (Friede sei auf ihm) sagte: Töte ihn nicht. Ich sagte: O Gesandter Allahs, er hat eine meiner Hände abgetrennt und dies erst gesagt, nachdem er sie abgetrennt hatte. Der Gesandte Allahs (Friede sei auf ihm) sagte: Töte ihn nicht. Wenn du ihn tötest, wird er vor deinem Töten deinen Rang haben, und du wirst vor dem von ihm gesprochenen Wort seinen Rang haben.` },
  "4020": { en: String.raw`Yaqub ibn Ibrahim narrated to me. Ibn Ulayya narrated to us. Sulayman al-Taymi narrated to us. Anas, may Allah be pleased with him, narrated to us that the Messenger of Allah (peace be upon him) said on the day of Badr: Who will see what Abu Jahl has done? Ibn Masud went and found that the two sons of Afra had struck him until he was cold. He said: Are you Abu Jahl? Ibn Ulayya said: Sulayman said that Anas said it this way. He said: You are Abu Jahl. Abu Jahl said: Is there anyone above a man you have killed? Sulayman said: Or he said: whom his people killed. Abu Mijlaz said: Abu Jahl said: If only a farmer and not someone else had killed me.`, de: String.raw`Yaqub ibn Ibrahim berichtete mir. Ibn Ulayya überlieferte uns. Sulayman at-Taymi überlieferte uns. Anas, möge Allah mit ihm zufrieden sein, berichtete uns, dass der Gesandte Allahs (Friede sei auf ihm) am Tag von Badr sagte: Wer sieht nach, was Abu Dschahl getan hat? Ibn Masud ging und fand ihn vor, nachdem die beiden Söhne von Afra ihn geschlagen hatten, bis er kalt war. Er sagte: Bist du Abu Dschahl? Ibn Ulayya sagte: Sulayman sagte, dass Anas es so gesagt hatte. Er sagte: Du bist Abu Dschahl. Abu Dschahl sagte: Gibt es jemanden über einem Mann, den ihr getötet habt? Sulayman sagte: Oder er sagte: den sein Volk getötet hat. Abu Midschlas sagte: Abu Dschahl sagte: Wenn mich doch nur ein Bauer und niemand sonst getötet hätte.` },
  "4021": { en: String.raw`Musa narrated to us. Abd al-Wahid narrated to us. Ma'mar narrated to us, from al-Zuhri, from Ubayd Allah ibn Abd Allah. Ibn Abbas narrated to me, from Umar, may Allah be pleased with them, who said: When the Prophet (peace be upon him) died, I said to Abu Bakr: Let us go to our brothers from the Ansar. Two righteous men from them, who had witnessed Badr, met us. I told Urwa ibn al-Zubayr, and he said: They were Uwaym ibn Saida and Maan ibn Adi.`, de: String.raw`Musa überlieferte uns. Abd al-Wahid überlieferte uns. Ma'mar überlieferte uns, von az-Zuhri, von Ubayd Allah ibn Abd Allah. Ibn Abbas berichtete mir von Umar, möge Allah mit ihnen zufrieden sein, der sagte: Als der Prophet (Friede sei auf ihm) starb, sagte ich zu Abu Bakr: Lass uns zu unseren Brüdern von den Ansar gehen. Zwei rechtschaffene Männer von ihnen, die Badr miterlebt hatten, trafen uns. Ich berichtete es Urwa ibn az-Zubayr, und er sagte: Es waren Uwaym ibn Saida und Maan ibn Adi.` }
};

const out = raw.map((row) => {
  const n = row.url.split(":").pop()!;
  const v = t[n];
  if (!v) throw new Error("missing " + n);
  return { id: row.id, n, en: v.en, de: v.de };
});
fs.writeFileSync("data/hadith-words-translations/codex-out-095.json", JSON.stringify(out, null, 2) + "\n", "utf8");
console.log("wrote " + out.length + " translations");
