import fs from 'fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-193.json','utf8'));
const tr:Record<string,[string,string]>={
'https://sunnah.com/muslim:204a':[ `Qutayba ibn Sa'id and Zuhayr ibn Harb narrated to us. They said: Jarir narrated to us, from Abd al-Malik ibn Umayr, from Musa ibn Talha, from Abu Hurayra, who said: When this verse was revealed, (Quran 26:214) Warn your nearest relatives, the Messenger of Allah (peace be upon him) called Quraysh, and they gathered. He addressed the general and the specific, saying: O children of Ka'b ibn Lu'ayy, save yourselves from the Fire. O children of Murra ibn Ka'b, save yourselves from the Fire. O children of Abd Shams, save yourselves from the Fire. O children of Abd Manaf, save yourselves from the Fire. O children of Hashim, save yourselves from the Fire. O children of Abd al-Muttalib, save yourselves from the Fire. O Fatima, save yourself from the Fire, for I cannot avail you against Allah in anything, except that you have a tie of kinship which I will maintain according to its due.`, `Qutayba ibn Sa'id und Zuhayr ibn Harb überlieferten uns. Sie sagten: Jarir überlieferte uns, von Abd al-Malik ibn Umayr, von Musa ibn Talha, von Abu Hurayra, der sagte: Als dieser Vers offenbart wurde, (Quran 26:214) Warne deine nächsten Verwandten, rief der Gesandte Allahs (Friede sei auf ihm) die Quraisch, und sie versammelten sich. Er sprach die Allgemeinheit und die Einzelnen an und sagte: O Kinder von Ka'b ibn Lu'ayy, rettet euch vor dem Feuer. O Kinder von Murra ibn Ka'b, rettet euch vor dem Feuer. O Kinder von Abd Schams, rettet euch vor dem Feuer. O Kinder von Abd Manaf, rettet euch vor dem Feuer. O Kinder von Haschim, rettet euch vor dem Feuer. O Kinder von Abd al-Muttalib, rettet euch vor dem Feuer. O Fatima, rette dich vor dem Feuer, denn ich kann euch gegenüber Allah in nichts nützen, außer dass ihr ein Verwandtschaftsband habt, das ich gemäß seinem Recht pflegen werde.`],
'https://sunnah.com/muslim:204b':[ `Ubayd Allah ibn Umar al-Qawariri narrated to us. Abu Awana narrated to us, from Abd al-Malik ibn Umayr, with this chain. Jarir's hadith is more complete and fuller.`, `Ubayd Allah ibn Umar al-Qawariri überlieferte uns. Abu Awana überlieferte uns, von Abd al-Malik ibn Umayr, mit dieser Überlieferungskette. Der Hadith von Jarir ist vollständiger und ausführlicher.`],
'https://sunnah.com/muslim:205':[ `Muhammad ibn Abdullah ibn Numayr narrated to us. Waki' and Yunus ibn Bukayr narrated to us. They said: Hisham ibn Urwa narrated to us, from his father, from Aisha, who said: When this verse was revealed, (Quran 26:214) Warn your nearest relatives, the Messenger of Allah (peace be upon him) stood on al-Safa and said: O Fatima daughter of Muhammad, O Safiyya daughter of Abd al-Muttalib, O children of Abd al-Muttalib, I cannot avail you against Allah in anything. Ask me from my wealth whatever you wish.`, `Muhammad ibn Abd Allah ibn Numayr überlieferte uns. Waki' und Yunus ibn Bukayr überlieferten uns. Sie sagten: Hischam ibn Urwa überlieferte uns, von seinem Vater, von Aischa, die sagte: Als dieser Vers offenbart wurde, (Quran 26:214) Warne deine nächsten Verwandten, stand der Gesandte Allahs (Friede sei auf ihm) auf as-Safa und sagte: O Fatima, Tochter Muhammads, o Safiyya, Tochter Abd al-Muttalibs, o Kinder von Abd al-Muttalib, ich kann euch gegenüber Allah in nichts nützen. Bittet mich um etwas von meinem Besitz, was ihr wollt.`],
'https://sunnah.com/muslim:206a':[ `Harmala ibn Yahya narrated to me. Ibn Wahb informed us. He said: Yunus informed me, from Ibn Shihab. He said: Ibn al-Musayyab and Abu Salama ibn Abd al-Rahman informed me that Abu Hurayra said: When the verse (Quran 26:214) Warn your nearest relatives was revealed to him, the Messenger of Allah (peace be upon him) said: O Quraysh, purchase your souls from Allah. I cannot avail you against Allah in anything. O children of Abd al-Muttalib, I cannot avail you against Allah in anything. O Abbas ibn Abd al-Muttalib, I cannot avail you against Allah in anything. O Safiyya, aunt of the Messenger of Allah, I cannot avail you against Allah in anything. O Fatima daughter of the Messenger of Allah, ask me for whatever you wish; I cannot avail you against Allah in anything.`, `Harmala ibn Yahya überlieferte mir. Ibn Wahb berichtete uns. Er sagte: Yunus berichtete mir, von Ibn Schihab. Er sagte: Ibn al-Musayyab und Abu Salama ibn Abd ar-Rahman berichteten mir, dass Abu Hurayra sagte: Als ihm der Vers (Quran 26:214) Warne deine nächsten Verwandten offenbart wurde, sagte der Gesandte Allahs (Friede sei auf ihm): O Quraisch, kauft euch bei Allah los. Ich kann euch gegenüber Allah in nichts nützen. O Kinder von Abd al-Muttalib, ich kann euch gegenüber Allah in nichts nützen. O Abbas ibn Abd al-Muttalib, ich kann dir gegenüber Allah in nichts nützen. O Safiyya, Tante des Gesandten Allahs, ich kann dir gegenüber Allah in nichts nützen. O Fatima, Tochter des Gesandten Allahs, bitte mich um alles, was du willst; ich kann dir gegenüber Allah in nichts nützen.`],
'https://sunnah.com/muslim:206b':[ `Amr the Critic narrated to me. Muawiya ibn Amr narrated to us. Za'ida narrated to us. Abdullah ibn Dhakwan narrated to us, from al-A'raj, from Abu Hurayra, from the Prophet (peace be upon him), with something similar.`, `Amr, der Kritiker, überlieferte mir. Mu'awiya ibn Amr überlieferte uns. Za'ida überlieferte uns. Abd Allah ibn Dhakwan überlieferte uns, von al-A'raj, von Abu Hurayra, vom Propheten (Friede sei auf ihm), mit etwas Ähnlichem.`],
'https://sunnah.com/muslim:207a':[ `Abu Kamil al-Jahdari narrated to us. Yazid ibn Zuray narrated to us. al-Taymi narrated to us, from Abu Uthman, from Qabisa ibn al-Mukhariq and Zuhayr ibn Amr, who said: When (Quran 26:214) Warn your nearest relatives was revealed, the Prophet of Allah (peace be upon him) went to a rocky mound on a mountain, climbed to its highest stone, and called: O children of Abd Manaf! I am a warner. My example and yours is like that of a man who saw the enemy, set out to scout for his people, and feared that they would overtake him, so he began shouting: O morning danger!`, `Abu Kamil al-Dschahdari überlieferte uns. Yazid ibn Zuray überlieferte uns. at-Taymi überlieferte uns, von Abu Uthman, von Qabisa ibn al-Muchariq und Zuhayr ibn Amr, die sagten: Als (Quran 26:214) Warne deine nächsten Verwandten offenbart wurde, ging der Prophet Allahs (Friede sei auf ihm) zu einem Felsenhügel eines Berges, stieg auf dessen höchsten Stein und rief: O Kinder von Abd Manaf! Ich bin ein Warner. Mein Beispiel und eures gleicht dem eines Mannes, der den Feind sah, losging, um für seine Leute Ausschau zu halten, und fürchtete, dass sie ihm zuvorkommen würden, sodass er zu rufen begann: O Gefahr am Morgen!`],
'https://sunnah.com/muslim:207b':[ `Muhammad ibn Abd al-A'la narrated to us. al-Mu'tamir narrated to us, from his father. Abu Uthman narrated to us, from Zuhayr ibn Amr and Qabisa ibn Mukhariq, from the Prophet (peace be upon him), with the same meaning.`, `Muhammad ibn Abd al-A'la überlieferte uns. al-Mu'tamir überlieferte uns, von seinem Vater. Abu Uthman überlieferte uns, von Zuhayr ibn Amr und Qabisa ibn Muchariq, vom Propheten (Friede sei auf ihm), mit derselben Bedeutung.`]
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,en:tr[r.url][0],de:tr[r.url][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-193-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-193-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
