import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:305c':{en:'Muhammad ibn al-Muthanna and Ibn Bashshar narrated to us. They said: Muhammad ibn Jafar narrated to us. Ubaydullah ibn Muadh also narrated to us. He said: My father narrated to us. Shuba narrated to us with this chain. Ibn al-Muthanna said in his hadith: al-Hakam narrated to us. I heard Ibrahim narrate.',de:'Muhammad ibn al-Muthanna und Ibn Bashshar überlieferten uns. Sie sagten: Muhammad ibn Jafar überlieferte uns. Auch Ubaydullah ibn Muadh überlieferte uns. Er sagte: Mein Vater überlieferte uns. Shuba überlieferte uns mit dieser Überlieferungskette. Ibn al-Muthanna sagte in seinem Hadith: al-Hakam überlieferte uns. Ich hörte Ibrahim überliefern.'},
'https://sunnah.com/muslim:306a':{en:'Muhammad ibn Abi Bakr al-Muqaddami and Zuhayr ibn Harb narrated to me. They said: Yahya, meaning ibn Said, narrated to us, from Ubaydullah. Abu Bakr ibn Abi Shayba and Ibn Numayr also narrated to us, and this is their wording. Ibn Numayr said: My father narrated to us, while Abu Bakr said: Abu Usama narrated to us. They both said: Ubaydullah narrated to us, from Nafi, from Ibn Umar, that Umar said: O Messenger of Allah, may one of us sleep while in a state of major ritual impurity? He said: Yes, if he performs wudu.',de:'Muhammad ibn Abi Bakr al-Muqaddami und Zuhayr ibn Harb überlieferten mir. Sie sagten: Yahya, gemeint ist ibn Said, überlieferte uns, von Ubaydullah. Auch Abu Bakr ibn Abi Shayba und Ibn Numayr überlieferten uns, und dies ist ihr Wortlaut. Ibn Numayr sagte: Mein Vater überlieferte uns, während Abu Bakr sagte: Abu Usama überlieferte uns. Beide sagten: Ubaydullah überlieferte uns, von Nafi, von Ibn Umar, dass Umar sagte: O Gesandter Allahs, darf einer von uns schlafen, während er sich im Zustand großer ritueller Unreinheit befindet? Er sagte: Ja, wenn er Wudu verrichtet.'},
'https://sunnah.com/muslim:306b':{en:'Muhammad ibn Rafi narrated to us. Abd al-Razzaq narrated to us, from Ibn Jurayj. Nafi informed me, from Ibn Umar, that Umar asked the Prophet (peace be upon him) for a ruling, saying: May one of us sleep while in a state of major ritual impurity? He said: Yes. Let him perform wudu and then sleep until he wishes to perform ghusl.',de:'Muhammad ibn Rafi überlieferte uns. Abd al-Razzaq überlieferte uns, von Ibn Jurayj. Nafi berichtete mir, von Ibn Umar, dass Umar den Propheten (Friede sei auf ihm) um eine Rechtsauskunft bat und sagte: Darf einer von uns schlafen, während er sich im Zustand großer ritueller Unreinheit befindet? Er sagte: Ja. Er soll Wudu verrichten und dann schlafen, bis er Ghusl verrichten möchte.'},
'https://sunnah.com/muslim:306c':{en:'Yahya ibn Yahya narrated to me. He said: I read to Malik, from Abdullah ibn Dinar, from Ibn Umar, who said: Umar ibn al-Khattab mentioned to the Messenger of Allah (peace be upon him) that major ritual impurity befell him during the night. The Messenger of Allah (peace be upon him) said to him: Perform wudu, wash your private part, and then sleep.',de:'Yahya ibn Yahya überlieferte mir. Er sagte: Ich las Malik vor, von Abdullah ibn Dinar, von Ibn Umar, der sagte: Umar ibn al-Khattab erwähnte gegenüber dem Gesandten Allahs (Friede sei auf ihm), dass ihn in der Nacht große rituelle Unreinheit befiel. Der Gesandte Allahs (Friede sei auf ihm) sagte zu ihm: Verrichte Wudu, wasche dein Geschlechtsteil und schlafe dann.'},
'https://sunnah.com/muslim:307a':{en:'Qutayba ibn Said narrated to us. Layth narrated to us, from Muawiya ibn Salih, from Abdullah ibn Abi Qays, who said: I asked Aisha about the Witr prayer of the Messenger of Allah (peace be upon him). He mentioned the hadith. I asked: What did he do when in a state of major ritual impurity? Did he perform ghusl before sleeping, or sleep before performing ghusl? She said: He did both. Sometimes he performed ghusl and slept, and sometimes he performed wudu and slept. I said: Praise belongs to Allah, who has made the matter broad.',de:'Qutayba ibn Said überlieferte uns. Layth überlieferte uns, von Muawiya ibn Salih, von Abdullah ibn Abi Qays, der sagte: Ich fragte Aisha nach dem Witr-Gebet des Gesandten Allahs (Friede sei auf ihm). Er erwähnte den Hadith. Ich fragte: Was tat er, wenn er sich im Zustand großer ritueller Unreinheit befand? Verrichtete er vor dem Schlafen Ghusl oder schlief er, bevor er Ghusl verrichtete? Sie sagte: Er tat beides. Manchmal verrichtete er Ghusl und schlief, und manchmal verrichtete er Wudu und schlief. Ich sagte: Lob gehört Allah, der die Angelegenheit weit gemacht hat.'},
'https://sunnah.com/muslim:307b':{en:'Zuhayr ibn Harb narrated it to me. Abd al-Rahman ibn Mahdi narrated to us. Harun ibn Said al-Ayli also narrated it to me: Ibn Wahb narrated to us. All of them narrated from Muawiya ibn Salih, with this chain, with the same wording.',de:'Zuhayr ibn Harb überlieferte ihn mir. Abd al-Rahman ibn Mahdi überlieferte uns. Auch Harun ibn Said al-Ayli überlieferte ihn mir: Ibn Wahb überlieferte uns. Alle überlieferten von Muawiya ibn Salih mit dieser Überlieferungskette und demselben Wortlaut.'},
'https://sunnah.com/muslim:308':{en:'Abu Bakr ibn Abi Shayba narrated to us. Hafs ibn Ghiyath narrated to us. Abu Kurayb also narrated to us: Ibn Abi Zaida informed us. Amr al-Naqid and Ibn Numayr also narrated to us. They said: Marwan ibn Muawiya al-Fazari narrated to us. All of them narrated from Asim, from Abu al-Mutawakkil, from Abu Said al-Khudri, who said: The Messenger of Allah (peace be upon him) said: When one of you has relations with his wife and then wants to return to her, let him perform wudu between the two occasions. Abu Bakr added in his hadith: with a wudu between them, and said: then wants to have relations again.',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Hafs ibn Ghiyath überlieferte uns. Auch Abu Kurayb überlieferte uns: Ibn Abi Zaida berichtete uns. Auch Amr al-Naqid und Ibn Numayr überlieferten uns. Sie sagten: Marwan ibn Muawiya al-Fazari überlieferte uns. Alle überlieferten von Asim, von Abu al-Mutawakkil, von Abu Said al-Khudri, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn einer von euch mit seiner Frau Geschlechtsverkehr hatte und dann erneut mit ihr verkehren möchte, soll er zwischen den beiden Malen Wudu verrichten. Abu Bakr fügte in seinem Hadith hinzu: mit einer Wudu zwischen ihnen, und sagte: wenn er dann erneut Geschlechtsverkehr haben möchte.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-219-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-219-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
