import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-207.json','utf8'));
const wanted=new Set(['https://sunnah.com/muslim:258','https://sunnah.com/muslim:259a','https://sunnah.com/muslim:259b','https://sunnah.com/muslim:259c','https://sunnah.com/muslim:260','https://sunnah.com/muslim:261a','https://sunnah.com/muslim:261b']);
const tr:any={
'https://sunnah.com/muslim:258':{en:'Yahya ibn Yahya and Qutayba ibn Sa\'id narrated to us, both from Ja\'far. Yahya said: Ja\'far ibn Sulayman informed us, from Abu Imran al-Jawni, from Anas ibn Malik. Anas said: A time limit was set for us regarding trimming the moustache, clipping the nails, plucking the armpit hair, and shaving the pubic hair: we must not leave any of them for more than forty nights.',de:'Yahya ibn Yahya und Qutayba ibn Sa\'id überlieferten uns, beide von Ja\'far. Yahya sagte: Ja\'far ibn Sulayman berichtete uns, von Abu Imran al-Jawni, von Anas ibn Malik. Anas sagte: Für das Kürzen des Schnurrbarts, das Schneiden der Nägel, das Auszupfen der Achselhaare und das Rasieren der Schamhaare wurde uns eine Frist gesetzt: Wir dürfen nichts davon länger als vierzig Nächte lassen.'},
'https://sunnah.com/muslim:259a':{en:'Muhammad ibn al-Muthanna narrated to us. Yahya, meaning ibn Sa\'id, narrated to us. Ibn Numayr also narrated to us: my father narrated to us, all from Ubaydullah, from Nafi\', from Ibn Umar, from the Prophet (peace be upon him), who said: Trim the moustaches closely and leave the beards.',de:'Muhammad ibn al-Muthanna überlieferte uns. Yahya, gemeint ist ibn Sa\'id, überlieferte uns. Auch Ibn Numayr überlieferte uns: Mein Vater überlieferte uns, alle von Ubaydullah, von Nafi\', von Ibn Umar, vom Propheten (Friede sei auf ihm), der sagte: Kürzt die Schnurrbärte gründlich und lasst die Bärte wachsen.'},
'https://sunnah.com/muslim:259b':{en:'Qutayba ibn Sa\'id narrated it to us, from Malik ibn Anas, from Abu Bakr ibn Nafi\', from his father, from Ibn Umar, from the Prophet (peace be upon him), that he ordered trimming the moustaches closely and leaving the beard.',de:'Qutayba ibn Sa\'id überlieferte ihn uns, von Malik ibn Anas, von Abu Bakr ibn Nafi\', von dessen Vater, von Ibn Umar, vom Propheten (Friede sei auf ihm), dass er befahl, die Schnurrbärte gründlich zu kürzen und den Bart wachsen zu lassen.'},
'https://sunnah.com/muslim:259c':{en:'Sahl ibn Uthman narrated to us. Yazid ibn Zuray narrated to us, from Umar ibn Muhammad. Nafi\' narrated to us, from Ibn Umar, who said: The Messenger of Allah (peace be upon him) said: Differ from the polytheists: trim the moustaches closely and let the beards grow fully.',de:'Sahl ibn Uthman überlieferte uns. Yazid ibn Zuray überlieferte uns, von Umar ibn Muhammad. Nafi\' überlieferte uns, von Ibn Umar, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Unterscheidet euch von den Götzendienern: Kürzt die Schnurrbärte gründlich und lasst die Bärte vollständig wachsen.'},
'https://sunnah.com/muslim:260':{en:'Abu Bakr ibn Ishaq narrated to me. Ibn Abi Maryam informed us. Muhammad ibn Ja\'far informed me. Al-Ala ibn Abd al-Rahman ibn Yaqub, the client of al-Huraqa, informed me, from his father, from Abu Hurayra, who said: The Messenger of Allah (peace be upon him) said: Cut the moustaches and let the beards grow. Differ from the Magians.',de:'Abu Bakr ibn Ishaq überlieferte mir. Ibn Abi Maryam berichtete uns. Muhammad ibn Ja\'far berichtete mir. Al-Ala ibn Abd al-Rahman ibn Yaqub, der Schutzbefohlene von al-Huraqa, berichtete mir, von seinem Vater, von Abu Hurayra, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Schneidet die Schnurrbärte und lasst die Bärte wachsen. Unterscheidet euch von den Magiern.'},
'https://sunnah.com/muslim:261a':{en:'Qutayba ibn Sa\'id, Abu Bakr ibn Abi Shayba, and Zuhayr ibn Harb narrated to us. They said: Waki narrated to us, from Zakariyya ibn Abi Zaida, from Musab ibn Shayba, from Talq ibn Habib, from Abdullah ibn al-Zubayr, from Aisha, who said: The Messenger of Allah (peace be upon him) said: Ten are part of the natural disposition: trimming the moustache, letting the beard grow, using the tooth-stick, drawing water into the nose, clipping the nails, washing the finger joints, plucking the armpit hair, shaving the pubic hair, and using water for cleansing. Zakariyya said: Musab said: I forgot the tenth, unless it was rinsing the mouth. Qutayba added: Waki said: Using water for cleansing means istinja.',de:'Qutayba ibn Sa\'id, Abu Bakr ibn Abi Shayba und Zuhayr ibn Harb überlieferten uns. Sie sagten: Waki überlieferte uns, von Zakariyya ibn Abi Zaida, von Musab ibn Shayba, von Talq ibn Habib, von Abdullah ibn al-Zubayr, von Aisha, die sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Zehn Dinge gehören zur natürlichen Veranlagung: den Schnurrbart kürzen, den Bart wachsen lassen, den Siwak benutzen, Wasser in die Nase ziehen, die Nägel schneiden, die Fingerknöchel waschen, die Achselhaare auszupfen, die Schamhaare rasieren und Wasser zur Reinigung verwenden. Zakariyya sagte: Musab sagte: Ich habe das zehnte vergessen, außer wenn es das Spülen des Mundes war. Qutayba fügte hinzu: Waki sagte: Wasser zur Reinigung zu verwenden bedeutet Istinja.'},
'https://sunnah.com/muslim:261b':{en:'Abu Kurayb narrated it to us. Ibn Abi Zaida informed us, from his father, from Musab ibn Shayba, with this chain, with the same wording, except that he said: His father said: I forgot the tenth.',de:'Abu Kurayb überlieferte ihn uns. Ibn Abi Zaida berichtete uns, von seinem Vater, von Musab ibn Shayba, mit dieser Überlieferungskette und demselben Wortlaut, außer dass er sagte: Sein Vater sagte: Ich habe das zehnte vergessen.'}
};
const out=rows.filter(r=>wanted.has(r.url)).map(r=>({...r,...tr[r.url]}));
if(out.length!==wanted.size) throw new Error(`expected ${wanted.size}, got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-207-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-207-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
