import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:Record<string,{en:string;de:string}>={
'https://sunnah.com/muslim:410d':{en:'Abdullah ibn Maslama al-Qanabi narrated to us. al-Mughira narrated to us, from Abu al-Zinad, from al-Araj, from Abu Hurayra, who said: The Messenger of Allah (peace be upon him) said: When one of you says Amin and the angels in heaven say Amin, and one of them coincides with the other, his previous sins will be forgiven.',de:'Abdullah ibn Maslama al-Qanabi überlieferte uns. al-Mughira überlieferte uns, von Abu al-Zinad, von al-Araj, von Abu Hurayra, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn einer von euch „Amin“ sagt und die Engel im Himmel „Amin“ sagen und eines mit dem anderen übereinstimmt, werden ihm seine früheren Sünden vergeben.'},
'https://sunnah.com/muslim:410e':{en:'Muhammad ibn Rafi narrated to us. Abd al-Razzaq narrated to us. Mamar narrated to us, from Hammam ibn Munabbih, from Abu Hurayra, from the Prophet (peace be upon him), with the same meaning.',de:'Muhammad ibn Rafi überlieferte uns. Abd al-Razzaq überlieferte uns. Mamar überlieferte uns, von Hammam ibn Munabbih, von Abu Hurayra, vom Propheten (Friede sei auf ihm), mit derselben Bedeutung.'},
'https://sunnah.com/muslim:410f':{en:'Qutayba ibn Said narrated to us. Yaqob, meaning Ibn Abd al-Rahman, narrated to us, from Suhayl, from his father, from Abu Hurayra, that the Messenger of Allah (peace be upon him) said: When the reciter says, “Not those who have incurred anger, nor those who are astray,” and those behind him say Amin, and his words coincide with the words of the inhabitants of heaven, his previous sins will be forgiven.',de:'Qutayba ibn Said überlieferte uns. Yaqob, gemeint ist Ibn Abd al-Rahman, überlieferte uns, von Suhayl, von dessen Vater, von Abu Hurayra, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn der Rezitierende sagt: „Nicht derer, die Zorn auf sich gezogen haben, und nicht der Irregehenden“, und diejenigen hinter ihm „Amin“ sagen und seine Worte mit den Worten der Bewohner des Himmels übereinstimmen, werden ihm seine früheren Sünden vergeben.'},
'https://sunnah.com/muslim:411a':{en:'Yahya ibn Yahya, Qutayba ibn Said, Abu Bakr ibn Abi Shayba, Amr al-Naqid, Zuhayr ibn Harb, and Abu Kurayb all narrated from Sufyan. Abu Bakr said: Sufyan ibn Uyayna narrated to us, from al-Zuhri, who said: I heard Anas ibn Malik say: The Prophet (peace be upon him) fell from a horse and injured the right side of his body. We went to visit him. The prayer time came, and he led us in prayer while sitting, so we prayed behind him while sitting. When he finished the prayer, he said: The imam is appointed to be followed. When he says the takbir, say the takbir; when he prostrates, prostrate; when he rises, rise; and when he says, “Allah hears whoever praises Him,” say, “Our Lord, and to You belongs praise.” If he prays sitting, then all of you pray sitting.',de:'Yahya ibn Yahya, Qutayba ibn Said, Abu Bakr ibn Abi Shayba, Amr al-Naqid, Zuhayr ibn Harb und Abu Kurayb überlieferten alle von Sufyan. Abu Bakr sagte: Sufyan ibn Uyayna überlieferte uns, von al-Zuhri, der sagte: Ich hörte Anas ibn Malik sagen: Der Prophet (Friede sei auf ihm) fiel von einem Pferd und verletzte sich an der rechten Körperseite. Wir gingen, um ihn zu besuchen. Die Gebetszeit kam, und er leitete uns im Sitzen im Gebet, sodass wir hinter ihm im Sitzen beteten. Als er das Gebet beendet hatte, sagte er: Der Imam ist eingesetzt, damit ihm gefolgt wird. Wenn er den Takbir spricht, sprecht den Takbir; wenn er sich niederwirft, werft euch nieder; wenn er sich erhebt, erhebt euch; und wenn er sagt: „Allah hört den, der Ihn lobt“, sagt: „Unser Herr, und Dir gebührt das Lob.“ Wenn er im Sitzen betet, dann betet ihr alle im Sitzen.'},
'https://sunnah.com/muslim:411b':{en:'Qutayba ibn Said narrated to us. Layth narrated to us. And Muhammad ibn Rumh narrated to us. Layth informed us, from Ibn Shihab, from Anas ibn Malik, who said: The Messenger of Allah (peace be upon him) fell from a horse and was injured, so he led us in prayer while sitting. Then he mentioned something similar.',de:'Qutayba ibn Said überlieferte uns. Layth überlieferte uns. Und Muhammad ibn Rumh überlieferte uns. Layth berichtete uns, von Ibn Shihab, von Anas ibn Malik, der sagte: Der Gesandte Allahs (Friede sei auf ihm) fiel von einem Pferd und wurde verletzt, sodass er uns im Sitzen im Gebet leitete. Dann erwähnte er etwas Ähnliches.'},
'https://sunnah.com/muslim:411c':{en:'Harmala ibn Yahya informed us. Ibn Wahb informed us. Yunus informed me, from Ibn Shihab. Anas ibn Malik informed me that the Messenger of Allah (peace be upon him) fell from a horse and injured the right side of his body, with the meaning of their hadith, and he added: If he prays standing, then pray standing.',de:'Harmala ibn Yahya berichtete uns. Ibn Wahb berichtete uns. Yunus berichtete mir, von Ibn Shihab. Anas ibn Malik berichtete mir, dass der Gesandte Allahs (Friede sei auf ihm) von einem Pferd fiel und sich an der rechten Körperseite verletzte, mit der Bedeutung ihres Hadith, und er fügte hinzu: Wenn er im Stehen betet, dann betet im Stehen.'},
'https://sunnah.com/muslim:411d':{en:'Ibn Abi Umar narrated to us. Maan ibn Isa narrated to us, from Malik ibn Anas, from al-Zuhri, from Anas, that the Messenger of Allah (peace be upon him) rode a horse, fell from it, and injured the right side of his body, with the meaning of their hadith. It contains: If he prays standing, then pray standing.',de:'Ibn Abi Umar überlieferte uns. Maan ibn Isa überlieferte uns, von Malik ibn Anas, von al-Zuhri, von Anas, dass der Gesandte Allahs (Friede sei auf ihm) auf einem Pferd ritt, von ihm fiel und sich an der rechten Körperseite verletzte, mit der Bedeutung ihres Hadith. Darin heißt es: Wenn er im Stehen betet, dann betet im Stehen.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]})); if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-251-part.json',JSON.stringify(out,null,2)); fs.writeFileSync('data/hadith-words-translations/codex-out-251-part.json',JSON.stringify(out,null,2)); console.log(`wrote ${out.length} staged translations`);
