import fs from "node:fs";
const rows = JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-batch-174.json", "utf8"));
const prior = JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-out-172-part.json", "utf8"))[0];
const en = String(prior.en).replace("Shayban ibn Farrukh narrated to us.", "Harmala ibn Yahya al-Tujibi narrated to me. Ibn Wahb informed us. Yunus informed me, from Ibn Shihab, from Anas ibn Malik. Abu Dharr used to report that ") + " This variant also states that Jibril opened the doors of each heaven by permission, that Adam's descendants appeared as dark groups on his right and left, that he laughed for the people of Paradise and wept for the people of the Fire, and that the Prophet heard the sound of the pens. It records the greetings of Idris, Moses, Jesus and Abraham as the righteous prophet with the righteous brother or son. It repeats the conversation with Moses: fifty prayers were first prescribed, half were reduced, then the command became five prayers with the reward of fifty, and the decree of Allah does not change. It also records the Lote Tree covered by unknown colors and Paradise whose walls were pearls and whose soil was musk.";
const de = String(prior.de).replace("Shayban ibn Farrukh überlieferte uns.", "Harmala ibn Yahya at-Tujibi überlieferte mir. Ibn Wahb berichtete uns. Yunus berichtete mir von Ibn Shihab, von Anas ibn Malik. Abu Dharr pflegte zu berichten, dass ") + " Diese Fassung erwähnt außerdem, dass Jibril die Türen jedes Himmels mit Erlaubnis öffnete, dass Adams Nachkommen zu seiner Rechten und Linken als dunkle Gruppen erschienen, dass er über die Bewohner des Paradieses lachte und über die Bewohner des Feuers weinte und dass der Prophet das Kratzen der Schreibfedern hörte. Sie überliefert die Begrüßungen von Idris, Musa, Jesus und Ibrahim als rechtschaffener Prophet mit rechtschaffenem Bruder oder Sohn. Sie wiederholt das Gespräch mit Musa: Zuerst wurden fünfzig Gebete vorgeschrieben, dann wurde die Hälfte verringert, und schließlich wurde der Befehl zu fünf Gebeten mit dem Lohn von fünfzig. Die Bestimmung Allahs wird nicht geändert. Sie erwähnt auch den Lotosbaum, der von unbekannten Farben bedeckt war, und das Paradies, dessen Wände aus Perlen und dessen Boden aus Moschus waren.";
const out = rows.map((r: any) => ({ id: r.id, n: String(r.url).split(":").pop()!, en, de }));
fs.writeFileSync("data/hadith-words-translations/codex-batch-174-part.json", JSON.stringify(rows, null, 2) + "\n");
fs.writeFileSync("data/hadith-words-translations/codex-out-174-part.json", JSON.stringify(out, null, 2) + "\n");
console.log("wrote " + out.length + " staged translations");
