import fs from 'node:fs';
const rows=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8')) as Array<{id:string,url:string}>;
const t:Record<string,[string,string]>= {
 'https://sunnah.com/muslim:588e':["Muhammad ibn Abbad narrated to us. Sufyan narrated to us, from Ibn Tawus, from his father, from Abu Hurayra, from the Prophet (peace be upon him), with the same meaning.","Muhammad ibn Abbad überlieferte uns. Sufyan überlieferte uns, von Ibn Tawus, von seinem Vater, von Abu Hurayra, vom Propheten (Friede sei auf ihm), mit derselben Bedeutung."],
 'https://sunnah.com/muslim:588f':["Muhammad ibn Abbad, Abu Bakr ibn Abi Shayba, and Zuhayr ibn Harb narrated to us. They said: Sufyan narrated to us, from Abu al-Zinad, from al-A'raj, from Abu Hurayra, from the Prophet (peace be upon him), with the same meaning.","Muhammad ibn Abbad, Abu Bakr ibn Abi Shayba und Zuhayr ibn Harb überlieferten uns. Sie sagten: Sufyan überlieferte uns, von Abu al-Zinad, von al-A'raj, von Abu Hurayra, vom Propheten (Friede sei auf ihm), mit derselben Bedeutung."],
 'https://sunnah.com/muslim:588g':["Muhammad ibn al-Muthanna narrated to us. Muhammad ibn Ja'far narrated to us. Shu'ba narrated to us, from Budayl, from Abdullah ibn Shaqiq, from Abu Hurayra, from the Prophet (peace be upon him), that he used to seek refuge from the punishment of the grave, the punishment of Hell, and the trial of the Dajjal.","Muhammad ibn al-Muthanna überlieferte uns. Muhammad ibn Ja'far überlieferte uns. Shu'ba überlieferte uns, von Budayl, von Abdullah ibn Shaqiq, von Abu Hurayra, vom Propheten (Friede sei auf ihm), dass er bei Allah um Schutz vor der Strafe des Grabes, der Strafe der Hölle und der Prüfung des Dajjal zu bitten pflegte."],
 'https://sunnah.com/muslim:589':["Abu Bakr ibn Ishaq narrated to me. Abu al-Yaman informed us. Shu'ayb informed us, from al-Zuhri. He said: Urwa ibn al-Zubayr informed me that Aisha, the wife of the Prophet (peace be upon him), informed him that the Prophet (peace be upon him) used to supplicate in prayer: O Allah, I seek refuge with You from the punishment of the grave. I seek refuge with You from the trial of the Dajjal. I seek refuge with You from the trial of life and death. O Allah, I seek refuge with You from sin and debt. Someone said to him: How often you seek refuge from debt, O Messenger of Allah. He said: When a man becomes indebted, he speaks and lies, and he makes a promise and breaks it.","Abu Bakr ibn Ishaq überlieferte mir. Abu al-Yaman berichtete uns. Shu'ayb berichtete uns, von al-Zuhri. Er sagte: Urwa ibn al-Zubayr berichtete mir, dass Aisha, die Ehefrau des Propheten (Friede sei auf ihm), ihm berichtete, dass der Prophet (Friede sei auf ihm) im Gebet zu bitten pflegte: O Allah, ich suche bei Dir Zuflucht vor der Strafe des Grabes. Ich suche bei Dir Zuflucht vor der Prüfung des Dajjal. Ich suche bei Dir Zuflucht vor der Prüfung des Lebens und des Todes. O Allah, ich suche bei Dir Zuflucht vor Sünde und Schuld. Jemand sagte zu ihm: Wie oft du doch vor Schuld Zuflucht suchst, Gesandter Allahs. Er sagte: Wenn ein Mann verschuldet ist, spricht er und lügt, und er verspricht und bricht sein Versprechen."],
 'https://sunnah.com/muslim:589b':["Abu Bakr ibn Abi Shayba and Abu Kurayb narrated to us, and this is Abu Bakr's wording. They said: Ibn Numayr narrated to us. Hisham narrated to us, from his father, from Aisha, that the Messenger of Allah (peace be upon him) used to supplicate with these supplications: O Allah, I seek refuge with You from the trial of the Fire and its punishment, from the trial of the grave and its punishment, from the evil of the trial of wealth and the evil of the trial of poverty. I seek refuge with You from the evil of the trial of the Dajjal. O Allah, wash away my sins with the water of snow and hail, purify my heart of sins as You purified the white garment of filth, and distance me from my sins as You distanced the east from the west. O Allah, I seek refuge with You from laziness, old age, sin, and debt.","Abu Bakr ibn Abi Shayba und Abu Kurayb überlieferten uns, und dies ist die Fassung von Abu Bakr. Sie sagten: Ibn Numayr überlieferte uns. Hisham überlieferte uns, von seinem Vater, von Aisha, dass der Gesandte Allahs (Friede sei auf ihm) mit diesen Bittgebeten zu bitten pflegte: O Allah, ich suche bei Dir Zuflucht vor der Prüfung des Feuers und seiner Strafe, vor der Prüfung des Grabes und seiner Strafe, vor dem Übel der Prüfung des Reichtums und vor dem Übel der Prüfung der Armut. Ich suche bei Dir Zuflucht vor dem Übel der Prüfung des Dajjal. O Allah, wasche meine Sünden mit dem Wasser von Schnee und Hagel ab, reinige mein Herz von Sünden, wie Du das weiße Kleidungsstück vom Schmutz gereinigt hast, und entferne mich von meinen Sünden, wie Du den Osten vom Westen entfernt hast. O Allah, ich suche bei Dir Zuflucht vor Faulheit, Altersschwäche, Sünde und Schuld."],
 'https://sunnah.com/muslim:589c':["Abu Kurayb narrated to us. Abu Muawiya and Waki narrated to us, from Hisham, with this chain.","Abu Kurayb überlieferte uns. Abu Muawiya und Waki überlieferten uns, von Hisham, mit dieser Überliefererkette."],
 'https://sunnah.com/muslim:590':["Qutayba ibn Sa'id narrated to us, from Malik ibn Anas, from Abu al-Zubayr, from Tawus, from Ibn Abbas, that the Messenger of Allah (peace be upon him) used to teach them this supplication just as he taught them a surah from the Quran: Say: O Allah, we seek refuge with You from the punishment of Hell, and we seek refuge with You from the punishment of the grave, and we seek refuge with You from the trial of the Dajjal, and we seek refuge with You from the trial of life and death. Muslim ibn al-Hajjaj said: It reached me that Tawus said to his son: Did you make this supplication in your prayer? He said: No. He said: Repeat your prayer, because Tawus narrated it from three or four, or as he said.","Qutayba ibn Sa'id überlieferte uns, von Malik ibn Anas, von Abu al-Zubayr, von Tawus, von Ibn Abbas, dass der Gesandte Allahs (Friede sei auf ihm) sie dieses Bittgebet zu lehren pflegte, wie er sie eine Sure aus dem Quran lehrte: Sagt: O Allah, wir suchen bei Dir Zuflucht vor der Strafe der Hölle, wir suchen bei Dir Zuflucht vor der Strafe des Grabes, wir suchen bei Dir Zuflucht vor der Prüfung des Dajjal und wir suchen bei Dir Zuflucht vor der Prüfung des Lebens und des Todes. Muslim ibn al-Hajjaj sagte: Mich erreichte, dass Tawus zu seinem Sohn sagte: Hast du dieses Bittgebet in deinem Gebet gesprochen? Er sagte: Nein. Er sagte: Wiederhole dein Gebet, denn Tawus überlieferte es von drei oder vier, oder wie er sagte."],
 'https://sunnah.com/muslim:591':["Dawud ibn Rushayd narrated to us. al-Walid narrated to us, from al-Awzai, from Abu Ammar, whose name was Shaddad ibn Abdullah, from Abu Asma, from Thawban. He said: When the Messenger of Allah (peace be upon him) finished his prayer, he sought forgiveness three times and said: O Allah, You are peace and peace comes from You. Blessed are You, Possessor of majesty and honor. al-Walid said: I said to al-Awzai: How is seeking forgiveness? He said: You say: I seek Allah's forgiveness, I seek Allah's forgiveness.","Dawud ibn Rushayd überlieferte uns. al-Walid überlieferte uns, von al-Awzai, von Abu Ammar, dessen Name Shaddad ibn Abdullah war, von Abu Asma, von Thawban. Er sagte: Wenn der Gesandte Allahs (Friede sei auf ihm) sein Gebet beendet hatte, bat er dreimal um Vergebung und sagte: O Allah, Du bist der Friede und von Dir kommt der Friede. Gesegnet bist Du, Besitzer der Majestät und Ehre. al-Walid sagte: Ich sagte zu al-Awzai: Wie bittet man um Vergebung? Er sagte: Du sagst: Ich bitte Allah um Vergebung, ich bitte Allah um Vergebung."],
 'https://sunnah.com/muslim:592a':["Abu Bakr ibn Abi Shayba and Ibn Numayr narrated to us. They said: Abu Muawiya narrated to us, from Asim, from Abdullah ibn al-Harith, from Aisha. She said: When the Prophet (peace be upon him) said the taslim, he would not remain seated except for the time it took to say: O Allah, You are peace and peace comes from You. Blessed are You, Possessor of majesty and honor. In Ibn Numayr's narration: O Possessor of majesty and honor.","Abu Bakr ibn Abi Shayba und Ibn Numayr überlieferten uns. Sie sagten: Abu Muawiya überlieferte uns, von Asim, von Abdullah ibn al-Harith, von Aisha. Sie sagte: Wenn der Prophet (Friede sei auf ihm) den Taslim gesprochen hatte, blieb er nur so lange sitzen, wie es dauerte zu sagen: O Allah, Du bist der Friede und von Dir kommt der Friede. Gesegnet bist Du, Besitzer der Majestät und Ehre. In der Überlieferung von Ibn Numayr: O Besitzer der Majestät und Ehre."],
 'https://sunnah.com/muslim:592b':["Ibn Numayr narrated to us. Abu Khalid, meaning al-Ahmar, narrated to us, from Asim, with this chain, and he said: O Possessor of majesty and honor.","Ibn Numayr überlieferte uns. Abu Khalid, das heißt al-Ahmar, überlieferte uns, von Asim, mit dieser Überliefererkette, und er sagte: O Besitzer der Majestät und Ehre."]
};
const out=rows.slice(0,10).map(r=>{const x=t[r.url];if(!x)throw Error(r.url);return {id:r.id,url:r.url,en:x[0],de:x[1]};});
fs.writeFileSync('data/hadith-words-translations/codex-batch-274-part.json',JSON.stringify(rows.slice(0,10),null,2)+'\n');
fs.writeFileSync('data/hadith-words-translations/codex-out-274-part.json',JSON.stringify(out,null,2)+'\n');
console.log(`translated=${out.length}`);
