import fs from 'node:fs';
const rows = JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json', 'utf8')) as Array<{id:string,url:string}>;
const t: Record<string,[string,string]> = {
 'https://sunnah.com/muslim:572b':["Abu Kurayb narrated to us. Ibn Bishr narrated to us. H He said: Muhammad ibn Hatim narrated to me. Waki' narrated to us, both of them from Mis'ar, from Mansur, with this chain. In Ibn Bishr's narration: Let him seek what is more likely to be correct. In Waki's narration: Let him seek the correct answer.","Abu Kurayb überlieferte uns. Ibn Bishr überlieferte uns. H Er sagte: Muhammad ibn Hatim überlieferte mir. Waki' überlieferte uns, beide von Mis'ar, von Mansur, mit dieser Überliefererkette. In der Überlieferung von Ibn Bishr heißt es: Er soll das suchen, was eher richtig ist. In der Überlieferung von Waki' heißt es: Er soll die richtige Antwort suchen."],
 'https://sunnah.com/muslim:572c':["Abdullah ibn Abd al-Rahman al-Darimi narrated to us. Yahya ibn Hassan informed us. Wuhaib ibn Khalid narrated to us. Mansur narrated to us with this chain, and Mansur said: Let him seek what is more likely to be correct.","Abdullah ibn Abd al-Rahman al-Darimi überlieferte uns. Yahya ibn Hassan berichtete uns. Wuhaib ibn Khalid überlieferte uns. Mansur überlieferte uns mit dieser Überliefererkette, und Mansur sagte: Er soll das suchen, was eher richtig ist."],
 'https://sunnah.com/muslim:572d':["Ishaq ibn Ibrahim narrated to us. Ubayd ibn Sa'id al-Umawi informed us. Sufyan narrated to us, from Mansur, with this chain, and he said: Let him seek the correct answer.","Ishaq ibn Ibrahim überlieferte uns. Ubayd ibn Sa'id al-Umawi berichtete uns. Sufyan überlieferte uns, von Mansur, mit dieser Überliefererkette, und er sagte: Er soll die richtige Antwort suchen."],
 'https://sunnah.com/muslim:572e':["Muhammad ibn al-Muthanna narrated to us. Muhammad ibn Ja'far narrated to us. Shu'ba narrated to us, from Mansur, with this chain, and he said: Let him seek the answer closest to what is correct.","Muhammad ibn al-Muthanna überlieferte uns. Muhammad ibn Ja'far überlieferte uns. Shu'ba überlieferte uns, von Mansur, mit dieser Überliefererkette, und er sagte: Er soll die Antwort suchen, die dem Richtigen am nächsten ist."],
 'https://sunnah.com/muslim:572f':["Yahya ibn Yahya narrated to us. Fudayl ibn Iyad informed us, from Mansur, with this chain, and he said: Let him seek what appears to him to be correct.","Yahya ibn Yahya überlieferte uns. Fudayl ibn Iyad berichtete uns, von Mansur, mit dieser Überliefererkette, und er sagte: Er soll das suchen, was ihm richtig erscheint."],
 'https://sunnah.com/muslim:572g':["Ibn Abi Umar narrated to us. Abd al-Aziz ibn Abd al-Samad narrated to us, from Mansur, with the chain of these narrators, and he said: Let him seek the correct answer.","Ibn Abi Umar überlieferte uns. Abd al-Aziz ibn Abd al-Samad überlieferte uns, von Mansur, mit der Überliefererkette dieser Überlieferer, und er sagte: Er soll die richtige Antwort suchen."]
};
const out = rows.slice(0,6).map(r => { const x=t[r.url]; if(!x) throw new Error(r.url); return {id:r.id,url:r.url,en:x[0],de:x[1]}; });
fs.writeFileSync('data/hadith-words-translations/codex-batch-268-part.json', JSON.stringify(rows.slice(0,6), null, 2) + '\n');
fs.writeFileSync('data/hadith-words-translations/codex-out-268-part.json', JSON.stringify(out,null,2)+'\n');
console.log(`translated=${out.length}`);
