import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:321a':{en:'Harun ibn Said al-Ayli narrated to us. Ibn Wahb narrated to us. Makhrama ibn Bukayr informed me, from his father, from Abu Salama ibn Abd al-Rahman, who said: Aisha said: When the Messenger of Allah (peace be upon him) performed ghusl, he began with his right side. He poured water over it and washed it, then poured water with his right hand over the impurity on him and washed it away with his left hand. When he finished that, he poured water over his head. Aisha said: The Messenger of Allah (peace be upon him) and I used to perform ghusl from one vessel while we were both in a state of major ritual impurity.',de:'Harun ibn Said al-Ayli überlieferte uns. Ibn Wahb überlieferte uns. Makhrama ibn Bukayr berichtete mir, von seinem Vater, von Abu Salama ibn Abd al-Rahman, der sagte: Aisha sagte: Wenn der Gesandte Allahs (Friede sei auf ihm) Ghusl verrichtete, begann er mit seiner rechten Seite. Er goss Wasser darüber und wusch sie, dann goss er mit seiner rechten Hand Wasser über die Unreinheit an ihm und wusch sie mit seiner linken Hand ab. Als er damit fertig war, goss er Wasser über seinen Kopf. Aisha sagte: Der Gesandte Allahs (Friede sei auf ihm) und ich pflegten aus einem Gefäß Ghusl zu verrichten, während wir beide im Zustand großer ritueller Unreinheit waren.'},
'https://sunnah.com/muslim:321b':{en:'Muhammad ibn Rafi narrated to me. Shababa narrated to us. Layth narrated to us, from Yazid, from Irak, from Hafsa bint Abd al-Rahman ibn Abi Bakr, who was married to al-Mundhir ibn al-Zubayr, that Aisha informed her that she and the Prophet (peace be upon him) used to perform ghusl from one vessel holding three mudds or approximately that amount.',de:'Muhammad ibn Rafi überlieferte mir. Shababa überlieferte uns. Layth überlieferte uns, von Yazid, von Irak, von Hafsa bint Abd al-Rahman ibn Abi Bakr, die mit al-Mundhir ibn al-Zubayr verheiratet war, dass Aisha ihr berichtete, dass sie und der Prophet (Friede sei auf ihm) aus einem Gefäß Ghusl zu verrichten pflegten, das drei Mudd oder ungefähr diese Menge fasste.'},
'https://sunnah.com/muslim:321c':{en:'Abdullah ibn Maslama ibn Qanab narrated to us. He said: Aflah ibn Humayd narrated to us, from al-Qasim ibn Muhammad, from Aisha, who said: The Messenger of Allah (peace be upon him) and I used to perform ghusl from one vessel for major ritual impurity, with our hands taking turns in it.',de:'Abdullah ibn Maslama ibn Qanab überlieferte uns. Er sagte: Aflah ibn Humayd überlieferte uns, von al-Qasim ibn Muhammad, von Aisha, die sagte: Der Gesandte Allahs (Friede sei auf ihm) und ich pflegten wegen großer ritueller Unreinheit aus einem Gefäß Ghusl zu verrichten, wobei unsere Hände sich darin abwechselten.'},
'https://sunnah.com/muslim:321d':{en:'Yahya ibn Yahya informed us. Abu Khaythama informed us, from Asim al-Ahwal, from Muadha, from Aisha, who said: The Messenger of Allah (peace be upon him) and I used to perform ghusl from one vessel between us. He would hurry before me until I said: Leave some for me, leave some for me. She said: They were both in a state of major ritual impurity.',de:'Yahya ibn Yahya berichtete uns. Abu Khaythama berichtete uns, von Asim al-Ahwal, von Muadha, von Aisha, die sagte: Der Gesandte Allahs (Friede sei auf ihm) und ich pflegten aus einem Gefäß zwischen uns Ghusl zu verrichten. Er beeilte sich vor mir, bis ich sagte: Lass mir etwas, lass mir etwas. Sie sagte: Beide befanden sich im Zustand großer ritueller Unreinheit.'},
'https://sunnah.com/muslim:322':{en:'Qutayba ibn Said and Abu Bakr ibn Abi Shayba narrated to us, both from Ibn Uyayna. Qutayba said: Sufyan narrated to us, from Amr, from Abu al-Shatha, from Ibn Abbas, who said: Maymuna informed me that she and the Prophet (peace be upon him) used to perform ghusl from one vessel.',de:'Qutayba ibn Said und Abu Bakr ibn Abi Shayba überlieferten uns, beide von Ibn Uyayna. Qutayba sagte: Sufyan überlieferte uns, von Amr, von Abu al-Shatha, von Ibn Abbas, der sagte: Maymuna berichtete mir, dass sie und der Prophet (Friede sei auf ihm) aus einem Gefäß Ghusl zu verrichten pflegten.'},
'https://sunnah.com/muslim:323':{en:'Ishaq ibn Ibrahim and Muhammad ibn Hatim narrated to us. Ishaq said: He informed us, while Ibn Hatim said: Muhammad ibn Bakr narrated to us. Ibn Jurayj informed us. Amr ibn Dinar informed me. He said: The strongest of my knowledge and what comes to my mind is that Abu al-Shatha informed me that Ibn Abbas informed him that the Messenger of Allah (peace be upon him) used the remaining water of Maymuna for ghusl.',de:'Ishaq ibn Ibrahim und Muhammad ibn Hatim überlieferten uns. Ishaq sagte: Er berichtete uns, während Ibn Hatim sagte: Muhammad ibn Bakr überlieferte uns. Ibn Jurayj berichtete uns. Amr ibn Dinar berichtete mir. Er sagte: Nach meinem sichersten Wissen und dem, was mir in den Sinn kommt, berichtete mir Abu al-Shatha, dass Ibn Abbas ihm berichtete, dass der Gesandte Allahs (Friede sei auf ihm) das übrig gebliebene Wasser von Maymuna für Ghusl verwendete.'},
'https://sunnah.com/muslim:324':{en:'Muhammad ibn al-Muthanna narrated to us. Muadh ibn Hisham said: My father narrated to me, from Yahya ibn Abi Kathir. Abu Salama ibn Abd al-Rahman narrated to us that Zaynab bint Umm Salama narrated to him that Umm Salama narrated to her, saying: She and the Messenger of Allah (peace be upon him) used to perform ghusl from one vessel because of major ritual impurity.',de:'Muhammad ibn al-Muthanna überlieferte uns. Muadh ibn Hisham sagte: Mein Vater überlieferte mir, von Yahya ibn Abi Kathir. Abu Salama ibn Abd al-Rahman berichtete uns, dass Zaynab bint Umm Salama ihm berichtete, dass Umm Salama ihr erzählte und sagte: Sie und der Gesandte Allahs (Friede sei auf ihm) pflegten wegen großer ritueller Unreinheit aus einem Gefäß Ghusl zu verrichten.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-223-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-223-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
