import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:Record<string,{en:string;de:string}>={
'https://sunnah.com/muslim:350':{en:'Harun ibn Maruf and Harun ibn Said al-Ayli narrated to us. They said: Ibn Wahb narrated to us. Iyad ibn Abdullah informed me, from Abu al-Zubayr, from Jabir ibn Abdullah, from Umm Kulthum, from Aisha, the wife of the Prophet (peace be upon him), who said: A man asked the Messenger of Allah (peace be upon him) about a man who has intercourse with his wife and then becomes unable to continue: Must both of them perform ghusl? Aisha was sitting there. The Messenger of Allah (peace be upon him) said: I do that, I and this woman, and then we perform ghusl.',de:'Harun ibn Maruf und Harun ibn Said al-Ayli überlieferten uns. Sie sagten: Ibn Wahb überlieferte uns. Iyad ibn Abdullah berichtete mir, von Abu al-Zubayr, von Jabir ibn Abdullah, von Umm Kulthum, von Aisha, der Ehefrau des Propheten (Friede sei auf ihm), die sagte: Ein Mann fragte den Gesandten Allahs (Friede sei auf ihm) nach einem Mann, der mit seiner Frau Geschlechtsverkehr hat und dann nicht mehr weitermachen kann: Müssen beide Ghusl verrichten? Aisha saß dabei. Der Gesandte Allahs (Friede sei auf ihm) sagte: Ich tue dies, ich und diese Frau, und dann verrichten wir Ghusl.'},
'https://sunnah.com/muslim:351':{en:'Abd al-Malik ibn Shuaib ibn al-Layth narrated to us. He said: My father narrated to me, from my grandfather. Uqayl ibn Khalid narrated to me. Ibn Shihab said: Abd al-Malik ibn Abi Bakr ibn Abd al-Rahman ibn al-Harith ibn Hisham informed me that Kharija ibn Zayd al-Ansari informed him that his father, Zayd ibn Thabit, said: I heard the Messenger of Allah (peace be upon him) say: Wudu is required because of what the fire has touched.',de:'Abd al-Malik ibn Shuaib ibn al-Layth überlieferte uns. Er sagte: Mein Vater überlieferte mir, von meinem Großvater. Uqayl ibn Khalid überlieferte mir. Ibn Shihab sagte: Abd al-Malik ibn Abi Bakr ibn Abd al-Rahman ibn al-Harith ibn Hisham berichtete mir, dass Kharija ibn Zayd al-Ansari ihm berichtete, dass sein Vater Zayd ibn Thabit sagte: Ich hörte den Gesandten Allahs (Friede sei auf ihm) sagen: Wudu ist wegen dessen erforderlich, was das Feuer berührt hat.'},
'https://sunnah.com/muslim:352':{en:'Ibn Shihab said: Umar ibn Abd al-Aziz informed me that Abdullah ibn Ibrahim ibn Qariz informed him that he found Abu Hurayra performing wudu at the mosque. He said: I am performing wudu only because I ate pieces of dried curd, for I heard the Messenger of Allah (peace be upon him) say: Perform wudu because of what the fire has touched.',de:'Ibn Shihab sagte: Umar ibn Abd al-Aziz berichtete mir, dass Abdullah ibn Ibrahim ibn Qariz ihm berichtete, dass er Abu Hurayra in der Moschee Wudu verrichten sah. Er sagte: Ich verrichte Wudu nur, weil ich Stücke von getrocknetem Quark gegessen habe, denn ich hörte den Gesandten Allahs (Friede sei auf ihm) sagen: Verrichtet Wudu wegen dessen, was das Feuer berührt hat.'},
'https://sunnah.com/muslim:353':{en:'Ibn Shihab said: Said ibn Khalid ibn Amr ibn Uthman, while I was narrating this hadith to him, informed me that he asked Urwa ibn al-Zubayr about wudu because of what the fire has touched. Urwa said: I heard Aisha, the wife of the Prophet (peace be upon him), say: The Messenger of Allah (peace be upon him) said: Perform wudu because of what the fire has touched.',de:'Ibn Shihab sagte: Said ibn Khalid ibn Amr ibn Uthman, dem ich diesen Hadith überlieferte, berichtete mir, dass er Urwa ibn al-Zubayr nach dem Wudu wegen dessen fragte, was das Feuer berührt hat. Urwa sagte: Ich hörte Aisha, die Ehefrau des Propheten (Friede sei auf ihm), sagen: Der Gesandte Allahs (Friede sei auf ihm) sagte: Verrichtet Wudu wegen dessen, was das Feuer berührt hat.'},
'https://sunnah.com/muslim:354a':{en:'Abdullah ibn Maslama ibn Qanab narrated to us. Malik narrated to us, from Zayd ibn Aslam, from Ata ibn Yasar, from Ibn Abbas, that the Messenger of Allah (peace be upon him) ate the shoulder of a sheep, then prayed and did not perform wudu.',de:'Abdullah ibn Maslama ibn Qanab überlieferte uns. Malik überlieferte uns, von Zaid ibn Aslam, von Ata ibn Yasar, von Ibn Abbas, dass der Gesandte Allahs (Friede sei auf ihm) die Schulter eines Schafs aß, dann betete und kein Wudu verrichtete.'},
'https://sunnah.com/muslim:354b':{en:'Zuhayr ibn Harb narrated to us. Yahya ibn Said narrated to us, from Hisham ibn Urwa. Wahb ibn Kaysan informed me, from Muhammad ibn Amr ibn Ata, from Ibn Abbas. And al-Zuhri narrated to me, from Ali ibn Abdullah ibn Abbas, from Ibn Abbas. And Muhammad ibn Ali narrated to me, from his father, from Ibn Abbas, that the Prophet (peace be upon him) ate a shoulder, or meat, then prayed without performing wudu and without touching water.',de:'Zuhayr ibn Harb überlieferte uns. Yahya ibn Said überlieferte uns, von Hisham ibn Urwa. Wahb ibn Kaysan berichtete mir, von Muhammad ibn Amr ibn Ata, von Ibn Abbas. Und al-Zuhri berichtete mir, von Ali ibn Abdullah ibn Abbas, von Ibn Abbas. Und Muhammad ibn Ali berichtete mir, von seinem Vater, von Ibn Abbas, dass der Prophet (Friede sei auf ihm) eine Schulter oder Fleisch aß, dann betete, ohne Wudu zu verrichten und ohne Wasser zu berühren.'},
'https://sunnah.com/muslim:355a':{en:'Muhammad ibn al-Sabbah narrated to us. Ibrahim ibn Sad narrated to us. al-Zuhri narrated to us, from Jafar ibn Amr ibn Umayya al-Damri, from his father, that he saw the Messenger of Allah (peace be upon him) cutting meat from a shoulder, eating from it, then praying without performing wudu.',de:'Muhammad ibn al-Sabbah überlieferte uns. Ibrahim ibn Sad überlieferte uns. al-Zuhri überlieferte uns, von Jafar ibn Amr ibn Umayya al-Damri, von dessen Vater, dass er den Gesandten Allahs (Friede sei auf ihm) sah, wie er Fleisch von einer Schulter schnitt, davon aß und dann betete, ohne Wudu zu verrichten.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]})); if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-232-part.json',JSON.stringify(out,null,2)); fs.writeFileSync('data/hadith-words-translations/codex-out-232-part.json',JSON.stringify(out,null,2)); console.log(`wrote ${out.length} staged translations`);
