import fs from 'fs';

const rows: any[] = JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-183.json', 'utf8'));
const tr: Record<string, [string, string]> = {
  'Sahih Muslim, hadith 188, book 1, باب أَدْنَى أَهْلِ الْجَنَّةِ مَنْزِلَةً فِيهَا ‏‏': [
    "Abu Bakr ibn Abi Shayba narrated to us. Yahya ibn Abi Bukayr narrated to us. Zuhayr ibn Muhammad narrated to us, from Suhayl ibn Abi Salih, from al-Nu'man ibn Abi Ayyash, from Abu Sa'id al-Khudri, that the Messenger of Allah (peace be upon him) said: The person with the lowest rank among the people of Paradise is a man whose face Allah turns away from the Fire toward Paradise. A tree with shade is shown to him, and he says: My Lord, bring me to this tree so that I may be in its shade. He then narrated the hadith in the same meaning as Ibn Mas'ud's hadith, but he did not mention: He says, 'Son of Adam, what will satisfy you from Me?' through the end of the hadith. He added: Allah reminds him, saying, 'Ask for this and that.' When his hopes come to an end, Allah says: It is yours, and ten times as much. He said: Then he enters his house, and his two wives from the houris enter upon him. They say: Praise belongs to Allah who gave you life for us and gave us life for you. He says: No one has been given what I have been given.",
    "Abu Bakr ibn Abi Shayba überlieferte uns. Yahya ibn Abi Bukayr überlieferte uns. Zuhayr ibn Muhammad überlieferte uns, von Suhayl ibn Abi Salih, von an-Nu'man ibn Abi Ayyasch, von Abu Sa'id al-Chudri, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Der Mensch mit dem niedrigsten Rang unter den Bewohnern des Paradieses ist ein Mann, dessen Gesicht Allah vom Feuer zum Paradies hin abwendet. Ihm wird ein schattenspendender Baum gezeigt, und er sagt: Mein Herr, bringe mich zu diesem Baum, damit ich in seinem Schatten bin. Dann überlieferte er den Hadith in ähnlichem Sinn wie den Hadith von Ibn Mas'ud, erwähnte aber nicht: Er sagt: 'Sohn Adams, was wird dich von Mir zufriedenstellen?' bis zum Ende des Hadiths. Er fügte hinzu: Allah erinnert ihn und sagt: 'Bitte um dies und jenes.' Wenn seine Hoffnungen erschöpft sind, sagt Allah: Es gehört dir und das Zehnfache davon. Er sagte: Dann betritt er sein Haus, und seine beiden Frauen von den Huris kommen zu ihm. Sie sagen: Lob gehört Allah, der dich für uns lebendig gemacht und uns für dich lebendig gemacht hat. Er sagt: Niemandem wurde etwas Gleiches wie mir gegeben."
  ],
  'Sahih Muslim, hadith 189 a, book 1, باب أَدْنَى أَهْلِ الْجَنَّةِ مَنْزِلَةً فِيهَا ‏‏': [
    "Sa'id ibn Amr al-Ash'athi narrated to us. Sufyan ibn Uyayna narrated to us, from Mutarrif and Ibn Abjar, from al-Sha'bi, who said: I heard al-Mughira ibn Shu'ba, reporting it, if Allah wills. And Ibn Abi Umar narrated to us. Sufyan narrated to us. Mutarrif ibn Tarif and Abd al-Malik ibn Sa'id narrated to us; they both heard al-Sha'bi report from al-Mughira ibn Shu'ba, who said: I heard him on the pulpit, attributing it to the Messenger of Allah (peace be upon him).",
    "Sa'id ibn Amr al-Asch'athi überlieferte uns. Sufyan ibn Uyayna überlieferte uns, von Mutarrif und Ibn Abjar, von asch-Scha'bi, der sagte: Ich hörte al-Mughira ibn Schu'ba, der es überlieferte, wenn Allah will. Und Ibn Abi Umar überlieferte uns. Sufyan überlieferte uns. Mutarrif ibn Tarif und Abd al-Malik ibn Sa'id überlieferten uns; beide hörten asch-Scha'bi von al-Mughira ibn Schu'ba berichten, der sagte: Ich hörte ihn auf der Kanzel, wie er es dem Gesandten Allahs (Friede sei auf ihm) zuschrieb."
  ],
  'Sahih Muslim, hadith 189 c, book 1, باب أَدْنَى أَهْلِ الْجَنَّةِ مَنْزِلَةً فِيهَا ‏‏': [
    "Abu Kurayb narrated to us. Ubayd Allah al-Ashja'i narrated to us, from Abd al-Malik ibn Abjar, who said: I heard al-Sha'bi say: I heard al-Mughira ibn Shu'ba say on the pulpit: Moses (peace be upon him) asked Allah, the Mighty and Majestic, about the person among the people of Paradise who would have the smallest share of it. He narrated the hadith in a similar manner.",
    "Abu Kuraib überlieferte uns. Ubayd Allah al-Aschja'i überlieferte uns, von Abd al-Malik ibn Abjar, der sagte: Ich hörte asch-Scha'bi sagen: Ich hörte al-Mughira ibn Schu'ba auf der Kanzel sagen: Moses (Friede sei auf ihm) fragte Allah, den Mächtigen und Erhabenen, nach dem Bewohner des Paradieses, der den geringsten Anteil daran haben würde. Er überlieferte den Hadith in ähnlicher Weise."
  ],
  'Sahih Muslim, hadith 190 b, book 1, باب أَدْنَى أَهْلِ الْجَنَّةِ مَنْزِلَةً فِيهَا ‏‏': [
    "Ibn Numayr narrated to us. Abu Mu'awiya and Waki' narrated to us. And Abu Bakr ibn Abi Shayba narrated to us. Waki' narrated to us. And Abu Kurayb narrated to us. Abu Mu'awiya narrated to us; both of them from al-A'mash, with this chain of transmission.",
    "Ibn Numayr überlieferte uns. Abu Mu'awiya und Waki' überlieferten uns. Und Abu Bakr ibn Abi Schayba überlieferte uns. Waki' überlieferte uns. Und Abu Kuraib überlieferte uns. Abu Mu'awiya überlieferte uns; beide von al-A'masch, mit dieser Überlieferungskette."
  ]
};
const out = rows.filter(r => tr[r.reference]).map(r => ({...r, en: tr[r.reference][0], de: tr[r.reference][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-183-short-part.json', JSON.stringify(out, null, 2));
fs.writeFileSync('data/hadith-words-translations/codex-out-183-short-part.json', JSON.stringify(out, null, 2));
console.log(`wrote ${out.length} staged translations`);
