import fs from "node:fs";

const all = JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-batch-086.json", "utf8")) as { id: string; url: string }[];
const keep = new Set(["3912", "3913", "3914", "3915", "3916", "3917", "3918", "3919", "3920", "3921"]);
const raw = all.filter((row) => keep.has(row.url.split(":").pop()!));
fs.writeFileSync("data/hadith-words-translations/codex-batch-086.json", JSON.stringify(raw, null, 2) + "\n", "utf8");

const t: Record<string, { en: string; de: string }> = {
  "3912": {
    en: String.raw`Ibrahim ibn Musa narrated to us. Hisham informed us, from Ibn Jurayj, who said: Ubayd Allah ibn Umar informed me, from Nafi, meaning, from Ibn Umar, from Umar ibn al-Khattab, may Allah be pleased with him, who said: He used to allot four thousand to each of the first Emigrants, and he allotted three thousand five hundred to Ibn Umar. It was said to him: He is one of the Emigrants, so why did you reduce his allotment from four thousand? He said: His parents migrated with him. He meant: He is not like one who migrated by himself.`,
    de: String.raw`Ibrahim ibn Musa überlieferte uns. Hisham berichtete uns, von Ibn Dschuraidsch, der sagte: Ubayd Allah ibn Umar berichtete mir, von Nafi, das heißt von Ibn Umar, von Umar ibn al-Khattab, möge Allah mit ihm zufrieden sein, der sagte: Er pflegte jedem der ersten Auswanderer viertausend zuzuteilen, und Ibn Umar teilte er dreitausendfünfhundert zu. Da wurde zu ihm gesagt: Er gehört zu den Auswanderern. Warum hast du ihm also weniger als viertausend gegeben? Er sagte: Seine Eltern wanderten mit ihm aus. Er meinte: Er ist nicht wie jemand, der selbst ausgewandert ist.`
  },
  "3913": {
    en: String.raw`Muhammad ibn Kathir narrated to us. Sufyan informed us, from al-A'mash, from Abu Wa'il, from Khabbab, who said: We migrated with the Messenger of Allah (peace be upon him).`,
    de: String.raw`Muhammad ibn Kathir überlieferte uns. Sufyan berichtete uns, von al-A'masch, von Abu Wa'il, von Khabbab, der sagte: Wir wanderten mit dem Gesandten Allahs (Friede sei auf ihm) aus.`
  },
  "3914": {
    en: String.raw`Musaddad narrated to us. Yahya narrated to us, from al-A'mash, who said: I heard Shaqiq ibn Salama say: Khabbab narrated to us. He said: We migrated with the Messenger of Allah (peace be upon him), seeking Allah's face, and our reward became due from Allah. Some of us passed away without receiving any of their reward, among them Musab ibn Umayr, who was killed on the day of Uhud. We found nothing with which to shroud him except a striped cloak. When we covered his head with it, his feet became exposed, and when we covered his feet, his head became exposed. The Messenger of Allah (peace be upon him) ordered us to cover his head with it and put idhkhir over his feet. Among us are those whose fruit has ripened for them, and they are picking it.`,
    de: String.raw`Musaddad überlieferte uns. Yahya überlieferte uns, von al-A'masch, der sagte: Ich hörte Schaqiq ibn Salama sagen: Khabbab berichtete uns. Er sagte: Wir wanderten mit dem Gesandten Allahs (Friede sei auf ihm) aus, wobei wir Allahs Angesicht suchten, und unser Lohn wurde Allah gegenüber fällig. Einige von uns starben, ohne etwas von ihrem Lohn erhalten zu haben, darunter Musab ibn Umayr, der am Tag von Uhud getötet wurde. Wir fanden nichts, womit wir ihn einhüllen konnten, außer einem gestreiften Umhang. Wenn wir damit seinen Kopf bedeckten, wurden seine Füße sichtbar, und wenn wir seine Füße bedeckten, wurde sein Kopf sichtbar. Der Gesandte Allahs (Friede sei auf ihm) befahl uns, seinen Kopf damit zu bedecken und Idhkhir über seine Füße zu legen. Unter uns gibt es solche, deren Früchte reif geworden sind, und sie pflücken sie.`
  },
  "3915": {
    en: String.raw`Yahya ibn Bishr narrated to us. Ruh narrated to us. Awf narrated to us, from Muawiya ibn Qurra, who said: Abu Burda ibn Abi Musa al-Ashari narrated to me. He said: Abd Allah ibn Umar said to me: Do you know what my father said to your father? I said: No. He said: My father said to your father: Abu Musa, would it please you if our Islam with the Messenger of Allah (peace be upon him), our migration with him, our jihad with him, and all our deeds with him were returned to us, and every deed we did after him saved us from its consequences equally, deed for deed? My father said: No, by Allah. We fought after the Messenger of Allah (peace be upon him), prayed, fasted, did much good, and many people embraced Islam through our hands, and we hope for that. My father said: But by Him in whose hand Umar's soul is, I wish that this were returned to us and that every deed we did afterward saved us from its consequences equally, deed for deed. I said: By Allah, your father is better than mine.`,
    de: String.raw`Yahya ibn Bishr überlieferte uns. Ruh überlieferte uns. Awf überlieferte uns, von Muawiya ibn Qurra, der sagte: Abu Burda ibn Abi Musa al-Aschari berichtete mir. Er sagte: Abd Allah ibn Umar sagte zu mir: Weißt du, was mein Vater zu deinem Vater sagte? Ich sagte: Nein. Er sagte: Mein Vater sagte zu deinem Vater: Abu Musa, würde es dich erfreuen, wenn uns unser Islam mit dem Gesandten Allahs (Friede sei auf ihm), unsere Auswanderung mit ihm, unser Dschihad mit ihm und alle unsere Taten mit ihm zurückgegeben würden und uns jede Tat, die wir nach ihm getan haben, gleichermaßen vor ihren Folgen retten würde, Tat für Tat? Mein Vater sagte: Nein, bei Allah. Wir kämpften nach dem Gesandten Allahs (Friede sei auf ihm), beteten, fasteten, taten viel Gutes, und durch unsere Hände traten viele Menschen zum Islam über, und wir hoffen darauf. Mein Vater sagte: Aber bei Dem, in dessen Hand die Seele Umars ist, wünschte ich, dass uns dies zurückgegeben würde und uns jede Tat, die wir danach getan haben, gleichermaßen vor ihren Folgen retten würde, Tat für Tat. Ich sagte: Bei Allah, dein Vater ist besser als meiner.`
  },
  "3916": {
    en: String.raw`Muhammad ibn Sabbah narrated to me, or it reached me from him. Ismail narrated to us, from Asim, from Abu Uthman, who said: I heard Ibn Umar, may Allah be pleased with them both. When he was told, “He migrated before his father,” he would become angry. He said: I and Umar came to the Messenger of Allah (peace be upon him) and found him sleeping, so we returned home. Umar sent me and said: Go and see whether he has woken up. I went to him, entered upon him, and pledged allegiance to him. Then I went to Umar and told him that he had woken up. We went to him, hurrying and running, until he entered upon him and pledged allegiance to him, then I pledged allegiance to him.`,
    de: String.raw`Muhammad ibn Sabbah überlieferte mir, oder es erreichte mich von ihm. Ismail überlieferte uns, von Asim, von Abu Uthman, der sagte: Ich hörte Ibn Umar, möge Allah mit ihnen beiden zufrieden sein. Wenn zu ihm gesagt wurde: „Er wanderte vor seinem Vater aus“, wurde er zornig. Er sagte: Ich und Umar kamen zum Gesandten Allahs (Friede sei auf ihm) und fanden ihn schlafend vor, also kehrten wir nach Hause zurück. Umar schickte mich und sagte: Geh und sieh nach, ob er aufgewacht ist. Ich ging zu ihm, trat bei ihm ein und leistete ihm den Treueid. Dann ging ich zu Umar und teilte ihm mit, dass er aufgewacht war. Wir gingen eilig und laufend zu ihm, bis er bei ihm eintrat und ihm den Treueid leistete, dann leistete ich ihm den Treueid.`
  },
  "3917": {
    en: String.raw`Ahmad ibn Uthman narrated to us. Shurayh ibn Maslama narrated to us. Ibrahim ibn Yusuf narrated to us, from his father, from Abu Ishaq, who said: I heard al-Bara narrate: Abu Bakr bought a saddle from Azib, and I carried it with him. Azib asked him about the journey of the Messenger of Allah (peace be upon him). He said: We were watched. We set out at night and traveled through our night and day until midday. Then a rock was raised for us, and we came to it, with some shade over it. I spread a fur I had for the Messenger of Allah (peace be upon him), and the Prophet lay down on it. I went to clear away what was around him, and suddenly a shepherd came with a small flock, wanting from the rock what we had wanted. I asked him: Whose are you, young man? He said: I belong to so-and-so. I said to him: Is there milk among your sheep? He said: Yes. I said to him: Can you milk? He said: Yes. He took a sheep from his flock, and I said to him: Shake the udder. He milked a little milk. I had a water-skin with a cloth over it, which I had cooled for the Messenger of Allah (peace be upon him). I poured water over the milk until its bottom became cool. Then I brought it to the Prophet (peace be upon him) and said: Drink, O Messenger of Allah. The Messenger of Allah (peace be upon him) drank until I was satisfied. Then we continued our journey while the pursuers were behind us.`,
    de: String.raw`Ahmad ibn Uthman überlieferte uns. Schurayh ibn Maslama überlieferte uns. Ibrahim ibn Yusuf überlieferte uns, von seinem Vater, von Abu Ishaq, der sagte: Ich hörte al-Bara berichten: Abu Bakr kaufte von Azib einen Sattel, und ich trug ihn mit ihm. Azib fragte ihn nach dem Weg des Gesandten Allahs (Friede sei auf ihm). Er sagte: Wir wurden beobachtet. Wir brachen nachts auf und zogen durch unsere Nacht und unseren Tag, bis der Mittag kam. Dann wurde uns ein Felsen sichtbar, und wir kamen zu ihm, während etwas Schatten auf ihm lag. Ich breitete einen Pelz, den ich beim Gesandten Allahs (Friede sei auf ihm) hatte, für ihn aus, und der Prophet legte sich darauf. Ich ging los, um alles um ihn herum wegzuschütteln, da kam plötzlich ein Hirte mit einer kleinen Herde, der von dem Felsen dasselbe wollte wie wir. Ich fragte ihn: Wem gehörst du, junger Mann? Er sagte: Ich gehöre dem und dem. Ich sagte zu ihm: Gibt es Milch unter deinen Schafen? Er sagte: Ja. Ich sagte zu ihm: Kannst du melken? Er sagte: Ja. Er nahm ein Schaf aus seiner Herde, und ich sagte zu ihm: Schüttle das Euter. Er molk etwas Milch. Ich hatte einen Wasserschlauch mit einem Tuch darüber, den ich für den Gesandten Allahs (Friede sei auf ihm) gekühlt hatte. Ich goss Wasser über die Milch, bis ihr Boden kühl wurde. Dann brachte ich sie zum Propheten (Friede sei auf ihm) und sagte: Trink, o Gesandter Allahs. Der Gesandte Allahs (Friede sei auf ihm) trank, bis ich zufrieden war. Dann setzten wir unsere Reise fort, während die Verfolger hinter uns waren.`
  },
  "3918": {
    en: String.raw`Al-Bara said: I entered with Abu Bakr upon his family, and Aisha, his daughter, was lying down with a fever that had afflicted her. I saw her father kiss her cheek and say: How are you, my dear daughter?`,
    de: String.raw`Al-Bara sagte: Ich trat mit Abu Bakr bei seiner Familie ein. Da lag Aisha, seine Tochter, mit Fieber danieder, das sie befallen hatte. Ich sah, wie ihr Vater ihre Wange küsste und sagte: Wie geht es dir, meine liebe Tochter?`
  },
  "3919": {
    en: String.raw`Sulaiman ibn Abd al-Rahman narrated to us. Muhammad ibn Humayr narrated to us. Ibrahim ibn Abi Abla narrated to us, that Uqba ibn Wassaj narrated to him, from Anas, the servant of the Prophet (peace be upon him), who said: The Prophet (peace be upon him) arrived while none of his Companions had grey hair except Abu Bakr. He dyed it with henna and katam.`,
    de: String.raw`Sulaiman ibn Abd ar-Rahman überlieferte uns. Muhammad ibn Humayr überlieferte uns. Ibrahim ibn Abi Abla überlieferte uns, dass Uqba ibn Wassadsch ihm von Anas, dem Diener des Propheten (Friede sei auf ihm), berichtete, der sagte: Der Prophet (Friede sei auf ihm) kam an, und keiner seiner Gefährten hatte graue Haare außer Abu Bakr. Er färbte sie mit Henna und Katam.`
  },
  "3920": {
    en: String.raw`Duhaym said: Al-Walid narrated to us. Al-Awzai narrated to us. Abu Ubayd narrated to me, from Uqba ibn Wassaj, from Anas ibn Malik, may Allah be pleased with him, who said: The Prophet (peace be upon him) arrived in Medina, and Abu Bakr was the oldest of his Companions. He dyed it with henna and katam until its color became deep.`,
    de: String.raw`Duhaym sagte: al-Walid überlieferte uns. al-Awzai überlieferte uns. Abu Ubayd berichtete mir, von Uqba ibn Wassadsch, von Anas ibn Malik, möge Allah mit ihm zufrieden sein, der sagte: Der Prophet (Friede sei auf ihm) kam in Medina an, und Abu Bakr war der Älteste seiner Gefährten. Er färbte es mit Henna und Katam, bis seine Farbe kräftig wurde.`
  },
  "3921": {
    en: String.raw`Asbagh narrated to us. Ibn Wahb narrated to us, from Yunus, from Ibn Shihab, from Urwa ibn al-Zubayr, from Aisha: Abu Bakr, may Allah be pleased with him, married a woman from Kalb called Umm Bakr. When Abu Bakr migrated, he divorced her, and her cousin, this poet, married her. He was the poet who composed this poem, mourning the disbelievers of Quraysh: “What is at the well, the well of Badr, of Shiza wood adorned with humps? And what is at the well, the well of Badr, of singing women and noble drinkers? Umm Bakr greets with peace, but what greeting remains for me after my people? The Messenger tells us that we will live, but how can ghosts and skulls live?”`,
    de: String.raw`Asbagh überlieferte uns. Ibn Wahb überlieferte uns, von Yunus, von Ibn Schihab, von Urwa ibn az-Zubayr, von Aisha: Abu Bakr, möge Allah mit ihm zufrieden sein, heiratete eine Frau aus Kalb namens Umm Bakr. Als Abu Bakr auswanderte, ließ er sich von ihr scheiden, und ihr Vetter, dieser Dichter, heiratete sie. Er war der Dichter, der dieses Gedicht verfasste und die ungläubigen Quraisch betrauerte: „Was ist am Brunnen, am Brunnen von Badr, an Schiza-Holz, das mit Höckern geschmückt ist? Und was ist am Brunnen, am Brunnen von Badr, an Sängerinnen und edlen Trinkern? Umm Bakr grüßt mit Frieden, und welchen Gruß habe ich nach meinem Volk noch? Der Gesandte berichtet uns, dass wir leben werden, doch wie können Geister und Schädel leben?“`
  }
};

const out = raw.map((row) => {
  const n = row.url.split(":").pop()!;
  const v = t[n];
  if (!v) throw new Error("missing " + n);
  return { id: row.id, n, en: v.en, de: v.de };
});
fs.writeFileSync("data/hadith-words-translations/codex-out-086.json", JSON.stringify(out, null, 2) + "\n", "utf8");
console.log("wrote " + out.length + " translations");
