import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:297d':{en:'Yahya ibn Yahya, Abu Bakr ibn Abi Shayba, Amr al-Naqid, Zuhayr ibn Harb, and Ibn Abi Umar narrated to us, and this is Zuhayr\'s wording. Yahya said: He informed us, while the others said: Sufyan ibn Uyayna narrated to us, from al-Zuhri, from Ubaydullah ibn Abdullah, from Umm Qays bint Mihsan, the sister of Ukasha ibn Mihsan, who said: I entered upon the Messenger of Allah (peace be upon him) with a son of mine who had not eaten food. He urinated on him, so he called for water and sprinkled it over him. She said: I also entered upon him with a son of mine on whom I had hung a talisman for a throat ailment. He said: Why do you strangle your children with this talisman? Use Indian costus, for it contains seven remedies. Among them is pleurisy: it is inhaled for a throat ailment and administered from the side of the mouth for pleurisy.',de:'Yahya ibn Yahya, Abu Bakr ibn Abi Shayba, Amr al-Naqid, Zuhayr ibn Harb und Ibn Abi Umar überlieferten uns, und dies ist Zuhayrs Wortlaut. Yahya sagte: Er berichtete uns, während die anderen sagten: Sufyan ibn Uyayna überlieferte uns, von al-Zuhri, von Ubaydullah ibn Abdullah, von Umm Qays bint Mihsan, der Schwester von Ukasha ibn Mihsan, die sagte: Ich trat beim Gesandten Allahs (Friede sei auf ihm) mit einem Sohn von mir ein, der noch keine Nahrung gegessen hatte. Er urinierte auf ihn, da ließ er Wasser bringen und spritzte es über ihn. Sie sagte: Ich trat auch mit einem Sohn von mir bei ihm ein, dem ich wegen einer Halskrankheit einen Anhänger umgehängt hatte. Er sagte: Warum würgt ihr eure Kinder mit diesem Anhänger? Verwendet indische Kostuswurzel, denn sie enthält sieben Heilmittel. Eines davon ist Brustfellentzündung: Bei einer Halskrankheit wird sie eingesogen und bei Brustfellentzündung seitlich in den Mund eingegeben.'},
'https://sunnah.com/muslim:297e':{en:'Abu Bakr ibn Abi Shayba narrated to us. Husayn ibn Ali narrated to us, from Zaida, from Mansur, from Ibrahim, from al-Aswad, from Aisha, who said: I used to wash the head of the Messenger of Allah (peace be upon him) while I was menstruating.',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Husayn ibn Ali überlieferte uns, von Zaida, von Mansur, von Ibrahim, von al-Aswad, von Aisha, die sagte: Ich pflegte den Kopf des Gesandten Allahs (Friede sei auf ihm) zu waschen, während ich menstruierte.'},
'https://sunnah.com/muslim:298a':{en:'Yahya ibn Yahya, Abu Bakr ibn Abi Shayba, and Abu Kurayb narrated to us. Yahya said: He informed us, while the other two said: Abu Muawiya narrated to us, from al-Amash, from Thabit ibn Ubayd, from al-Qasim ibn Muhammad, from Aisha, who said: The Messenger of Allah (peace be upon him) said to me: Hand me the prayer mat from the mosque. I said: I am menstruating. He said: Your menstruation is not in your hand.',de:'Yahya ibn Yahya, Abu Bakr ibn Abi Shayba und Abu Kurayb überlieferten uns. Yahya sagte: Er berichtete uns, während die beiden anderen sagten: Abu Muawiya überlieferte uns, von al-Amash, von Thabit ibn Ubayd, von al-Qasim ibn Muhammad, von Aisha, die sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte zu mir: Reich mir die Gebetsmatte aus der Moschee. Ich sagte: Ich menstruiere. Er sagte: Deine Menstruation ist nicht in deiner Hand.'},
'https://sunnah.com/muslim:298b':{en:'Abu Kurayb narrated to us. Ibn Abi Zaida narrated to us, from Hajjaj, and Ibn Abi Ghaniyya, from Thabit ibn Ubayd, from al-Qasim ibn Muhammad, from Aisha, who said: The Messenger of Allah (peace be upon him) ordered me to hand him the prayer mat from the mosque. I said: I am menstruating. He said: Take it, for menstruation is not in your hand.',de:'Abu Kurayb überlieferte uns. Ibn Abi Zaida überlieferte uns, von Hajjaj und Ibn Abi Ghaniyya, von Thabit ibn Ubayd, von al-Qasim ibn Muhammad, von Aisha, die sagte: Der Gesandte Allahs (Friede sei auf ihm) befahl mir, ihm die Gebetsmatte aus der Moschee zu reichen. Ich sagte: Ich menstruiere. Er sagte: Nimm sie, denn die Menstruation ist nicht in deiner Hand.'},
'https://sunnah.com/muslim:299':{en:'Zuhayr ibn Harb, Abu Kamil, and Muhammad ibn Hatim narrated to me, all from Yahya ibn Said. Zuhayr said: Yahya narrated to us, from Yazid ibn Kaysan, from Abu Hazim, from Abu Hurayra, who said: While the Messenger of Allah (peace be upon him) was in the mosque, he said: O Aisha, hand me the garment. She said: I am menstruating. He said: Your menstruation is not in your hand. So she handed it to him.',de:'Zuhayr ibn Harb, Abu Kamil und Muhammad ibn Hatim überlieferten mir, alle von Yahya ibn Said. Zuhayr sagte: Yahya überlieferte uns, von Yazid ibn Kaysan, von Abu Hazim, von Abu Hurayra, der sagte: Während der Gesandte Allahs (Friede sei auf ihm) in der Moschee war, sagte er: O Aisha, reich mir das Gewand. Sie sagte: Ich menstruiere. Er sagte: Deine Menstruation ist nicht in deiner Hand. Da reichte sie es ihm.'},
'https://sunnah.com/muslim:300':{en:'Abu Bakr ibn Abi Shayba and Zuhayr ibn Harb narrated to us. They said: Waki narrated to us, from Misar and Sufyan, from al-Miqdam ibn Shurayh, from his father, from Aisha, who said: I used to drink while I was menstruating, then hand it to the Prophet (peace be upon him), and he would place his mouth where my mouth had been and drink. I used to bite meat from a bone while I was menstruating, then hand it to the Prophet (peace be upon him), and he would place his mouth where my mouth had been. Zuhayr did not mention “and drink.”',de:'Abu Bakr ibn Abi Shayba und Zuhayr ibn Harb überlieferten uns. Sie sagten: Waki überlieferte uns, von Misar und Sufyan, von al-Miqdam ibn Shurayh, von dessen Vater, von Aisha, die sagte: Ich pflegte zu trinken, während ich menstruierte, und reichte es dann dem Propheten (Friede sei auf ihm), der seinen Mund an die Stelle setzte, an der mein Mund gewesen war, und trank. Ich pflegte, während ich menstruierte, Fleisch von einem Knochen abzunagen, und reichte ihn dann dem Propheten (Friede sei auf ihm), der seinen Mund an die Stelle setzte, an der mein Mund gewesen war. Zuhayr erwähnte nicht: „und trank.“'},
'https://sunnah.com/muslim:301':{en:'Yahya ibn Yahya informed us. Dawud ibn Abd al-Rahman al-Makki informed us, from Mansur, from his mother, from Aisha, who said: The Messenger of Allah (peace be upon him) would recline in my lap while I was menstruating and recite the Quran.',de:'Yahya ibn Yahya berichtete uns. Dawud ibn Abd al-Rahman al-Makki berichtete uns, von Mansur, von seiner Mutter, von Aisha, die sagte: Der Gesandte Allahs (Friede sei auf ihm) lehnte sich in meinem Schoß zurück, während ich menstruierte, und rezitierte den Quran.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-217-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-217-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
