import fs from 'fs';
const rows:any[] = JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-185-current.json','utf8'));
const tr:Record<string,[string,string]> = {
 'https://sunnah.com/muslim:190a':[ `Muhammad ibn Abdullah ibn Numayr narrated to us. My father narrated to us. al-A'mash narrated to us, from al-Ma'rur ibn Suwayd, from Abu Dharr, who said: The Messenger of Allah (peace be upon him) said: I know the last of the people of Paradise to enter it and the last of the people of the Fire to come out of it. He is a man brought on the Day of Resurrection, and it is said: Show him his minor sins and withhold his major sins. His minor sins are shown to him, and it is said: You did this on such-and-such a day, and this on such-and-such a day. He says: Yes. He cannot deny, while he fears that his major sins will be shown to him. It is said to him: In place of every bad deed you will have a good deed. He says: My Lord, I have done things that I do not see here. I saw the Messenger of Allah (peace be upon him) laugh until his molars became visible.`, `Muhammad ibn Abd Allah ibn Numayr überlieferte uns. Mein Vater überlieferte uns. al-A'masch überlieferte uns, von al-Ma'rur ibn Suwayd, von Abu Dharr, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Ich kenne den Letzten der Bewohner des Paradieses, der es betritt, und den Letzten der Bewohner des Feuers, der daraus herauskommt. Es ist ein Mann, der am Tag der Auferstehung gebracht wird, und es wird gesagt: Zeigt ihm seine kleinen Sünden und haltet seine großen zurück. Seine kleinen Sünden werden ihm gezeigt, und es wird gesagt: Du hast an diesem und jenem Tag dies getan und an diesem und jenem Tag jenes getan. Er sagt: Ja. Er kann es nicht leugnen, während er fürchtet, dass ihm seine großen Sünden gezeigt werden. Zu ihm wird gesagt: Anstelle jeder schlechten Tat wirst du eine gute Tat haben. Er sagt: Mein Herr, ich habe Dinge getan, die ich hier nicht sehe. Ich sah den Gesandten Allahs (Friede sei auf ihm) lachen, bis seine Backenzähne sichtbar wurden.` ],
 'https://sunnah.com/muslim:193b':[ `Muhammad ibn al-Muthanna and Muhammad ibn Bashshar narrated to us. Ibn Abi Adi narrated to us, from Sa'id, from Qatada, from Anas, who said: The Messenger of Allah (peace be upon him) said: The believers will gather on the Day of Resurrection and be concerned about that, or be inspired to do that, in the same manner as Abu Awana's hadith. He said in the hadith: Then I will come to him a fourth time, or return a fourth time, and say: My Lord, none remains except the one whom the Quran has held back.`, `Muhammad ibn al-Muthanna und Muhammad ibn Baschar überlieferten uns. Ibn Abi Adi überlieferte uns, von Sa'id, von Qatada, von Anas, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Die Gläubigen werden sich am Tag der Auferstehung versammeln und darüber bekümmert sein oder dazu inspiriert werden, wie im Hadith von Abu Awana. Er sagte im Hadith: Dann komme ich ein viertes Mal zu ihm oder kehre ein viertes Mal zurück und sage: Mein Herr, niemand bleibt außer dem, den der Quran zurückgehalten hat.` ],
 'https://sunnah.com/muslim:193c':[ `Muhammad ibn al-Muthanna narrated to us. Muadh ibn Hisham narrated to us. He said: My father narrated to me, from Qatada, from Anas ibn Malik, that the Prophet (peace be upon him) said: Allah will gather the believers on the Day of Resurrection and they will be inspired to do that, in the same manner as their two reports. He mentioned in the fourth: I will say: My Lord, none remains in the Fire except the one whom the Quran has held back, meaning the one for whom remaining forever has become obligatory.`, `Muhammad ibn al-Muthanna überlieferte uns. Mu'adh ibn Hischam überlieferte uns. Er sagte: Mein Vater überlieferte mir, von Qatada, von Anas ibn Malik, dass der Prophet (Friede sei auf ihm) sagte: Allah wird die Gläubigen am Tag der Auferstehung versammeln und sie werden dazu inspiriert, wie in ihren beiden Überlieferungen. Er erwähnte beim vierten Mal: Ich werde sagen: Mein Herr, niemand bleibt im Feuer außer dem, den der Quran zurückgehalten hat, das heißt, für den das ewige Verbleiben verpflichtend geworden ist.` ],
 'https://sunnah.com/muslim:193d':[ `Muhammad ibn Minhal al-Darir narrated to us. Yazid ibn Zuray narrated to us. Sa'id ibn Abi Aruba and Hisham, the companion of al-Dastawa'i, narrated to us, from Qatada, from Anas ibn Malik, who said: The Messenger of Allah (peace be upon him) said: Whoever said, 'There is no god but Allah,' and had goodness in his heart weighing a barley grain, will come out of the Fire. Then whoever said, 'There is no god but Allah,' and had goodness in his heart weighing a wheat grain, will come out of the Fire. Then whoever said, 'There is no god but Allah,' and had goodness in his heart weighing an atom, will come out of the Fire. Ibn Minhal added: Yazid said: I met Shu'ba and told him the hadith. Shu'ba said: Qatada narrated it to us from Anas ibn Malik, from the Prophet (peace be upon him), except that Shu'ba used 'corn grain' instead of 'atom'. Yazid said: Abu Bustam made a copying error in it.`, `Muhammad ibn Minhal ad-Darir überlieferte uns. Yazid ibn Zuray überlieferte uns. Sa'id ibn Abi Aruba und Hischam, der Gefährte von ad-Dastuwa'i, überlieferten uns, von Qatada, von Anas ibn Malik, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Wer sagte: 'Es gibt keinen Gott außer Allah', und in dessen Herz sich Gutes im Gewicht eines Gerstenkorns befand, wird aus dem Feuer herauskommen. Dann wird aus dem Feuer herauskommen, wer sagte: 'Es gibt keinen Gott außer Allah', und in dessen Herz sich Gutes im Gewicht eines Weizenkorns befand. Dann wird aus dem Feuer herauskommen, wer sagte: 'Es gibt keinen Gott außer Allah', und in dessen Herz sich Gutes im Gewicht eines Atoms befand. Ibn Minhal fügte hinzu: Yazid sagte: Ich traf Schu'ba und berichtete ihm den Hadith. Schu'ba sagte: Qatada überlieferte ihn uns von Anas ibn Malik, vom Propheten (Friede sei auf ihm), außer dass Schu'ba statt 'Atom' 'Maiskorn' sagte. Yazid sagte: Abu Bistam hat darin einen Abschreibfehler gemacht.` ]
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,en:tr[r.url][0],de:tr[r.url][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-185-short-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-185-short-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
