import fs from "node:fs";
type Raw = { id: string; url: string; text_original: string };
type Out = { id: string; n: number; en: string; de: string };
const raw = JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-batch-040.json", "utf8")) as Raw[];
const t: Record<number, [string, string]> = {
3125: ["Sadaqa informed us. Abd al-Rahman informed us, from Malik, from Zayd ibn Aslam, from his father, who said: Umar, may Allah be pleased with him, said: Were it not for concern for the Muslims who come later, I would not conquer a town without dividing it among its people, as the Prophet (peace be upon him) divided Khaybar.", "Sadaqa informierte uns. Abd al-Rahman informierte uns, von Malik, von Zayd ibn Aslam, von seinem Vater, der sagte: Umar, mÃ¶ge Allah mit ihm zufrieden sein, sagte: WÃ¤re nicht die RÃ¼cksicht auf die spÃ¤ter kommenden Muslime, wÃ¼rde ich keine Stadt erobern, ohne sie unter ihren Bewohnern aufzuteilen, wie der Prophet (Friede sei auf ihm) Khaybar aufteilte."],
3126: ["Muhammad ibn Bashshar narrated to me. Ghundar narrated to us. Shu'ba narrated to us, from Amr, who said: I heard Abu Wa'il say: Abu Musa al-Ashari, may Allah be pleased with him, narrated to us that a Bedouin said to the Prophet (peace be upon him): A man fights for the spoils, a man fights so that he will be mentioned, and a man fights so that his position will be seen. Which of them is in the path of Allah? He said: Whoever fights so that Allah's word is supreme is in the path of Allah.", "Muhammad ibn Bashshar berichtete mir. Ghundar Ã¼berlieferte uns. Shu'ba Ã¼berlieferte uns, von Amr, der sagte: Ich hÃ¶rte Abu Wa'il sagen: Abu Musa al-Ashari, mÃ¶ge Allah mit ihm zufrieden sein, berichtete uns, dass ein Beduine zum Propheten (Friede sei auf ihm) sagte: Ein Mann kÃ¤mpft wegen der Beute, ein Mann kÃ¤mpft, damit man ihn erwÃ¤hnt, und ein Mann kÃ¤mpft, damit seine Stellung gesehen wird. Wer von ihnen ist auf Allahs Weg? Er sagte: Wer kÃ¤mpft, damit Allahs Wort das hÃ¶chste ist, der ist auf Allahs Weg."],
3127: ["Abdullah ibn Abd al-Wahhab narrated to us. Hammad ibn Zayd narrated to us, from Ayyub, from Abdullah ibn Abi Mulayka, that the Prophet (peace be upon him) was given brocade robes fastened with gold buttons. He distributed them among some of his Companions and set one aside for Makhrama ibn Nawfal. Makhrama came with his son al-Miswar ibn Makhrama and stood at the door, saying: Call him for me. The Prophet (peace be upon him) heard his voice, took a robe, met him with it, and faced him with its buttons, saying: O Abu al-Miswar, I saved this for you. O Abu al-Miswar, I saved this for you. He was a man of a harsh character. Ibn Ulayya narrated it from Ayyub. Hatim ibn Wardan said: Ayyub narrated to us, from Ibn Abi Mulayka, from al-Miswar: Brocade robes were brought to the Prophet (peace be upon him). al-Layth followed him in this from Ibn Abi Mulayka.", "Abdullah ibn Abd al-Wahhab Ã¼berlieferte uns. Hammad ibn Zayd Ã¼berlieferte uns, von Ayyub, von Abdullah ibn Abi Mulayka, dass dem Propheten (Friede sei auf ihm) BrokatmÃ¤ntel gebracht wurden, die mit goldenen KnÃ¶pfen verschlossen waren. Er verteilte sie unter einigen seiner GefÃ¤hrten und legte einen fÃ¼r Makhrama ibn Nawfal beiseite. Makhrama kam mit seinem Sohn al-Miswar ibn Makhrama und stellte sich an die TÃ¼r und sagte: Ruf ihn fÃ¼r mich. Der Prophet (Friede sei auf ihm) hÃ¶rte seine Stimme, nahm einen Mantel, ging ihm damit entgegen und wandte ihm die KnÃ¶pfe zu und sagte: O Abu al-Miswar, ich habe diesen fÃ¼r dich aufgehoben. O Abu al-Miswar, ich habe diesen fÃ¼r dich aufgehoben. Er war ein Mann mit rauem Charakter. Ibn Ulayya Ã¼berlieferte dies von Ayyub. Hatim ibn Wardan sagte: Ayyub Ã¼berlieferte uns, von Ibn Abi Mulayka, von al-Miswar: Dem Propheten (Friede sei auf ihm) wurden BrokatmÃ¤ntel gebracht. al-Layth Ã¼berlieferte dies ebenfalls von Ibn Abi Mulayka."],
3128: ["Abdullah ibn Abi al-Aswad narrated to us. Mutamir narrated to us, from his father, who said: I heard Anas ibn Malik, may Allah be pleased with him, say: A man used to give the Prophet (peace be upon him) date palms until he conquered Qurayza and al-Nadir. After that, he returned them to him.", "Abdullah ibn Abi al-Aswad Ã¼berlieferte uns. Mutamir Ã¼berlieferte uns, von seinem Vater, der sagte: Ich hÃ¶rte Anas ibn Malik, mÃ¶ge Allah mit ihm zufrieden sein, sagen: Ein Mann pflegte dem Propheten (Friede sei auf ihm) Dattelpalmen zu Ã¼berlassen, bis er Qurayza und al-Nadir eroberte. Danach gab er sie ihm zurÃ¼ck."],
};
const out: Out[] = raw.map((row) => { const n = Number(row.url.split(":").pop()); const pair = t[n]; if (!pair) throw new Error("Missing translation for " + row.url); return { id: row.id, n, en: pair[0], de: pair[1] }; });
for (const row of out) {
  if (row.n === 3127) row.de = row.de.replace("KnÃ¶pfen", "Kn\u00f6pfen");
}
fs.writeFileSync("data/hadith-words-translations/codex-out-040.json", JSON.stringify(out, null, 2) + "\n", "utf8");
console.log("wrote " + out.length + " translations");
