import fs from 'fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-201.json','utf8'));
const tr:Record<string,[string,string]>={
'https://sunnah.com/muslim:235c':[ `Ishaq ibn Musa al-Ansari narrated to me. Ma'n narrated to us. Malik ibn Anas narrated to us, from Amr ibn Yahya, with this chain. He said: He rinsed his mouth and drew water into his nose three times, and he did not say, with one handful. He added after his saying, He moved his hands forward and backward: He began at the front of his head, took them to the back of his head, then returned them until he reached the place where he began. And he washed his feet.`, `Ishaq ibn Musa al-Ansari überlieferte mir. Ma'n überlieferte uns. Malik ibn Anas überlieferte uns, von Amr ibn Yahya, mit dieser Kette. Er sagte: Er spülte seinen Mund und zog dreimal Wasser in seine Nase, und er sagte nicht: mit einer Handvoll. Nach den Worten: Er bewegte seine Hände nach vorn und zurück, fügte er hinzu: Er begann an der Vorderseite seines Kopfes, führte sie zum Hinterkopf und brachte sie dann zurück, bis er zu der Stelle gelangte, an der er begonnen hatte. Und er wusch seine Füße.`],
'https://sunnah.com/muslim:235d':[ `Abd al-Rahman ibn Bashir al-Abdi narrated to us. Bahz narrated to us. Wuhayb narrated to us. Amr ibn Yahya narrated to us, with their chain, and he related the hadith. He said in it: He rinsed his mouth, drew water into his nose, and expelled it from three handfuls. He also said: He wiped his head, moving his hands forward and backward once. Bahz said: Wuhayb dictated this hadith to me. Wuhayb said: Amr ibn Yahya dictated this hadith to me twice.`, `Abd ar-Rahman ibn Baschir al-Abdi überlieferte uns. Bahz überlieferte uns. Wuhayb überlieferte uns. Amr ibn Yahya überlieferte uns mit ihrer Kette und berichtete den Hadith. Darin sagte er: Er spülte seinen Mund, zog Wasser in seine Nase und stieß es aus drei Handvoll aus. Er sagte auch: Er strich über seinen Kopf und bewegte seine Hände einmal nach vorn und zurück. Bahz sagte: Wuhayb diktierte mir diesen Hadith. Wuhayb sagte: Amr ibn Yahya diktierte mir diesen Hadith zweimal.`],
'https://sunnah.com/muslim:236':[ `Harun ibn Ma'ruf narrated to us. And Harun ibn Sa'id al-Ayli and Abu al-Tahir narrated to me. They said: Ibn Wahb narrated to us. Amr ibn al-Harith informed me that Hibban ibn Wasi' narrated to him that his father narrated to him that he heard Abdullah ibn Zayd ibn Asim al-Mazini mention that he saw the Messenger of Allah (peace be upon him) perform wudu. He rinsed his mouth, then drew water into his nose, then washed his face three times, his right hand three times and the other three times. He wiped his head with water other than the leftover water on his hand, and washed his feet until he cleaned them. Abu al-Tahir said: Ibn Wahb narrated to us, from Amr ibn al-Harith.`, `Harun ibn Ma'ruf überlieferte uns. Und Harun ibn Sa'id al-Ayli und Abu at-Tahir überlieferten mir. Sie sagten: Ibn Wahb überlieferte uns. Amr ibn al-Harith berichtete mir, dass Hibban ibn Wasi' ihm überlieferte, dass sein Vater ihm überlieferte, dass er Abd Allah ibn Zayd ibn Asim al-Mazini hörte, der erwähnte, dass er den Gesandten Allahs (Friede sei auf ihm) die Gebetswaschung vollziehen sah. Er spülte seinen Mund, zog dann Wasser in seine Nase, wusch danach sein Gesicht dreimal, seine rechte Hand dreimal und die andere dreimal. Er strich mit Wasser über seinen Kopf, das nicht das Restwasser seiner Hand war, und wusch seine Füße, bis er sie reinigte. Abu at-Tahir sagte: Ibn Wahb überlieferte uns, von Amr ibn al-Harith.`],
'https://sunnah.com/muslim:237a':[ `Qutayba ibn Sa'id, Amr the Critic, and Muhammad ibn Abdullah ibn Numayr narrated to us, all from Ibn Uyayna. Qutayba said: Sufyan narrated to us, from Abu al-Zinad, from al-A'raj, from Abu Hurayra, attributing it to the Prophet (peace be upon him), who said: When one of you uses stones for cleaning, let him use an odd number. When one of you performs wudu, let him put water into his nose and then expel it.`, `Qutayba ibn Sa'id, Amr, der Kritiker, und Muhammad ibn Abd Allah ibn Numayr überlieferten uns, alle von Ibn Uyayna. Qutayba sagte: Sufyan überlieferte uns, von Abu az-Zinad, von al-A'raj, von Abu Hurayra, der es dem Propheten (Friede sei auf ihm) zuschrieb, der sagte: Wenn einer von euch Steine zur Reinigung benutzt, soll er eine ungerade Zahl verwenden. Wenn einer von euch die Gebetswaschung vollzieht, soll er Wasser in seine Nase ziehen und es dann ausstoßen.`],
'https://sunnah.com/muslim:237b':[ `Muhammad ibn Rafi narrated to us. Abd al-Razzaq ibn Hammam narrated to us. Ma'mar informed us, from Hammam ibn Munabbih, who said: This is what Abu Hurayra narrated to us from Muhammad, the Messenger of Allah (peace be upon him). He mentioned several hadiths, among them: The Messenger of Allah (peace be upon him) said: When one of you performs wudu, let him draw water into his nostrils and then expel it.`, `Muhammad ibn Rafi überlieferte uns. Abd ar-Razzaq ibn Hammam überlieferte uns. Ma'mar berichtete uns, von Hammam ibn Munabbih, der sagte: Dies ist, was Abu Hurayra uns von Muhammad, dem Gesandten Allahs (Friede sei auf ihm), überlieferte. Er erwähnte mehrere Hadithe, darunter: Der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn einer von euch die Gebetswaschung vollzieht, soll er Wasser in seine Nasenlöcher ziehen und es dann ausstoßen.`],
'https://sunnah.com/muslim:237c':[ `Yahya ibn Yahya narrated to us. He said: I read to Malik, from Ibn Shihab, from Abu Idris al-Khawlani, from Abu Hurayra, that the Messenger of Allah (peace be upon him) said: Whoever performs wudu, let him expel water from his nose, and whoever uses stones for cleaning, let him use an odd number.`, `Yahya ibn Yahya überlieferte uns. Er sagte: Ich las Malik vor, von Ibn Schihab, von Abu Idris al-Chawlani, von Abu Hurayra, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Wer die Gebetswaschung vollzieht, soll Wasser aus seiner Nase ausstoßen, und wer Steine zur Reinigung benutzt, soll eine ungerade Zahl verwenden.`],
'https://sunnah.com/muslim:237d':[ `Sa'id ibn Mansur narrated to us. Hassan ibn Ibrahim narrated to us. Yunus ibn Yazid narrated to us. And Harmala ibn Yahya narrated to me. Ibn Wahb informed us. Yunus informed me, from Ibn Shihab. Abu Idris al-Khawlani informed me that he heard Abu Hurayra and Abu Sa'id al-Khudri say: The Messenger of Allah (peace be upon him) said something with the same meaning.`, `Sa'id ibn Mansur überlieferte uns. Hassan ibn Ibrahim überlieferte uns. Yunus ibn Yazid überlieferte uns. Und Harmala ibn Yahya überlieferte mir. Ibn Wahb berichtete uns. Yunus berichtete mir, von Ibn Schihab. Abu Idris al-Chawlani berichtete mir, dass er Abu Hurayra und Abu Sa'id al-Chudri sagen hörte: Der Gesandte Allahs (Friede sei auf ihm) sagte etwas mit derselben Bedeutung.`]
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,en:tr[r.url][0],de:tr[r.url][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-201-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-201-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
