import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:289b':{en:'Abu Kamil al-Jahdari narrated to us. Abd al-Wahid, meaning ibn Ziyad, narrated to us. Abu Kurayb also narrated to us: Ibn al-Mubarak and Ibn Abi Zaida informed us. All of them narrated from Amr ibn Maymun with this chain. Ibn Abi Zaida\'s hadith is as Ibn Bishr said: The Messenger of Allah (peace be upon him) used to wash sexual fluid. In the hadith of Ibn al-Mubarak and Abd al-Wahid she said: I used to wash it from the garment of the Messenger of Allah (peace be upon him).',de:'Abu Kamil al-Jahdari überlieferte uns. Abd al-Wahid, gemeint ist ibn Ziyad, überlieferte uns. Auch Abu Kurayb überlieferte uns: Ibn al-Mubarak und Ibn Abi Zaida berichteten uns. Alle überlieferten von Amr ibn Maymun mit dieser Überlieferungskette. Der Hadith von Ibn Abi Zaida lautet wie bei Ibn Bishr: Der Gesandte Allahs (Friede sei auf ihm) pflegte die Samenflüssigkeit zu waschen. Im Hadith von Ibn al-Mubarak und Abd al-Wahid sagte sie: Ich pflegte sie aus dem Gewand des Gesandten Allahs (Friede sei auf ihm) zu waschen.'},
'https://sunnah.com/muslim:290':{en:'Ahmad ibn Jawwas al-Hanafi, Abu Asim, narrated to us. Abu al-Ahwas narrated to us, from Shabib ibn Gharqada, from Abdullah ibn Shihab al-Khawlani, who said: I was staying with Aisha and had a wet dream in my two garments, so I dipped them in water. Aisha\'s servant girl saw me and told her. Aisha sent for me and said: What made you do this with your two garments? I said: I saw in them what a sleeper sees in his dream. She said: Did you see anything on them? I said: No. She said: If you had seen something, you would have washed it. I saw myself scraping it, while it was dry, from the garment of the Messenger of Allah (peace be upon him) with my fingernail.',de:'Ahmad ibn Jawwas al-Hanafi, Abu Asim, überlieferte uns. Abu al-Ahwas überlieferte uns, von Shabib ibn Gharqada, von Abdullah ibn Shihab al-Khawlani, der sagte: Ich hielt mich bei Aisha auf und hatte in meinen beiden Gewändern einen feuchten Traum, daher tauchte ich sie in Wasser. Aishas Dienstmädchen sah mich und berichtete es ihr. Aisha ließ mich rufen und sagte: Was hat dich dazu gebracht, dies mit deinen beiden Gewändern zu tun? Ich sagte: Ich sah darin, was ein Schlafender in seinem Traum sieht. Sie sagte: Hast du etwas darauf gesehen? Ich sagte: Nein. Sie sagte: Wenn du etwas gesehen hättest, hättest du es gewaschen. Ich sah mich selbst, wie ich es, als es trocken war, mit meinem Fingernagel aus dem Gewand des Gesandten Allahs (Friede sei auf ihm) abkratzte.'},
'https://sunnah.com/muslim:291a':{en:'Abu Bakr ibn Abi Shayba narrated to us. Waki narrated to us. Hisham ibn Urwa narrated to us. Muhammad ibn Hatim also narrated to me, and this is his wording: Yahya ibn Said narrated to us, from Hisham ibn Urwa, who said: Fatima narrated to me, from Asma, who said: A woman came to the Prophet (peace be upon him) and said: If menstrual blood gets on the garment of one of us, what should she do with it? He said: She should scrape it, rub it with water, sprinkle it, and then pray in it.',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Waki überlieferte uns. Hisham ibn Urwa überlieferte uns. Auch Muhammad ibn Hatim überlieferte mir, und dies ist sein Wortlaut: Yahya ibn Said überlieferte uns, von Hisham ibn Urwa, der sagte: Fatima überlieferte mir, von Asma, die sagte: Eine Frau kam zum Propheten (Friede sei auf ihm) und sagte: Wenn Menstruationsblut auf das Gewand einer von uns gelangt, was soll sie damit tun? Er sagte: Sie soll es abkratzen, mit Wasser ausreiben, Wasser darauf spritzen und dann darin beten.'},
'https://sunnah.com/muslim:291b':{en:'Abu Kurayb narrated to us. Ibn Numayr narrated to us. Abu al-Tahir also narrated to me: Ibn Wahb informed me. Yahya ibn Abdullah ibn Salim, Malik ibn Anas, and Amr ibn al-Harith informed me, all from Hisham ibn Urwa, with this chain, with the same meaning as Yahya ibn Said\'s hadith.',de:'Abu Kurayb überlieferte uns. Ibn Numayr überlieferte uns. Auch Abu al-Tahir überlieferte mir: Ibn Wahb berichtete mir. Yahya ibn Abdullah ibn Salim, Malik ibn Anas und Amr ibn al-Harith berichteten mir, alle von Hisham ibn Urwa, mit dieser Überlieferungskette und derselben Bedeutung wie der Hadith von Yahya ibn Said.'},
'https://sunnah.com/muslim:292a':{en:'Abu Said al-Ashajj, Abu Kurayb Muhammad ibn al-Ala, and Ishaq ibn Ibrahim narrated to us. Ishaq said: He informed us, while the other two said: Waki narrated to us. Al-Amash said: I heard Mujahid narrate from Tawus, from Ibn Abbas, who said: The Messenger of Allah (peace be upon him) passed by two graves and said: They are certainly being punished, and they are not being punished for something major. One of them used to spread tales, and the other did not protect himself from his urine. He called for a fresh palm branch, split it in two, and planted one piece on each grave. Then he said: Perhaps their punishment will be lightened as long as these have not dried.',de:'Abu Said al-Ashajj, Abu Kurayb Muhammad ibn al-Ala und Ishaq ibn Ibrahim überlieferten uns. Ishaq sagte: Er berichtete uns, während die beiden anderen sagten: Waki überlieferte uns. Al-Amash sagte: Ich hörte Mujahid von Tawus, von Ibn Abbas, überliefern, der sagte: Der Gesandte Allahs (Friede sei auf ihm) kam an zwei Gräbern vorbei und sagte: Sie werden gewiss bestraft, und sie werden nicht wegen etwas Großem bestraft. Einer von ihnen pflegte üble Nachrede zu verbreiten, und der andere schützte sich nicht vor seinem Urin. Er ließ einen frischen Palmzweig bringen, spaltete ihn in zwei Teile und pflanzte auf jedes Grab einen. Dann sagte er: Vielleicht wird ihre Strafe gelindert, solange diese nicht trocken geworden sind.'},
'https://sunnah.com/muslim:292b':{en:'Ahmad ibn Yusuf al-Azdi narrated it to me. Mualla ibn Asad narrated to us. Abd al-Wahid narrated to us, from Sulayman al-Amash, with this chain, except that he said: The other one did not keep away from urine or protect himself from urine.',de:'Ahmad ibn Yusuf al-Azdi überlieferte ihn mir. Mualla ibn Asad überlieferte uns. Abd al-Wahid überlieferte uns, von Sulayman al-Amash, mit dieser Überlieferungskette, außer dass er sagte: Der andere hielt sich nicht vom Urin fern oder schützte sich nicht vor dem Urin.'},
'https://sunnah.com/muslim:293a':{en:'Abu Bakr ibn Abi Shayba, Zuhayr ibn Harb, and Ishaq ibn Ibrahim narrated to us. Ishaq said: He informed us, while the other two said: Jarir narrated to us, from Mansur, from Ibrahim, from al-Aswad, from Aisha, who said: When one of us was menstruating, the Messenger of Allah (peace be upon him) would order her to wear a waist wrapper, and then he would be intimate with her.',de:'Abu Bakr ibn Abi Shayba, Zuhayr ibn Harb und Ishaq ibn Ibrahim überlieferten uns. Ishaq sagte: Er berichtete uns, während die beiden anderen sagten: Jarir überlieferte uns, von Mansur, von Ibrahim, von al-Aswad, von Aisha, die sagte: Wenn eine von uns menstruierte, pflegte der Gesandte Allahs (Friede sei auf ihm) ihr zu befehlen, einen Hüftschurz anzulegen, und dann war er mit ihr intim.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-215-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-215-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
