import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:284b':{en:'Muhammad ibn al-Muthanna narrated to us. Yahya ibn Said al-Qattan narrated to us, from Yahya ibn Said al-Ansari. Yahya ibn Yahya and Qutayba ibn Said also narrated to us, both from al-Darawardi. Yahya ibn Yahya said: Abd al-Aziz ibn Muhammad al-Madani informed us, from Yahya ibn Said, who heard Anas ibn Malik mention that a Bedouin stood in a part of the mosque and urinated there. The people shouted at him, so the Messenger of Allah (peace be upon him) said: Leave him. When he finished, the Messenger of Allah (peace be upon him) ordered a bucket of water to be poured over his urine.',de:'Muhammad ibn al-Muthanna überlieferte uns. Yahya ibn Said al-Qattan überlieferte uns, von Yahya ibn Said al-Ansari. Auch Yahya ibn Yahya und Qutayba ibn Said überlieferten uns, beide von al-Darawardi. Yahya ibn Yahya sagte: Abd al-Aziz ibn Muhammad al-Madani berichtete uns, von Yahya ibn Said, der Anas ibn Malik sagen hörte, dass ein Beduine an einer Stelle der Moschee aufstand und dort urinierte. Die Leute schrien ihn an, da sagte der Gesandte Allahs (Friede sei auf ihm): Lasst ihn. Als er fertig war, befahl der Gesandte Allahs (Friede sei auf ihm), einen Eimer Wasser über seinen Urin zu gießen.'},
'https://sunnah.com/muslim:285':{en:'Zuhayr ibn Harb narrated to us. Umar ibn Yunus al-Hanafi narrated to us. Ikrima ibn Ammar narrated to us. Ishaq ibn Abi Talha narrated to us. Anas ibn Malik, the uncle of Ishaq, narrated to me and said: While we were in the mosque with the Messenger of Allah (peace be upon him), a Bedouin came and stood urinating in the mosque. The companions of the Messenger of Allah (peace be upon him) said: Stop, stop. The Messenger of Allah (peace be upon him) said: Do not interrupt him; leave him. They left him until he had urinated. Then the Messenger of Allah (peace be upon him) called him and said: These mosques are not suitable for any of this urine or filth. They are only for the remembrance of Allah, the Mighty and Majestic, prayer, and recitation of the Quran, or as the Messenger of Allah (peace be upon him) said. He said: Then he ordered a man from the people to bring a bucket of water and pour it over the urine.',de:'Zuhayr ibn Harb überlieferte uns. Umar ibn Yunus al-Hanafi überlieferte uns. Ikrima ibn Ammar überlieferte uns. Ishaq ibn Abi Talha überlieferte uns. Anas ibn Malik, der Onkel von Ishaq, überlieferte mir und sagte: Während wir mit dem Gesandten Allahs (Friede sei auf ihm) in der Moschee waren, kam ein Beduine und begann, in der Moschee zu urinieren. Die Gefährten des Gesandten Allahs (Friede sei auf ihm) sagten: Hör auf, hör auf. Der Gesandte Allahs (Friede sei auf ihm) sagte: Unterbrecht ihn nicht, lasst ihn. Sie ließen ihn, bis er uriniert hatte. Dann rief der Gesandte Allahs (Friede sei auf ihm) ihn und sagte: Diese Moscheen sind nicht für irgendeinen solchen Urin oder Schmutz geeignet. Sie sind nur für das Gedenken an Allah, den Mächtigen und Erhabenen, für das Gebet und das Rezitieren des Quran, oder so ähnlich sagte der Gesandte Allahs (Friede sei auf ihm). Er sagte: Dann befahl er einem Mann aus der Gruppe, einen Eimer Wasser zu bringen und es über den Urin zu gießen.'},
'https://sunnah.com/muslim:286a':{en:'Abu Bakr ibn Abi Shayba and Abu Kurayb narrated to us. They said: Abdullah ibn Numayr narrated to us, from Hisham, from his father, from Aisha, the wife of the Prophet (peace be upon him), that children were brought to the Messenger of Allah (peace be upon him), and he blessed them and softened dates in their mouths. A boy was brought to him, urinated on him, so he called for water and sprinkled it over the urine without washing it.',de:'Abu Bakr ibn Abi Shayba und Abu Kurayb überlieferten uns. Sie sagten: Abdullah ibn Numayr überlieferte uns, von Hisham, von dessen Vater, von Aisha, der Ehefrau des Propheten (Friede sei auf ihm), dass Kinder zum Gesandten Allahs (Friede sei auf ihm) gebracht wurden und er für sie Segen erbat und ihnen Datteln in den Mund rieb. Ein Junge wurde zu ihm gebracht und urinierte auf ihn. Da ließ er Wasser bringen und spritzte es über den Urin, ohne ihn zu waschen.'},
'https://sunnah.com/muslim:286b':{en:'Zuhayr ibn Harb narrated to us. Jarir narrated to us, from Hisham, from his father, from Aisha, who said: A nursing boy was brought to the Messenger of Allah (peace be upon him). He urinated in his lap, so he called for water and poured it over him.',de:'Zuhayr ibn Harb überlieferte uns. Jarir überlieferte uns, von Hisham, von dessen Vater, von Aisha, die sagte: Ein Säugling wurde zum Gesandten Allahs (Friede sei auf ihm) gebracht. Er urinierte in seinen Schoß, da ließ er Wasser bringen und goss es über ihn.'},
'https://sunnah.com/muslim:286c':{en:'Ishaq ibn Ibrahim narrated to us. Isa informed us. Hisham narrated to us, with this chain, with the same meaning as Ibn Numayr\'s hadith.',de:'Ishaq ibn Ibrahim überlieferte uns. Isa berichtete uns. Hisham überlieferte uns, mit dieser Überlieferungskette und derselben Bedeutung wie der Hadith von Ibn Numayr.'},
'https://sunnah.com/muslim:287a':{en:'Muhammad ibn Rumh ibn al-Muhajir informed us. al-Layth narrated to us, from Ibn Shihab, from Ubaydullah ibn Abdullah, from Umm Qays bint Mihsan, that she brought a son of hers who had not yet eaten food to the Messenger of Allah (peace be upon him). She placed him in his lap, and he urinated. He said: He did no more than sprinkle water over it.',de:'Muhammad ibn Rumh ibn al-Muhajir berichtete uns. al-Layth überlieferte uns, von Ibn Shihab, von Ubaydullah ibn Abdullah, von Umm Qays bint Mihsan, dass sie einen ihrer Söhne, der noch keine Nahrung gegessen hatte, zum Gesandten Allahs (Friede sei auf ihm) brachte. Sie setzte ihn auf seinen Schoß, und er urinierte. Er sagte: Er tat nicht mehr, als Wasser darüber zu spritzen.'},
'https://sunnah.com/muslim:287b':{en:'Yahya ibn Yahya, Abu Bakr ibn Abi Shayba, Amr al-Naqid, and Zuhayr ibn Harb narrated it to us, all from Ibn Uyayna, from al-Zuhri, with this chain. He said: He called for water and sprinkled it over him.',de:'Yahya ibn Yahya, Abu Bakr ibn Abi Shayba, Amr al-Naqid und Zuhayr ibn Harb überlieferten ihn uns, alle von Ibn Uyayna, von al-Zuhri, mit dieser Überlieferungskette. Er sagte: Er ließ Wasser bringen und spritzte es über ihn.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-213-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-213-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
