import fs from 'fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-205.json','utf8'));
const tr:Record<string,[string,string]>={
'https://sunnah.com/muslim:249b':[ `Qutayba ibn Sa'id narrated to us. Abd al-Aziz, al-Darawardi, narrated to us. And Ishaq ibn Musa al-Ansari narrated to me. Ma'n narrated to us. Malik narrated to us. All of them narrated from al-Ala ibn Abd al-Rahman, from his father, from Abu Hurayra, that the Messenger of Allah (peace be upon him) went out to the cemetery and said: Peace be upon you, abode of believing people. If Allah wills, we will join you. It is like Isma'il ibn Ja'far's hadith, except that Malik's hadith says: Some men will certainly be driven away from my Basin.`, `Qutayba ibn Sa'id überlieferte uns. Abd al-Aziz, ad-Darawardi, überlieferte uns. Und Ishaq ibn Musa al-Ansari überlieferte mir. Ma'n überlieferte uns. Malik überlieferte uns. Alle überlieferten von al-Ala ibn Abd ar-Rahman, von seinem Vater, von Abu Hurayra, dass der Gesandte Allahs (Friede sei auf ihm) zum Friedhof hinausging und sagte: Friede sei mit euch, ihr Wohnstätte gläubiger Menschen. Wenn Allah will, werden wir uns euch anschließen. Es ist wie der Hadith von Isma'il ibn Dscha'far, außer dass es im Hadith von Malik heißt: Einige Männer werden gewiss von meinem Becken abgewiesen werden.`],
'https://sunnah.com/muslim:250':[ `Qutayba ibn Sa'id narrated to us. Khalaf, meaning Ibn Khalifa, narrated to us, from Abu Malik al-Ashja'i, from Abu Hazim, who said: I was behind Abu Hurayra while he was performing wudu for prayer. He would extend his hand until it reached his armpit. I said to him: Abu Hurayra, what is this wudu? He said: Children of Farrukh, you are here? If I had known you were here, I would not have performed this wudu. I heard my close friend (peace be upon him) say: The adornment of the believer reaches as far as the wudu reaches.`, `Qutayba ibn Sa'id überlieferte uns. Khalaf, das heißt Ibn Chalifa, überlieferte uns, von Abu Malik al-Aschdschai, von Abu Hazim, der sagte: Ich war hinter Abu Hurayra, während er für das Gebet die Gebetswaschung vollzog. Er streckte seine Hand aus, bis sie seine Achselhöhle erreichte. Ich sagte zu ihm: Abu Hurayra, was ist diese Gebetswaschung? Er sagte: Kinder von Farruch, ihr seid hier? Wenn ich gewusst hätte, dass ihr hier seid, hätte ich diese Gebetswaschung nicht vollzogen. Ich hörte meinen engen Freund (Friede sei auf ihm) sagen: Der Schmuck des Gläubigen reicht so weit, wie die Gebetswaschung reicht.`],
'https://sunnah.com/muslim:251a':[ `Yahya ibn Ayyub, Qutayba, and Ibn Hujr narrated to us, all from Isma'il ibn Ja'far. Ibn Ayyub said: Isma'il narrated to us. al-Ala informed me, from his father, from Abu Hurayra, that the Messenger of Allah (peace be upon him) said: Shall I not tell you about something by which Allah erases sins and raises ranks? They said: Yes, Messenger of Allah. He said: Completing wudu despite difficulties, taking many steps to the mosques, and waiting for one prayer after another. That is ribat.`, `Yahya ibn Ayyub, Qutayba und Ibn Hudschr überlieferten uns, alle von Isma'il ibn Dscha'far. Ibn Ayyub sagte: Isma'il überlieferte uns. al-Ala berichtete mir, von seinem Vater, von Abu Hurayra, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Soll ich euch nicht etwas nennen, wodurch Allah Sünden tilgt und die Rangstufen erhöht? Sie sagten: Ja, Gesandter Allahs. Er sagte: Die Gebetswaschung trotz Schwierigkeiten vollständig zu verrichten, viele Schritte zu den Moscheen zu gehen und auf ein Gebet nach dem anderen zu warten. Das ist Ribat.`],
'https://sunnah.com/muslim:251b':[ `Ishaq ibn Musa al-Ansari narrated to me. Ma'n narrated to us. Malik narrated to us. And Muhammad ibn al-Muthanna narrated to us. Muhammad ibn Ja'far narrated to us. Shu'ba narrated to us. All of them narrated from al-Ala ibn Abd al-Rahman with this chain. Shu'ba's hadith does not mention ribat. In Malik's hadith it says twice: That is ribat, that is ribat.`, `Ishaq ibn Musa al-Ansari überlieferte mir. Ma'n überlieferte uns. Malik überlieferte uns. Und Muhammad ibn al-Muthanna überlieferte uns. Muhammad ibn Dscha'far überlieferte uns. Schu'ba überlieferte uns. Alle überlieferten von al-Ala ibn Abd ar-Rahman mit dieser Kette. Im Hadith von Schu'ba wird Ribat nicht erwähnt. Im Hadith von Malik heißt es zweimal: Das ist Ribat, das ist Ribat.`],
'https://sunnah.com/muslim:252':[ `Qutayba ibn Sa'id, Amr the Critic, and Zuhayr ibn Harb narrated to us. They said: Sufyan narrated to us, from Abu al-Zinad, from al-A'raj, from Abu Hurayra, from the Prophet (peace be upon him), who said: If it would not be hard on the believers, or in Zuhayr's hadith, on my community, I would have commanded them to use the tooth-stick at every prayer.`, `Qutayba ibn Sa'id, Amr, der Kritiker, und Zuhayr ibn Harb überlieferten uns. Sie sagten: Sufyan überlieferte uns, von Abu az-Zinad, von al-A'raj, von Abu Hurayra, vom Propheten (Friede sei auf ihm), der sagte: Wenn es den Gläubigen, oder im Hadith von Zuhayr meiner Gemeinschaft, nicht schwerfallen würde, hätte ich ihnen befohlen, bei jedem Gebet den Siwak zu benutzen.`],
'https://sunnah.com/muslim:253a':[ `Abu Kurayb, Muhammad ibn al-Ala, narrated to us. Ibn Bishr narrated to us, from Mis'ar, from al-Miqdam ibn Shurayh, from his father, who said: I asked Aisha: What did the Prophet (peace be upon him) begin with when he entered his house? She said: The tooth-stick.`, `Abu Kuraib, Muhammad ibn al-Ala, überlieferte uns. Ibn Bischr überlieferte uns, von Mis'ar, von al-Miqdam ibn Schurayh, von seinem Vater, der sagte: Ich fragte Aischa: Womit begann der Prophet (Friede sei auf ihm), wenn er sein Haus betrat? Sie sagte: Mit dem Siwak.`],
'https://sunnah.com/muslim:253b':[ `Abu Bakr ibn Nafi al-Abdi narrated to me. Abd al-Rahman narrated to us, from Sufyan, from al-Miqdam ibn Shurayh, from his father, from Aisha, that when the Prophet (peace be upon him) entered his house, he began with the tooth-stick.`, `Abu Bakr ibn Nafi al-Abdi überlieferte mir. Abd ar-Rahman überlieferte uns, von Sufyan, von al-Miqdam ibn Schurayh, von seinem Vater, von Aischa, dass der Prophet (Friede sei auf ihm), wenn er sein Haus betrat, mit dem Siwak begann.`]
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,en:tr[r.url][0],de:tr[r.url][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-205-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-205-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
