import fs from "node:fs";
const input="data/hadith-words-translations/codex-batch-111.json";
const rows=JSON.parse(fs.readFileSync(input,"utf8"));
const t:Record<string,{en:string;de:string}>={
"4238":{en:"It is reported from al-Zubaydi, from al-Zuhri, who said: Anbasa ibn Said informed me that he heard Abu Hurayra tell Said ibn al-As: The Messenger of Allah (peace be upon him) sent Aban with a unit from Medina toward Najd. Abu Hurayra said: Aban and his companions came to the Prophet (peace be upon him) at Khaybar after he had conquered it, and the packs of their horses were only palm-fiber. Abu Hurayra said: I said, Messenger of Allah, do not give them a share. Aban said: And you say this, you desert hyrax dangling from a sheep’s head? The Prophet (peace be upon him) said: Aban, sit down. He did not give them a share.",de:"Es wird von az-Zubaydi von al-Zuhri berichtet, der sagte: Anbasa ibn Said berichtete mir, dass er Abu Hurayra den Said ibn al-As sagen hörte: Der Gesandte Allahs (Friede sei auf ihm) sandte Aban mit einer Einheit von Medina in Richtung Nadschd. Abu Hurayra sagte: Aban und seine Gefährten kamen nach der Eroberung von Khaybar zum Propheten (Friede sei auf ihm), und die Packsättel ihrer Pferde waren nur aus Palmfasern. Abu Hurayra sagte: Ich sagte: O Gesandter Allahs, gib ihnen keinen Anteil. Aban sagte: Und du sagst so etwas, du Wüstenhyrax, der vom Kopf eines Schafes herabhängt? Der Prophet (Friede sei auf ihm) sagte: O Aban, setz dich. Er gab ihnen keinen Anteil."},
"4239":{en:"Musa ibn Ismail narrated to us. Amr ibn Yahya ibn Said narrated to us: My grandfather informed me that Aban ibn Said came to the Prophet (peace be upon him) and greeted him. Abu Hurayra said: Messenger of Allah, this is the killer of Ibn Qawqal. Aban said to Abu Hurayra: How astonishing you are, a desert hyrax tumbling down from the peak of a sheep! You reproach me for a man whom Allah honored through my hand and prevented from humiliating me through his hand.",de:"Musa ibn Ismail überlieferte uns. Amr ibn Yahya ibn Said überlieferte uns: Mein Großvater berichtete mir, dass Aban ibn Said zum Propheten (Friede sei auf ihm) kam und ihn grüßte. Abu Hurayra sagte: O Gesandter Allahs, das ist der Mörder von Ibn Qawqal. Aban sagte zu Abu Hurayra: Wie erstaunlich du bist, eine Wüstenhyrax, die vom Gipfel eines Schafes hinabrollt! Du machst mir einen Mann zum Vorwurf, den Allah durch meine Hand ehrte und den Er daran hinderte, mich durch seine Hand zu erniedrigen."}
};
const out=rows.map((r:any)=>{const n=r.url.split(":").pop()!;return{id:r.id,n,en:t[n].en,de:t[n].de};});
fs.writeFileSync("data/hadith-words-translations/codex-out-111.json",JSON.stringify(out,null,2)+"\n","utf8");
console.log("wrote "+out.length+" translations");
