import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:334c':{en:'Abu Imran, Muhammad ibn Jafar ibn Ziyad, narrated to me. Ibrahim, meaning ibn Sad, informed us, from Ibn Shihab, from Amra bint Abd al-Rahman, from Aisha, who said: Umm Habiba bint Jahsh came to the Messenger of Allah (peace be upon him), having suffered prolonged bleeding for seven years. This is like the hadith of Amr ibn al-Harith up to the statement: until the redness of the blood rose above the water. He did not mention what followed.',de:'Abu Imran, Muhammad ibn Jafar ibn Ziyad, überlieferte mir. Ibrahim, gemeint ist ibn Sad, berichtete uns, von Ibn Shihab, von Amra bint Abd al-Rahman, von Aisha, die sagte: Umm Habiba bint Jahsh kam zum Gesandten Allahs (Friede sei auf ihm), nachdem sie sieben Jahre lang anhaltende Blutungen gehabt hatte. Dies entspricht dem Hadith von Amr ibn al-Harith bis zu den Worten: bis die Röte des Blutes über das Wasser stieg. Er erwähnte nicht, was danach kam.'},
'https://sunnah.com/muslim:334d':{en:'Muhammad ibn al-Muthanna narrated to me. Sufyan ibn Uyayna narrated to us, from al-Zuhri, from Amra, from Aisha, that the daughter of Jahsh suffered prolonged bleeding for seven years, with a report like theirs.',de:'Muhammad ibn al-Muthanna überlieferte mir. Sufyan ibn Uyayna überlieferte uns, von al-Zuhri, von Amra, von Aisha, dass die Tochter von Jahsh sieben Jahre lang anhaltende Blutungen hatte, mit einem Bericht wie ihren.'},
'https://sunnah.com/muslim:334e':{en:'Muhammad ibn Rumh informed us. Layth narrated to us. Qutayba ibn Said also narrated to us: Layth narrated to us, from Yazid ibn Abi Habib, from Jafar, from Irak, from Urwa, from Aisha, who said: Aisha said: Umm Habiba asked the Messenger of Allah (peace be upon him) about the blood. I saw her tub filled with blood. The Messenger of Allah (peace be upon him) said to her: Stay for the length of time your menstruation used to keep you from prayer, then perform ghusl and pray.',de:'Muhammad ibn Rumh berichtete uns. Layth überlieferte uns. Auch Qutayba ibn Said überlieferte uns: Layth überlieferte uns, von Yazid ibn Abi Habib, von Jafar, von Irak, von Urwa, von Aisha, die sagte: Aisha sagte: Umm Habiba fragte den Gesandten Allahs (Friede sei auf ihm) über das Blut. Ich sah ihre Wanne voller Blut. Der Gesandte Allahs (Friede sei auf ihm) sagte zu ihr: Bleibe so lange, wie deine Menstruation dich gewöhnlich vom Gebet abhielt, dann verrichte Ghusl und bete.'},
'https://sunnah.com/muslim:334f':{en:'Musa ibn Quraysh al-Tamimi narrated to me. Ishaq ibn Bakr ibn Mudar narrated to us. My father narrated to me. Jafar ibn Rabia narrated to me, from Irak ibn Malik, from Urwa ibn al-Zubayr, from Aisha, the wife of the Prophet (peace be upon him), that she said: Umm Habiba bint Jahsh, who was married to Abd al-Rahman ibn Awf, complained to the Messenger of Allah (peace be upon him) about the blood. He said to her: Stay for the length of time your menstruation used to keep you from prayer, then perform ghusl. She used to perform ghusl for every prayer.',de:'Musa ibn Quraysh al-Tamimi überlieferte mir. Ishaq ibn Bakr ibn Mudar überlieferte uns. Mein Vater überlieferte mir. Jafar ibn Rabia überlieferte mir, von Irak ibn Malik, von Urwa ibn al-Zubayr, von Aisha, der Ehefrau des Propheten (Friede sei auf ihm), die sagte: Umm Habiba bint Jahsh, die mit Abd al-Rahman ibn Awf verheiratet war, beklagte sich beim Gesandten Allahs (Friede sei auf ihm) über das Blut. Er sagte zu ihr: Bleibe so lange, wie deine Menstruation dich gewöhnlich vom Gebet abhielt, dann verrichte Ghusl. Sie pflegte für jedes Gebet Ghusl zu verrichten.'},
'https://sunnah.com/muslim:335a':{en:'Abu al-Rabi al-Zahrani narrated to us. Hammad narrated to us, from Ayyub, from Abu Qilaba, from Muadha. Hammad also narrated to us, from Yazid al-Rishk, from Muadha, that a woman asked Aisha: Does one of us make up the prayers from the days of her menstruation? Aisha said: Are you a Haruri? One of us used to menstruate during the time of the Messenger of Allah (peace be upon him), and she was not ordered to make them up.',de:'Abu al-Rabi al-Zahrani überlieferte uns. Hammad überlieferte uns, von Ayyub, von Abu Qilaba, von Muadha. Auch Hammad überlieferte uns, von Yazid al-Rishk, von Muadha, dass eine Frau Aisha fragte: Muss eine von uns die Gebete aus den Tagen ihrer Menstruation nachholen? Aisha sagte: Bist du eine Haruri? Eine von uns menstruierte zur Zeit des Gesandten Allahs (Friede sei auf ihm), und ihr wurde nicht befohlen, sie nachzuholen.'},
'https://sunnah.com/muslim:335b':{en:'Muhammad ibn al-Muthanna narrated to us. Muhammad ibn Jafar narrated to us. Shuba narrated to us, from Yazid, who said: I heard Muadha say that she asked Aisha: Does a menstruating woman make up the prayer? Aisha said: Are you a Haruri? The wives of the Messenger of Allah (peace be upon him) used to menstruate, but did he order them to make them up? Muhammad ibn Jafar said: She meant make them up.',de:'Muhammad ibn al-Muthanna überlieferte uns. Muhammad ibn Jafar überlieferte uns. Shuba überlieferte uns, von Yazid, der sagte: Ich hörte Muadha sagen, dass sie Aisha fragte: Muss eine menstruierende Frau das Gebet nachholen? Aisha sagte: Bist du eine Haruri? Die Ehefrauen des Gesandten Allahs (Friede sei auf ihm) pflegten zu menstruieren, aber befahl er ihnen, sie nachzuholen? Muhammad ibn Jafar sagte: Sie meinte, sie nachzuholen.'},
'https://sunnah.com/muslim:335c':{en:'Abd ibn Humayd informed us. Abd al-Razzaq informed us. Ma\'mar informed us, from Asim, from Muadha, who said: I asked Aisha: Why does a menstruating woman make up the fast but not the prayer? She said: Are you a Haruri? I said: I am not a Haruri, but I am asking. She said: That used to happen to us, and we were ordered to make up the fast, but we were not ordered to make up the prayer.',de:'Abd ibn Humayd berichtete uns. Abd al-Razzaq berichtete uns. Ma\'mar berichtete uns, von Asim, von Muadha, die sagte: Ich fragte Aisha: Warum holt eine menstruierende Frau das Fasten nach, aber nicht das Gebet? Sie sagte: Bist du eine Haruri? Ich sagte: Ich bin keine Haruri, sondern frage nur. Sie sagte: Das geschah uns, und uns wurde befohlen, das Fasten nachzuholen, aber uns wurde nicht befohlen, das Gebet nachzuholen.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-227-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-227-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
