import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:Record<string,{en:string;de:string}>={
'https://sunnah.com/muslim:390a':{en:'Yahya ibn Yahya, Said ibn Mansur, Abu Bakr ibn Abi Shayba, Amr al-Naqid, Zuhayr ibn Harb, and Ibn Numayr all narrated from Sufyan ibn Uyayna. This is Yahya’s wording: Sufyan ibn Uyayna informed us, from al-Zuhri, from Salim, from his father, who said: I saw the Messenger of Allah (peace be upon him) raise his hands when he began prayer until they were level with his shoulders, before bowing, and when he rose from bowing. He did not raise them between the two prostrations.',de:'Yahya ibn Yahya, Said ibn Mansur, Abu Bakr ibn Abi Shayba, Amr al-Naqid, Zuhayr ibn Harb und Ibn Numayr überlieferten alle von Sufyan ibn Uyayna. Dies ist Yahyas Wortlaut: Sufyan ibn Uyayna berichtete uns, von al-Zuhri, von Salim, von dessen Vater, der sagte: Ich sah den Gesandten Allahs (Friede sei auf ihm) beim Beginn des Gebets seine Hände heben, bis sie auf Höhe seiner Schultern waren, vor der Verbeugung und wenn er sich aus der Verbeugung erhob. Zwischen den beiden Niederwerfungen hob er sie nicht.'},
'https://sunnah.com/muslim:390b':{en:'Muhammad ibn Rafi narrated to me. Abd al-Razzaq narrated to us. Ibn Jurayj informed us. Ibn Shihab narrated to me, from Salim ibn Abdullah, that Ibn Umar said: When the Messenger of Allah (peace be upon him) stood for prayer, he raised his hands until they were level with his shoulders, then said the takbir. When he wanted to bow, he did the same, and when he rose from bowing, he did the same. He did not do this when he raised his head from prostration.',de:'Muhammad ibn Rafi überlieferte mir. Abd al-Razzaq überlieferte uns. Ibn Jurayj berichtete uns. Ibn Shihab überlieferte mir, von Salim ibn Abdullah, dass Ibn Umar sagte: Wenn der Gesandte Allahs (Friede sei auf ihm) zum Gebet aufstand, hob er seine Hände, bis sie auf Höhe seiner Schultern waren, und sprach dann den Takbir. Wenn er sich verbeugen wollte, tat er dasselbe, und wenn er sich aus der Verbeugung erhob, tat er dasselbe. Wenn er den Kopf aus der Niederwerfung hob, tat er dies nicht.'},
'https://sunnah.com/muslim:390c':{en:'Muhammad ibn Rafi narrated to me. Hujayn, who was Ibn al-Muthanna, narrated to us. al-Layth narrated to us, from Uqayl. And Muhammad ibn Abdullah ibn Qahdhaz narrated to me. Salama ibn Sulayman narrated to us. Yunus informed us. Both narrated from al-Zuhri with this chain, as Ibn Jurayj said: When the Messenger of Allah (peace be upon him) stood for prayer, he raised his hands until they were level with his shoulders, then said the takbir.',de:'Muhammad ibn Rafi überlieferte mir. Hujayn, nämlich Ibn al-Muthanna, überlieferte uns. al-Layth überlieferte uns, von Uqayl. Und Muhammad ibn Abdullah ibn Qahdhaz überlieferte mir. Salama ibn Sulayman überlieferte uns. Yunus berichtete uns. Beide überlieferten von al-Zuhri mit dieser Überlieferungskette, wie Ibn Jurayj sagte: Wenn der Gesandte Allahs (Friede sei auf ihm) zum Gebet aufstand, hob er seine Hände, bis sie auf Höhe seiner Schultern waren, und sprach dann den Takbir.'},
'https://sunnah.com/muslim:391a':{en:'Yahya ibn Yahya informed us. Khalid ibn Abdullah informed us, from Khalid, from Abu Qilaba, that he saw Malik ibn al-Huwayrith: When he prayed, he said the takbir, then raised his hands. When he wanted to bow, he raised his hands, and when he raised his head from bowing, he raised his hands. He related that the Messenger of Allah (peace be upon him) used to do this.',de:'Yahya ibn Yahya berichtete uns. Khalid ibn Abdullah berichtete uns, von Khalid, von Abu Qilaba, dass er Malik ibn al-Huwayrith sah: Wenn er betete, sprach er den Takbir und hob dann seine Hände. Wenn er sich verbeugen wollte, hob er seine Hände, und wenn er seinen Kopf aus der Verbeugung hob, hob er seine Hände. Er berichtete, dass der Gesandte Allahs (Friede sei auf ihm) dies zu tun pflegte.'},
'https://sunnah.com/muslim:391b':{en:'Abu Kamil al-Jahdari narrated to us. Abu Awana narrated to us, from Qatada, from Nasr ibn Asim, from Malik ibn al-Huwayrith, that when the Messenger of Allah (peace be upon him) said the takbir, he raised his hands until they were level with his ears. When he bowed, he raised his hands until they were level with his ears. When he raised his head from bowing and said, “Allah hears whoever praises Him,” he did the same.',de:'Abu Kamil al-Jahdari überlieferte uns. Abu Awana überlieferte uns, von Qatada, von Nasr ibn Asim, von Malik ibn al-Huwayrith, dass der Gesandte Allahs (Friede sei auf ihm), wenn er den Takbir sprach, seine Hände hob, bis sie auf Höhe seiner Ohren waren. Wenn er sich verbeugte, hob er seine Hände, bis sie auf Höhe seiner Ohren waren. Wenn er seinen Kopf aus der Verbeugung hob und sagte: „Allah hört den, der Ihn lobt“, tat er dasselbe.'},
'https://sunnah.com/muslim:391c':{en:'Muhammad ibn al-Muthanna narrated it to us. Ibn Abi Adi narrated to us, from Said, from Qatada, with this chain, that he saw the Prophet of Allah (peace be upon him), and he said: Until they were level with the tips of his ears.',de:'Muhammad ibn al-Muthanna überlieferte ihn uns. Ibn Abi Adi überlieferte uns, von Said, von Qatada, mit dieser Überlieferungskette, dass er den Propheten Allahs (Friede sei auf ihm) sah, und er sagte: Bis sie auf Höhe der Ohrspitzen waren.'},
'https://sunnah.com/muslim:392a':{en:'Yahya ibn Yahya narrated to us. He said: I read to Malik, from Ibn Shihab, from Abu Salama ibn Abd al-Rahman, that Abu Hurayra used to lead them in prayer. He said the takbir every time he lowered himself and rose. When he finished, he said: By Allah, my prayer most closely resembles the prayer of the Messenger of Allah (peace be upon him).',de:'Yahya ibn Yahya überlieferte uns. Er sagte: Ich las Malik vor, von Ibn Shihab, von Abu Salama ibn Abd al-Rahman, dass Abu Hurayra sie im Gebet leitete. Er sprach jedes Mal den Takbir, wenn er sich niederließ und aufstand. Als er fertig war, sagte er: Bei Allah, mein Gebet ähnelt dem Gebet des Gesandten Allahs (Friede sei auf ihm) am meisten.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]})); if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-243-part.json',JSON.stringify(out,null,2)); fs.writeFileSync('data/hadith-words-translations/codex-out-243-part.json',JSON.stringify(out,null,2)); console.log(`wrote ${out.length} staged translations`);
