import fs from 'node:fs';

const rows: any[] = JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json', 'utf8'));
const tr: Record<string, { en: string; de: string }> = {
  'https://sunnah.com/muslim:346a': {
    en: 'Abu al-Rabi al-Zahrani narrated to us. Hammad narrated to us. Hisham ibn Urwa narrated to us. And Abu Kurayb, Muhammad ibn al-Ala, narrated to us, and this is his wording. Abu Muawiya narrated to us. Hisham narrated to us, from his father, from Abu Ayyub, from Ubayy ibn Kab, who said: I asked the Messenger of Allah (peace be upon him) about a man who has intercourse with a woman and then becomes unable to continue. He said: He should wash whatever touched the woman, then perform wudu and pray.',
    de: 'Abu al-Rabi al-Zahrani überlieferte uns. Hammad überlieferte uns. Hisham ibn Urwa überlieferte uns. Und Abu Kurayb, Muhammad ibn al-Ala, überlieferte uns, und dies ist sein Wortlaut. Abu Muawiya überlieferte uns. Hisham überlieferte uns, von dessen Vater, von Abu Ayyub, von Ubayy ibn Kab, der sagte: Ich fragte den Gesandten Allahs (Friede sei auf ihm) nach einem Mann, der mit einer Frau Geschlechtsverkehr hat und dann nicht mehr weitermachen kann. Er sagte: Er soll das waschen, was die Frau berührt hat, dann Wudu verrichten und beten.'
  },
  'https://sunnah.com/muslim:346b': {
    en: 'Muhammad ibn al-Muthanna narrated to us. Muhammad ibn Jafar narrated to us. Shuba narrated to us, from Hisham ibn Urwa, who said: My father narrated to me, from al-Milli, from al-Milli, meaning by his statement “al-Milli from al-Milli”: Abu Ayyub, from Ubayy ibn Kab, from the Messenger of Allah (peace be upon him), that he said concerning a man who goes to his wife and then does not ejaculate: He should wash his penis and perform wudu.',
    de: 'Muhammad ibn al-Muthanna überlieferte uns. Muhammad ibn Jafar überlieferte uns. Shuba überlieferte uns, von Hisham ibn Urwa, der sagte: Mein Vater überlieferte mir, von al-Milli, von al-Milli, wobei mit seiner Aussage „al-Milli von al-Milli“ gemeint ist: Abu Ayyub, von Ubayy ibn Kab, vom Gesandten Allahs (Friede sei auf ihm), dass er über einen Mann sagte, der zu seiner Frau geht und dann nicht ejakuliert: Er soll sein Geschlechtsteil waschen und Wudu verrichten.'
  },
  'https://sunnah.com/muslim:347a': {
    en: 'Zuhayr ibn Harb and Abd ibn Humayd narrated to us. They said: Abd al-Samad ibn Abd al-Warith narrated to us. And Abd al-Warith ibn Abd al-Samad narrated to me, and this is his wording. My father narrated to me, from my grandfather, from al-Husayn ibn Dhakwan, from Yahya ibn Abi Kathir. Abu Salama informed me that Ata ibn Yasar informed him that Zayd ibn Khalid al-Juhani informed him that he asked Uthman ibn Affan. He said: I said: What do you say if a man has intercourse with his wife but does not ejaculate? Uthman said: He should perform wudu as for prayer and wash his penis. Uthman said: I heard this from the Messenger of Allah (peace be upon him).',
    de: 'Zuhayr ibn Harb und Abd ibn Humayd überlieferten uns. Sie sagten: Abd al-Samad ibn Abd al-Warith überlieferte uns. Und Abd al-Warith ibn Abd al-Samad überlieferte mir, und dies ist sein Wortlaut. Mein Vater überlieferte mir, von meinem Großvater, von al-Husayn ibn Dhakwan, von Yahya ibn Abi Kathir. Abu Salama berichtete mir, dass Ata ibn Yasar ihm berichtete, dass Zaid ibn Khalid al-Juhani ihm berichtete, dass er Uthman ibn Affan fragte. Er sagte: Ich sagte: Was sagst du, wenn ein Mann mit seiner Frau Geschlechtsverkehr hat, aber nicht ejakuliert? Uthman sagte: Er soll Wudu wie zum Gebet verrichten und sein Geschlechtsteil waschen. Uthman sagte: Ich hörte dies vom Gesandten Allahs (Friede sei auf ihm).'
  },
  'https://sunnah.com/muslim:347b': {
    en: 'Abd al-Warith ibn Abd al-Samad narrated to us. My father narrated to me, from my grandfather, from al-Husayn. Yahya said: Abu Salama informed me that Urwa ibn al-Zubayr informed him that Abu Ayyub informed him that he heard this from the Messenger of Allah (peace be upon him).',
    de: 'Abd al-Warith ibn Abd al-Samad überlieferte uns. Mein Vater überlieferte mir, von meinem Großvater, von al-Husayn. Yahya sagte: Abu Salama berichtete mir, dass Urwa ibn al-Zubayr ihm berichtete, dass Abu Ayyub ihm berichtete, dass er dies vom Gesandten Allahs (Friede sei auf ihm) hörte.'
  },
  'https://sunnah.com/muslim:348a': {
    en: 'Zuhayr ibn Harb and Abu Ghassan al-Mismai narrated it to me. Muhammad ibn al-Muthanna and Ibn Bashshar also narrated it to us. They said: Muadh ibn Hisham narrated to us. He said: My father narrated to me, from Qatada and Matar, from al-Hasan, from Abu Rafi, from Abu Hurayra, that the Prophet of Allah (peace be upon him) said: When he sits between her four limbs and then exerts himself with her, ghusl becomes obligatory for him. In Matar’s hadith: Even if he does not ejaculate. Zuhayr said in their wording: Between her four openings.',
    de: 'Zuhayr ibn Harb und Abu Ghassan al-Mismai überlieferten ihn mir. Muhammad ibn al-Muthanna und Ibn Bashshar überlieferten ihn uns ebenfalls. Sie sagten: Muadh ibn Hisham überlieferte uns. Er sagte: Mein Vater überlieferte mir, von Qatada und Matar, von al-Hasan, von Abu Rafi, von Abu Hurayra, dass der Prophet Allahs (Friede sei auf ihm) sagte: Wenn er zwischen ihren vier Gliedmaßen sitzt und sich dann mit ihr anstrengt, wird der Ghusl für ihn verpflichtend. In Matars Hadith: Auch wenn er nicht ejakuliert. Zuhayr sagte in ihrem Wortlaut: Zwischen ihren vier Öffnungen.'
  },
  'https://sunnah.com/muslim:348b': {
    en: 'Muhammad ibn Amr ibn Abbad ibn Jabala narrated to us. Muhammad ibn Abi Adi narrated to us. And Muhammad ibn al-Muthanna narrated to us: Wahb ibn Jarir narrated to me. Both narrated from Shuba, from Qatada, with this chain and the same meaning, except that in Shuba’s hadith it says: Then he exerted himself, and it does not say: Even if he does not ejaculate.',
    de: 'Muhammad ibn Amr ibn Abbad ibn Jabala überlieferte uns. Muhammad ibn Abi Adi überlieferte uns. Und Muhammad ibn al-Muthanna überlieferte uns: Wahb ibn Jarir überlieferte mir. Beide überlieferten von Shuba, von Qatada, mit dieser Überlieferungskette und derselben Bedeutung, außer dass es in Shubas Hadith heißt: Dann strengte er sich an, und es heißt nicht: Auch wenn er nicht ejakuliert.'
  },
  'https://sunnah.com/muslim:349': {
    en: 'Muhammad ibn al-Muthanna narrated to us. Muhammad ibn Abdullah al-Ansari narrated to us. Hisham ibn Hassan narrated to us. Humayd ibn Hilal narrated to us, from Abu Burda, from Abu Musa al-Ashari. And Muhammad ibn al-Muthanna narrated to us. Abd al-Ala narrated to us, and this is his hadith. Hisham narrated to us, from Humayd ibn Hilal, who said: I know this only from Abu Burda, from Abu Musa, who said: A group of the Emigrants and the Ansar differed about this. The Ansar said: Ghusl is only obligatory because of emission or fluid. The Emigrants said: Rather, when the sexual organs meet, ghusl becomes obligatory. Abu Musa said: I will resolve this for you. I stood up, sought permission to enter upon Aisha, and was given permission. I said to her: O Mother, or O Mother of the Believers, I want to ask you about something, but I am shy before you. She said: Do not be shy to ask me about what you would ask your mother who gave birth to you, for I am your mother. I said: What makes ghusl obligatory? She said: You have asked an expert. The Messenger of Allah (peace be upon him) said: When he sits between her four limbs and the circumcised parts touch each other, ghusl becomes obligatory.',
    de: 'Muhammad ibn al-Muthanna überlieferte uns. Muhammad ibn Abdullah al-Ansari überlieferte uns. Hisham ibn Hassan überlieferte uns. Humayd ibn Hilal überlieferte uns, von Abu Burda, von Abu Musa al-Ashari. Und Muhammad ibn al-Muthanna überlieferte uns. Abd al-Ala überlieferte uns, und dies ist sein Hadith. Hisham überlieferte uns, von Humayd ibn Hilal, der sagte: Ich kenne dies nur von Abu Burda, von Abu Musa, der sagte: Eine Gruppe der Auswanderer und der Ansar war sich darüber uneinig. Die Ansar sagten: Der Ghusl wird nur durch Samenerguss oder Flüssigkeit verpflichtend. Die Auswanderer sagten: Vielmehr wird der Ghusl verpflichtend, wenn die Geschlechtsteile einander berühren. Abu Musa sagte: Ich werde diese Frage für euch klären. Ich stand auf, bat um Erlaubnis, bei Aisha einzutreten, und erhielt die Erlaubnis. Ich sagte zu ihr: O Mutter, oder o Mutter der Gläubigen, ich möchte dich nach etwas fragen, aber ich schäme mich vor dir. Sie sagte: Schäme dich nicht, mich nach dem zu fragen, wonach du deine Mutter fragen würdest, die dich geboren hat, denn ich bin deine Mutter. Ich sagte: Was macht den Ghusl verpflichtend? Sie sagte: Du bist zu einem Kenner gelangt. Der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn er zwischen ihren vier Gliedmaßen sitzt und die beschnittenen Teile einander berühren, wird der Ghusl verpflichtend.'
  }
};

const out = rows.filter((r) => tr[r.url]).map((r) => ({ ...r, ...tr[r.url] }));
if (out.length !== 7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-231-part.json', JSON.stringify(out, null, 2));
fs.writeFileSync('data/hadith-words-translations/codex-out-231-part.json', JSON.stringify(out, null, 2));
console.log(`wrote ${out.length} staged translations`);
