import fs from 'fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-206.json','utf8'));
const tr:Record<string,[string,string]>={
'https://sunnah.com/muslim:254':[ `Yahya ibn Habib al-Harithi narrated to us. Hammad ibn Zayd narrated to us, from Ghailan, Ibn Jarir al-Ma'wali, from Abu Burda, from Abu Musa, who said: I entered upon the Prophet (peace be upon him) while the end of the tooth-stick was on his tongue.`, `Yahya ibn Habib al-Harithi überlieferte uns. Hammad ibn Zayd überlieferte uns, von Ghailan, Ibn Dscharir al-Ma'wali, von Abu Burda, von Abu Musa, der sagte: Ich trat beim Propheten (Friede sei auf ihm) ein, während sich das Ende des Siwak auf seiner Zunge befand.`],
'https://sunnah.com/muslim:255a':[ `Abu Bakr ibn Abi Shayba narrated to us. Hushaym narrated to us, from Husayn, from Abu Wa'il, from Hudhayfa, who said: When the Messenger of Allah (peace be upon him) stood to perform the night prayer, he cleaned his mouth with the tooth-stick.`, `Abu Bakr ibn Abi Schayba überlieferte uns. Huschaym überlieferte uns, von Husayn, von Abu Wa'il, von Hudhayfa, der sagte: Wenn der Gesandte Allahs (Friede sei auf ihm) zum Nachtgebet aufstand, reinigte er seinen Mund mit dem Siwak.`],
'https://sunnah.com/muslim:255b':[ `Ishaq ibn Ibrahim informed us. Jarir narrated to us, from Mansur. And Ibn Numayr narrated to us. My father and Abu Muawiya narrated to us, from al-A'mash. Both narrated from Abu Wa'il, from Hudhayfa, who said: When the Messenger of Allah (peace be upon him) stood at night, he did the same. They did not say: to perform the night prayer.`, `Ishaq ibn Ibrahim berichtete uns. Jarir überlieferte uns, von Mansur. Und Ibn Numayr überlieferte uns. Mein Vater und Abu Mu'awiya überlieferten uns, von al-A'masch. Beide überlieferten von Abu Wa'il, von Hudhayfa, der sagte: Wenn der Gesandte Allahs (Friede sei auf ihm) nachts aufstand, tat er dasselbe. Sie sagten nicht: um das Nachtgebet zu verrichten.`],
'https://sunnah.com/muslim:255c':[ `Muhammad ibn al-Muthanna and Ibn Bashshar narrated to us. They said: Abd al-Rahman narrated to us. Sufyan narrated to us, from Mansur, Husayn, and al-A'mash, from Abu Wa'il, from Hudhayfa, that when the Messenger of Allah (peace be upon him) stood at night, he cleaned his mouth with the tooth-stick.`, `Muhammad ibn al-Muthanna und Ibn Baschar überlieferten uns. Sie sagten: Abd ar-Rahman überlieferte uns. Sufyan überlieferte uns, von Mansur, Husayn und al-A'masch, von Abu Wa'il, von Hudhayfa, dass der Gesandte Allahs (Friede sei auf ihm), wenn er nachts aufstand, seinen Mund mit dem Siwak reinigte.`],
'https://sunnah.com/muslim:256':[ `Abd ibn Humayd narrated to us. Abu Nu'aym narrated to us. Isma'il ibn Muslim narrated to us. Abu al-Mutawakkil narrated to us that Ibn Abbas told him that he spent a night with the Prophet (peace be upon him). The Prophet of Allah (peace be upon him) rose late in the night, went out, looked at the sky, and recited this verse from Al Imran: (Quran 3:190) Surely in the creation of the heavens and the earth and the alternation of night and day, until he reached (Quran 3:191) So protect us from the punishment of the Fire. Then he returned to the house, used the tooth-stick, performed wudu, and prayed. Then he lay down, then rose, went out, looked at the sky, recited the verse, returned, used the tooth-stick, performed wudu, and prayed.`, `Abd ibn Humayd überlieferte uns. Abu Nu'aym überlieferte uns. Isma'il ibn Muslim überlieferte uns. Abu al-Mutawakkil überlieferte uns, dass Ibn Abbas ihm berichtete, dass er eine Nacht beim Propheten (Friede sei auf ihm) verbrachte. Der Prophet Allahs (Friede sei auf ihm) stand spät in der Nacht auf, ging hinaus, schaute zum Himmel und rezitierte diesen Vers aus Al Imran: (Quran 3:190) Wahrlich, in der Schöpfung der Himmel und der Erde und im Wechsel von Nacht und Tag, bis er zu (Quran 3:191) So bewahre uns vor der Strafe des Feuers, gelangte. Dann kehrte er ins Haus zurück, benutzte den Siwak, vollzog die Gebetswaschung und betete. Dann legte er sich hin, stand wieder auf, ging hinaus, schaute zum Himmel und rezitierte den Vers, kehrte zurück, benutzte den Siwak, vollzog die Gebetswaschung und betete.`],
'https://sunnah.com/muslim:257a':[ `Abu Bakr ibn Abi Shayba, Amr the Critic, and Zuhayr ibn Harb narrated to us, all from Sufyan. Abu Bakr said: Ibn Uyayna narrated to us, from al-Zuhri, from Sa'id ibn al-Musayyab, from Abu Hurayra, from the Prophet (peace be upon him), who said: The natural disposition is five, or five things belong to the natural disposition: circumcision, shaving the pubic hair, trimming the nails, plucking the armpit hair, and trimming the moustache.`, `Abu Bakr ibn Abi Schayba, Amr, der Kritiker, und Zuhayr ibn Harb überlieferten uns, alle von Sufyan. Abu Bakr sagte: Ibn Uyayna überlieferte uns, von az-Zuhri, von Sa'id ibn al-Musayyab, von Abu Hurayra, vom Propheten (Friede sei auf ihm), der sagte: Die natürliche Veranlagung umfasst fünf Dinge, oder fünf Dinge gehören zur natürlichen Veranlagung: Beschneidung, Rasieren der Schamhaare, Schneiden der Nägel, Auszupfen der Achselhaare und Kürzen des Schnurrbarts.`],
'https://sunnah.com/muslim:257b':[ `Abu al-Tahir and Harmala ibn Yahya narrated to me. They said: Ibn Wahb informed us. Yunus informed me, from Ibn Shihab, from Sa'id ibn al-Musayyab, from Abu Hurayra, from the Messenger of Allah (peace be upon him), that he said: The natural disposition is five: circumcision, shaving the pubic hair, trimming the moustache, trimming the nails, and plucking the armpit hair.`, `Abu at-Tahir und Harmala ibn Yahya überlieferten mir. Sie sagten: Ibn Wahb berichtete uns. Yunus berichtete mir, von Ibn Schihab, von Sa'id ibn al-Musayyab, von Abu Hurayra, vom Gesandten Allahs (Friede sei auf ihm), dass er sagte: Die natürliche Veranlagung umfasst fünf Dinge: Beschneidung, Rasieren der Schamhaare, Kürzen des Schnurrbarts, Schneiden der Nägel und Auszupfen der Achselhaare.`]
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,en:tr[r.url][0],de:tr[r.url][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-206-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-206-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
