import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-207.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:262a':{en:'Abu Bakr ibn Abi Shayba narrated to us. Abu Muawiya and Waki narrated to us, from al-Amash. Yahya ibn Yahya also narrated to us, and this is his wording: Abu Muawiya informed us, from al-Amash, from Ibrahim, from Abd al-Rahman ibn Yazid, from Salman, who said: He was told, “Your Prophet has taught you everything, even how to relieve yourselves.” He said: Yes indeed. He forbade us to face the qiblah for defecation or urination, to clean ourselves with the right hand, to clean ourselves with fewer than three stones, or to clean ourselves with dung or bones.',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Abu Muawiya und Waki überlieferten uns, von al-Amash. Yahya ibn Yahya überlieferte uns ebenfalls, und dies ist sein Wortlaut: Abu Muawiya berichtete uns, von al-Amash, von Ibrahim, von Abd al-Rahman ibn Yazid, von Salman, der sagte: Zu ihm wurde gesagt: „Euer Prophet hat euch alles gelehrt, sogar wie ihr euch erleichtert.“ Er sagte: Ja, gewiss. Er verbot uns, bei der Darmentleerung oder dem Urinieren die Qibla zugewandt zu sein, uns mit der rechten Hand zu reinigen, uns mit weniger als drei Steinen zu reinigen oder uns mit Dung oder Knochen zu reinigen.'},
'https://sunnah.com/muslim:262b':{en:'Muhammad ibn al-Muthanna narrated to us. Abd al-Rahman narrated to us. Sufyan narrated to us, from al-Amash and Mansur, from Ibrahim, from Abd al-Rahman ibn Yazid, from Salman, who said: The polytheists said to us, “I see that your companion teaches you everything, even how to relieve yourselves.” He said: Yes. He forbade us that any of us should clean himself with his right hand or face the qiblah, and he forbade dung and bones. He said: None of you should clean himself with fewer than three stones.',de:'Muhammad ibn al-Muthanna überlieferte uns. Abd al-Rahman überlieferte uns. Sufyan überlieferte uns, von al-Amash und Mansur, von Ibrahim, von Abd al-Rahman ibn Yazid, von Salman, der sagte: Die Götzendiener sagten zu uns: „Ich sehe, dass euer Gefährte euch alles lehrt, sogar wie ihr euch erleichtert.“ Er sagte: Ja. Er verbot uns, dass einer von uns sich mit seiner rechten Hand reinigen oder der Qibla zugewandt sein soll, und er verbot Dung und Knochen. Er sagte: Keiner von euch soll sich mit weniger als drei Steinen reinigen.'},
'https://sunnah.com/muslim:263':{en:'Zuhayr ibn Harb narrated to us. Ruh ibn Ubadah narrated to us. Zakariyya ibn Ishaq narrated to us. Abu al-Zubayr narrated to us that he heard Jabir say: The Messenger of Allah (peace be upon him) forbade using a bone or dried dung for wiping.',de:'Zuhayr ibn Harb überlieferte uns. Ruh ibn Ubadah überlieferte uns. Zakariyya ibn Ishaq überlieferte uns. Abu al-Zubayr überlieferte uns, dass er Jabir sagen hörte: Der Gesandte Allahs (Friede sei auf ihm) verbot, einen Knochen oder getrockneten Dung zum Abwischen zu verwenden.'},
'https://sunnah.com/muslim:264':{en:'Zuhayr ibn Harb and Ibn Numayr narrated to us. They said: Sufyan ibn Uyayna narrated to us. He said: Yahya ibn Yahya narrated to us, and this is his wording. I said to Sufyan ibn Uyayna: Did you hear al-Zuhri mention, from Ata ibn Yazid al-Laythi, from Abu Ayyub, that the Prophet (peace be upon him) said: When you go to relieve yourselves, do not face the qiblah or turn your backs to it while urinating or defecating, but face east or west. Abu Ayyub said: When we came to Syria, we found toilets built facing the qiblah, so we turned away from them and asked Allah for forgiveness. He said: Yes.',de:'Zuhayr ibn Harb und Ibn Numayr überlieferten uns. Sie sagten: Sufyan ibn Uyayna überlieferte uns. Er sagte: Yahya ibn Yahya überlieferte uns, und dies ist sein Wortlaut. Ich sagte zu Sufyan ibn Uyayna: Hast du al-Zuhri gehört, wie er von Ata ibn Yazid al-Laythi, von Abu Ayyub, erwähnte, dass der Prophet (Friede sei auf ihm) sagte: Wenn ihr euch erleichtert, dann wendet euch beim Urinieren oder beim Stuhlgang nicht der Qibla zu und kehrt ihr nicht den Rücken zu, sondern wendet euch nach Osten oder Westen. Abu Ayyub sagte: Als wir nach Syrien kamen, fanden wir Toiletten, die zur Qibla hin gebaut waren. Daher wandten wir uns von ihnen ab und baten Allah um Vergebung. Er sagte: Ja.'},
'https://sunnah.com/muslim:265':{en:'Ahmad ibn al-Hasan ibn Khirash narrated to us. Umar ibn Abd al-Wahhab narrated to us. Yazid, meaning ibn Zuray, narrated to us. Ruh narrated to us, from Suhayl, from al-Qaqa, from Abu Salih, from Abu Hurayra, from the Messenger of Allah (peace be upon him), who said: When one of you sits to relieve himself, let him not face the qiblah or turn his back to it.',de:'Ahmad ibn al-Hasan ibn Khirash überlieferte uns. Umar ibn Abd al-Wahhab überlieferte uns. Yazid, gemeint ist ibn Zuray, überlieferte uns. Ruh überlieferte uns, von Suhayl, von al-Qaqa, von Abu Salih, von Abu Hurayra, vom Gesandten Allahs (Friede sei auf ihm), der sagte: Wenn einer von euch sich hinsetzt, um sich zu erleichtern, soll er sich weder der Qibla zuwenden noch ihr den Rücken zukehren.'},
'https://sunnah.com/muslim:266a':{en:'Abdullah ibn Maslama ibn Qanab narrated to us. Sulayman, meaning ibn Bilal, narrated to us, from Yahya ibn Sa\'id, from Muhammad ibn Yahya, from his uncle, Wasil ibn Hayyan, who said: I was praying in the mosque while Abdullah ibn Umar was leaning with his back toward the qiblah. When I finished my prayer, I turned toward him from my side. Abdullah said: Some people say that when you sit to relieve yourself, you must not sit facing the qiblah or Bayt al-Maqdis. Abdullah said: I once climbed onto the roof of a house and saw the Messenger of Allah (peace be upon him) sitting on two bricks, facing Bayt al-Maqdis while relieving himself.',de:'Abdullah ibn Maslama ibn Qanab überlieferte uns. Sulayman, gemeint ist ibn Bilal, überlieferte uns, von Yahya ibn Sa\'id, von Muhammad ibn Yahya, von dessen Onkel Wasil ibn Hayyan, der sagte: Ich betete in der Moschee, während Abdullah ibn Umar mit dem Rücken zur Qibla gelehnt war. Als ich mein Gebet beendet hatte, wandte ich mich von der Seite zu ihm. Abdullah sagte: Manche Menschen sagen, wenn du dich hinsetzt, um dich zu erleichtern, darfst du weder der Qibla noch Bayt al-Maqdis zugewandt sitzen. Abdullah sagte: Ich stieg einmal auf das Dach eines Hauses und sah den Gesandten Allahs (Friede sei auf ihm) auf zwei Ziegeln sitzen, Bayt al-Maqdis zugewandt, während er sich erleichterte.'},
'https://sunnah.com/muslim:266b':{en:'Abu Bakr ibn Abi Shayba narrated to us. Muhammad ibn Bishr al-Abdi narrated to us. Ubaydullah ibn Umar narrated to us, from Muhammad ibn Yahya ibn Haban, from his uncle Wasil ibn Hayyan, from Ibn Umar, who said: I climbed onto the house of my sister Hafsa and saw the Messenger of Allah (peace be upon him) sitting to relieve himself, facing Syria and turning his back to the qiblah.',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Muhammad ibn Bishr al-Abdi überlieferte uns. Ubaydullah ibn Umar überlieferte uns, von Muhammad ibn Yahya ibn Haban, von dessen Onkel Wasil ibn Hayyan, von Ibn Umar, der sagte: Ich stieg auf das Haus meiner Schwester Hafsa und sah den Gesandten Allahs (Friede sei auf ihm) sitzen, um sich zu erleichtern, Syrien zugewandt und der Qibla den Rücken zugekehrt.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-207-part2.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-207-part2.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
