import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-next.json','utf8'));
const tr:Record<string,{en:string;de:string}>={
'https://sunnah.com/muslim:374c':{en:'Yahya ibn Yahya narrated to us. Muhammad ibn Muslim al-Taifi informed us, from Amr ibn Dinar, from Said ibn al-Huwayrith, the client of the family of al-Saib, that he heard Abdullah ibn Abbas say: The Messenger of Allah (peace be upon him) went to relieve himself. When he came back, food was presented to him, and it was said: O Messenger of Allah, will you not perform wudu? He said: Why? For prayer?',de:'Yahya ibn Yahya überlieferte uns. Muhammad ibn Muslim al-Taifi berichtete uns, von Amr ibn Dinar, von Said ibn al-Huwayrith, dem Schutzbefohlenen der Familie von al-Saib, dass er Abdullah ibn Abbas sagen hörte: Der Gesandte Allahs (Friede sei auf ihm) ging, um sich zu erleichtern. Als er zurückkam, wurde ihm Essen vorgesetzt, und es wurde gesagt: O Gesandter Allahs, wirst du nicht Wudu verrichten? Er sagte: Warum? Für das Gebet?'},
'https://sunnah.com/muslim:374d':{en:'Muhammad ibn Amr ibn Abbad ibn Jabala narrated to me. Abu Asim narrated to us, from Ibn Jurayj, who said: Said ibn Huwayrith narrated to us that he heard Ibn Abbas say: The Prophet (peace be upon him) relieved himself, then food was brought near him. He ate without touching water. He said: Amr ibn Dinar added to me, from Said ibn Huwayrith, that the Prophet (peace be upon him) was told: You did not perform wudu. He said: I did not intend to pray, so why should I perform wudu? Amr claimed that he heard this from Said ibn Huwayrith.',de:'Muhammad ibn Amr ibn Abbad ibn Jabala überlieferte mir. Abu Asim überlieferte uns, von Ibn Jurayj, der sagte: Said ibn Huwayrith überlieferte uns, dass er Ibn Abbas sagen hörte: Der Prophet (Friede sei auf ihm) erleichterte sich, dann wurde ihm Essen gebracht. Er aß, ohne Wasser zu berühren. Er sagte: Amr ibn Dinar fügte mir von Said ibn Huwayrith hinzu, dass dem Propheten (Friede sei auf ihm) gesagt wurde: Du hast kein Wudu verrichtet. Er sagte: Ich hatte nicht vor zu beten, warum sollte ich also Wudu verrichten? Amr behauptete, dass er dies von Said ibn Huwayrith gehört hatte.'},
'https://sunnah.com/muslim:375a':{en:'Yahya ibn Yahya narrated to us. Hammad ibn Zayd informed us, and Yahya also said: Hushaym informed us. Both narrated from Abd al-Aziz ibn Suhayb, from Anas. In Hammad’s hadith: When the Messenger of Allah (peace be upon him) entered the toilet. In Hushaym’s hadith: When the Messenger of Allah (peace be upon him) entered the privy, he said: O Allah, I seek refuge in You from male and female devils.',de:'Yahya ibn Yahya überlieferte uns. Hammad ibn Zayd berichtete uns, und Yahya sagte außerdem: Hushaym berichtete uns. Beide überlieferten von Abd al-Aziz ibn Suhayb, von Anas. In Hammads Hadith heißt es: Wenn der Gesandte Allahs (Friede sei auf ihm) die Toilette betrat. In Hushayms Hadith heißt es: Wenn der Gesandte Allahs (Friede sei auf ihm) den Abtritt betrat, sagte er: O Allah, ich suche Zuflucht bei Dir vor männlichen und weiblichen Teufeln.'},
'https://sunnah.com/muslim:375b':{en:'Abu Bakr ibn Abi Shayba and Zuhayr ibn Harb narrated to us. They said: Ismail, who was Ibn Ulayya, narrated to us, from Abd al-Aziz, with this chain, and he said: I seek refuge in Allah from male and female devils.',de:'Abu Bakr ibn Abi Shayba und Zuhayr ibn Harb überlieferten uns. Sie sagten: Ismail, nämlich Ibn Ulayya, überlieferte uns, von Abd al-Aziz, mit dieser Überlieferungskette, und er sagte: Ich suche Zuflucht bei Allah vor männlichen und weiblichen Teufeln.'},
'https://sunnah.com/muslim:376a':{en:'Zuhayr ibn Harb narrated to me. Ismail ibn Ulayya narrated to us. And Shayban ibn Farrukh narrated to us. Abd al-Warith narrated to us. Both narrated from Abd al-Aziz, from Anas, who said: The prayer was announced, while the Messenger of Allah (peace be upon him) was privately speaking with a man. In Abd al-Warith’s hadith: The Prophet of Allah (peace be upon him) was privately speaking with the man. He did not stand for prayer until the people fell asleep.',de:'Zuhayr ibn Harb überlieferte mir. Ismail ibn Ulayya überlieferte uns. Und Shayban ibn Farrukh überlieferte uns. Abd al-Warith überlieferte uns. Beide überlieferten von Abd al-Aziz, von Anas, der sagte: Zum Gebet wurde gerufen, während der Gesandte Allahs (Friede sei auf ihm) sich mit einem Mann vertraulich unterhielt. In Abd al-Wariths Hadith heißt es: Der Prophet Allahs (Friede sei auf ihm) unterhielt sich vertraulich mit dem Mann. Er stand nicht zum Gebet auf, bis die Menschen einschliefen.'},
'https://sunnah.com/muslim:376b':{en:'Ubayd Allah ibn Muadh al-Anbari narrated to us. My father narrated to us. Shuba narrated to us, from Abd al-Aziz ibn Suhayb, who heard Anas ibn Malik say: The prayer was announced while the Prophet (peace be upon him) was privately speaking with a man. He continued speaking with him until his Companions fell asleep, then he came and led them in prayer.',de:'Ubayd Allah ibn Muadh al-Anbari überlieferte uns. Mein Vater überlieferte uns. Shuba überlieferte uns, von Abd al-Aziz ibn Suhayb, der Anas ibn Malik sagen hörte: Zum Gebet wurde gerufen, während der Prophet (Friede sei auf ihm) sich mit einem Mann vertraulich unterhielt. Er unterhielt sich weiter mit ihm, bis seine Gefährten einschliefen. Dann kam er und leitete sie im Gebet.'},
'https://sunnah.com/muslim:376c':{en:'Yahya ibn Habib al-Harithy narrated to me. Khalid, who was Ibn al-Harith, narrated to us. Shuba narrated to us, from Qatada, who said: I heard Anas say: The Companions of the Messenger of Allah (peace be upon him) used to sleep and then pray without performing wudu. I said: Did you hear this from Anas? He said: Yes, by Allah.',de:'Yahya ibn Habib al-Harithy überlieferte mir. Khalid, nämlich Ibn al-Harith, überlieferte uns. Shuba überlieferte uns, von Qatada, der sagte: Ich hörte Anas sagen: Die Gefährten des Gesandten Allahs (Friede sei auf ihm) pflegten zu schlafen und dann zu beten, ohne Wudu zu verrichten. Ich sagte: Hast du dies von Anas gehört? Er sagte: Ja, bei Allah.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]})); if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-238-part.json',JSON.stringify(out,null,2)); fs.writeFileSync('data/hadith-words-translations/codex-out-238-part.json',JSON.stringify(out,null,2)); console.log(`wrote ${out.length} staged translations`);
