import fs from "node:fs";
const raw=JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-batch-084.json","utf8")) as {id:string;url:string}[];
const t:Record<string,{en:string;de:string}>={
"3907":{en:String.raw`Abd Allah ibn Abi Shayba narrated to us. Abu Usama narrated to us. Hisham narrated to us, from his father and Fatima, from Asma, may Allah be pleased with her, who said: I prepared a travel meal for the Prophet (peace be upon him) and Abu Bakr when they wanted to go to Medina. I said to my father: I cannot find anything with which to tie it except my waistband. He said: Cut it in two. I did so, and I was called the woman of the two waistbands.`,de:String.raw`Abd Allah ibn Abi Schayba überlieferte uns. Abu Usama überlieferte uns. Hisham überlieferte uns, von seinem Vater und Fatima, von Asma, möge Allah mit ihr zufrieden sein, die sagte: Ich bereitete dem Propheten (Friede sei auf ihm) und Abu Bakr eine Wegzehrung zu, als sie nach Medina aufbrechen wollten. Ich sagte zu meinem Vater: Ich finde nichts, womit ich sie festbinden kann, außer meinem Gürtel. Er sagte: Teile ihn in zwei Stücke. Ich tat es, und ich wurde die Frau der beiden Gürtel genannt.`},
"3908":{en:String.raw`Muhammad ibn Bashshar narrated to us. Ghundar narrated to us. Shu'ba narrated to us, from Abu Ishaq, who said: I heard al-Bara, may Allah be pleased with him, say: When the Prophet (peace be upon him) set out for Medina, Suraqa ibn Malik ibn Jushum followed him. The Prophet prayed against him, and his horse sank with him into the ground. He said: Pray to Allah for me, and I will not harm you. The Prophet prayed for him. He said: The Messenger of Allah became thirsty and passed by a water trough. Abu Bakr said: I took a bowl, milked a little milk into it, and brought it to him. He drank until I was satisfied.`,de:String.raw`Muhammad ibn Baschar überlieferte uns. Ghundar überlieferte uns. Schu'ba überlieferte uns, von Abu Ishaq, der sagte: Ich hörte al-Bara, möge Allah mit ihm zufrieden sein, sagen: Als der Prophet (Friede sei auf ihm) nach Medina aufbrach, folgte ihm Suraqa ibn Malik ibn Dschu'schum. Der Prophet sprach gegen ihn, und sein Pferd versank mit ihm im Boden. Er sagte: Bitte Allah für mich, und ich werde dir keinen Schaden zufügen. Der Prophet bat für ihn. Er sagte: Der Gesandte Allahs bekam Durst und kam an einer Wassertränke vorbei. Abu Bakr sagte: Ich nahm eine Schale, molk etwas Milch hinein und brachte sie ihm. Er trank, bis ich zufrieden war.`},
"3909":{en:String.raw`Zakariya ibn Yahya narrated to me, from Abu Usama, from Hisham ibn Urwa, from his father, from Asma, may Allah be pleased with her, that she carried Abd Allah ibn al-Zubayr while she was pregnant. She said: I set out while I was near delivery and came to Medina. I stayed at Quba and gave birth there. Then I brought him to the Prophet (peace be upon him), placed him in his lap, and he called for a date. He chewed it, then put some of his saliva into the child's mouth. The first thing to enter his stomach was the saliva of the Messenger of Allah (peace be upon him). Then he rubbed him with a date, prayed for him, and blessed him. He was the first child born in Islam.`,de:String.raw`Zakariya ibn Yahya überlieferte mir, von Abu Usama, von Hisham ibn Urwa, von seinem Vater, von Asma, möge Allah mit ihr zufrieden sein, dass sie Abd Allah ibn az-Zubayr trug, während sie schwanger war. Sie sagte: Ich brach auf, als die Geburt nahe war, und kam nach Medina. Ich blieb in Quba und gebar ihn dort. Dann brachte ich ihn zum Propheten (Friede sei auf ihm), legte ihn in seinen Schoß, und er ließ eine Dattel bringen. Er kaute sie, gab dann etwas von seinem Speichel in den Mund des Kindes. Das Erste, was in seinen Magen gelangte, war der Speichel des Gesandten Allahs (Friede sei auf ihm). Dann rieb er ihn mit einer Dattel ein, betete für ihn und segnete ihn. Er war das erste im Islam geborene Kind.`},
"3910":{en:String.raw`Qutayba narrated to us, from Abu Usama, from Hisham ibn Urwa, from his father, from Aisha, may Allah be pleased with her, who said: The first child born in Islam was Abd Allah ibn al-Zubayr. They brought him to the Prophet (peace be upon him), and the Prophet took a date, chewed it, and put it into his mouth. The first thing that entered his stomach was the saliva of the Prophet (peace be upon him).`,de:String.raw`Qutayba überlieferte uns, von Abu Usama, von Hisham ibn Urwa, von seinem Vater, von Aisha, möge Allah mit ihr zufrieden sein, die sagte: Das erste im Islam geborene Kind war Abd Allah ibn az-Zubayr. Sie brachten ihn zum Propheten (Friede sei auf ihm), und der Prophet nahm eine Dattel, kaute sie und legte sie in seinen Mund. Das Erste, was in seinen Magen gelangte, war der Speichel des Propheten (Friede sei auf ihm).`}
};
const out=raw.map(row=>{const k=row.url.split(":").pop()!;const v=t[k];if(!v)throw new Error("missing "+k);return{id:row.id,n:k,en:v.en,de:v.de};});
fs.writeFileSync("data/hadith-words-translations/codex-out-084.json",JSON.stringify(out,null,2)+"\n","utf8");
console.log("wrote "+out.length+" translations");
