import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-208.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:270':{en:'Yahya ibn Yahya narrated to us. Khalid ibn Abdullah informed us, from Khalid, from Ata ibn Abi Maymuna, from Anas ibn Malik, that the Messenger of Allah (peace be upon him) entered a garden, followed by a boy carrying a small vessel for purification, the youngest of us. He placed it beside a lote tree, relieved himself, then came out to us having cleaned himself with water.',de:'Yahya ibn Yahya überlieferte uns. Khalid ibn Abdullah berichtete uns, von Khalid, von Ata ibn Abi Maymuna, von Anas ibn Malik, dass der Gesandte Allahs (Friede sei auf ihm) einen Garten betrat. Ihm folgte ein Junge, der ein kleines Gefäß für die Reinigung trug, der Jüngste von uns. Er stellte es neben einen Lotosbaum, erleichterte sich und kam dann zu uns heraus, nachdem er sich mit Wasser gereinigt hatte.'},
'https://sunnah.com/muslim:271a':{en:'Abu Bakr ibn Abi Shayba narrated to us. Waki and Ghundar narrated to us, from Shuba. Muhammad ibn al-Muthanna also narrated to us, and this is his wording: Muhammad ibn Jafar narrated to us. Shuba narrated to us, from Ata ibn Abi Maymuna, that he heard Anas ibn Malik say: The Messenger of Allah (peace be upon him) would enter the place of relieving himself, and I and a boy like me would carry a vessel of water and a short spear. He would clean himself with water.',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Waki und Ghundar überlieferten uns, von Shuba. Auch Muhammad ibn al-Muthanna überlieferte uns, und dies ist sein Wortlaut: Muhammad ibn Jafar überlieferte uns. Shuba überlieferte uns, von Ata ibn Abi Maymuna, dass er Anas ibn Malik sagen hörte: Der Gesandte Allahs (Friede sei auf ihm) betrat den Ort zum Erleichtern, und ich und ein Junge meines Alters trugen ein Gefäß Wasser und einen kurzen Speer. Er reinigte sich mit Wasser.'},
'https://sunnah.com/muslim:271b':{en:'Zuhayr ibn Harb and Abu Kurayb narrated to me, and this is Zuhayr\'s wording: Ismail, meaning ibn Ulayya, narrated to us. Ruh ibn al-Qasim narrated to me, from Ata ibn Abi Maymuna, from Anas ibn Malik, who said: The Messenger of Allah (peace be upon him) would go aside to relieve himself, and I would bring him water, with which he would wash himself.',de:'Zuhayr ibn Harb und Abu Kurayb überlieferten mir, und dies ist Zuhayrs Wortlaut: Ismail, gemeint ist ibn Ulayya, überlieferte uns. Ruh ibn al-Qasim überlieferte mir, von Ata ibn Abi Maymuna, von Anas ibn Malik, der sagte: Der Gesandte Allahs (Friede sei auf ihm) ging beiseite, um sich zu erleichtern, und ich brachte ihm Wasser, mit dem er sich wusch.'},
'https://sunnah.com/muslim:272a':{en:'Yahya ibn Yahya al-Tamimi, Ishaq ibn Ibrahim, and Abu Kurayb narrated to us, all from Abu Muawiya. Abu Bakr ibn Abi Shayba also narrated to us: Abu Muawiya and Waki narrated to us, and this is Yahya\'s wording. He said: Abu Muawiya informed us, from al-Amash, from Ibrahim, from Hammam, who said: Jarir urinated, then performed wudu and wiped over his leather socks. He was asked: Do you do this? He said: Yes, I saw the Messenger of Allah (peace be upon him) urinate, then perform wudu and wipe over his leather socks. Al-Amash said: Ibrahim said: They liked this hadith because Jarir accepted Islam after the revelation of al-Maida.',de:'Yahya ibn Yahya al-Tamimi, Ishaq ibn Ibrahim und Abu Kurayb überlieferten uns, alle von Abu Muawiya. Auch Abu Bakr ibn Abi Shayba überlieferte uns: Abu Muawiya und Waki überlieferten uns, und dies ist Yahyas Wortlaut. Er sagte: Abu Muawiya berichtete uns, von al-Amash, von Ibrahim, von Hammam, der sagte: Jarir urinierte, verrichtete dann Wudu und strich über seine Ledersocken. Man fragte ihn: Tust du das? Er sagte: Ja, ich sah den Gesandten Allahs (Friede sei auf ihm) urinieren, dann Wudu verrichten und über seine Ledersocken streichen. Al-Amash sagte: Ibrahim sagte: Sie mochten diesen Hadith, weil Jarir den Islam nach der Offenbarung von al-Maida annahm.'},
'https://sunnah.com/muslim:272b':{en:'Ishaq ibn Ibrahim and Ali ibn Khashram narrated it to us. They said: Isa ibn Yunus informed us. Muhammad ibn Abi Umar also narrated it: Sufyan narrated to us. Minjab ibn al-Harith al-Tamimi also narrated to us: Ibn Mushir informed us. All of them narrated from al-Amash with this chain, with the meaning of Abu Muawiya\'s hadith, except that in the narration of Isa and Sufyan it says: The companions of Abdullah liked this hadith because Jarir accepted Islam after the revelation of al-Maida.',de:'Ishaq ibn Ibrahim und Ali ibn Khashram überlieferten ihn uns. Sie sagten: Isa ibn Yunus berichtete uns. Auch Muhammad ibn Abi Umar überlieferte ihn uns: Sufyan überlieferte uns. Ebenso überlieferte uns Minjab ibn al-Harith al-Tamimi: Ibn Mushir berichtete uns. Alle überlieferten von al-Amash mit dieser Kette, sinngemäß wie der Hadith von Abu Muawiya, außer dass es in der Überlieferung von Isa und Sufyan heißt: Die Gefährten von Abdullah mochten diesen Hadith, weil Jarir den Islam nach der Offenbarung von al-Maida annahm.'},
'https://sunnah.com/muslim:273a':{en:'Yahya ibn Yahya al-Tamimi narrated to us. Abu Khaythama informed us, from al-Amash, from Shaqiq, from Hudhayfa, who said: I was with the Prophet (peace be upon him), and he came to a rubbish area belonging to some people and urinated standing. I moved away, so he said: Come closer. I came closer until I stood by his heels. He performed wudu and wiped over his leather socks.',de:'Yahya ibn Yahya al-Tamimi überlieferte uns. Abu Khaythama berichtete uns, von al-Amash, von Shaqiq, von Hudhayfa, der sagte: Ich war beim Propheten (Friede sei auf ihm), als er zu einem Müllplatz einiger Leute kam und im Stehen urinierte. Ich entfernte mich, da sagte er: Komm näher. Ich kam näher, bis ich bei seinen Fersen stand. Er verrichtete Wudu und strich über seine Ledersocken.'},
'https://sunnah.com/muslim:273b':{en:'Yahya ibn Yahya narrated to us. Jarir informed us, from Mansur, from Abu Wail, who said: Abu Musa was strict about urine and urinated into a bottle. He used to say: When urine touched the skin of one of the Children of Israel, they cut that part out with scissors. Hudhayfa said: I wish your companion would not be so strict. I saw the Messenger of Allah (peace be upon him) and me walking together. He came to a rubbish area behind a wall and urinated standing, as one of you does. I moved away from him, so he gestured to me, and I came and stood by his heels until he finished.',de:'Yahya ibn Yahya überlieferte uns. Jarir berichtete uns, von Mansur, von Abu Wail, der sagte: Abu Musa war beim Urin sehr streng und urinierte in eine Flasche. Er pflegte zu sagen: Wenn der Urin die Haut eines der Kinder Israels berührte, schnitten sie diese Stelle mit Scheren heraus. Hudhayfa sagte: Ich wünschte, euer Gefährte wäre dabei nicht so streng. Ich sah, wie der Gesandte Allahs (Friede sei auf ihm) und ich gemeinsam gingen. Er kam zu einem Müllplatz hinter einer Mauer und urinierte im Stehen, wie einer von euch. Ich entfernte mich von ihm, da winkte er mir, und ich kam und stellte mich zu seinen Fersen, bis er fertig war.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-208-part2.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-208-part2.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
