import fs from 'fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-195.json','utf8'));
const tr:Record<string,[string,string]>={
'https://sunnah.com/muslim:212':[ `Abu Bakr ibn Abi Shayba narrated to us. Affan narrated to us. Hammad ibn Salama narrated to us. Thabit narrated to us, from Abu Uthman al-Nahdi, from Ibn Abbas, that the Messenger of Allah (peace be upon him) said: The person receiving the lightest punishment among the people of the Fire is Abu Talib. He will wear two sandals, and his brain will boil because of them.`, `Abu Bakr ibn Abi Schayba überlieferte uns. Affan überlieferte uns. Hammad ibn Salama überlieferte uns. Thabit überlieferte uns, von Abu Uthman an-Nahdi, von Ibn Abbas, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Derjenige mit der leichtesten Strafe unter den Bewohnern des Feuers ist Abu Talib. Er wird zwei Sandalen tragen, und sein Gehirn wird ihretwegen kochen.`],
'https://sunnah.com/muslim:213a':[ `Muhammad ibn al-Muthanna and Ibn Bashshar narrated to us, and this is Ibn al-Muthanna's wording. They said: Muhammad ibn Ja'far narrated to us. Shu'ba narrated to us. He said: I heard Abu Ishaq say: I heard al-Nu'man ibn Bashir preaching and saying: I heard the Messenger of Allah (peace be upon him) say: The person receiving the lightest punishment among the people of the Fire on the Day of Resurrection is a man with two embers placed in the hollows of his feet, from which his brain will boil.`, `Muhammad ibn al-Muthanna und Ibn Baschar überlieferten uns, und dies ist der Wortlaut von Ibn al-Muthanna. Sie sagten: Muhammad ibn Dscha'far überlieferte uns. Schu'ba überlieferte uns. Er sagte: Ich hörte Abu Ishaq sagen: Ich hörte an-Nu'man ibn Baschir predigen und sagen: Ich hörte den Gesandten Allahs (Friede sei auf ihm) sagen: Derjenige mit der leichtesten Strafe unter den Bewohnern des Feuers am Tag der Auferstehung ist ein Mann, dem zwei glühende Kohlen in die Fußsohlen gelegt werden, durch die sein Gehirn kochen wird.`],
'https://sunnah.com/muslim:213b':[ `Abu Bakr ibn Abi Shayba narrated to us. Abu Usama narrated to us, from al-A'mash, from Abu Ishaq, from al-Nu'man ibn Bashir, who said: The Messenger of Allah (peace be upon him) said: The person receiving the lightest punishment among the people of the Fire will have two sandals and two straps of fire, and his brain will boil from them as a pot boils. He will not think that anyone is being punished more severely than him, yet he will be the one receiving the lightest punishment among them.`, `Abu Bakr ibn Abi Schayba überlieferte uns. Abu Usama überlieferte uns, von al-A'masch, von Abu Ishaq, von an-Nu'man ibn Baschir, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Derjenige mit der leichtesten Strafe unter den Bewohnern des Feuers wird zwei Sandalen und zwei Riemen aus Feuer haben, und sein Gehirn wird dadurch kochen, wie ein Topf kocht. Er wird nicht meinen, dass jemand härter bestraft wird als er, und doch wird er unter ihnen die leichteste Strafe haben.`],
'https://sunnah.com/muslim:214':[ `Abu Bakr ibn Abi Shayba narrated to me. Hafs ibn Ghiyath narrated to us, from Dawud, from al-Sha'bi, from Masruq, from Aisha, who said: I said: Messenger of Allah, Ibn Jud'an used to maintain family ties and feed the poor during the pre-Islamic period. Will that benefit him? He said: It will not benefit him. He never said one day: My Lord, forgive me my sin on the Day of Judgment.`, `Abu Bakr ibn Abi Schayba überlieferte mir. Hafs ibn Ghiyath überlieferte uns, von Dawud, von asch-Scha'bi, von Masruq, von Aischa, die sagte: Ich sagte: Gesandter Allahs, Ibn Dschud'an pflegte in der vorislamischen Zeit die Verwandtschaftsbande zu pflegen und den Armen zu speisen. Wird ihm das nützen? Er sagte: Es wird ihm nicht nützen. Er sagte niemals: Mein Herr, vergib mir meine Sünde am Tag des Gerichts.`],
'https://sunnah.com/muslim:215':[ `Ahmad ibn Hanbal narrated to me. Muhammad ibn Ja'far narrated to us. Shu'ba narrated to us, from Isma'il ibn Abi Khalid, from Qays, from Amr ibn al-As, who said: I heard the Messenger of Allah (peace be upon him) openly, not secretly, say: Be aware that the family of Abu, meaning so-and-so, are not my allies. My ally is Allah and the righteous believers.`, `Ahmad ibn Hanbal überlieferte mir. Muhammad ibn Dscha'far überlieferte uns. Schu'ba überlieferte uns, von Isma'il ibn Abi Khalid, von Qays, von Amr ibn al-As, der sagte: Ich hörte den Gesandten Allahs (Friede sei auf ihm) offen und nicht heimlich sagen: Wisset, dass die Familie von Abu, das heißt Soundso, nicht meine Verbündeten sind. Mein Verbündeter ist Allah und die rechtschaffenen Gläubigen.`],
'https://sunnah.com/muslim:216a':[ `Abd al-Rahman ibn Sallam ibn Ubayd Allah al-Jumahi narrated to us. al-Rabi', meaning Ibn Muslim, narrated to us, from Muhammad ibn Ziyad, from Abu Hurayra, that the Prophet (peace be upon him) said: Seventy thousand from my community will enter Paradise without reckoning. A man said: Messenger of Allah, ask Allah to make me one of them. He said: O Allah, make him one of them. Then another man stood and said: Messenger of Allah, ask Allah to make me one of them. He said: Ukasha has preceded you in that.`, `Abd ar-Rahman ibn Sallam ibn Ubayd Allah al-Dschumahi überlieferte uns. ar-Rabi', das heißt Ibn Muslim, überlieferte uns, von Muhammad ibn Ziyad, von Abu Hurayra, dass der Prophet (Friede sei auf ihm) sagte: Siebzigtausend aus meiner Gemeinschaft werden ohne Abrechnung ins Paradies eintreten. Ein Mann sagte: Gesandter Allahs, bitte Allah, mich zu einem von ihnen zu machen. Er sagte: O Allah, mache ihn zu einem von ihnen. Dann stand ein anderer Mann auf und sagte: Gesandter Allahs, bitte Allah, mich zu einem von ihnen zu machen. Er sagte: Ukascha ist dir darin zuvorgekommen.`],
'https://sunnah.com/muslim:216b':[ `Muhammad ibn Bashshar narrated to us. Muhammad ibn Ja'far narrated to us. Shu'ba narrated to us. He said: I heard Muhammad ibn Ziyad say: I heard Abu Hurayra say: I heard the Messenger of Allah (peace be upon him) say, with the meaning of al-Rabi's hadith.`, `Muhammad ibn Baschar überlieferte uns. Muhammad ibn Dscha'far überlieferte uns. Schu'ba überlieferte uns. Er sagte: Ich hörte Muhammad ibn Ziyad sagen: Ich hörte Abu Hurayra sagen: Ich hörte den Gesandten Allahs (Friede sei auf ihm) sagen, mit der Bedeutung des Hadith von ar-Rabi'.`]
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,en:tr[r.url][0],de:tr[r.url][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-195-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-195-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
