import fs from 'fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-202.json','utf8'));
const tr:Record<string,[string,string]>={
'https://sunnah.com/muslim:238':[ `Bishr ibn al-Hakam al-Abdi narrated to me. Abd al-Aziz, meaning al-Darawardi, narrated to us, from Ibn al-Had, from Muhammad ibn Ibrahim, from Isa ibn Talha, from Abu Hurayra, that the Prophet (peace be upon him) said: When one of you wakes from sleep, let him expel water from his nose three times, for Satan spends the night in his nasal passages.`, `Bischr ibn al-Hakam al-Abdi überlieferte mir. Abd al-Aziz, das heißt ad-Darawardi, überlieferte uns, von Ibn al-Had, von Muhammad ibn Ibrahim, von Isa ibn Talha, von Abu Hurayra, dass der Prophet (Friede sei auf ihm) sagte: Wenn einer von euch aus dem Schlaf erwacht, soll er dreimal Wasser aus seiner Nase ausstoßen, denn Satan verbringt die Nacht in seinen Nasengängen.`],
'https://sunnah.com/muslim:239':[ `Ishaq ibn Ibrahim and Muhammad ibn Rafi narrated to us. Ibn Rafi said: Abd al-Razzaq narrated to us. Ibn Jurayj informed us. Abu al-Zubayr informed me that he heard Jabir ibn Abdullah say: The Messenger of Allah (peace be upon him) said: When one of you uses stones for cleaning, let him use an odd number.`, `Ishaq ibn Ibrahim und Muhammad ibn Rafi überlieferten uns. Ibn Rafi sagte: Abd ar-Razzaq überlieferte uns. Ibn Dschuraidsch berichtete uns. Abu az-Zubayr berichtete mir, dass er Dschabir ibn Abd Allah sagen hörte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn einer von euch Steine zur Reinigung benutzt, soll er eine ungerade Zahl verwenden.`],
'https://sunnah.com/muslim:240a':[ `Harun ibn Sa'id al-Ayli, Abu al-Tahir, and Ahmad ibn Isa narrated to us. They said: Abdullah ibn Wahb informed us, from Makhrama ibn Bukayr, from his father, from Salim, the freedman of Shaddad, who said: I entered upon Aisha, the wife of the Prophet (peace be upon him), on the day Sa'd ibn Abi Waqqas died. Abd al-Rahman ibn Abi Bakr entered and performed wudu there. She said: Abd al-Rahman, complete the wudu, for I heard the Messenger of Allah (peace be upon him) say: Woe to the heels because of the Fire.`, `Harun ibn Sa'id al-Ayli, Abu at-Tahir und Ahmad ibn Isa überlieferten uns. Sie sagten: Abd Allah ibn Wahb berichtete uns, von Makhrama ibn Bukayr, von seinem Vater, von Salim, dem Freigelassenen von Schaddad, der sagte: Ich trat bei Aischa, der Ehefrau des Propheten (Friede sei auf ihm), am Tag des Todes von Sa'd ibn Abi Waqqas ein. Abd ar-Rahman ibn Abi Bakr trat ein und vollzog dort die Gebetswaschung. Sie sagte: Abd ar-Rahman, vollende die Gebetswaschung, denn ich hörte den Gesandten Allahs (Friede sei auf ihm) sagen: Wehe den Fersen wegen des Feuers.`],
'https://sunnah.com/muslim:240b':[ `Harmala ibn Yahya narrated it to me. Ibn Wahb narrated to us. Haywa informed me. Muhammad ibn Abd al-Rahman informed me that Abu Abdullah, the freedman of Shaddad ibn al-Had, narrated to him that he entered upon Aisha and narrated from her, from the Prophet (peace be upon him), something with the same meaning.`, `Harmala ibn Yahya überlieferte es mir. Ibn Wahb überlieferte uns. Haywa berichtete mir. Muhammad ibn Abd ar-Rahman berichtete mir, dass Abu Abd Allah, der Freigelassene von Schaddad ibn al-Had, ihm überlieferte, dass er bei Aischa eintrat und von ihr, vom Propheten (Friede sei auf ihm), etwas mit derselben Bedeutung berichtete.`],
'https://sunnah.com/muslim:240c':[ `Muhammad ibn Hatim and Abu Ma'n al-Raqashi narrated to me. They said: Umar ibn Yunus narrated to us. Ikrima ibn Ammar narrated to us. Yahya ibn Abi Kathir narrated to me, or narrated to us. Abu Salama ibn Abd al-Rahman narrated to me. Salim, the freedman of al-Mihri, said: I and Abd al-Rahman ibn Abi Bakr went out for the funeral of Sa'd ibn Abi Waqqas. We passed by the door of Aisha's room, and he narrated from her, from the Prophet (peace be upon him), something like it.`, `Muhammad ibn Hatim und Abu Ma'n ar-Raqaschi überlieferten mir. Sie sagten: Umar ibn Yunus überlieferte uns. Ikrima ibn Ammar überlieferte uns. Yahya ibn Abi Kathir überlieferte mir oder überlieferte uns. Abu Salama ibn Abd ar-Rahman überlieferte mir. Salim, der Freigelassene von al-Mihri, sagte: Ich und Abd ar-Rahman ibn Abi Bakr gingen zum Begräbnis von Sa'd ibn Abi Waqqas hinaus. Wir kamen an der Tür von Aischas Zimmer vorbei, und er überlieferte von ihr, vom Propheten (Friede sei auf ihm), etwas Ähnliches.`],
'https://sunnah.com/muslim:240d':[ `Salama ibn Shabib narrated to me. al-Hasan ibn A'yun narrated to us. Fulayh narrated to us. Nu'aym ibn Abdullah narrated to me, from Salim, the freedman of Shaddad ibn al-Had, who said: I was with Aisha (may Allah be pleased with her), and he narrated from her, from the Prophet (peace be upon him), something with the same meaning.`, `Salama ibn Schabib überlieferte mir. al-Hasan ibn A'yun überlieferte uns. Fulayh überlieferte uns. Nu'aym ibn Abd Allah überlieferte mir, von Salim, dem Freigelassenen von Schaddad ibn al-Had, der sagte: Ich war mit Aischa (möge Allah mit ihr zufrieden sein), und er überlieferte von ihr, vom Propheten (Friede sei auf ihm), etwas mit derselben Bedeutung.`],
'https://sunnah.com/muslim:241a':[ `Zuhayr ibn Harb narrated to me. Jarir narrated to us. And Ishaq narrated to us. He said: Jarir informed us, from Mansur, from Hilal ibn Yasaf, from Abu Yahya, from Abdullah ibn Amr, who said: We returned with the Messenger of Allah (peace be upon him) from Mecca to Medina. When we reached a watering place on the road, some people hurried at Asr time and performed wudu hurriedly. We reached them while their heels were shining, untouched by water. The Messenger of Allah (peace be upon him) said: Woe to the heels because of the Fire. Complete the wudu.`, `Zuhayr ibn Harb überlieferte mir. Jarir überlieferte uns. Und Ishaq überlieferte uns. Er sagte: Jarir berichtete uns, von Mansur, von Hilal ibn Yasaf, von Abu Yahya, von Abd Allah ibn Amr, der sagte: Wir kehrten mit dem Gesandten Allahs (Friede sei auf ihm) von Mekka nach Medina zurück. Als wir eine Wasserstelle am Weg erreichten, beeilten sich einige Menschen zur Nachmittagszeit und vollzogen hastig die Gebetswaschung. Wir holten sie ein, während ihre Fersen glänzten, ohne dass sie vom Wasser berührt worden waren. Der Gesandte Allahs (Friede sei auf ihm) sagte: Wehe den Fersen wegen des Feuers. Vollendet die Gebetswaschung.`]
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,en:tr[r.url][0],de:tr[r.url][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-202-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-202-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
