import fs from "node:fs";

const raw = JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-batch-096.json", "utf8")) as { id: string; url: string }[];
const t: Record<string, { en: string; de: string }> = {
  "4022": { en: String.raw`Ishaq ibn Ibrahim narrated to us. He heard Muhammad ibn Fudayl, from Ismail, from Qays: The allotments of the people of Badr were five thousand each. Umar said: I will certainly give them precedence over those after them.`, de: String.raw`Ishaq ibn Ibrahim überlieferte uns. Er hörte Muhammad ibn Fudayl, von Ismail, von Qays: Die Zuteilungen der Leute von Badr betrugen jeweils fünftausend. Umar sagte: Ich werde ihnen gewiss Vorrang vor denen geben, die nach ihnen kommen.` },
  "4023": { en: String.raw`Ishaq ibn Mansur narrated to me. Abd al-Razzaq narrated to us. Ma'mar informed us, from al-Zuhri, from Muhammad ibn Jubayr, from his father, who said: I heard the Prophet (peace be upon him) recite Surat al-Tur in the sunset prayer. That was the first time faith settled in my heart.`, de: String.raw`Ishaq ibn Mansur berichtete mir. Abd ar-Razzaq überlieferte uns. Ma'mar berichtete uns, von az-Zuhri, von Muhammad ibn Dschubayr, von seinem Vater, der sagte: Ich hörte den Propheten (Friede sei auf ihm) in der Abendgebetszeit die Sura at-Tur rezitieren. Das war das erste Mal, dass sich der Glaube in meinem Herzen festsetzte.` },
  "4024": { en: String.raw`From al-Zuhri, from Muhammad ibn Jubayr ibn Mutim, from his father, that the Prophet (peace be upon him) said concerning the captives of Badr: If al-Mutim ibn Adi were alive and then spoke to me about these filthy men, I would release them to him. Al-Layth said, from Yahya, from Said ibn al-Musayyab: The first tribulation, meaning the killing of Uthman, occurred and left none of the Companions of Badr alive. Then the second tribulation, meaning al-Harra, occurred and left none of the Companions of al-Hudaybiyya alive. Then the third occurred, and it did not subside, while the people had no strength left.`, de: String.raw`Von az-Zuhri, von Muhammad ibn Dschubayr ibn Mutim, von seinem Vater, dass der Prophet (Friede sei auf ihm) über die Gefangenen von Badr sagte: Wenn al-Mutim ibn Adi noch leben würde und dann bei mir wegen dieser üblen Männer sprechen würde, würde ich sie ihm freigeben. Al-Layth sagte, von Yahya, von Said ibn al-Musayyab: Die erste Fitna, womit die Tötung Uthmans gemeint ist, ereignete sich und ließ keinen der Gefährten von Badr übrig. Dann ereignete sich die zweite Fitna, womit al-Harra gemeint ist, und ließ keinen der Gefährten von al-Hudaybiyya übrig. Dann ereignete sich die dritte, und sie legte sich nicht, während die Menschen keine Kraft mehr hatten.` },
  "4025": { en: String.raw`Al-Hajjaj ibn Minhal narrated to us. Abd Allah ibn Umar al-Numayri narrated to us. Yunus ibn Yazid narrated to us. He said: I heard al-Zuhri say: I heard Urwa ibn al-Zubayr, Said ibn al-Musayyab, Alqama ibn Waqqas, and Ubayd Allah ibn Abd Allah each narrate from the report of Aisha, may Allah be pleased with her, the wife of the Prophet (peace be upon him). Each conveyed part of the report. She said: I and Umm Mistah went out. Umm Mistah stumbled over her cloak and said: May Mistah perish! I said: What a bad thing you have said! You insult a man who witnessed Badr. Then he mentioned the story of the slander.`, de: String.raw`Al-Haddschadsch ibn Minhal überlieferte uns. Abd Allah ibn Umar an-Numayri überlieferte uns. Yunus ibn Yazid überlieferte uns. Er sagte: Ich hörte az-Zuhri sagen: Ich hörte Urwa ibn az-Zubayr, Said ibn al-Musayyab, Alqama ibn Waqqas und Ubayd Allah ibn Abd Allah jeweils aus dem Bericht von Aisha, möge Allah mit ihr zufrieden sein, der Ehefrau des Propheten (Friede sei auf ihm), berichten. Jeder überlieferte einen Teil des Berichts. Sie sagte: Ich und Umm Mistah gingen hinaus. Umm Mistah stolperte über ihren Umhang und sagte: Mistah soll zugrunde gehen! Ich sagte: Wie schlecht ist, was du gesagt hast! Du beschimpfst einen Mann, der Badr miterlebt hat. Dann erwähnte er die Geschichte der Verleumdung.` },
  "4026": { en: String.raw`Ibrahim ibn al-Mundhir narrated to us. Muhammad ibn Fulayh ibn Sulayman narrated to us, from Musa ibn Uqba, from Ibn Shihab, who said: These are the campaigns of the Messenger of Allah (peace be upon him. He mentioned the report and said: The Messenger of Allah (peace be upon him) said while addressing them: Have you found what your Lord promised you to be true? Musa said: Nafi said, from Abd Allah: Some of his Companions said: O Messenger of Allah, are you calling people who are dead? The Messenger of Allah (peace be upon him) said: You do not hear what I said any better than they do. Abu Abd Allah said: All those from Quraysh who witnessed Badr and were assigned a share numbered eighty-one men. Urwa ibn al-Zubayr used to say that al-Zubayr said: Their shares were distributed, and they numbered one hundred. Allah knows best.`, de: String.raw`Ibrahim ibn al-Mundhir überlieferte uns. Muhammad ibn Fulayh ibn Sulayman überlieferte uns, von Musa ibn Uqba, von Ibn Schihab, der sagte: Dies sind die Feldzüge des Gesandten Allahs (Friede sei auf ihm). Er erwähnte den Bericht und sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte, während er sie ansprach: Habt ihr gefunden, dass die Verheißung eures Herrn wahr ist? Musa sagte: Nafi sagte von Abd Allah: Einige seiner Gefährten sagten: O Gesandter Allahs, rufst du Menschen an, die tot sind? Der Gesandte Allahs (Friede sei auf ihm) sagte: Ihr hört meine Worte nicht besser als sie. Abu Abd Allah sagte: Alle Männer aus den Quraisch, die Badr miterlebten und denen ein Anteil zugeteilt wurde, waren einundachtzig. Urwa ibn az-Zubayr pflegte zu sagen, dass az-Zubayr sagte: Ihre Anteile wurden verteilt, und sie waren einhundert. Allah weiß es am besten.` },
  "4027": { en: String.raw`Ibrahim ibn Musa informed us. Hisham informed us, from Ma'mar, from Hisham ibn Urwa, from his father, from al-Zubayr, who said: On the day of Badr, one hundred shares were assigned to the Emigrants.`, de: String.raw`Ibrahim ibn Musa berichtete uns. Hisham berichtete uns, von Ma'mar, von Hisham ibn Urwa, von seinem Vater, von az-Zubayr, der sagte: Am Tag von Badr wurden den Auswanderern einhundert Anteile zugeteilt.` },
  "4028": { en: String.raw`Ishaq ibn Nasr narrated to us. Abd al-Razzaq narrated to us. Ibn Jurayj informed us, from Musa ibn Uqba, from Nafi, from Ibn Umar, may Allah be pleased with them both, who said: The Nadir and Qurayza fought. The Banu Nadir were expelled, while Qurayza were spared and treated generously. Then Qurayza fought, so their men were killed, and their women, children, and property were divided among the Muslims. Some of them joined the Prophet (peace be upon him), and he granted them safety, and they embraced Islam. He expelled all the Jews of Medina: Banu Qaynuqa, who were the clan of Abd Allah ibn Salam, the Jews of Banu Haritha, and all the Jews of Medina.`, de: String.raw`Ishaq ibn Nasr überlieferte uns. Abd ar-Razzaq überlieferte uns. Ibn Dschuraidsch berichtete uns, von Musa ibn Uqba, von Nafi, von Ibn Umar, möge Allah mit ihnen beiden zufrieden sein, der sagte: Die Banu an-Nadir und Qurayza kämpften. Die Banu an-Nadir wurden vertrieben, während Qurayza verschont und begünstigt wurde. Dann kämpfte Qurayza, worauf ihre Männer getötet und ihre Frauen, Kinder und ihr Besitz unter den Muslimen verteilt wurden. Einige von ihnen schlossen sich dem Propheten (Friede sei auf ihm) an, und er gewährte ihnen Sicherheit, worauf sie den Islam annahmen. Er vertrieb alle Juden von Medina: die Banu Qaynuqa, die der Clan von Abd Allah ibn Salam waren, die Juden der Banu Haritha und alle Juden von Medina.` },
  "4029": { en: String.raw`Al-Hasan ibn Mudrik narrated to me. Yahya ibn Hammad narrated to us. Abu Awana informed us, from Abu Bishr, from Said ibn Jubayr, who said: I said to Ibn Abbas: Surat al-Hashr. He said: Say Surat al-Nadir. Hushaym followed it from Abu Bishr.`, de: String.raw`Al-Hasan ibn Mudrik berichtete mir. Yahya ibn Hammad überlieferte uns. Abu Awana berichtete uns, von Abu Bischar, von Said ibn Dschubayr, der sagte: Ich sagte zu Ibn Abbas: Sura al-Haschr. Er sagte: Sag Sura an-Nadir. Huschaym überlieferte es ebenfalls von Abu Bischar.` },
  "4030": { en: String.raw`Abd Allah ibn Abi al-Aswad narrated to us. Mutamir narrated to us, from his father. I heard Anas ibn Malik, may Allah be pleased with him, say: A man used to give the Prophet (peace be upon him) date palms until he conquered Qurayza and the Nadir. After that, he would return them to him.`, de: String.raw`Abd Allah ibn Abi al-Aswad überlieferte uns. Mutamir überlieferte uns, von seinem Vater. Ich hörte Anas ibn Malik, möge Allah mit ihm zufrieden sein, sagen: Ein Mann pflegte dem Propheten (Friede sei auf ihm) Dattelpalmen zu überlassen, bis er Qurayza und an-Nadir eroberte. Danach gab er sie ihm zurück.` },
  "4031": { en: String.raw`Adam narrated to us. Al-Layth narrated to us, from Nafi, from Ibn Umar, may Allah be pleased with them both, who said: The Messenger of Allah (peace be upon him) burned the date palms of Banu Nadir and cut them down at al-Buwayra. Then the verse was revealed: “Whatever palm trees you cut down or left standing on their roots, it was by Allah's permission” (Quran 59:5).`, de: String.raw`Adam überlieferte uns. Al-Layth überlieferte uns, von Nafi, von Ibn Umar, möge Allah mit ihnen beiden zufrieden sein, der sagte: Der Gesandte Allahs (Friede sei auf ihm) verbrannte die Dattelpalmen der Banu an-Nadir und fällte sie bei al-Buwayra. Dann wurde der Vers offenbart: „Was immer ihr an Palmen gefällt oder auf ihren Wurzeln stehen gelassen habt, geschah mit Allahs Erlaubnis“ (Quran 59:5).` },
  "4032": { en: String.raw`Ishaq narrated to me. Habban informed us. Juwayriya ibn Asma informed us, from Nafi, from Ibn Umar, may Allah be pleased with them both, that the Prophet (peace be upon him) burned the date palms of Banu Nadir. Hassan ibn Thabit said about it: “It was no small matter for the leaders of Banu Luayy: a spreading fire at al-Buwayra.” Abu Sufyan ibn al-Harith answered him: “May Allah perpetuate that deed, and may the blazing fire spread around it. You will learn which of us will depart from it safely, and you will learn which of our lands it will harm.”`, de: String.raw`Ishaq berichtete mir. Habban berichtete uns. Dschuwairiya ibn Asma berichtete uns, von Nafi, von Ibn Umar, möge Allah mit ihnen beiden zufrieden sein, dass der Prophet (Friede sei auf ihm) die Dattelpalmen der Banu an-Nadir verbrannte. Hassan ibn Thabit sagte darüber: „Für die Vornehmen der Banu Luayy war es keine Kleinigkeit: ein sich ausbreitendes Feuer bei al-Buwayra.“ Abu Sufyan ibn al-Harith antwortete ihm: „Möge Allah diese Tat fortbestehen lassen, und möge sich das lodernde Feuer ringsum ausbreiten. Ihr werdet erfahren, wer von uns sich sicher von ihr entfernt, und ihr werdet erfahren, welches unserer Länder sie schädigen wird.“` }
};

const out = raw.map((row) => {
  const n = row.url.split(":").pop()!;
  const v = t[n];
  if (!v) throw new Error("missing " + n);
  return { id: row.id, n, en: v.en, de: v.de };
});
fs.writeFileSync("data/hadith-words-translations/codex-out-096.json", JSON.stringify(out, null, 2) + "\n", "utf8");
console.log("wrote " + out.length + " translations");
