import fs from 'fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-203.json','utf8'));
const tr:Record<string,[string,string]>={
'https://sunnah.com/muslim:241b':[ `Abu Bakr ibn Abi Shayba narrated it to us. Waki' narrated to us, from Sufyan. And Ibn al-Muthanna and Ibn Bashshar narrated to us. They said: Muhammad ibn Ja'far narrated to us. He said: Shu'ba narrated to us. Both of them narrated from Mansur, with this chain. Shu'ba's hadith does not contain: Complete the wudu. His hadith is from Abu Yahya al-A'raj.`, `Abu Bakr ibn Abi Schayba überlieferte es uns. Waki' überlieferte uns, von Sufyan. Und Ibn al-Muthanna und Ibn Baschar überlieferten uns. Sie sagten: Muhammad ibn Dscha'far überlieferte uns. Er sagte: Schu'ba überlieferte uns. Beide überlieferten von Mansur, mit dieser Kette. Im Hadith von Schu'ba steht nicht: Vervollständigt die Gebetswaschung. Sein Hadith stammt von Abu Yahya al-A'raj.`],
'https://sunnah.com/muslim:241c':[ `Shayban ibn Farrukh and Abu Kamil al-Jahdari narrated to us, both from Abu Awana. Abu Kamil said: Abu Awana narrated to us, from Abu Bishr, from Yusuf ibn Mahak, from Abdullah ibn Amr, who said: The Prophet (peace be upon him) stayed behind us during a journey we were making. He caught up with us when the Asr prayer had become due, and we were wiping over our feet. He called out: Woe to the heels because of the Fire.`, `Schayban ibn Farrukh und Abu Kamil al-Dschahdari überlieferten uns, beide von Abu Awana. Abu Kamil sagte: Abu Awana überlieferte uns, von Abu Bischr, von Yusuf ibn Mahak, von Abd Allah ibn Amr, der sagte: Der Prophet (Friede sei auf ihm) blieb während einer Reise, die wir unternahmen, hinter uns zurück. Er holte uns ein, als das Nachmittagsgebet fällig geworden war, und wir strichen über unsere Füße. Er rief: Wehe den Fersen wegen des Feuers.`],
'https://sunnah.com/muslim:242a':[ `Abd al-Rahman ibn Sallam al-Jumahi narrated to us. al-Rabi', meaning Ibn Muslim, narrated to us, from Muhammad, meaning Ibn Ziyad, from Abu Hurayra, that the Prophet (peace be upon him) saw a man who had not washed his heels and said: Woe to the heels because of the Fire.`, `Abd ar-Rahman ibn Sallam al-Dschumahi überlieferte uns. ar-Rabi', das heißt Ibn Muslim, überlieferte uns, von Muhammad, das heißt Ibn Ziyad, von Abu Hurayra, dass der Prophet (Friede sei auf ihm) einen Mann sah, der seine Fersen nicht gewaschen hatte, und sagte: Wehe den Fersen wegen des Feuers.`],
'https://sunnah.com/muslim:242b':[ `Qutayba, Abu Bakr ibn Abi Shayba, and Abu Kurayb narrated to us. They said: Waki' narrated to us, from Shu'ba, from Muhammad ibn Ziyad, from Abu Hurayra, who saw people performing wudu from a water vessel. He said: Complete the wudu, for I heard Abu al-Qasim (peace be upon him) say: Woe to the heels because of the Fire.`, `Qutayba, Abu Bakr ibn Abi Schayba und Abu Kuraib überlieferten uns. Sie sagten: Waki' überlieferte uns, von Schu'ba, von Muhammad ibn Ziyad, von Abu Hurayra, der Menschen sah, die aus einem Wassergefäß die Gebetswaschung vollzogen. Er sagte: Vervollständigt die Gebetswaschung, denn ich hörte Abu al-Qasim (Friede sei auf ihm) sagen: Wehe den Fersen wegen des Feuers.`],
'https://sunnah.com/muslim:242c':[ `Zuhayr ibn Harb narrated to me. Jarir narrated to us, from Suhayl, from his father, from Abu Hurayra, who said: The Messenger of Allah (peace be upon him) said: Woe to the heels because of the Fire.`, `Zuhayr ibn Harb überlieferte mir. Jarir überlieferte uns, von Suhayl, von seinem Vater, von Abu Hurayra, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Wehe den Fersen wegen des Feuers.`],
'https://sunnah.com/muslim:243':[ `Salama ibn Shabib narrated to us. al-Hasan ibn Muhammad ibn A'yun narrated to us. Ma'qil narrated to us, from Abu al-Zubayr, from Jabir. Umar ibn al-Khattab informed me that a man performed wudu but left an area the size of a fingernail on his foot. The Prophet (peace be upon him) saw it and said: Go back and perform wudu well. He went back, then prayed.`, `Salama ibn Schabib überlieferte uns. al-Hasan ibn Muhammad ibn A'yun überlieferte uns. Ma'qil überlieferte uns, von Abu az-Zubayr, von Dschabir. Umar ibn al-Chattab berichtete mir, dass ein Mann die Gebetswaschung vollzog, aber an seinem Fuß eine Stelle in der Größe eines Fingernagels ausließ. Der Prophet (Friede sei auf ihm) sah sie und sagte: Geh zurück und vollziehe die Gebetswaschung gut. Er ging zurück und betete dann.`],
'https://sunnah.com/muslim:244':[ `Suwayd ibn Sa'id narrated to us, from Malik ibn Anas. And Abu al-Tahir narrated to us, and this is his wording. Abdullah ibn Wahb informed us, from Malik ibn Anas, from Suhayl ibn Abi Salih, from his father, from Abu Hurayra, that the Messenger of Allah (peace be upon him) said: When the Muslim servant, or believer, performs wudu and washes his face, every sin that his eyes looked at leaves his face with the water, or with the last drop of water. When he washes his hands, every sin his hands committed leaves his hands with the water, or with the last drop of water. When he washes his feet, every sin his feet walked toward leaves them with the water, or with the last drop of water, until he emerges purified of sins.`, `Suwayd ibn Sa'id überlieferte uns, von Malik ibn Anas. Und Abu at-Tahir überlieferte uns, und dies ist sein Wortlaut. Abd Allah ibn Wahb berichtete uns, von Malik ibn Anas, von Suhayl ibn Abi Salih, von seinem Vater, von Abu Hurayra, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn der muslimische Diener oder der Gläubige die Gebetswaschung vollzieht und sein Gesicht wäscht, verlässt jede Sünde, die seine Augen betrachtet haben, sein Gesicht mit dem Wasser oder mit dem letzten Tropfen Wasser. Wenn er seine Hände wäscht, verlässt jede Sünde, die seine Hände begangen haben, seine Hände mit dem Wasser oder mit dem letzten Tropfen Wasser. Wenn er seine Füße wäscht, verlässt jede Sünde, zu der seine Füße gegangen sind, sie mit dem Wasser oder mit dem letzten Tropfen Wasser, bis er von den Sünden gereinigt hervorkommt.`]
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,en:tr[r.url][0],de:tr[r.url][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-203-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-203-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
