import fs from 'fs';
const rows:any[] = JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:Record<string,[string,string]> = {
 'Sahih Muslim, hadith 191 b, book 1, باب أَدْنَى أَهْلِ الْجَنَّةِ مَنْزِلَةً فِيهَا ‏‏':["Abu Bakr ibn Abi Shayba narrated to us. Sufyan ibn Uyayna narrated to us, from Amr, who heard Jabir say that he heard the Prophet (peace be upon him) with his own ears say: Allah will bring people out of the Fire and admit them to Paradise.","Abu Bakr ibn Abi Schayba überlieferte uns. Sufyan ibn Uyayna überlieferte uns, von Amr, der Dschabir sagen hörte, dass er den Propheten (Friede sei auf ihm) mit eigenen Ohren sagen hörte: Allah wird Menschen aus dem Feuer herausbringen und sie ins Paradies eintreten lassen."],
 'Sahih Muslim, hadith 191 c, book 1, باب أَدْنَى أَهْلِ الْجَنَّةِ مَنْزِلَةً فِيهَا ‏‏':["Abu al-Rabi narrated to us. Hammad ibn Zayd narrated to us. I said to Amr ibn Dinar: Did you hear Jabir ibn Abdullah narrate from the Messenger of Allah (peace be upon him), 'Allah will bring a group of people out of the Fire through intercession'? He said: Yes.","Abu ar-Rabi überlieferte uns. Hammad ibn Zayd überlieferte uns. Ich sagte zu Amr ibn Dinar: Hast du gehört, dass Dschabir ibn Abd Allah vom Gesandten Allahs (Friede sei auf ihm) überlieferte: 'Allah wird durch Fürsprache eine Gruppe von Menschen aus dem Feuer herausbringen'? Er sagte: Ja."],
 'Sahih Muslim, hadith 191 d, book 1, باب أَدْنَى أَهْلِ الْجَنَّةِ مَنْزِلَةً فِيهَا ‏‏':["Hajjaj ibn al-Sha'ir narrated to us. Abu Ahmad al-Zubayri narrated to us. Qays ibn Sulaym al-Anbari narrated to us. Yazid al-Faqir narrated to me. Jabir ibn Abdullah narrated to us that the Messenger of Allah (peace be upon him) said: Some people will be brought out of the Fire after being burned in it, except for the marks on their faces, until they enter Paradise.","Haddschadsch ibn asch-Scha'ir überlieferte uns. Abu Ahmad az-Zubayri überlieferte uns. Qays ibn Sulaym al-Anbari überlieferte uns. Yazid al-Faqir überlieferte mir. Dschabir ibn Abd Allah überlieferte uns, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Einige Menschen werden aus dem Feuer herausgebracht, nachdem sie darin verbrannt sind, außer an den Spuren ihrer Gesichter, bis sie ins Paradies eintreten."],
 'Sahih Muslim, hadith 192, book 1, باب أَدْنَى أَهْلِ الْجَنَّةِ مَنْزِلَةً فِيهَا ‏‏':["Haddab ibn Khalid al-Azdi narrated to us. Hammad ibn Salama narrated to us, from Abu Imran and Thabit, from Anas ibn Malik, that the Messenger of Allah (peace be upon him) said: Four people will come out of the Fire and be presented to Allah. One of them will turn and say: My Lord, since You brought me out of it, do not return me to it. Allah will save him from it.","Haddab ibn Khalid al-Azdi überlieferte uns. Hammad ibn Salama überlieferte uns, von Abu Imran und Thabit, von Anas ibn Malik, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Vier Menschen werden aus dem Feuer herauskommen und Allah vorgestellt werden. Einer von ihnen wird sich umwenden und sagen: Mein Herr, da Du mich daraus herausgebracht hast, bringe mich nicht wieder hinein. Allah wird ihn davor retten."],
 'Sahih Muslim, hadith 193 b, book 1, باب أَدْنَى أَهْلِ الْجَنَّةِ مَنْزِلَةً فِيهَا ‏‏':["Muhammad ibn al-Muthanna and Muhammad ibn Bashshar narrated to us. Ibn Abi Adi narrated to us, from Sa'id, from Qatada, from Anas, who said: The Messenger of Allah (peace be upon him) said: The believers will gather on the Day of Resurrection and be concerned about that, or be inspired to do that, in the same manner as Abu Awana's hadith. He said in the hadith: Then I will come to him a fourth time, or return a fourth time, and say: My Lord, none remains except the one whom the Quran has held back.","Muhammad ibn al-Muthanna und Muhammad ibn Baschar überlieferten uns. Ibn Abi Adi überlieferte uns, von Sa'id, von Qatada, von Anas, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Die Gläubigen werden sich am Tag der Auferstehung versammeln und darüber bekümmert sein oder dazu inspiriert werden, wie im Hadith von Abu Awana. Er sagte darin: Dann komme ich ein viertes Mal zu Ihm oder kehre ein viertes Mal zurück und sage: Mein Herr, niemand bleibt außer dem, den der Quran zurückgehalten hat."],
 'Sahih Muslim, hadith 193 c, book 1, باب أَدْنَى أَهْلِ الْجَنَّةِ مَنْزِلَةً فِيهَا ‏‏':["Muhammad ibn al-Muthanna narrated to us. Muadh ibn Hisham narrated to us. He said: My father narrated to me, from Qatada, from Anas ibn Malik, that the Prophet (peace be upon him) said: Allah will gather the believers on the Day of Resurrection and they will be inspired to do that, in the same manner as their two hadiths. He mentioned in the fourth: I will say: My Lord, none remains in the Fire except the one whom the Quran has held back, meaning the one for whom remaining forever has become obligatory.","Muhammad ibn al-Muthanna überlieferte uns. Mu'adh ibn Hischam überlieferte uns. Er sagte: Mein Vater überlieferte mir, von Qatada, von Anas ibn Malik, dass der Prophet (Friede sei auf ihm) sagte: Allah wird die Gläubigen am Tag der Auferstehung versammeln und sie werden dazu inspiriert, wie in ihren beiden Hadithen. Er erwähnte beim vierten Mal: Ich werde sagen: Mein Herr, niemand bleibt im Feuer außer dem, den der Quran zurückgehalten hat, das heißt, für den das ewige Verbleiben verpflichtend geworden ist."],
 'Sahih Muslim, hadith 193 d, book 1, باب أَدْنَى أَهْلِ الْجَنَّةِ مَنْزِلَةً فِيهَا ‏‏':["Muhammad ibn Minhal al-Darir narrated to us. Yazid ibn Zuray narrated to us. Sa'id ibn Abi Aruba and Hisham, the companion of al-Dastawa'i, narrated to us, from Qatada, from Anas ibn Malik, who said: The Messenger of Allah (peace be upon him) said: Whoever said, 'There is no god but Allah,' and had goodness in his heart weighing a barley grain, will come out of the Fire. Then whoever said, 'There is no god but Allah,' and had goodness in his heart weighing a wheat grain, will come out of the Fire. Then whoever said, 'There is no god but Allah,' and had goodness in his heart weighing an atom, will come out of the Fire. Ibn Minhal added in his report: Yazid said: I met Shu'ba and told him the hadith. Shu'ba said: Qatada narrated it to us from Anas ibn Malik, from the Prophet (peace be upon him), except that Shu'ba used 'corn grain' instead of 'atom'. Yazid said: Abu Bustam made a copying error in it.","Muhammad ibn Minhal ad-Darir überlieferte uns. Yazid ibn Zuray überlieferte uns. Sa'id ibn Abi Aruba und Hischam, der Gefährte von ad-Dastuwa'i, überlieferten uns, von Qatada, von Anas ibn Malik, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Wer sagte: 'Es gibt keinen Gott außer Allah', und in dessen Herz sich Gutes im Gewicht eines Gerstenkorns befand, wird aus dem Feuer herauskommen. Dann wird aus dem Feuer herauskommen, wer sagte: 'Es gibt keinen Gott außer Allah', und in dessen Herz sich Gutes im Gewicht eines Weizenkorns befand. Dann wird aus dem Feuer herauskommen, wer sagte: 'Es gibt keinen Gott außer Allah', und in dessen Herz sich Gutes im Gewicht eines Atoms befand. Ibn Minhal fügte in seiner Überlieferung hinzu: Yazid sagte: Ich traf Schu'ba und berichtete ihm den Hadith. Schu'ba sagte: Qatada überlieferte ihn uns von Anas ibn Malik, vom Propheten (Friede sei auf ihm), außer dass Schu'ba statt 'Atom' 'Maiskorn' sagte. Yazid sagte: Abu Bistam hat darin einen Abschreibfehler gemacht.]
};
const out=rows.filter(r=>tr[r.reference]).map(r=>({...r,en:tr[r.reference][0],de:tr[r.reference][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-183-more-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-183-more-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
