import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-next.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:278d':{en:'Salama ibn Shabib narrated to me. al-Hasan ibn Ayan narrated to us. Maqil narrated to us, from Abu al-Zubayr, from Jabir, from Abu Hurayra, who informed him that the Prophet (peace be upon him) said: When one of you wakes, let him pour water over his hand three times before putting it into his vessel, for he does not know in what condition his hand spent the night.',de:'Salama ibn Shabib überlieferte mir. al-Hasan ibn Ayan überlieferte uns. Maqil überlieferte uns, von Abu al-Zubayr, von Jabir, von Abu Hurayra, der ihm berichtete, dass der Prophet (Friede sei auf ihm) sagte: Wenn einer von euch aufwacht, soll er dreimal Wasser über seine Hand gießen, bevor er sie in sein Gefäß steckt, denn er weiß nicht, in welchem Zustand seine Hand die Nacht verbracht hat.'},
'https://sunnah.com/muslim:278e':{en:'Qutayba ibn Said narrated to us. al-Mughira, meaning al-Hizami, narrated to us, from Abu al-Zinad, from al-Araj, from Abu Hurayra. Nasr ibn Ali also narrated to us. Abd al-Ala narrated to us, from Hisham, from Muhammad, from Abu Hurayra. Abu Kurayb also narrated to me. Khalid, meaning ibn Makhlad, narrated to us, from Muhammad ibn Jafar, from al-Ala, from his father, from Abu Hurayra. Muhammad ibn Rafi also narrated to us. Abd al-Razzaq narrated to us. Ma\'mar narrated to us, from Hammam ibn Munabbih, from Abu Hurayra. Muhammad ibn Hatim also narrated to me. Muhammad ibn Bakr narrated to us. Al-Hulwani and Ibn Rafi also narrated to us. They said: Abd al-Razzaq narrated to us. They all informed us: Ibn Jurayj informed us. Ziyad informed me that Thabit, the client of Abd al-Rahman ibn Zayd, informed him that he heard Abu Hurayra narrate this hadith from the Prophet (peace be upon him). All of them say: until he washes it. None of them says “three times,” except the reports already mentioned from Jabir, Ibn al-Musayyab, Abu Salama, Abdullah ibn Shaqiq, Abu Salih, and Abu Razin, for their hadiths mention three times.',de:'Qutayba ibn Said überlieferte uns. al-Mughira, gemeint ist al-Hizami, überlieferte uns, von Abu al-Zinad, von al-Araj, von Abu Hurayra. Auch Nasr ibn Ali überlieferte uns. Abd al-Ala überlieferte uns, von Hisham, von Muhammad, von Abu Hurayra. Auch Abu Kurayb überlieferte mir. Khalid, gemeint ist ibn Makhlad, überlieferte uns, von Muhammad ibn Jafar, von al-Ala, von dessen Vater, von Abu Hurayra. Auch Muhammad ibn Rafi überlieferte uns. Abd al-Razzaq überlieferte uns. Ma\'mar überlieferte uns, von Hammam ibn Munabbih, von Abu Hurayra. Auch Muhammad ibn Hatim überlieferte mir. Muhammad ibn Bakr überlieferte uns. Al-Hulwani und Ibn Rafi überlieferten uns ebenfalls. Sie sagten: Abd al-Razzaq überlieferte uns. Sie alle berichteten uns: Ibn Jurayj berichtete mir. Ziyad berichtete mir, dass Thabit, der Schutzbefohlene von Abd al-Rahman ibn Zayd, ihm berichtete, dass er Abu Hurayra diesen Hadith vom Propheten (Friede sei auf ihm) überliefern hörte. Alle sagen: bis er es wäscht. Keiner von ihnen sagt „dreimal“, außer den bereits erwähnten Überlieferungen von Jabir, Ibn al-Musayyab, Abu Salama, Abdullah ibn Shaqiq, Abu Salih und Abu Razin, denn in ihren Hadithen werden drei Mal erwähnt.'},
'https://sunnah.com/muslim:279a':{en:'Ali ibn Hujr al-Sadi narrated to me. Ali ibn Mushir narrated to us. Al-Amash informed us, from Abu Razin and Abu Salih, from Abu Hurayra, who said: The Messenger of Allah (peace be upon him) said: If a dog licks one of your vessels, let him pour it out, then wash it seven times.',de:'Ali ibn Hujr al-Sadi überlieferte mir. Ali ibn Mushir überlieferte uns. Al-Amash berichtete uns, von Abu Razin und Abu Salih, von Abu Hurayra, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn ein Hund eines eurer Gefäße beleckt, soll er es ausgießen und es danach siebenmal waschen.'},
'https://sunnah.com/muslim:279b':{en:'Muhammad ibn al-Sabbah narrated to me. Ismail ibn Zakariyya narrated to us, from al-Amash, with this chain, with the same wording, but he did not say: let him pour it out.',de:'Muhammad ibn al-Sabbah überlieferte mir. Ismail ibn Zakariyya überlieferte uns, von al-Amash, mit dieser Überlieferungskette und demselben Wortlaut, aber er sagte nicht: Er soll es ausgießen.'},
'https://sunnah.com/muslim:279c':{en:'Yahya ibn Yahya narrated to us. He said: I read to Malik, from Abu al-Zinad, from al-Araj, from Abu Hurayra, that the Messenger of Allah (peace be upon him) said: If a dog drinks from one of your vessels, let him wash it seven times.',de:'Yahya ibn Yahya überlieferte uns. Er sagte: Ich las Malik vor, von Abu al-Zinad, von al-Araj, von Abu Hurayra, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn ein Hund aus einem eurer Gefäße trinkt, soll er es siebenmal waschen.'},
'https://sunnah.com/muslim:279d':{en:'Zuhayr ibn Harb narrated to us. Ismail ibn Ibrahim narrated to us, from Hisham ibn Hassan, from Muhammad ibn Sirin, from Abu Hurayra, who said: The Messenger of Allah (peace be upon him) said: The purification of one of your vessels, when a dog licks it, is that you wash it seven times, the first of them with soil.',de:'Zuhayr ibn Harb überlieferte uns. Ismail ibn Ibrahim überlieferte uns, von Hisham ibn Hassan, von Muhammad ibn Sirin, von Abu Hurayra, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Die Reinigung eines eurer Gefäße, wenn ein Hund es beleckt, besteht darin, dass ihr es siebenmal wascht, das erste Mal mit Erde.'},
'https://sunnah.com/muslim:279e':{en:'Muhammad ibn Rafi narrated to us. Abd al-Razzaq narrated to us. Ma\'mar narrated to us, from Hammam ibn Munabbih, who said: This is what Abu Hurayra narrated to us from Muhammad, the Messenger of Allah (peace be upon him). He mentioned several hadiths, including this: The Messenger of Allah (peace be upon him) said: The purification of one of your vessels, when a dog licks it, is that you wash it seven times.',de:'Muhammad ibn Rafi überlieferte uns. Abd al-Razzaq überlieferte uns. Ma\'mar überlieferte uns, von Hammam ibn Munabbih, der sagte: Dies ist, was Abu Hurayra uns von Muhammad, dem Gesandten Allahs (Friede sei auf ihm), überlieferte. Er erwähnte mehrere Hadithe, darunter: Der Gesandte Allahs (Friede sei auf ihm) sagte: Die Reinigung eines eurer Gefäße, wenn ein Hund es beleckt, besteht darin, dass ihr es siebenmal wascht.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-211-part2.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-211-part2.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
