import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-next.json','utf8'));
const tr:Record<string,{en:string;de:string}>={
'https://sunnah.com/muslim:363c':{en:'Hasan al-Hulwani and Abd ibn Humayd narrated to us, both from Yaqob ibn Ibrahim ibn Sad. My father narrated to me, from Salih, from Ibn Shihab, with this chain and approximately the wording of Yunus’s narration.',de:'Hasan al-Hulwani und Abd ibn Humayd überlieferten uns, beide von Yaqob ibn Ibrahim ibn Sad. Mein Vater überlieferte mir, von Salih, von Ibn Shihab, mit dieser Überlieferungskette und ungefähr dem Wortlaut von Yunus’ Überlieferung.'},
'https://sunnah.com/muslim:363d':{en:'Ibn Abi Umar and Abdullah ibn Muhammad al-Zuhri narrated to us, and this is Ibn Abi Umar’s wording. They said: Sufyan narrated to us, from Amr, from Ata, from Ibn Abbas, that the Messenger of Allah (peace be upon him) passed by a sheep lying dead that had been given as charity to a client of Maymuna. The Prophet (peace be upon him) said: Why did they not take its hide, tan it, and benefit from it?',de:'Ibn Abi Umar und Abdullah ibn Muhammad al-Zuhri überlieferten uns, und dies ist der Wortlaut von Ibn Abi Umar. Sie sagten: Sufyan überlieferte uns, von Amr, von Ata, von Ibn Abbas, dass der Gesandte Allahs (Friede sei auf ihm) an einem verendeten Schaf vorbeikam, das einem Schutzbefohlenen von Maymuna als Almosen gegeben worden war. Der Prophet (Friede sei auf ihm) sagte: Warum haben sie nicht seine Haut genommen, sie gegerbt und sie genutzt?'},
'https://sunnah.com/muslim:364':{en:'Ahmad ibn Uthman al-Nawfali narrated to us. Abu Asim narrated to us. Ibn Jurayj narrated to us. Amr ibn Dinar informed me. Ata informed me some time ago, saying: Ibn Abbas informed me that Maymuna informed him that a domestic animal belonging to one of the wives of the Messenger of Allah (peace be upon him) died. The Messenger of Allah (peace be upon him) said: Why did you not take its hide and make use of it?',de:'Ahmad ibn Uthman al-Nawfali überlieferte uns. Abu Asim überlieferte uns. Ibn Jurayj überlieferte uns. Amr ibn Dinar berichtete mir. Ata berichtete mir vor einiger Zeit, dass Ibn Abbas ihm berichtete, dass Maymuna ihm berichtete, dass ein Haustier einer der Ehefrauen des Gesandten Allahs (Friede sei auf ihm) verendete. Der Gesandte Allahs (Friede sei auf ihm) sagte: Warum habt ihr nicht seine Haut genommen und sie genutzt?'},
'https://sunnah.com/muslim:365':{en:'Abu Bakr ibn Abi Shayba narrated to us. Abd al-Rahim ibn Sulayman narrated to us, from Abd al-Malik ibn Abi Sulayman, from Ata, from Ibn Abbas, that the Prophet (peace be upon him) passed by a sheep belonging to a client of Maymuna and said: Why did you not make use of its hide?',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Abd al-Rahim ibn Sulayman überlieferte uns, von Abd al-Malik ibn Abi Sulayman, von Ata, von Ibn Abbas, dass der Prophet (Friede sei auf ihm) an einem Schaf vorbeikam, das einem Schutzbefohlenen von Maymuna gehörte, und sagte: Warum habt ihr seine Haut nicht genutzt?'},
'https://sunnah.com/muslim:366a':{en:'Yahya ibn Yahya informed us. Sulayman ibn Bilal informed us, from Zayd ibn Aslam, that Abd al-Rahman ibn Waʿla informed him, from Abdullah ibn Abbas, who said: I heard the Messenger of Allah (peace be upon him) say: When a hide is tanned, it becomes pure.',de:'Yahya ibn Yahya berichtete uns. Sulayman ibn Bilal berichtete uns, von Zaid ibn Aslam, dass Abd al-Rahman ibn Wala ihm berichtete, von Abdullah ibn Abbas, der sagte: Ich hörte den Gesandten Allahs (Friede sei auf ihm) sagen: Wenn eine Haut gegerbt wird, wird sie rein.'},
'https://sunnah.com/muslim:366b':{en:'Abu Bakr ibn Abi Shayba and Amr al-Naqid narrated to us. They said: Ibn Uyayna narrated to us. Qutayba ibn Said narrated to us: Abd al-Aziz, meaning Ibn Muhammad, narrated to us. Abu Kurayb and Ishaq ibn Ibrahim both narrated from Waki, from Sufyan. All of them narrated from Zayd ibn Aslam, from Abd al-Rahman ibn Waʿla, from Ibn Abbas, from the Prophet (peace be upon him), with the same meaning, meaning the hadith of Yahya ibn Yahya.',de:'Abu Bakr ibn Abi Shayba und Amr al-Naqid überlieferten uns. Sie sagten: Ibn Uyayna überlieferte uns. Qutayba ibn Said überlieferte uns: Abd al-Aziz, nämlich Ibn Muhammad, überlieferte uns. Abu Kurayb und Ishaq ibn Ibrahim überlieferten beide von Waki, von Sufyan. Alle überlieferten von Zaid ibn Aslam, von Abd al-Rahman ibn Wala, von Ibn Abbas, vom Propheten (Friede sei auf ihm), mit derselben Bedeutung, nämlich dem Hadith von Yahya ibn Yahya.'},
'https://sunnah.com/muslim:366c':{en:'Ishaq ibn Mansur and Abu Bakr ibn Ishaq narrated to me. Abu Bakr said: He narrated to us, while Ibn Mansur said: Amr ibn al-Rabi informed us. Yahya ibn Ayyub informed us, from Yazid ibn Abi Habib, that Abu al-Khayr narrated to him. He said: I saw Ibn Waʿla al-Sabai wearing a fur and touched it. He said: Why are you touching it? I asked Abdullah ibn Abbas about it. I said: We are in the Maghrib, with Berbers and Magians among us. A ram that they slaughtered is brought to us, but we do not eat their slaughtered animals. They bring us a waterskin in which they put fat. Ibn Abbas said: We asked the Messenger of Allah (peace be upon him) about that, and he said: Its tanning is its purification.',de:'Ishaq ibn Mansur und Abu Bakr ibn Ishaq überlieferten mir. Abu Bakr sagte: Er überlieferte uns, während Ibn Mansur sagte: Amr ibn al-Rabi berichtete uns. Yahya ibn Ayyub berichtete uns, von Yazid ibn Abi Habib, dass Abu al-Khayr ihm erzählte. Er sagte: Ich sah Ibn Wala al-Sabai einen Pelz tragen und berührte ihn. Er sagte: Warum berührst du ihn? Ich fragte Abdullah ibn Abbas danach. Ich sagte: Wir befinden uns im Maghrib, und unter uns sind Berber und Magier. Man bringt uns einen Widder, den sie geschlachtet haben, aber wir essen ihre geschlachteten Tiere nicht. Sie bringen uns einen Schlauch, in den sie Fett geben. Ibn Abbas sagte: Wir fragten den Gesandten Allahs (Friede sei auf ihm) danach, und er sagte: Sein Gerben ist seine Reinigung.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]})); if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-235-part.json',JSON.stringify(out,null,2)); fs.writeFileSync('data/hadith-words-translations/codex-out-235-part.json',JSON.stringify(out,null,2)); console.log(`wrote ${out.length} staged translations`);
