import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:302':{en:'Zuhayr ibn Harb narrated to me. Abd al-Rahman ibn Mahdi narrated to us. Hammad ibn Salama narrated to us. Thabit narrated to us, from Anas, that when Jewish women menstruated, the Jews did not eat with them or live with them intimately in their houses. The companions of the Prophet (peace be upon him) asked the Prophet (peace be upon him), and Allah Most High revealed: “They ask you about menstruation. Say: It is harm, so keep away from women during menstruation” (Quran 2:222), to the end of the verse. The Messenger of Allah (peace be upon him) said: Do everything except intercourse. The Jews heard about that and said: What does this man want? He leaves nothing of our practice without opposing us in it. Usayd ibn Hudayr and Abbad ibn Bishr came and said: O Messenger of Allah, the Jews say such and such. So shall we not have intercourse with them? The face of the Messenger of Allah (peace be upon him) changed until we thought he was angry with them. They left, and a gift of milk was brought to the Prophet (peace be upon him). He sent after them and gave them milk to drink, and they knew that he was not angry with them.',de:'Zuhayr ibn Harb überlieferte mir. Abd al-Rahman ibn Mahdi überlieferte uns. Hammad ibn Salama überlieferte uns. Thabit überlieferte uns, von Anas, dass die Juden, wenn ihre Frauen menstruieren, weder mit ihnen aßen noch mit ihnen in den Häusern intim waren. Die Gefährten des Propheten (Friede sei auf ihm) fragten den Propheten (Friede sei auf ihm), und Allah, der Erhabene, offenbarte: „Sie fragen dich nach der Menstruation. Sag: Sie ist eine Schädigung, so haltet euch während der Menstruation von den Frauen fern“ (Quran 2:222), bis zum Ende des Verses. Der Gesandte Allahs (Friede sei auf ihm) sagte: Tut alles außer dem Geschlechtsverkehr. Das hörten die Juden und sagten: Was will dieser Mann? Er lässt nichts von unserer Angelegenheit, ohne uns darin zu widersprechen. Usayd ibn Hudayr und Abbad ibn Bishr kamen und sagten: O Gesandter Allahs, die Juden sagen dies und jenes. Sollen wir dann keinen Geschlechtsverkehr mit ihnen haben? Das Gesicht des Gesandten Allahs (Friede sei auf ihm) veränderte sich, bis wir dachten, er sei über sie verärgert. Sie gingen hinaus, und dem Propheten (Friede sei auf ihm) wurde ein Geschenk Milch gebracht. Er sandte ihnen nach und gab ihnen Milch zu trinken, und sie erkannten, dass er nicht über sie verärgert war.'},
'https://sunnah.com/muslim:303a':{en:'Abu Bakr ibn Abi Shayba narrated to us. Waki, Abu Muawiya, and Hushaym narrated to us, from al-Amash, from Mundhir ibn Yala, who was known as Abu Yala, from Ibn al-Hanafiyya, from Ali, who said: I was a man who experienced a great deal of pre-seminal fluid, and I was too shy to ask the Prophet (peace be upon him) because of his daughter. So I ordered al-Miqdad ibn al-Aswad to ask him, and he said: He should wash his private part and perform wudu.',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Waki, Abu Muawiya und Hushaym überlieferten uns, von al-Amash, von Mundhir ibn Yala, der als Abu Yala bekannt war, von Ibn al-Hanafiyya, von Ali, der sagte: Bei mir trat häufig Präejakulat aus, und ich schämte mich, den Propheten (Friede sei auf ihm) wegen seiner Tochter zu fragen. Daher beauftragte ich al-Miqdad ibn al-Aswad, ihn zu fragen, und er sagte: Er soll sein Geschlechtsteil waschen und Wudu verrichten.'},
'https://sunnah.com/muslim:303b':{en:'Yahya ibn Habib al-HarithI narrated to us. Khalid, meaning ibn al-Harith, narrated to us. Shuba informed me. Sulayman said: I heard Mundhir narrate from Muhammad ibn Ali, from Ali, that he said: I was too shy to ask the Prophet (peace be upon him) about pre-seminal fluid because of Fatima, so I ordered al-Miqdad to ask him. He said: It requires wudu.',de:'Yahya ibn Habib al-Harithi überlieferte uns. Khalid, gemeint ist ibn al-Harith, überlieferte uns. Shuba berichtete mir. Sulayman sagte: Ich hörte Mundhir von Muhammad ibn Ali, von Ali, überliefern, dass er sagte: Ich schämte mich, den Propheten (Friede sei auf ihm) wegen Fatima nach Präejakulat zu fragen. Daher beauftragte ich al-Miqdad, ihn zu fragen. Er sagte: Dafür ist Wudu erforderlich.'},
'https://sunnah.com/muslim:303c':{en:'Harun ibn Said al-Ayli and Ahmad ibn Isa narrated to me. They said: Ibn Wahb narrated to us. Makhrama ibn Bukayr informed me, from his father, from Sulayman ibn Yasar, from Ibn Abbas, who said: Ali ibn Abi Talib said: We sent al-Miqdad ibn al-Aswad to the Messenger of Allah (peace be upon him) to ask him about pre-seminal fluid that comes from a person: What should he do about it? The Messenger of Allah (peace be upon him) said: Perform wudu and sprinkle water on your private part.',de:'Harun ibn Said al-Ayli und Ahmad ibn Isa überlieferten mir. Sie sagten: Ibn Wahb überlieferte uns. Makhrama ibn Bukayr berichtete mir, von seinem Vater, von Sulayman ibn Yasar, von Ibn Abbas, der sagte: Ali ibn Abi Talib sagte: Wir schickten al-Miqdad ibn al-Aswad zum Gesandten Allahs (Friede sei auf ihm), um ihn über Präejakulat zu fragen, das aus einem Menschen austritt: Was soll er damit tun? Der Gesandte Allahs (Friede sei auf ihm) sagte: Verrichte Wudu und spritze Wasser auf dein Geschlechtsteil.'},
'https://sunnah.com/muslim:304':{en:'Abu Bakr ibn Abi Shayba and Abu Kurayb narrated to us. They said: Waki narrated to us, from Sufyan, from Salama ibn Kuhayl, from Kurayb, from Ibn Abbas, that the Prophet (peace be upon him) got up at night, relieved himself, then washed his face and hands, and then slept.',de:'Abu Bakr ibn Abi Shayba und Abu Kurayb überlieferten uns. Sie sagten: Waki überlieferte uns, von Sufyan, von Salama ibn Kuhayl, von Kurayb, von Ibn Abbas, dass der Prophet (Friede sei auf ihm) nachts aufstand, sich erleichterte, dann sein Gesicht und seine Hände wusch und danach schlief.'},
'https://sunnah.com/muslim:305a':{en:'Yahya ibn Yahya al-Tamimi and Muhammad ibn Rumh narrated to us. They said: al-Layth informed us. Qutayba ibn Said also narrated to us: Layth narrated to us, from Ibn Shihab, from Abu Salama ibn Abd al-Rahman, from Aisha, that when the Messenger of Allah (peace be upon him) wanted to sleep while in a state of major ritual impurity, he performed the wudu for prayer before sleeping.',de:'Yahya ibn Yahya al-Tamimi und Muhammad ibn Rumh überlieferten uns. Sie sagten: al-Layth berichtete uns. Auch Qutayba ibn Said überlieferte uns: Layth überlieferte uns, von Ibn Shihab, von Abu Salama ibn Abd al-Rahman, von Aisha, dass der Gesandte Allahs (Friede sei auf ihm), wenn er im Zustand großer ritueller Unreinheit schlafen wollte, vor dem Schlafen die Wudu für das Gebet verrichtete.'},
'https://sunnah.com/muslim:305b':{en:'Abu Bakr ibn Abi Shayba narrated to us. Ibn Ulayya, Waki, and Ghundar narrated to us, from Shuba, from al-Hakam, from Ibrahim, from al-Aswad, from Aisha, who said: When the Messenger of Allah (peace be upon him) was in a state of major ritual impurity and wanted to eat or sleep, he performed the wudu for prayer.',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Ibn Ulayya, Waki und Ghundar überlieferten uns, von Shuba, von al-Hakam, von Ibrahim, von al-Aswad, von Aisha, die sagte: Wenn der Gesandte Allahs (Friede sei auf ihm) im Zustand großer ritueller Unreinheit war und essen oder schlafen wollte, verrichtete er die Wudu für das Gebet.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-218-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-218-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
