import fs from 'fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-192.json','utf8'));
const tr:Record<string,[string,string]>={
'https://sunnah.com/muslim:200a':[ `Abu Ghassan al-Misma'i, Muhammad ibn al-Muthanna, and Ibn Bashshar narrated to us, and this is Abu Ghassan's wording. They said: Muadh, meaning Ibn Hisham, narrated to us. He said: My father narrated to me, from Qatada. Anas ibn Malik narrated to us that the Prophet of Allah (peace be upon him) said: Every prophet has a supplication that he made for his community, and I have reserved my supplication as intercession for my community on the Day of Resurrection.`, `Abu Ghassan al-Misma'i, Muhammad ibn al-Muthanna und Ibn Baschar überlieferten uns, und dies ist der Wortlaut von Abu Ghassan. Sie sagten: Mu'adh, das heißt Ibn Hischam, überlieferte uns. Er sagte: Mein Vater überlieferte mir, von Qatada. Anas ibn Malik überlieferte uns, dass der Prophet Allahs (Friede sei auf ihm) sagte: Jeder Prophet hat ein Bittgebet, das er für seine Gemeinschaft gesprochen hat, und ich habe mein Bittgebet als Fürsprache für meine Gemeinschaft am Tag der Auferstehung aufbewahrt.`],
'https://sunnah.com/muslim:200b':[ `Zuhayr ibn Harb and Ibn Abi Khalaf narrated it to me. They said: Ruh narrated to us. Shu'ba narrated to us, from Qatada, with this chain of transmission.`, `Zuhayr ibn Harb und Ibn Abi Chalaf überlieferten es mir. Sie sagten: Ruh überlieferte uns. Schu'ba überlieferte uns, von Qatada, mit dieser Überlieferungskette.`],
'https://sunnah.com/muslim:200c':[ `Abu Kurayb narrated to us. Waki' narrated to us. And Ibrahim ibn Sa'id al-Jawhari narrated it to me. Abu Usama narrated to us; all of them from Mis'ar, from Qatada, with this chain. However, in Waki's hadith it says: He was given. In Abu Usama's hadith it is from the Prophet (peace be upon him).`, `Abu Kuraib überlieferte uns. Waki' überlieferte uns. Und Ibrahim ibn Sa'id al-Dschauhari überlieferte es mir. Abu Usama überlieferte uns; alle von Mis'ar, von Qatada, mit dieser Überlieferungskette. In Waki's Hadith heißt es jedoch: Ihm wurde gegeben. In Abu Usamas Hadith wird es vom Propheten (Friede sei auf ihm) berichtet.`],
'https://sunnah.com/muslim:200d':[ `Muhammad ibn Abd al-A'la narrated to me. al-Mu'tamir narrated to us, from his father, from Anas, that the Prophet of Allah (peace be upon him) said, and he mentioned something like the hadith of Qatada from Anas.`, `Muhammad ibn Abd al-A'la überlieferte mir. al-Mu'tamir überlieferte uns, von seinem Vater, von Anas, dass der Prophet Allahs (Friede sei auf ihm) sagte und etwas Ähnliches wie den Hadith von Qatada von Anas erwähnte.`],
'https://sunnah.com/muslim:201':[ `Muhammad ibn Ahmad ibn Abi Khalaf narrated to me. Ruh narrated to us. Ibn Jurayj narrated to us. He said: Abu al-Zubayr informed me that he heard Jabir ibn Abdullah say, reporting from the Prophet (peace be upon him): Every prophet made a supplication for his community, and I have hidden my supplication as intercession for my community on the Day of Resurrection.`, `Muhammad ibn Ahmad ibn Abi Chalaf überlieferte mir. Ruh überlieferte uns. Ibn Dschuraidsch überlieferte uns. Er sagte: Abu az-Zubayr berichtete mir, dass er Dschabir ibn Abd Allah sagen hörte, vom Propheten (Friede sei auf ihm) berichtend: Jeder Prophet sprach ein Bittgebet für seine Gemeinschaft, und ich habe mein Bittgebet als Fürsprache für meine Gemeinschaft am Tag der Auferstehung verborgen.`],
'https://sunnah.com/muslim:202':[ `Yunus ibn Abd al-A'la al-Sadafi narrated to me. Ibn Wahb informed us. He said: Amr ibn al-Harith informed me that Bakr ibn Sawada narrated to him, from Abd al-Rahman ibn Jubayr, from Abdullah ibn Amr ibn al-As, that the Prophet recited Allah's saying about Ibrahim: (Quran 14:36) My Lord, they have led many people astray. Whoever follows me is truly of me. And Jesus, peace be upon him, said: (Quran 5:118) If You punish them, they are Your servants; and if You forgive them, You are truly the Mighty, the Wise. He raised his hands and said: O Allah, my community, my community. He wept. Allah, the Mighty and Majestic, said: Gabriel, go to Muhammad, while your Lord knows best, and ask him what makes him weep. Gabriel, peace and blessings be upon him, came to him and asked him, and the Messenger of Allah (peace be upon him) told him what he had said, though Allah knows best. Allah said: Gabriel, go to Muhammad and tell him: We will make you pleased concerning your community and will not distress you.`, `Yunus ibn Abd al-A'la as-Sadafi überlieferte mir. Ibn Wahb berichtete uns. Er sagte: Amr ibn al-Harith berichtete mir, dass Bakr ibn Sawada ihm von Abd ar-Rahman ibn Dschubayr, von Abd Allah ibn Amr ibn al-As, überlieferte, dass der Prophet die Worte Allahs über Ibrahim rezitierte: (Quran 14:36) Mein Herr, sie haben viele Menschen irregeführt. Wer mir folgt, gehört wahrlich zu mir. Und Jesus, Friede sei auf ihm, sagte: (Quran 5:118) Wenn Du sie bestrafst, so sind sie Deine Diener; und wenn Du ihnen vergibst, so bist Du wahrlich der Mächtige, der Weise. Er hob seine Hände und sagte: O Allah, meine Gemeinschaft, meine Gemeinschaft. Er weinte. Allah, der Mächtige und Erhabene, sagte: Gabriel, geh zu Muhammad, während dein Herr es am besten weiß, und frage ihn, was ihn weinen lässt. Gabriel, Friede und Segen seien auf ihm, kam zu ihm und fragte ihn. Der Gesandte Allahs (Friede sei auf ihm) teilte ihm mit, was er gesagt hatte, obwohl Allah es am besten weiß. Allah sagte: Gabriel, geh zu Muhammad und sage ihm: Wir werden dich in Bezug auf deine Gemeinschaft zufriedenstellen und dich nicht betrüben.`],
'https://sunnah.com/muslim:203':[ `Abu Bakr ibn Abi Shayba narrated to us. Affan narrated to us. Hammad ibn Salama narrated to us, from Thabit, from Anas, that a man said: Messenger of Allah, where is my father? He said: In the Fire. When the man turned away, he called him and said: My father and your father are in the Fire.`, `Abu Bakr ibn Abi Schayba überlieferte uns. Affan überlieferte uns. Hammad ibn Salama überlieferte uns, von Thabit, von Anas, dass ein Mann sagte: Gesandter Allahs, wo ist mein Vater? Er sagte: Im Feuer. Als der Mann sich abwandte, rief er ihn und sagte: Mein Vater und dein Vater sind im Feuer.`]
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,en:tr[r.url][0],de:tr[r.url][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-192-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-192-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
