import fs from "node:fs";

const all = JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-batch-100.json", "utf8")) as { id: string; url: string }[];
const keep = new Set(["4055", "4056", "4057", "4058", "4059", "4060", "4062", "4063", "4064", "4065"]);
const raw = all.filter((row) => keep.has(row.url.split(":").pop()!));
fs.writeFileSync("data/hadith-words-translations/codex-batch-100.json", JSON.stringify(raw, null, 2) + "\n", "utf8");

const t: Record<string, { en: string; de: string }> = {
  "4055": { en: String.raw`Abd Allah ibn Muhammad narrated to me. Marwan ibn Muawiya narrated to us. Hashim ibn Hashim al-Sadi narrated to us. He said: I heard Said ibn al-Musayyab say: I heard Sad ibn Abi Waqqas say: On the day of Uhud, the Prophet (peace be upon him) emptied his quiver before me and said: Shoot, may my father and mother be your ransom.`, de: String.raw`Abd Allah ibn Muhammad berichtete mir. Marwan ibn Muawiya überlieferte uns. Hashim ibn Hashim as-Sadi überlieferte uns. Er sagte: Ich hörte Said ibn al-Musayyab sagen: Ich hörte Sad ibn Abi Waqqas sagen: Am Tag von Uhud schüttete der Prophet (Friede sei auf ihm) seinen Köcher vor mir aus und sagte: Schieß, mögen mein Vater und meine Mutter dein Lösegeld sein.` },
  "4056": { en: String.raw`Musaddad narrated to us. Yahya narrated to us, from Yahya ibn Said, who said: I heard Said ibn al-Musayyab say: I heard Sad say: On the day of Uhud, the Prophet (peace be upon him) invoked both his parents for me.`, de: String.raw`Musaddad überlieferte uns. Yahya überlieferte uns, von Yahya ibn Said, der sagte: Ich hörte Said ibn al-Musayyab sagen: Ich hörte Sad sagen: Am Tag von Uhud rief der Prophet (Friede sei auf ihm) für mich seine beiden Eltern als Lösegeld an.` },
  "4057": { en: String.raw`Qutayba narrated to us. Layth narrated to us, from Yahya, from Ibn al-Musayyab, who said: Sad ibn Abi Waqqas, may Allah be pleased with him, said: The Messenger of Allah (peace be upon him) invoked both his parents for me on the day of Uhud. He meant when he said: May my father and mother be your ransom, while he was fighting.`, de: String.raw`Qutayba überlieferte uns. Layth überlieferte uns, von Yahya, von Ibn al-Musayyab, der sagte: Sad ibn Abi Waqqas, möge Allah mit ihm zufrieden sein, sagte: Der Gesandte Allahs (Friede sei auf ihm) rief am Tag von Uhud für mich seine beiden Eltern als Lösegeld an. Er meinte damit, als er sagte: Mögen mein Vater und meine Mutter dein Lösegeld sein, während er kämpfte.` },
  "4058": { en: String.raw`Abu Nuaim narrated to us. Misar narrated to us, from Sad, from Ibn Shaddad, who said: I never heard the Prophet (peace be upon him) invoke both his parents for anyone except Sad.`, de: String.raw`Abu Nuaym überlieferte uns. Misar überlieferte uns, von Sad, von Ibn Schaddad, der sagte: Ich hörte den Propheten (Friede sei auf ihm) für niemanden außer Sad seine beiden Eltern als Lösegeld anrufen.` },
  "4059": { en: String.raw`Yasara ibn Safwan narrated to us. Ibrahim narrated to us, from his father, from Abd Allah ibn Shaddad, from Ali, may Allah be pleased with him, who said: I never heard the Prophet (peace be upon him) invoke both his parents for anyone except Sad ibn Malik. I heard him say on the day of Uhud: O Sad, shoot, may my father and mother be your ransom.`, de: String.raw`Yasara ibn Safwan überlieferte uns. Ibrahim überlieferte uns, von seinem Vater, von Abd Allah ibn Schaddad, von Ali, möge Allah mit ihm zufrieden sein, der sagte: Ich hörte den Propheten (Friede sei auf ihm) für niemanden außer Sad ibn Malik seine beiden Eltern als Lösegeld anrufen. Ich hörte ihn am Tag von Uhud sagen: O Sad, schieß, mögen mein Vater und meine Mutter dein Lösegeld sein.` },
  "4060": { en: String.raw`Musa ibn Ismail narrated to us, from Mutamir, from his father, who said: Abu Uthman claimed that on some of those days when the Prophet (peace be upon him) was fighting, none remained with him except Talha and Sad, based on their report.`, de: String.raw`Musa ibn Ismail überlieferte uns, von Mutamir, von seinem Vater, der sagte: Abu Uthman behauptete, dass an einigen jener Tage, an denen der Prophet (Friede sei auf ihm) kämpfte, niemand außer Talha und Sad bei ihm blieb, wie aus ihrem Bericht hervorgeht.` },
  "4062": { en: String.raw`Abd Allah ibn Abi al-Aswad narrated to us. Hatim ibn Ismail narrated to us, from Muhammad ibn Yusuf, who said: I heard al-Saib ibn Yazid say: I accompanied Abd al-Rahman ibn Awf, Talha ibn Ubayd Allah, al-Miqdad, and Sad, may Allah be pleased with them. I never heard any of them narrate from the Prophet (peace be upon him), except that I heard Talha narrate about the day of Uhud.`, de: String.raw`Abd Allah ibn Abi al-Aswad überlieferte uns. Hatim ibn Ismail überlieferte uns, von Muhammad ibn Yusuf, der sagte: Ich hörte as-Saib ibn Yazid sagen: Ich begleitete Abd ar-Rahman ibn Awf, Talha ibn Ubayd Allah, al-Miqdad und Sad, möge Allah mit ihnen zufrieden sein. Ich hörte keinen von ihnen vom Propheten (Friede sei auf ihm) berichten, außer dass ich Talha über den Tag von Uhud berichten hörte.` },
  "4063": { en: String.raw`Abd Allah ibn Abi Shayba narrated to me. Waki narrated to us, from Ismail, from Qays, who said: I saw the paralyzed hand of Talha. He had protected the Prophet (peace be upon him) with it on the day of Uhud.`, de: String.raw`Abd Allah ibn Abi Schayba berichtete mir. Waki überlieferte uns, von Ismail, von Qays, der sagte: Ich sah die gelähmte Hand Talhas. Mit ihr hatte er den Propheten (Friede sei auf ihm) am Tag von Uhud geschützt.` },
  "4064": { en: String.raw`Abu Mamr narrated to us. Abd al-Warith narrated to us. Abd al-Aziz narrated to us, from Anas, may Allah be pleased with him, who said: When the day of Uhud came, the people fled from the Prophet (peace be upon him), while Abu Talha stood before the Prophet (peace be upon him), shielding him with his leather shield. Abu Talha was a strong archer who drew his bow powerfully. That day he broke two or three bows. If a man passed by carrying a quiver of arrows, he would say: Scatter them for Abu Talha. He said: The Prophet (peace be upon him) would look out at the people, and Abu Talha would say: May my father and mother be your ransom, do not raise your head, lest an arrow from the people strike you. My chest is before your chest. I saw Aisha bint Abi Bakr and Umm Sulaym, both with their garments tucked up. I could see their anklets as they carried water-skins on their backs, emptied them into the mouths of the people, then returned and filled them, then came back and emptied them into the mouths of the people. Abu Talha's sword fell from his hand twice or three times.`, de: String.raw`Abu Mamr überlieferte uns. Abd al-Warith überlieferte uns. Abd al-Aziz überlieferte uns, von Anas, möge Allah mit ihm zufrieden sein, der sagte: Als der Tag von Uhud kam, flohen die Menschen vor dem Propheten (Friede sei auf ihm), während Abu Talha vor dem Propheten (Friede sei auf ihm) stand und ihn mit seinem Lederschild schützte. Abu Talha war ein starker Bogenschütze, der seinen Bogen kraftvoll spannte. An jenem Tag zerbrach er zwei oder drei Bögen. Wenn ein Mann mit einem Köcher voller Pfeile an ihm vorbeikam, sagte er: Schütte sie für Abu Talha aus. Er sagte: Der Prophet (Friede sei auf ihm) blickte auf die Leute hinaus, und Abu Talha sagte: Mögen mein Vater und meine Mutter dein Lösegeld sein, hebe deinen Kopf nicht, damit dich kein Pfeil der Leute trifft. Meine Brust steht vor deiner Brust. Ich sah Aisha bint Abi Bakr und Umm Sulaym, beide mit hochgerafften Gewändern. Ich konnte ihre Fußkettchen sehen, während sie Wasserschläuche auf ihren Rücken trugen, sie in die Münder der Leute ausgossen, dann zurückgingen, sie füllten, wiederkamen und sie in die Münder der Leute ausgossen. Abu Talhas Schwert fiel ihm zwei- oder dreimal aus der Hand.` },
  "4065": { en: String.raw`Ubayd Allah ibn Said narrated to us. Abu Usama narrated to us, from Hisham ibn Urwa, from his father, from Aisha, may Allah be pleased with her, who said: When the day of Uhud came, the polytheists were defeated, and Iblis, may Allah's curse be upon him, shouted: O servants of Allah, watch your rear! The front ranks turned back and fought with the rear ranks. Hudhayfa saw his father al-Yaman and said: O servants of Allah, my father, my father! She said: By Allah, they did not stop until they killed him. Hudhayfa said: May Allah forgive you. Urwa said: By Allah, goodness remained in Hudhayfa until he joined Allah. The wording means: I perceived and knew, from insight into the matter; and I saw with the eye. It is also said with the same meaning.`, de: String.raw`Ubayd Allah ibn Said überlieferte uns. Abu Usama überlieferte uns, von Hisham ibn Urwa, von seinem Vater, von Aisha, möge Allah mit ihr zufrieden sein, die sagte: Als der Tag von Uhud kam, wurden die Götzendiener besiegt, und Iblis, Allahs Fluch sei auf ihm, rief: O Diener Allahs, achtet auf euren Rücken! Die vorderen Reihen kehrten um und kämpften mit den hinteren Reihen. Hudhayfa sah seinen Vater al-Yaman und sagte: O Diener Allahs, mein Vater, mein Vater! Sie sagte: Bei Allah, sie hörten nicht auf, bis sie ihn getötet hatten. Hudhayfa sagte: Möge Allah euch vergeben. Urwa sagte: Bei Allah, das Gute blieb in Hudhayfa, bis er zu Allah ging. Die Worterklärung bedeutet: Ich nahm wahr und wusste es, aus Einsicht in die Angelegenheit; und ich sah mit dem Auge. Es wird auch mit derselben Bedeutung gebraucht.` }
};

const out = raw.map((row) => {
  const n = row.url.split(":").pop()!;
  const v = t[n];
  if (!v) throw new Error("missing " + n);
  return { id: row.id, n, en: v.en, de: v.de };
});
fs.writeFileSync("data/hadith-words-translations/codex-out-100.json", JSON.stringify(out, null, 2) + "\n", "utf8");
console.log("wrote " + out.length + " translations");
