import fs from "node:fs";

const input = "data/hadith-words-translations/codex-batch-113.json";
const rows = JSON.parse(fs.readFileSync(input, "utf8"));
const t: Record<string, [string, string]> = {
  "4242": [
    "Muhammad ibn Bashshar narrated to us: Haramiyy narrated to us: Shu'bah narrated to us: Umara informed me, from Ikrima, from Aisha, may Allah be pleased with her, who said: When Khaybar was conquered, we said, 'Now we will eat our fill of dates.'",
    "Muhammad ibn Bashshar überlieferte uns: Haramiyy überlieferte uns: Shu'ba überlieferte uns: Umara berichtete mir von Ikrima, von Aisha, möge Allah mit ihr zufrieden sein, die sagte: Als Khaybar erobert worden war, sagten wir: „Jetzt werden wir uns an Datteln satt essen.“"
  ],
  "4243": [
    "Al-Hasan narrated to us: Qurrat ibn Habib narrated to us: Abd al-Rahman ibn Abd Allah ibn Dinar narrated to us, from his father, from Ibn Umar, who said: We did not eat our fill until we conquered Khaybar.",
    "Al-Hasan überlieferte uns: Qurrat ibn Habib überlieferte uns: Abd ar-Rahman ibn Abd Allah ibn Dinar überlieferte uns von seinem Vater, von Ibn Umar, der sagte: Wir aßen uns erst satt, nachdem wir Khaybar erobert hatten."
  ],
  "4244": [
    "Ismail narrated to us: Malik narrated to me, from Abd al-Majid ibn Suhayl, from Said ibn al-Musayyab, from Abu Said al-Khudri and Abu Hurayra, may Allah be pleased with them, that the Messenger of Allah, peace and blessings be upon him, appointed a man over Khaybar. He came to him with high-quality dates. The Messenger of Allah, peace and blessings be upon him, said, 'Are all the dates of Khaybar like this?' He replied, 'No, by Allah, O Messenger of Allah. We take one measure of these for two measures, and two measures for three.' He said, 'Do not do that. Sell the mixed dates for dirhams, then buy high-quality dates with the dirhams.'",
    "Ismail überlieferte uns: Malik überlieferte mir von Abd al-Majid ibn Suhayl, von Said ibn al-Musayyab, von Abu Said al-Khudri und Abu Huraira, möge Allah mit ihnen zufrieden sein, dass der Gesandte Allahs, Friede sei auf ihm, einen Mann mit der Verwaltung von Khaybar betraute. Dieser brachte ihm hochwertige Datteln. Der Gesandte Allahs, Friede sei auf ihm, sagte: „Sind alle Datteln von Khaybar so?“ Er antwortete: „Nein, bei Allah, o Gesandter Allahs. Wir nehmen für ein Maß davon zwei Maße und für zwei Maße drei.“ Er sagte: „Tu das nicht. Verkaufe die gemischten Datteln gegen Dirham und kaufe dann mit den Dirham hochwertige Datteln.“"
  ],
  "4246": [
    "Abd al-Aziz ibn Muhammad narrated from Abd al-Majid, from Said, that Abu Said and Abu Hurayra told them: The Prophet, peace and blessings be upon him, sent a man from the Ansar of Banu Adi to Khaybar and appointed him over it. The same report was narrated from Abd al-Majid, from Abu Salih al-Samman, from Abu Hurayra and Abu Said.",
    "Abd al-Aziz ibn Muhammad überlieferte von Abd al-Majid, von Said, dass Abu Said und Abu Huraira ihnen berichteten: Der Prophet, Friede sei auf ihm, sandte einen Mann von den Ansar aus Banu Adi nach Khaybar und betraute ihn damit. Derselbe Bericht wurde von Abd al-Majid, von Abu Salih as-Samman, von Abu Huraira und Abu Said überliefert."
  ],
  "4248": [
    "Musa ibn Ismail narrated to us: Juwayriya narrated to us, from Nafi, from Abd Allah, who said: The Prophet, peace and blessings be upon him, gave the Jews of Khaybar the right to work its land and cultivate it, while they received half of what it produced.",
    "Musa ibn Ismail überlieferte uns: Juwayriya überlieferte uns von Nafi, von Abd Allah, der sagte: Der Prophet, Friede sei auf ihm, überließ den Juden von Khaybar das Recht, ihr Land zu bearbeiten und zu bebauen, wobei ihnen die Hälfte dessen gehörte, was es hervorbrachte."
  ],
  "4249": [
    "Abd Allah ibn Yusuf narrated to us: al-Layth narrated to us: Said narrated to me, from Abu Hurayra, who said: When Khaybar was conquered, a poisoned sheep was given as a gift to the Messenger of Allah, peace and blessings be upon him.",
    "Abd Allah ibn Yusuf überlieferte uns: al-Layth überlieferte uns: Said berichtete mir von Abu Huraira, der sagte: Als Khaybar erobert worden war, wurde dem Gesandten Allahs, Friede sei auf ihm, ein vergiftetes Schaf geschenkt."
  ],
  "4250": [
    "Musaddad narrated to us: Yahya ibn Said narrated to us: Sufyan ibn Said narrated to us: Abd Allah ibn Dinar narrated to us, from Ibn Umar, may Allah be pleased with them, who said: The Messenger of Allah, peace and blessings be upon him, appointed Usama over some people. They criticized his appointment, so he said, 'If you criticize his appointment, you previously criticized the appointment of his father. By Allah, he was worthy of command, and he was among the people most beloved to me. This one is among the people most beloved to me after him.'",
    "Musaddad überlieferte uns: Yahya ibn Said überlieferte uns: Sufyan ibn Said überlieferte uns: Abd Allah ibn Dinar überlieferte uns von Ibn Umar, möge Allah mit ihnen zufrieden sein, der sagte: Der Gesandte Allahs, Friede sei auf ihm, setzte Usama über einige Menschen ein. Sie kritisierten seine Ernennung, worauf er sagte: „Wenn ihr seine Ernennung kritisiert, habt ihr zuvor auch die Ernennung seines Vaters kritisiert. Bei Allah, er war für das Amt geeignet und gehörte zu den Menschen, die ich am meisten liebte. Dieser hier gehört nach ihm zu den Menschen, die ich am meisten liebe.“"
  ],
  "4251": [
    "Ubayd Allah ibn Musa narrated from Israil, from Abu Ishaq, from al-Bara, may Allah be pleased with him, who said: When the Prophet, peace and blessings be upon him, performed the Umrah of al-Qada, the people of Mecca refused to let him enter Mecca until they agreed with him that he would stay there for three days. When they wrote the document, they wrote: 'This is what Muhammad, the Messenger of Allah, has agreed.' They said, 'We do not approve of this. If we knew that you were the Messenger of Allah, we would not prevent you from anything, but you are Muhammad ibn Abd Allah.' He said, 'I am the Messenger of Allah and I am Muhammad ibn Abd Allah.' Then he said to Ali, 'Erase the words “Messenger of Allah.”' Ali said, 'No, by Allah, I will never erase you.' The Messenger of Allah, peace and blessings be upon him, took the document, though he did not write well, and wrote: 'This is what Muhammad ibn Abd Allah has agreed: no weapon shall enter Mecca except in its sheath; no one from its people shall leave with him even if he wishes to follow him; and he shall not prevent any of his companions from staying there if they wish.' When he entered it and the appointed time passed, they came to Ali and said, 'Tell your companion to leave us, for the appointed time has passed.' The Prophet, peace and blessings be upon him, left, and Hamza's daughter followed him, calling, 'Uncle, uncle!' Ali took her hand and said to Fatima, peace be upon her, 'Take your uncle's daughter.' Ali, Zayd and Ja'far disputed about her. Ali said, 'I have more right to her; she is my uncle's daughter.' Ja'far said, 'She is my uncle's daughter, and her maternal aunt is my wife.' Zayd said, 'She is my brother's daughter.' The Prophet, peace and blessings be upon him, judged her for her maternal aunt and said, 'The maternal aunt has the status of the mother.' He said to Ali, 'You are from me and I am from you.' To Ja'far he said, 'You resemble me in appearance and character.' To Zayd he said, 'You are our brother and our freedman.'",
    "Ubayd Allah ibn Musa überlieferte von Israil, von Abu Ishaq, von al-Bara, möge Allah mit ihm zufrieden sein, der sagte: Als der Prophet, Friede sei auf ihm, die Umra des Nachholens vollzog, weigerten sich die Bewohner von Mekka, ihn Mekka betreten zu lassen, bis sie mit ihm vereinbarten, dass er dort drei Tage bleiben würde. Als sie die Vereinbarung niederschrieben, schrieben sie: „Dies ist, was Muhammad, der Gesandte Allahs, vereinbart hat.“ Sie sagten: „Dem stimmen wir nicht zu. Wenn wir wüssten, dass du der Gesandte Allahs bist, würden wir dich an nichts hindern; doch du bist Muhammad ibn Abd Allah.“ Er sagte: „Ich bin der Gesandte Allahs und ich bin Muhammad ibn Abd Allah.“ Dann sagte er zu Ali: „Lösche die Worte ,Gesandter Allahs‘.“ Ali sagte: „Nein, bei Allah, ich werde dich niemals auslöschen.“ Der Gesandte Allahs, Friede sei auf ihm, nahm das Dokument, obwohl er nicht gut schreiben konnte, und schrieb: „Dies ist, was Muhammad ibn Abd Allah vereinbart hat: Keine Waffe darf Mekka betreten, außer in ihrer Scheide; niemand von seinen Bewohnern darf mit ihm hinausgehen, selbst wenn er ihm folgen möchte; und er darf keinen seiner Gefährten daran hindern, dort zu bleiben, wenn sie dies wünschen.“ Als er es betreten hatte und die Frist verstrichen war, kamen sie zu Ali und sagten: „Sag deinem Gefährten, dass er uns verlassen soll, denn die Frist ist abgelaufen.“ Der Prophet, Friede sei auf ihm, zog aus, und die Tochter Hamzas folgte ihm und rief: „Onkel, Onkel!“ Ali nahm ihre Hand und sagte zu Fatima, Friede sei auf ihr: „Nimm die Tochter deines Onkels.“ Ali, Zayd und Ja'far stritten um sie. Ali sagte: „Ich habe mehr Recht auf sie; sie ist die Tochter meines Onkels.“ Ja'far sagte: „Sie ist die Tochter meines Onkels, und ihre Tante mütterlicherseits ist meine Ehefrau.“ Zayd sagte: „Sie ist die Tochter meines Bruders.“ Der Prophet, Friede sei auf ihm, sprach sie ihrer Tante mütterlicherseits zu und sagte: „Die Tante mütterlicherseits hat den Rang der Mutter.“ Er sagte zu Ali: „Du bist von mir und ich bin von dir.“ Zu Ja'far sagte er: „Du ähnelst mir in Aussehen und Charakter.“ Zu Zayd sagte er: „Du bist unser Bruder und unser Freigelassener.“"
  ],
  "4248x": ["", ""],
  "4252": [
    "Abd al-Aziz ibn Abd Allah narrated to us: Malik narrated to us, from Zayd ibn Aslam, from his father, from Umar ibn al-Khattab, who said: The Messenger of Allah, peace and blessings be upon him, gave the Jews of Khaybar the condition that we would expel them whenever we wished.",
    "Abd al-Aziz ibn Abd Allah überlieferte uns: Malik überlieferte uns von Zayd ibn Aslam, von seinem Vater, von Umar ibn al-Khattab, der sagte: Der Gesandte Allahs, Friede sei auf ihm, vereinbarte mit den Juden von Khaybar, dass wir sie jederzeit ausweisen würden, wenn wir dies wollten."
  ],
  "4253": [
    "Musa narrated to us: Abu Awanah narrated to us, from Husayn, from Mujahid, from Ibn Umar, who said: The Messenger of Allah, peace and blessings be upon him, dealt with the people of Khaybar on the condition that they would work it and receive half of its produce. The Prophet, peace and blessings be upon him, used to give his wives one hundred wasqs: eighty of dates and twenty of barley. When Umar became caliph, he gave the choice to the wives of the Prophet, peace and blessings be upon him, to receive the land and water as an allotment or the wasqs. Aisha and Hafsa chose the water and land.",
    "Musa überlieferte uns: Abu Awana überlieferte uns von Husain, von Mujahid, von Ibn Umar, der sagte: Der Gesandte Allahs, Friede sei auf ihm, traf mit den Bewohnern von Khaybar die Vereinbarung, dass sie das Land bearbeiten und die Hälfte seines Ertrags erhalten würden. Der Prophet, Friede sei auf ihm, gab seinen Ehefrauen jeweils hundert Wasq: achtzig Wasq Datteln und zwanzig Wasq Gerste. Als Umar Kalif wurde, ließ er den Ehefrauen des Propheten, Friede sei auf ihm, die Wahl, entweder Land und Wasser als Anteil oder die Wasq zu erhalten. Aisha und Hafsa wählten Wasser und Land."
  ],
  "4255": [
    "Abd Allah ibn Maslamah narrated to us: Abd al-Aziz ibn Abi Hazim narrated to us, from his father, from Sahl ibn Sad, who said: The Prophet, peace and blessings be upon him, said on the day of Khaybar, 'Tomorrow I will give this banner to a man through whose hands Allah will grant victory. He loves Allah and His Messenger, and Allah and His Messenger love him.' The people spent the night wondering who would receive it. In the morning they went to the Messenger of Allah, each hoping to be given it. He said, 'Where is Ali ibn Abi Talib?' They said, 'He has eye trouble.' He was brought, and the Messenger of Allah, peace and blessings be upon him, spat into his eyes and supplicated for him, and he recovered as if he had never suffered. He gave him the banner and said, 'Advance calmly until you reach their territory, then invite them to Islam and tell them what Allah has made obligatory for them. By Allah, if Allah guides one man through you, that is better for you than red camels.'",
    "Abd Allah ibn Maslama überlieferte uns: Abd al-Aziz ibn Abi Hazim überlieferte uns von seinem Vater, von Sahl ibn Sad, der sagte: Der Prophet, Friede sei auf ihm, sagte am Tag von Khaybar: „Morgen werde ich dieses Banner einem Mann geben, durch dessen Hände Allah den Sieg gewähren wird. Er liebt Allah und Seinen Gesandten, und Allah und Sein Gesandter lieben ihn.“ Die Menschen verbrachten die Nacht damit, sich zu fragen, wem es gegeben werden würde. Am Morgen gingen sie zum Gesandten Allahs, jeder in der Hoffnung, es zu erhalten. Er sagte: „Wo ist Ali ibn Abi Talib?“ Sie sagten: „Er hat Beschwerden an den Augen.“ Er wurde gebracht, und der Gesandte Allahs, Friede sei auf ihm, spuckte in seine Augen und betete für ihn, worauf er gesund wurde, als hätte er nie Beschwerden gehabt. Er gab ihm das Banner und sagte: „Zieh ruhig vor, bis du ihr Gebiet erreichst. Dann lade sie zum Islam ein und teile ihnen mit, was Allah ihnen verpflichtend gemacht hat. Bei Allah, wenn Allah durch dich einen einzigen Menschen rechtleitet, ist das besser für dich als rote Kamele.“"
  ],
  "4256": [
    "Abu al-Walid narrated to us: Layth narrated to us, from Ibn Shihab, from Urwah, from Aisha, may Allah be pleased with her, who said: The Prophet, peace and blessings be upon him, performed tawaf in the Farewell Pilgrimage, jogging during the first three circuits and walking during the remaining four. He also walked between Safa and Marwa.",
    "Abu al-Walid überlieferte uns: Layth überlieferte uns von Ibn Shihab, von Urwa, von Aisha, möge Allah mit ihr zufrieden sein, die sagte: Der Prophet, Friede sei auf ihm, vollzog den Tawaf bei der Abschiedspilgerfahrt. In den ersten drei Umrundungen lief er zügig und in den übrigen vier ging er. Auch zwischen Safa und Marwa ging er."
  ],
  "4257": [
    "Abd Allah ibn Yusuf narrated to us: Malik narrated to us, from Ibn Shihab, from Salim ibn Abd Allah, from his father, who said: I saw the Messenger of Allah, peace and blessings be upon him, arrive in Mecca, touch the Black Stone at the beginning of his tawaf, and jog in the first three circuits of the tawaf.",
    "Abd Allah ibn Yusuf überlieferte uns: Malik überlieferte uns von Ibn Shihab, von Salim ibn Abd Allah, von seinem Vater, der sagte: Ich sah, wie der Gesandte Allahs, Friede sei auf ihm, in Mekka ankam, zu Beginn seines Tawaf den Schwarzen Stein berührte und in den ersten drei Umrundungen des Tawaf zügig lief."
  ],
  "4258": [
    "Qutaybah narrated to us: Jarir narrated to us, from Mansur, from Mujahid, from Tawus, from Ibn Abbas, who said: The Prophet, peace and blessings be upon him, married Maymunah while he was in ihram. He consummated the marriage while he was no longer in ihram.",
    "Qutaiba überlieferte uns: Jarir überlieferte uns von Mansur, von Mujahid, von Tawus, von Ibn Abbas, der sagte: Der Prophet, Friede sei auf ihm, heiratete Maymuna, während er sich im Ihram befand. Er vollzog die Ehe, als er nicht mehr im Ihram war."
  ],
  "4259": [
    "Abd Allah ibn Yusuf narrated to us: Malik narrated to us, from Rabi'ah ibn Abi Abd al-Rahman, from Sulayman ibn Yasar, from Abu Rafi, who said: The Messenger of Allah, peace and blessings be upon him, married Maymunah while he was in ihram, during the Umrah of al-Qada.",
    "Abd Allah ibn Yusuf überlieferte uns: Malik überlieferte uns von Rabia ibn Abi Abd ar-Rahman, von Sulayman ibn Yasar, von Abu Rafi, der sagte: Der Gesandte Allahs, Friede sei auf ihm, heiratete Maymuna, während er sich im Ihram befand, bei der Umra des Nachholens."
  ],
  "4260": [
    "Muhammad ibn Bashshar narrated to us: Ghundar narrated to us: Shu'bah narrated to us, from Abu Ishaq, from al-Bara, who said: The Prophet, peace and blessings be upon him, performed Umrah in Dhu al-Qadah, and the people of Mecca made a condition that he would stay there for three days. When they wrote the document, they did not write 'Muhammad, the Messenger of Allah'; they wrote 'This is what Muhammad ibn Abd Allah has agreed.'",
    "Muhammad ibn Bashshar überlieferte uns: Ghundar überlieferte uns: Shu'ba überlieferte uns von Abu Ishaq, von al-Bara, der sagte: Der Prophet, Friede sei auf ihm, vollzog im Monat Dhu l-Qada eine Umra, und die Bewohner von Mekka stellten die Bedingung, dass er dort drei Tage bleiben würde. Als sie die Vereinbarung niederschrieben, schrieben sie nicht „Muhammad, der Gesandte Allahs“, sondern: „Dies ist, was Muhammad ibn Abd Allah vereinbart hat.“"
  ],
  "4261": [
    "Abd Allah ibn Maslamah narrated to us: Malik narrated to us, from Ibn Shihab, from Urwah, from Aisha, who said: The Prophet, peace and blessings be upon him, performed the Umrah of al-Qada in Dhu al-Qadah.",
    "Abd Allah ibn Maslama überlieferte uns: Malik überlieferte uns von Ibn Shihab, von Urwa, von Aisha, die sagte: Der Prophet, Friede sei auf ihm, vollzog die Umra des Nachholens im Monat Dhu l-Qada."
  ],
  "4262": [
    "Abd Allah ibn Yusuf narrated to us: Malik narrated to us, from Hisham, from his father, from Aisha, that the Messenger of Allah, peace and blessings be upon him, died when Abu Bakr was at al-Sunh. Ismail said: That means al-Awali.",
    "Abd Allah ibn Yusuf überlieferte uns: Malik überlieferte uns von Hisham, von seinem Vater, von Aisha, dass der Gesandte Allahs, Friede sei auf ihm, starb, während Abu Bakr in as-Sunh war. Ismail sagte: Damit ist al-Awali gemeint."
  ],
  "4263": [
    "Abd Allah ibn Maslamah narrated to us: Malik narrated to us, from Ibn Shihab, from Urwah, from Aisha, who said: The Messenger of Allah, peace and blessings be upon him, died while Abu Bakr was at al-Sunh. Umar stood up and said, 'By Allah, the Messenger of Allah has not died.' Umar said, 'By Allah, it occurred to me that he would send him forward and he would cut off the hands and legs of some people.' Abu Bakr came and uncovered the Prophet's face, kissed him between the eyes, and said, 'O my father, may my father be sacrificed for you! You are good in life and in death. By the One in whose hand is my soul, Allah will never make you taste two deaths.' Then he went out and said, 'O one who swears an oath, be patient.' When Abu Bakr spoke, Umar sat down. Abu Bakr praised Allah and said, 'Whoever worships Muhammad, Muhammad has died; whoever worships Allah, Allah is Living and does not die.' Then he recited: 'Muhammad is only a messenger; messengers passed away before him. If he dies or is killed, will you turn back on your heels?' (Quran 3:144). The people began to weep loudly as if they had never experienced such weeping before. Anas ibn Malik said: On the day he entered Medina, everything in it shone; on the day he died, everything in it became dark. We had scarcely shaken the dust from our hands after burying the Messenger of Allah, peace and blessings be upon him, before our hearts changed.",
    "Abd Allah ibn Maslama überlieferte uns: Malik überlieferte uns von Ibn Shihab, von Urwa, von Aisha, die sagte: Der Gesandte Allahs, Friede sei auf ihm, starb, während Abu Bakr in as-Sunh war. Umar stand auf und sagte: „Bei Allah, der Gesandte Allahs ist nicht gestorben.“ Umar sagte: „Bei Allah, mir kam der Gedanke, dass er ihn vorschicken und dieser einigen Menschen Hände und Füße abschlagen würde.“ Abu Bakr kam, enthüllte das Gesicht des Propheten, küsste ihn zwischen die Augen und sagte: „O mein Vater, möge mein Vater für dich geopfert werden! Du bist im Leben und im Tod gut. Bei Dem, in Dessen Hand meine Seele ist, Allah wird dich niemals zwei Tode kosten lassen.“ Dann ging er hinaus und sagte: „O du, der du schwörst, sei geduldig.“ Als Abu Bakr sprach, setzte Umar sich. Abu Bakr pries Allah und sagte: „Wer Muhammad verehrt, so ist Muhammad gestorben; wer Allah verehrt, so ist Allah lebendig und stirbt nicht.“ Dann rezitierte er: „Muhammad ist nur ein Gesandter; Gesandte sind vor ihm dahingegangen. Wenn er stirbt oder getötet wird, werdet ihr dann auf euren Fersen umkehren?“ (Quran 3:144). Die Menschen begannen laut zu weinen, als hätten sie nie zuvor so geweint. Anas ibn Malik sagte: An dem Tag, an dem er Medina betrat, strahlte alles darin; an dem Tag, an dem er starb, wurde alles darin dunkel. Kaum hatten wir nach der Beerdigung des Gesandten Allahs, Friede sei auf ihm, den Staub von unseren Händen geschüttelt, da veränderten sich bereits unsere Herzen."
  ],
  "4264": [
    "Muhammad ibn al-Muthanna narrated to us: Yahya narrated to us: Hisham narrated to us, who said: My father informed me, from Aisha, that the Prophet, peace and blessings be upon him, died while Abu Bakr was at al-Sunh. Ismail said: That means al-Awali. Umar stood and said, 'By Allah, the Messenger of Allah has not died.'",
    "Muhammad ibn al-Muthanna überlieferte uns: Yahya überlieferte uns: Hisham überlieferte uns, der sagte: Mein Vater berichtete mir von Aisha, dass der Prophet, Friede sei auf ihm, starb, während Abu Bakr in as-Sunh war. Ismail sagte: Damit ist al-Awali gemeint. Umar stand auf und sagte: „Bei Allah, der Gesandte Allahs ist nicht gestorben.“"
  ],
  "4265": [
    "Abd Allah ibn Muhammad narrated to us: Sufyan narrated to us, from al-Zuhri, from Said ibn al-Musayyab, from Jubayr ibn Mutim, who said: A woman came to the Prophet, peace and blessings be upon him, and he told her to return to him. She said, 'What if I come and do not find you?' It was as if she meant death. He said, 'If you do not find me, then go to Abu Bakr.'",
    "Abd Allah ibn Muhammad überlieferte uns: Sufyan überlieferte uns von az-Zuhri, von Said ibn al-Musayyab, von Jubair ibn Mutim, der sagte: Eine Frau kam zum Propheten, Friede sei auf ihm, und er sagte ihr, sie solle zu ihm zurückkehren. Sie sagte: „Was ist, wenn ich komme und dich nicht vorfinde?“ Es war, als meinte sie den Tod. Er sagte: „Wenn du mich nicht vorfindest, dann geh zu Abu Bakr.“"
  ],
  "4266": [
    "Abd Allah ibn Muhammad narrated to us: Sufyan narrated to us, from Hisham, from his father, from Aisha, that the Prophet, peace and blessings be upon him, became ill and asked, 'Has the people prayed?' They said, 'No, they are waiting for you.' He said, 'Put water in the basin for me.' She did so, and he washed, but he fainted. When he recovered, he asked again, and she did the same several times. Finally he said, 'Tell Abu Bakr to lead the people in prayer.'",
    "Abd Allah ibn Muhammad überlieferte uns: Sufyan überlieferte uns von Hisham, von seinem Vater, von Aisha, dass der Prophet, Friede sei auf ihm, krank wurde und fragte: „Haben die Menschen gebetet?“ Sie sagten: „Nein, sie warten auf dich.“ Er sagte: „Stellt mir Wasser in das Becken.“ Sie tat es, und er wusch sich, wurde aber ohnmächtig. Als er wieder zu sich kam, fragte er erneut, und sie tat dasselbe mehrmals. Schließlich sagte er: „Sagt Abu Bakr, dass er die Menschen im Gebet führen soll.“"
  ],
  "4267": [
    "Abu al-Yaman narrated to us: Shuayb narrated to us, from al-Zuhri, who said: Anas ibn Malik informed me that the Muslims, while in the dawn prayer on Monday and Abu Bakr was leading them, saw the Prophet, peace and blessings be upon him, uncover the curtain of Aisha's room. He looked at them while standing, and his face was like a page of the Quran. He smiled and almost made us lose our prayer from joy. Abu Bakr stepped back, thinking that the Prophet wanted to come out for prayer. The Prophet gestured to them to complete their prayer and let the curtain fall. He died that day.",
    "Abu al-Yaman überlieferte uns: Shu'aib überlieferte uns von az-Zuhri, der sagte: Anas ibn Malik berichtete mir, dass die Muslime im Morgengebet am Montag, während Abu Bakr sie führte, den Propheten, Friede sei auf ihm, sahen, wie er den Vorhang des Zimmers von Aisha öffnete. Er blickte im Stehen zu ihnen, und sein Gesicht war wie eine Seite des Quran. Er lächelte, und vor Freude hätten wir beinahe unser Gebet verloren. Abu Bakr trat zurück, weil er dachte, der Prophet wolle zum Gebet herauskommen. Der Prophet gab ihnen ein Zeichen, ihr Gebet zu vollenden, und ließ den Vorhang fallen. Er starb an diesem Tag."
  ],
  "4268": [
    "Abd Allah ibn Muhammad narrated to us: Sufyan narrated to us, from Hisham, from his father, from Aisha, who said: The Prophet, peace and blessings be upon him, ordered Abu Bakr to lead the people in prayer during his illness. Abu Bakr used to lead them, but the Prophet found some improvement in himself and came out. When Abu Bakr saw him, he stepped back, but the Prophet gestured to him to remain. The Prophet sat beside Abu Bakr, and Abu Bakr followed the prayer of the Prophet while the people followed the prayer of Abu Bakr.",
    "Abd Allah ibn Muhammad überlieferte uns: Sufyan überlieferte uns von Hisham, von seinem Vater, von Aisha, die sagte: Der Prophet, Friede sei auf ihm, befahl Abu Bakr, die Menschen während seiner Krankheit im Gebet zu führen. Abu Bakr führte sie, doch der Prophet fühlte sich etwas besser und kam heraus. Als Abu Bakr ihn sah, trat er zurück, aber der Prophet gab ihm ein Zeichen, zu bleiben. Der Prophet setzte sich neben Abu Bakr, und Abu Bakr folgte dem Gebet des Propheten, während die Menschen dem Gebet Abu Bakrs folgten."
  ],
  "4269": [
    "Abd Allah ibn Muhammad narrated to us: Sufyan narrated to us, from al-Zuhri, from Ata ibn Yazid, from Usama ibn Zayd, who said: The Prophet, peace and blessings be upon him, sent us to al-Huraqat. We attacked them at dawn and defeated them. I and an Ansari man caught one of them. When we overcame him, he said, 'There is no deity except Allah.' The Ansari held back, but I struck him with my spear until I killed him. When we came to the Prophet, peace and blessings be upon him, he heard about it and said, 'O Usama, did you kill him after he said there is no deity except Allah?' I said, 'He only said it to protect himself.' He kept repeating it until I wished I had not accepted Islam before that day.",
    "Abd Allah ibn Muhammad überlieferte uns: Sufyan überlieferte uns von az-Zuhri, von Ata ibn Yazid, von Usama ibn Zayd, der sagte: Der Prophet, Friede sei auf ihm, sandte uns nach al-Huraqat. Wir griffen sie im Morgengrauen an und besiegten sie. Ein Ansari und ich holten einen von ihnen ein. Als wir ihn überwältigt hatten, sagte er: „Es gibt keine Gottheit außer Allah.“ Der Ansari hielt inne, doch ich stieß mit meinem Speer nach ihm, bis ich ihn tötete. Als wir zum Propheten, Friede sei auf ihm, kamen, erfuhr er davon und sagte: „O Usama, hast du ihn getötet, nachdem er gesagt hatte: Es gibt keine Gottheit außer Allah?“ Ich sagte: „Er sagte es nur, um sich zu schützen.“ Er wiederholte dies so lange, bis ich wünschte, ich hätte den Islam vor jenem Tag nicht angenommen."
  ],
  "4270": [
    "Muhammad ibn Abd Allah narrated to us: Hammad ibn Musaddah narrated to us, from Yazid ibn Abi Ubayd, from Salama ibn al-Akwa, who said: I went on seven expeditions with the Prophet, peace and blessings be upon him, and I went on seven expeditions with Ibn Haritha, whom he appointed over us.",
    "Muhammad ibn Abd Allah überlieferte uns: Hammad ibn Musadda überlieferte uns von Yazid ibn Abi Ubaid, von Salama ibn al-Akwa, der sagte: Ich nahm mit dem Propheten, Friede sei auf ihm, an sieben Feldzügen teil und nahm mit Ibn Haritha an sieben Feldzügen teil, den er über uns eingesetzt hatte."
  ],
  "4271": [
    "Muhammad ibn Abd Allah narrated to us: Hammad ibn Musaddah narrated to us, from Yazid, from Salama, who said: I fought with the Prophet, peace and blessings be upon him, seven expeditions. He also mentioned Khaybar, Hudaybiyyah, the day of Hunayn and the day of the Battle of the Qarad. Yazid said: I forgot the rest of them.",
    "Muhammad ibn Abd Allah überlieferte uns: Hammad ibn Musadda überlieferte uns von Yazid, von Salama, der sagte: Ich kämpfte mit dem Propheten, Friede sei auf ihm, in sieben Feldzügen. Er erwähnte außerdem Khaybar, Hudaybiyya, den Tag von Hunain und den Tag des Feldzugs von al-Qarad. Yazid sagte: Die übrigen habe ich vergessen."
  ],
  "4272": [
    "Abu Asim al-Dahhak ibn Makhlad narrated to us: Yazid narrated to us, from Salama ibn al-Akwa, who said: I took part in seven expeditions with the Prophet, peace and blessings be upon him, and I took part with Ibn Haritha when he appointed him over us.",
    "Abu Asim ad-Dahhak ibn Makhlad überlieferte uns: Yazid überlieferte uns von Salama ibn al-Akwa, der sagte: Ich nahm mit dem Propheten, Friede sei auf ihm, an sieben Feldzügen teil und nahm mit Ibn Haritha teil, als er ihn über uns eingesetzt hatte."
  ],
  "4273": [
    "Muhammad ibn Abd Allah narrated to us: Hammad ibn Masadah narrated to us, from Yazid ibn Abi Ubayd, from Salama ibn al-Akwa, who said: I took part in seven expeditions with the Prophet, peace and blessings be upon him. He mentioned Khaybar, Hudaybiyyah, the day of Hunayn and the day of the Battle of the Qarad. Yazid said: I forgot the rest of them.",
    "Muhammad ibn Abd Allah überlieferte uns: Hammad ibn Masada überlieferte uns von Yazid ibn Abi Ubaid, von Salama ibn al-Akwa, der sagte: Ich nahm mit dem Propheten, Friede sei auf ihm, an sieben Feldzügen teil. Er erwähnte Khaybar, Hudaybiyya, den Tag von Hunain und den Tag des Feldzugs von al-Qarad. Yazid sagte: Die übrigen habe ich vergessen."
  ],
  "4274": [
    "Qutaybah narrated to us: Sufyan narrated to us, from Amr ibn Dinar, who said: al-Hasan ibn Muhammad informed me that he heard Ubayd Allah ibn Abi Rafi say: I heard Ali, may Allah be pleased with him, say: The Messenger of Allah, peace and blessings be upon him, sent me, al-Zubayr and al-Miqdad and said, 'Go until you reach Rawdat Khakh, for there is a woman there carrying a letter. Take it from her.' We set out, our horses carrying us swiftly, until we reached the garden. We said to her, 'Bring out the letter.' She said, 'I have no letter.' We said, 'You will bring it out, or we will remove your clothes.' She took it out from her braid, and we brought it to the Messenger of Allah, peace and blessings be upon him. It contained a letter from Hatib ibn Abi Baltaa to some polytheists in Mecca, telling them about some of the Messenger of Allah's plans. The Messenger of Allah, peace and blessings be upon him, said, 'O Hatib, what is this?' He said, 'Do not hasten against me, O Messenger of Allah. I was a man closely attached to Quraysh, meaning I was their ally, but I was not one of them. The emigrants who are with you have relatives who protect their families and property in Mecca, so I wanted to gain a hand among them that would protect my relatives. I did not do it out of apostasy from my religion or approval of disbelief after Islam.' The Messenger of Allah, peace and blessings be upon him, said, 'He has spoken the truth.' Umar said, 'O Messenger of Allah, let me strike the neck of this hypocrite.' He said, 'He took part in Badr. How do you know? Perhaps Allah looked at the people of Badr and said: Do whatever you wish; I have forgiven you.' Then Allah revealed the verse: 'O you who believe, do not take My enemies and your enemies as allies, offering them affection' up to 'then he has strayed from the right path.' (Quran 60:1).",
    "Qutaiba überlieferte uns: Sufyan überlieferte uns von Amr ibn Dinar, der sagte: al-Hasan ibn Muhammad berichtete mir, dass er Ubaid Allah ibn Abi Rafi sagen hörte: Ich hörte Ali, möge Allah mit ihm zufrieden sein, sagen: Der Gesandte Allahs, Friede sei auf ihm, sandte mich, az-Zubair und al-Miqdad aus und sagte: „Geht, bis ihr Rawdat Khakh erreicht; dort befindet sich eine Frau, die einen Brief bei sich trägt. Nehmt ihn ihr ab.“ Wir machten uns auf den Weg, und unsere Pferde trugen uns rasch, bis wir den Garten erreichten. Wir sagten zu ihr: „Hol den Brief heraus.“ Sie sagte: „Ich habe keinen Brief.“ Wir sagten: „Du wirst ihn herausgeben, oder wir werden dir die Kleidung ausziehen.“ Da holte sie ihn aus ihrem Haargeflecht hervor, und wir brachten ihn zum Gesandten Allahs, Friede sei auf ihm. Darin befand sich ein Brief von Hatib ibn Abi Baltaa an einige Götzendiener in Mekka, in dem er ihnen von einigen Vorhaben des Gesandten Allahs berichtete. Der Gesandte Allahs, Friede sei auf ihm, sagte: „O Hatib, was ist das?“ Er sagte: „Übereile nichts gegen mich, o Gesandter Allahs. Ich war ein Mann, der eng mit Quraisch verbunden war, das heißt, ich war ihr Verbündeter, aber ich gehörte nicht zu ihnen. Die Auswanderer, die bei dir sind, haben Verwandte, die ihre Familien und ihr Eigentum in Mekka schützen. Deshalb wollte ich bei ihnen eine Hand gewinnen, die meine Verwandten schützen würde. Ich tat dies weder aus Abfall von meiner Religion noch aus Zustimmung zum Unglauben nach dem Islam.“ Der Gesandte Allahs, Friede sei auf ihm, sagte: „Er hat die Wahrheit gesprochen.“ Umar sagte: „O Gesandter Allahs, erlaube mir, den Hals dieses Heuchlers zu schlagen.“ Er sagte: „Er hat an Badr teilgenommen. Woher willst du wissen? Vielleicht hat Allah auf die Menschen von Badr geblickt und gesagt: ,Tut, was ihr wollt; Ich habe euch vergeben.‘“ Dann offenbarte Allah den Vers: „O ihr, die ihr glaubt, nehmt Meine Feinde und eure Feinde nicht zu Verbündeten, indem ihr ihnen Zuneigung entgegenbringt“, bis zu: „Dann ist er vom geraden Weg abgeirrt.“ (Quran 60:1)."
  ]
};
Object.assign(t, {
  "4252": ["Muhammad ibn Rafi narrated to me: Surayj narrated to us: Fulayh narrated to us. Muhammad ibn al-Husayn ibn Ibrahim also narrated to me, from his father, from Fulayh ibn Sulayman, from Nafi, from Ibn Umar, may Allah be pleased with them, that the Messenger of Allah, peace and blessings be upon him, set out for Umrah. The Quraysh disbelievers prevented him from reaching the House, so he sacrificed his offering and shaved his head at Hudaybiyyah. He agreed with them that he would perform Umrah the following year, carry no weapons against them except sheathed swords, and stay there only as long as they allowed. He performed Umrah the following year and entered as agreed. After three days they ordered him to leave, and he left.", "Muhammad ibn Rafi überlieferte mir: Surayj überlieferte uns: Fulaih überlieferte uns. Auch Muhammad ibn al-Husain ibn Ibrahim überlieferte mir von seinem Vater, von Fulaih ibn Sulaiman, von Nafi, von Ibn Umar, möge Allah mit ihnen zufrieden sein, dass der Gesandte Allahs, Friede sei auf ihm, zur Umra aufbrach. Die Ungläubigen von Quraisch hinderten ihn am Heiligtum, worauf er sein Opfertier schlachtete und sich in Hudaybiyya den Kopf rasierte. Er vereinbarte mit ihnen, im folgenden Jahr die Umra zu vollziehen, gegen sie keine Waffen außer Schwertern in Scheiden zu tragen und dort nur so lange zu bleiben, wie sie es erlaubten. Im folgenden Jahr vollzog er die Umra und betrat Mekka gemäß der Vereinbarung. Nach drei Tagen forderten sie ihn zum Auszug auf, und er zog aus."],
  "4253": ["Uthman ibn Abi Shaybah narrated to me: Jarir narrated to us, from Mansur, from Mujahid, who said: Urwah ibn al-Zubayr and I entered the mosque and found Abd Allah ibn Umar sitting beside Aisha's room. He was asked how many Umra pilgrimages the Prophet, peace and blessings be upon him, performed. He said, 'Four, one of them in Rajab.' We then heard Aisha brushing her teeth. Urwah said, 'Mother of the Believers, do you not hear what Abu Abd al-Rahman says? The Prophet performed four Umra pilgrimages.' She said, 'The Prophet did not perform any Umrah without my witnessing it, and he never performed Umrah in Rajab.'", "Uthman ibn Abi Schaiba überlieferte mir: Jarir überlieferte uns von Mansur, von Mujahid, der sagte: Urwa ibn az-Zubair und ich betraten die Moschee und fanden Abd Allah ibn Umar neben Aishas Zimmer sitzen. Er wurde gefragt, wie viele Umras der Prophet, Friede sei auf ihm, vollzogen habe. Er sagte: „Vier, eine davon im Radschab.“ Dann hörten wir Aisha ihre Zähne reinigen. Urwa sagte: „Mutter der Gläubigen, hörst du nicht, was Abu Abd ar-Rahman sagt? Der Prophet vollzog vier Umras.“ Sie sagte: „Der Prophet vollzog keine Umra, ohne dass ich dabei war, und er vollzog niemals eine Umra im Radschab.“"],
  "4255": ["Ali ibn Abd Allah narrated to us: Sufyan narrated to us, from Ismail ibn Abi Khalid, who heard Ibn Abi Awfa say: When the Messenger of Allah, peace and blessings be upon him, performed Umrah, we shielded him from the young men of the polytheists and from their harming him.", "Ali ibn Abd Allah überlieferte uns: Sufyan überlieferte uns von Ismail ibn Abi Khalid, der Ibn Abi Awfa sagen hörte: Als der Gesandte Allahs, Friede sei auf ihm, die Umra vollzog, schützten wir ihn vor den jungen Männern der Götzendiener und davor, dass sie ihm Schaden zufügten."],
  "4256": ["Sulayman ibn Harb narrated to us: Hammad, meaning Ibn Zayd, narrated to us, from Ayyub, from Said ibn Jubayr, from Ibn Abbas, may Allah be pleased with them, who said: The Messenger of Allah, peace and blessings be upon him, and his Companions arrived. The polytheists said, 'A delegation is coming to you; the fever of Yathrib has weakened them.' The Prophet ordered them to jog during the first three circuits and to walk between the two corners. He was prevented from ordering them to jog all the circuits only by his concern for them. Ibn Salama added that he said, 'Jog so that the polytheists may see your strength,' while the polytheists were near Qaiqa'an.", "Sulaiman ibn Harb überlieferte uns: Hammad, also Ibn Zaid, überlieferte uns von Ayyub, von Said ibn Dschubair, von Ibn Abbas, möge Allah mit ihnen zufrieden sein, der sagte: Der Gesandte Allahs, Friede sei auf ihm, und seine Gefährten kamen an. Die Götzendiener sagten: „Eine Abordnung kommt zu euch; das Fieber von Yathrib hat sie geschwächt.“ Der Prophet befahl ihnen, in den ersten drei Umrundungen zügig zu laufen und zwischen den beiden Ecken zu gehen. Nur seine Fürsorge für sie hinderte ihn daran, ihnen das Laufen in allen Umrundungen zu befehlen. Ibn Salama fügte hinzu, dass er sagte: „Lauft zügig, damit die Götzendiener eure Kraft sehen“, während die Götzendiener bei Qaiqa'an waren."],
  "4257": ["Muhammad narrated to me, from Sufyan ibn Uyaynah, from Amr, from Ata, from Ibn Abbas, may Allah be pleased with them, who said: The Prophet jogged around the House and between Safa and Marwa only to show the polytheists his strength.", "Muhammad überlieferte mir von Sufyan ibn Uyayna, von Amr, von Ata, von Ibn Abbas, möge Allah mit ihnen zufrieden sein, der sagte: Der Prophet lief nur deshalb zügig um das Haus und zwischen Safa und Marwa, um den Götzendienern seine Kraft zu zeigen."],
  "4260": ["Ahmad narrated to us: Ibn Wahb narrated to us, from Amr, from Ibn Abi Hilal, who said: Nafi informed me that Ibn Umar told him that he stood over Ja'far on that day after he had been killed. He counted fifty wounds between spear thrusts and blows, none of them on his back.", "Ahmad überlieferte uns: Ibn Wahb überlieferte uns von Amr, von Ibn Abi Hilal, der sagte: Nafi berichtete mir, dass Ibn Umar ihm erzählte, er habe an jenem Tag bei Ja'far gestanden, nachdem dieser getötet worden war. Er zählte fünfzig Wunden durch Stiche und Schläge, keine davon an seinem Rücken."],
  "4261": ["Ahmad ibn Abi Bakr narrated to us: Mughirah ibn Abd al-Rahman narrated to us, from Abd Allah ibn Said, from Nafi, from Abd Allah ibn Umar, may Allah be pleased with them, who said: The Messenger of Allah, peace and blessings be upon him, appointed Zayd ibn Harithah over the expedition of Mutah and said, 'If Zayd is killed, then Ja'far; if Ja'far is killed, then Abd Allah ibn Rawahah.' Abd Allah said: I was among them in that expedition. We searched for Ja'far ibn Abi Talib and found him among the slain. We found more than ninety wounds on his body from spear thrusts and arrows.", "Ahmad ibn Abi Bakr überlieferte uns: Mughirah ibn Abd ar-Rahman überlieferte uns von Abd Allah ibn Said, von Nafi, von Abd Allah ibn Umar, möge Allah mit ihnen zufrieden sein, der sagte: Der Gesandte Allahs, Friede sei auf ihm, setzte Zayd ibn Haritha über den Feldzug von Mutah ein und sagte: „Wenn Zayd getötet wird, dann Ja'far; wenn Ja'far getötet wird, dann Abd Allah ibn Rawaha.“ Abd Allah sagte: Ich war bei jenem Feldzug unter ihnen. Wir suchten nach Ja'far ibn Abi Talib und fanden ihn unter den Gefallenen. An seinem Körper fanden wir mehr als neunzig Wunden von Speerstichen und Pfeilen."],
  "4262": ["Ahmad ibn Waqid narrated to us: Hammad ibn Zayd narrated to us, from Ayyub, from Humayd ibn Hilal, from Anas, may Allah be pleased with him, that the Prophet, peace and blessings be upon him, announced the deaths of Zayd, Ja'far and Ibn Rawahah to the people before their news arrived. He said, 'Zayd took the banner and was struck down; then Ja'far took it and was struck down; then Ibn Rawahah took it and was struck down,' while his eyes shed tears, 'until one of the swords of Allah took the banner and Allah granted them victory.'", "Ahmad ibn Waqid überlieferte uns: Hammad ibn Zaid überlieferte uns von Ayyub, von Humayd ibn Hilal, von Anas, möge Allah mit ihm zufrieden sein, dass der Prophet, Friede sei auf ihm, den Menschen den Tod von Zayd, Ja'far und Ibn Rawaha verkündete, bevor ihre Nachricht eintraf. Er sagte: „Zayd nahm das Banner und wurde getroffen; dann nahm Ja'far es und wurde getroffen; dann nahm Ibn Rawaha es und wurde getroffen“ – dabei liefen ihm die Tränen aus den Augen –, „bis eines der Schwerter Allahs das Banner nahm und Allah ihnen den Sieg verlieh.“"],
  "4263": ["Qutaybah narrated to us: Abd al-Wahhab narrated to us: I heard Yahya ibn Said say: Amrah informed me: I heard Aisha, may Allah be pleased with her, say: When news came of the deaths of Ibn Harithah, Ja'far ibn Abi Talib and Abd Allah ibn Rawahah, the Messenger of Allah, peace and blessings be upon him, sat with grief visible in him. Aisha said: I was looking through a crack in the door. A man came and said, 'O Messenger of Allah, the women of Ja'far...' and mentioned their weeping. He ordered him to stop them. The man returned and said they had not obeyed him. He ordered him again. The man returned and said, 'By Allah, they have overcome us.' The Messenger of Allah said, 'Put dust in their mouths.' Aisha said, 'May Allah soil your nose! By Allah, you are not doing it, and you have not spared the Messenger of Allah trouble.'", "Qutaiba überlieferte uns: Abd al-Wahhab überlieferte uns: Ich hörte Yahya ibn Said sagen: Amra berichtete mir: Ich hörte Aisha, möge Allah mit ihr zufrieden sein, sagen: Als die Nachricht vom Tod von Ibn Haritha, Ja'far ibn Abi Talib und Abd Allah ibn Rawaha kam, setzte sich der Gesandte Allahs, Friede sei auf ihm, und die Trauer war an ihm zu erkennen. Aisha sagte: Ich schaute durch einen Spalt in der Tür. Ein Mann kam und sagte: „O Gesandter Allahs, die Frauen Ja'fars …“ und erwähnte ihr Weinen. Er befahl ihm, sie davon abzuhalten. Der Mann kehrte zurück und sagte, sie hätten ihm nicht gehorcht. Er befahl es erneut. Der Mann kehrte zurück und sagte: „Bei Allah, sie haben uns überwältigt.“ Der Gesandte Allahs sagte: „Stopft ihnen Staub in den Mund.“ Aisha sagte: „Möge Allah deine Nase beschmutzen! Bei Allah, du tust es nicht, und du hast dem Gesandten Allahs keine Mühe erspart.“"],
  "4264": ["Muhammad ibn Abi Bakr narrated to me: Umar ibn Ali narrated to us, from Ismail ibn Abi Khalid, from Amir, who said: When Ibn Umar greeted Ja'far's son, he said, 'Peace be upon you, O son of the two-winged one.'", "Muhammad ibn Abi Bakr überlieferte mir: Umar ibn Ali überlieferte uns von Ismail ibn Abi Khalid, von Amir, der sagte: Wenn Ibn Umar den Sohn Ja'fars begrüßte, sagte er: Friede sei mit dir, o Sohn des Mannes mit den zwei Flügeln."],
  "4265": ["Abu Nuaym narrated to us: Sufyan narrated to us, from Ismail, from Qays ibn Abi Hazim, who said: I heard Khalid ibn al-Walid say: On the day of Mutah, nine swords broke in my hand; only a Yemeni blade remained in my hand.", "Abu Nu'aim überlieferte uns: Sufyan überlieferte uns von Ismail, von Qais ibn Abi Hazim, der sagte: Ich hörte Khalid ibn al-Walid sagen: Am Tag von Mutah zerbrachen neun Schwerter in meiner Hand; nur eine jemenitische Klinge blieb in meiner Hand."],
  "4266": ["Muhammad ibn al-Muthanna narrated to me: Yahya narrated to us, from Ismail, who said: Qays narrated to me: I heard Khalid ibn al-Walid say, 'On the day of Mutah, nine swords were broken in my hand, and a Yemeni blade remained in my hand.'", "Muhammad ibn al-Muthanna überlieferte mir: Yahya überlieferte uns von Ismail, der sagte: Qais überlieferte mir: Ich hörte Khalid ibn al-Walid sagen: Am Tag von Mutah zerbrachen neun Schwerter in meiner Hand, und eine jemenitische Klinge blieb in meiner Hand."],
  "4267": ["Imran ibn Maysarah narrated to me: Muhammad ibn Fudayl narrated to us, from Husayn, from Amir, from al-Numan ibn Bashir, may Allah be pleased with them, who said: Abd Allah ibn Rawahah fainted, and his sister Amrah began to weep, saying, 'O my mountain!' and similar words, enumerating his virtues. When he regained consciousness, he said, 'Whenever you said something, I was told, “Are you really like that?”'", "Imran ibn Maisara überlieferte mir: Muhammad ibn Fudail überlieferte uns von Husain, von Amir, von an-Numan ibn Baschir, möge Allah mit ihnen zufrieden sein, der sagte: Abd Allah ibn Rawaha wurde ohnmächtig, und seine Schwester Amra begann zu weinen und sagte: „O mein Berg!“ und ähnliche Worte, wobei sie seine Vorzüge aufzählte. Als er wieder zu sich kam, sagte er: „Immer wenn du etwas gesagt hast, wurde mir gesagt: ,Bist du wirklich so?‘“"],
  "4268": ["Qutaybah narrated to us: Abthar narrated to us, from Husayn, from al-Shabi, from al-Numan ibn Bashir, who said: Abd Allah ibn Rawahah fainted because of this. When he died, she did not weep for him.", "Qutaiba überlieferte uns: Abthar überlieferte uns von Husain, von asch-Scha'bi, von an-Numan ibn Baschir, der sagte: Abd Allah ibn Rawaha wurde deswegen ohnmächtig. Als er starb, weinte sie nicht um ihn."]
});
const out = rows.map((r: any) => {
  const n = String(r.url).split(":").pop();
  const pair = t[n];
  if (!pair || !pair[0] || !pair[1]) throw new Error(`Missing translation for ${n}`);
  return { id: r.id, n, en: pair[0], de: pair[1] };
});
fs.writeFileSync("data/hadith-words-translations/codex-out-113.json", JSON.stringify(out, null, 2) + "\n", "utf8");
console.log(`wrote ${out.length} translations`);
