import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:280a':{en:'Ubaydullah ibn Muadh narrated to us. My father narrated to us. Shuba narrated to us, from Abu al-Tayyah, who heard Mutarrif ibn Abdullah narrate from Ibn al-Mughaffal, who said: The Messenger of Allah (peace be upon him) ordered that dogs be killed, then said: What is wrong with them and dogs? Then he allowed hunting dogs and sheep dogs, and said: If a dog licks a vessel, wash it seven times and rub it with soil the eighth time.',de:'Ubaydullah ibn Muadh überlieferte uns. Mein Vater überlieferte uns. Shuba überlieferte uns, von Abu al-Tayyah, der Mutarrif ibn Abdullah von Ibn al-Mughaffal überliefern hörte, der sagte: Der Gesandte Allahs (Friede sei auf ihm) befahl, Hunde zu töten, und sagte dann: Was ist mit ihnen und den Hunden? Danach erlaubte er Jagdhunde und Schäferhunde und sagte: Wenn ein Hund ein Gefäß beleckt, wascht es siebenmal und reibt es beim achten Mal mit Erde aus.'},
'https://sunnah.com/muslim:280b':{en:'Yahya ibn Habib al-HarithI narrated it to me. Khalid, meaning ibn al-Harith, narrated to us. Muhammad ibn Hatim also narrated it to me. Yahya ibn Said narrated to us. Muhammad ibn al-Walid also narrated to me. All of them narrated from Shuba with this chain and the same wording, except that in the narration of Yahya ibn Said there is the addition: And he allowed sheep dogs, hunting dogs, and dogs used for crops. No one other than Yahya mentioned crops in the narration.',de:'Yahya ibn Habib al-Harithi überlieferte ihn mir. Khalid, gemeint ist ibn al-Harith, überlieferte uns. Auch Muhammad ibn Hatim überlieferte ihn mir. Yahya ibn Said überlieferte uns. Auch Muhammad ibn al-Walid überlieferte mir. Alle überlieferten von Shuba mit dieser Überlieferungskette und demselben Wortlaut, außer dass in der Überlieferung von Yahya ibn Said hinzugefügt wird: Und er erlaubte Schäferhunde, Jagdhunde und Hunde für Felder. Niemand außer Yahya erwähnte in der Überlieferung die Felder.'},
'https://sunnah.com/muslim:281':{en:'Yahya ibn Yahya and Muhammad ibn Rumh narrated to us. They said: al-Layth informed us. Qutayba also narrated to us: al-Layth narrated to us, from Abu al-Zubayr, from Jabir, from the Messenger of Allah (peace be upon him), that he forbade urinating into stagnant water.',de:'Yahya ibn Yahya und Muhammad ibn Rumh überlieferten uns. Sie sagten: al-Layth berichtete uns. Auch Qutayba überlieferte uns: al-Layth überlieferte uns, von Abu al-Zubayr, von Jabir, vom Gesandten Allahs (Friede sei auf ihm), dass er das Urinieren in stehendes Wasser verbot.'},
'https://sunnah.com/muslim:282a':{en:'Zuhayr ibn Harb narrated to me. Jarir narrated to us, from Hisham, from Ibn Sirin, from Abu Hurayra, from the Prophet (peace be upon him), who said: None of you should urinate into standing water and then bathe in it.',de:'Zuhayr ibn Harb überlieferte mir. Jarir überlieferte uns, von Hisham, von Ibn Sirin, von Abu Hurayra, vom Propheten (Friede sei auf ihm), der sagte: Keiner von euch soll in stehendes Wasser urinieren und sich dann darin baden.'},
'https://sunnah.com/muslim:282b':{en:'Muhammad ibn Rafi narrated to us. Abd al-Razzaq narrated to us. Ma\'mar narrated to us, from Hammam ibn Munabbih, who said: This is what Abu Hurayra narrated to us from Muhammad, the Messenger of Allah (peace be upon him). He mentioned several hadiths, including this: The Messenger of Allah (peace be upon him) said: Do not urinate into standing water that does not flow, then bathe in it.',de:'Muhammad ibn Rafi überlieferte uns. Abd al-Razzaq überlieferte uns. Ma\'mar überlieferte uns, von Hammam ibn Munabbih, der sagte: Dies ist, was Abu Hurayra uns von Muhammad, dem Gesandten Allahs (Friede sei auf ihm), überlieferte. Er erwähnte mehrere Hadithe, darunter: Der Gesandte Allahs (Friede sei auf ihm) sagte: Uriniert nicht in stehendes Wasser, das nicht fließt, und badet euch dann darin.'},
'https://sunnah.com/muslim:283':{en:'Harun ibn Said al-Ayli, Abu al-Tahir, and Ahmad ibn Isa narrated to us, all from Ibn Wahb. Harun said: Ibn Wahb narrated to us. Amr ibn al-Harith informed me, from Bukayr ibn al-Ashajj, that Abu al-Saib, the client of Hisham ibn Zuhra, narrated to him that he heard Abu Hurayra say: The Messenger of Allah (peace be upon him) said: None of you should bathe in standing water while in a state of major ritual impurity. Someone asked: How should he do it, O Abu Hurayra? He said: He should take water from it in handfuls.',de:'Harun ibn Said al-Ayli, Abu al-Tahir und Ahmad ibn Isa überlieferten uns, alle von Ibn Wahb. Harun sagte: Ibn Wahb überlieferte uns. Amr ibn al-Harith berichtete mir, von Bukayr ibn al-Ashajj, dass Abu al-Saib, der Schutzbefohlene von Hisham ibn Zuhra, ihm berichtete, dass er Abu Hurayra sagen hörte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Keiner von euch soll sich in stehendem Wasser baden, während er sich im Zustand großer ritueller Unreinheit befindet. Jemand fragte: Wie soll er es tun, o Abu Hurayra? Er sagte: Er soll Wasser daraus schöpfen.'},
'https://sunnah.com/muslim:284a':{en:'Qutayba ibn Said narrated to us. Hammad, meaning ibn Zayd, narrated to us, from Thabit, from Anas, that a Bedouin urinated in the mosque. Some of the people rose toward him, so the Messenger of Allah (peace be upon him) said: Leave him and do not interrupt him. He said: When he finished, he called for a bucket of water and poured it over it.',de:'Qutayba ibn Said überlieferte uns. Hammad, gemeint ist ibn Zayd, überlieferte uns, von Thabit, von Anas, dass ein Beduine in der Moschee urinierte. Einige Leute gingen auf ihn zu, da sagte der Gesandte Allahs (Friede sei auf ihm): Lasst ihn und unterbrecht ihn nicht. Als er fertig war, ließ er einen Eimer Wasser bringen und goss es darüber.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-212-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-212-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
