import fs from "node:fs";
const input=JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-batch-010.json","utf8").replace(/^\uFEFF/,""));
const t:Record<string,[string,string]>={
"2469":[
"Ibn Salam narrated to us. Al-Fazari narrated to us, from Humayd the Long, from Anas (may Allah be pleased with him), who said: The Messenger of Allah (peace be upon him) swore that he would abstain from his wives for a month. His foot had become injured, so he stayed in an upper room belonging to him. Umar came and asked: Have you divorced your wives? He said: No, but I have sworn to abstain from them for a month. He stayed there for twenty-nine days, then came down and entered upon his wives.",
"Ibn Salam überlieferte uns. Al-Fazari überlieferte uns, von Humayd dem Langen, von Anas (möge Allah mit ihm zufrieden sein), der sagte: Der Gesandte Allahs (Friede sei auf ihm) schwor, sich einen Monat lang von seinen Ehefrauen fernzuhalten. Sein Fuß war verletzt worden, daher blieb er in einer oberen Kammer, die ihm gehörte. Umar kam und fragte: Hast du dich von deinen Ehefrauen geschieden? Er sagte: Nein, aber ich habe geschworen, mich einen Monat lang von ihnen fernzuhalten. Er blieb dort neunundzwanzig Tage und kam dann herab und trat bei seinen Ehefrauen ein."
],
"2470":[
"Muslim narrated to us. Abu Aqil narrated to us. Abu al-Mutawakkil an-Naji narrated to us. He said: I came to Jabir ibn Abdullah (may Allah be pleased with them both). He said: The Prophet (peace be upon him) entered the mosque, and I went in to him. I tied the camel in a corner of the paved courtyard and said: This is your camel. He came out and walked around the camel, then said: The price and the camel are yours.",
"Muslim überlieferte uns. Abu Aqil überlieferte uns. Abu al-Mutawakkil an-Nadschi überlieferte uns. Er sagte: Ich kam zu Jabir ibn Abdullah (möge Allah mit ihnen beiden zufrieden sein). Er sagte: Der Prophet (Friede sei auf ihm) betrat die Moschee, und ich ging zu ihm hinein. Ich band das Kamel an einer Ecke des gepflasterten Hofes an und sagte: Dies ist dein Kamel. Er kam heraus, ging um das Kamel herum und sagte dann: Der Preis und das Kamel gehören dir."
],
"2471":[
"Sulayman ibn Harb narrated to us, from Shu'ba, from Mansur, from Abu Wa'il, from Hudhayfa (may Allah be pleased with him), who said: I saw the Messenger of Allah (peace be upon him), or he said: The Prophet (peace be upon him) came to the rubbish dump of some people and urinated while standing.",
"Sulayman ibn Harb überlieferte uns, von Shu'ba, von Mansur, von Abu Wa'il, von Hudhayfa (möge Allah mit ihm zufrieden sein), der sagte: Ich sah den Gesandten Allahs (Friede sei auf ihm), oder er sagte: Der Prophet (Friede sei auf ihm) kam zu einem Abfallplatz von Menschen und urinierte im Stehen."
],
"2472":[
"Abdullah narrated to us. Malik informed us, from Sumayy, from Abu Salih, from Abu Hurayra (may Allah be pleased with him), that the Messenger of Allah (peace be upon him) said: While a man was walking along a road, he found a thorny branch and removed it. Allah appreciated this deed for him and forgave him.",
"Abdullah überlieferte uns. Malik berichtete uns, von Sumayy, von Abu Salih, von Abu Hurayra (möge Allah mit ihm zufrieden sein), dass der Gesandte Allahs (Friede sei auf ihm) sagte: Während ein Mann auf einem Weg ging, fand er einen dornigen Zweig und entfernte ihn. Allah würdigte diese Tat für ihn und vergab ihm."
],
"2473":[
"Musa ibn Ismail narrated to us. Jarir ibn Hazim narrated to us, from az-Zubayr ibn Khirrit, from Ikrima, who heard Abu Hurayra (may Allah be pleased with him) say: The Prophet (peace be upon him) decided that when people disputed over a road, it should be seven cubits wide.",
"Musa ibn Ismail überlieferte uns. Jarir ibn Hazim überlieferte uns, von az-Zubayr ibn Khirrit, von Ikrima, der Abu Hurayra (möge Allah mit ihm zufrieden sein) sagen hörte: Der Prophet (Friede sei auf ihm) entschied, dass ein Weg, über den Menschen stritten, sieben Ellen breit sein soll."
],
"2474":[
"Adam ibn Abi Iyas narrated to us. Shu'ba narrated to us. Adi ibn Thabit narrated to us. I heard Abdullah ibn Yazid al-Ansari, who was his maternal grandfather Abu Umama, say: The Prophet (peace be upon him) forbade plunder and mutilation.",
"Adam ibn Abi Iyas überlieferte uns. Shu'ba überlieferte uns. Adi ibn Thabit überlieferte uns. Ich hörte Abdullah ibn Yazid al-Ansari, dessen Großvater mütterlicherseits Abu Umama war, sagen: Der Prophet (Friede sei auf ihm) verbot Plünderung und Verstümmelung."
],
"2475":[
"Sa'id ibn Ufayr said: Al-Layth narrated to me. Uqayl narrated to us, from Ibn Shihab, from Abu Bakr ibn Abd ar-Rahman, from Abu Hurayra (may Allah be pleased with him), who said: The Prophet (peace be upon him) said: The adulterer is not a believer while committing adultery; the drinker of wine is not a believer while drinking it; the thief is not a believer while stealing; and the plunderer is not a believer while plundering in a way that makes people raise their eyes toward him. Sa'id and Abu Salama also narrated from Abu Hurayra, from the Prophet (peace be upon him), the same report except for plundering.",
"Sa'id ibn Ufayr sagte: Al-Layth berichtete mir. Uqayl überlieferte uns, von Ibn Schihab, von Abu Bakr ibn Abd ar-Rahman, von Abu Hurayra (möge Allah mit ihm zufrieden sein), der sagte: Der Prophet (Friede sei auf ihm) sagte: Der Ehebrecher ist während seines Ehebruchs kein Gläubiger; der Weintrinker ist während des Trinkens kein Gläubiger; der Dieb ist während des Diebstahls kein Gläubiger; und der Plünderer ist während einer Plünderung, bei der die Menschen ihre Augen zu ihm erheben, kein Gläubiger. Sa'id und Abu Salama überlieferten von Abu Hurayra vom Propheten (Friede sei auf ihm) denselben Bericht, außer hinsichtlich der Plünderung."
],
"2476":[
"Ali ibn Abdullah narrated to us. Sufyan narrated to us. Az-Zuhri narrated to us. Sa'id ibn al-Musayyab informed me that he heard Abu Hurayra (may Allah be pleased with him) report from the Messenger of Allah (peace be upon him), who said: The Hour will not be established until the son of Mary descends among you as a just judge. He will break the cross, kill the swine, abolish the jizya, and wealth will flow so abundantly that no one will accept it.",
"Ali ibn Abdullah überlieferte uns. Sufyan überlieferte uns. Az-Zuhri überlieferte uns. Sa'id ibn al-Musayyab berichtete mir, dass er Abu Hurayra (möge Allah mit ihm zufrieden sein) vom Gesandten Allahs (Friede sei auf ihm) berichten hörte, der sagte: Die Stunde wird nicht eintreten, bis der Sohn Maryams als gerechter Richter zu euch herabsteigt. Er wird das Kreuz zerbrechen, das Schwein töten, die Dschizya aufheben, und das Vermögen wird so reichlich fließen, dass niemand es annehmen wird."
],
"2477":[
"Abu Asim ad-Dahhak ibn Makhlad narrated to us, from Yazid ibn Abi Ubayd, from Salama ibn al-Akwa (may Allah be pleased with him), that the Prophet (peace be upon him) saw fires being lit on the day of Khaybar. He asked: What are these fires being lit for? They said: For domestic donkeys. He said: Break them and pour them out. They asked: Should we not pour them out and wash the vessels? He said: Wash them. Abu Abdullah said: Ibn Abi Uways used to pronounce the phrase for domestic donkeys with the alif and nun vocalized.",
"Abu Asim ad-Dahhak ibn Makhlad überlieferte uns, von Yazid ibn Abi Ubayd, von Salama ibn al-Aqwa (möge Allah mit ihm zufrieden sein), dass der Prophet (Friede sei auf ihm) am Tag von Chaibar Feuer brennen sah. Er fragte: Wofür werden diese Feuer entzündet? Sie sagten: Für Hausesel. Er sagte: Zerbrecht sie und schüttet sie aus. Sie fragten: Sollen wir sie nicht ausschütten und die Gefäße waschen? Er sagte: Wascht sie. Abu Abdullah sagte: Ibn Abi Uways sprach die Bezeichnung für Hausesel mit der Vokalisierung von Alif und Nun."
],
"2478":[
"Ali ibn Abdullah narrated to us. Sufyan narrated to us. Ibn Abi Najih narrated to us, from Mujahid, from Abu Ma'mar, from Abdullah ibn Masud (may Allah be pleased with him), who said: The Prophet (peace be upon him) entered Mecca while there were three hundred and sixty idols around the Kaaba. He began striking them with a stick in his hand and recited: Truth has come and falsehood has vanished (Quran 17:81).",
"Ali ibn Abdullah überlieferte uns. Sufyan überlieferte uns. Ibn Abi Najih überlieferte uns, von Mujahid, von Abu Ma'mar, von Abdullah ibn Masud (möge Allah mit ihm zufrieden sein), der sagte: Der Prophet (Friede sei auf ihm) betrat Mekka, während sich dreihundertsechzig Götzen um die Kaaba befanden. Er begann, sie mit einem Stock in seiner Hand zu schlagen, und rezitierte: Die Wahrheit ist gekommen und das Falsche ist vergangen (Quran 17:81)."
],
"2479":[
"Ibrahim ibn al-Mundhir narrated to us. Anas ibn Iyad narrated to us, from Ubaydullah, from Abd ar-Rahman ibn al-Qasim, from his father al-Qasim, from Aisha (may Allah be pleased with her), that she had hung a curtain in a small room of hers containing images. The Prophet (peace be upon him) tore it down. She then made two cushions from it, and they remained in the house, with people sitting on them.",
"Ibrahim ibn al-Mundhir überlieferte uns. Anas ibn Iyad überlieferte uns, von Ubaydullah, von Abd ar-Rahman ibn al-Qasim, von seinem Vater al-Qasim, von Aischa (möge Allah mit ihr zufrieden sein), dass sie in einer kleinen Kammer von ihr einen Vorhang mit Bildern aufgehängt hatte. Der Prophet (Friede sei auf ihm) riss ihn herunter. Sie machte daraus zwei Kissen, die im Haus blieben und auf denen man saß."
],
"2480":[
"Abdullah ibn Yazid narrated to us. Sa'id, the son of Abu Ayyub, narrated to us. Abu al-Aswad narrated to me, from Ikrima, from Abdullah ibn Amr (may Allah be pleased with them both), who said: I heard the Prophet (peace be upon him) say: Whoever is killed defending his property is a martyr.",
"Abdullah ibn Yazid überlieferte uns. Sa'id, der Sohn von Abu Ayyub, überlieferte uns. Abu al-Aswad berichtete mir, von Ikrima, von Abdullah ibn Amr (möge Allah mit ihnen beiden zufrieden sein), der sagte: Ich hörte den Propheten (Friede sei auf ihm) sagen: Wer getötet wird, während er sein Vermögen verteidigt, ist ein Märtyrer."
],
"2481":[
"Musaddad narrated to us. Yahya ibn Sa'id narrated to us, from Humayd, from Anas (may Allah be pleased with him), that the Prophet (peace be upon him) was with one of his wives. One of the Mothers of the Believers sent a servant with a bowl containing food. The wife struck it with her hand and broke the bowl. He gathered the pieces, put the food into it and said: Eat. He kept the Messenger and the bowl until they had finished, then he gave the sound bowl and kept the broken one. Ibn Abi Maryam said: Yahya ibn Ayyub informed us, from Humayd, from Anas, from the Prophet (peace be upon him).",
"Musaddad überlieferte uns. Yahya ibn Sa'id überlieferte uns, von Humayd, von Anas (möge Allah mit ihm zufrieden sein), dass der Prophet (Friede sei auf ihm) bei einer seiner Ehefrauen war. Eine der Mütter der Gläubigen schickte einen Diener mit einer Schüssel, in der sich Essen befand. Die Ehefrau schlug mit ihrer Hand danach und zerbrach die Schüssel. Er sammelte die Stücke, legte das Essen hinein und sagte: Esst. Er hielt den Gesandten und die Schüssel zurück, bis sie fertig waren. Dann gab er die unbeschädigte Schüssel und behielt die zerbrochene. Ibn Abi Maryam sagte: Yahya ibn Ayyub berichtete uns, von Humayd, von Anas, vom Propheten (Friede sei auf ihm)."
],
"2482":[
"Muslim ibn Ibrahim narrated to us. Jarir ibn Hazim narrated to us, from Muhammad ibn Sirin, from Abu Hurayra (may Allah be pleased with him), who said: The Messenger of Allah (peace be upon him) said: There was a man among the Children of Israel called Jurayj who used to pray. His mother came and called him, but he refused to answer her, saying: Shall I answer her or continue praying? She came again and said: O Allah, do not let him die until You show him the faces of immoral women. Jurayj was in his cell. A woman said: I will tempt Jurayj. She exposed herself to him and spoke to him, but he refused her. She went to a shepherd, allowed him access to her, and gave birth to a boy. She said: This is from Jurayj. They came to him, broke his cell, brought him down and insulted him. He performed wudu and prayed, then went to the boy and asked: Who is your father, boy? He said: The shepherd. They said: Shall we build your cell of gold? He said: No, only of clay.",
"Muslim ibn Ibrahim überlieferte uns. Jarir ibn Hazim überlieferte uns, von Muhammad ibn Sirin, von Abu Hurayra (möge Allah mit ihm zufrieden sein), der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Unter den Kindern Israels lebte ein Mann namens Dschuraisch, der zu beten pflegte. Seine Mutter kam und rief ihn, doch er weigerte sich zu antworten und sagte: Soll ich ihr antworten oder weiterbeten? Sie kam erneut und sagte: O Allah, lass ihn nicht sterben, bis Du ihm die Gesichter unmoralischer Frauen zeigst. Dschuraisch war in seiner Gebetszelle. Eine Frau sagte: Ich werde Dschuraisch verführen. Sie stellte sich ihm aus und sprach mit ihm, doch er wies sie zurück. Sie ging zu einem Hirten, ließ ihn mit sich verkehren und gebar einen Jungen. Sie sagte: Dieser stammt von Dschuraisch. Sie kamen zu ihm, zerbrachen seine Zelle, holten ihn herunter und beschimpften ihn. Er vollzog die Gebetswaschung und betete, ging dann zu dem Jungen und fragte: Wer ist dein Vater, Junge? Er sagte: Der Hirte. Sie sagten: Sollen wir deine Zelle aus Gold bauen? Er sagte: Nein, nur aus Lehm."
],
"2483":[
"Abdullah ibn Yusuf informed us. Malik informed us, from Wahb ibn Kaysan, from Jabir ibn Abdullah (may Allah be pleased with them both), who said: The Messenger of Allah (peace be upon him) sent an expedition toward the coast and appointed Abu Ubayda ibn al-Jarrah over them. They were three hundred, and I was among them. We set out, and when we were on part of the road our provisions ran out. Abu Ubayda ordered the provisions of the army to be gathered. All of it became two bags of dates, and he gave us a little each day until it ran out, so that we received only one date at a time. I asked: What can one date do? He said: We realized its loss when even that was gone. Then we reached the sea and found a fish like a great hill. The army ate from it for eighteen nights. Abu Ubayda ordered two ribs to be erected, then ordered a riding camel to be saddled and led beneath them, and it passed beneath them without touching them.",
"Abdullah ibn Yusuf berichtete uns. Malik berichtete uns, von Wahb ibn Kaysan, von Jabir ibn Abdullah (möge Allah mit ihnen beiden zufrieden sein), der sagte: Der Gesandte Allahs (Friede sei auf ihm) schickte ein Heer zur Küste und setzte Abu Ubayda ibn al-Dscharrah über sie. Sie waren dreihundert, und ich war unter ihnen. Wir brachen auf, und als wir einen Teil des Weges zurückgelegt hatten, gingen unsere Vorräte aus. Abu Ubayda befahl, die Vorräte des Heeres zusammenzutragen. Alles zusammen ergab zwei Säcke Datteln. Er gab uns jeden Tag ein wenig, bis sie ausgingen, sodass wir nur noch jeweils eine Dattel erhielten. Ich fragte: Was kann eine Dattel bewirken? Er sagte: Wir bemerkten ihren Verlust, als auch sie aufgebraucht war. Dann erreichten wir das Meer und fanden einen Fisch, groß wie ein Hügel. Das Heer aß achtzehn Nächte lang davon. Abu Ubayda befahl, zwei Rippen aufzustellen. Dann ließ er ein Reittier satteln und darunter hindurchführen, und es ging darunter hindurch, ohne sie zu berühren."
],
"2484":[
"Bishr ibn Marhum narrated to us. Hatim ibn Ismail narrated to us, from Yazid ibn Abi Ubayd, from Salama (may Allah be pleased with him), who said: The people's provisions became scarce and they were in poverty. They came to the Prophet (peace be upon him) asking permission to slaughter their camels, and he permitted them. Umar met them, and they told him. He said: What will remain for you after your camels? He entered upon the Prophet (peace be upon him) and said: Messenger of Allah, what will remain for them after their camels? The Messenger of Allah said: Call among the people, and let them bring whatever provisions they have left. A leather mat was spread for that, and they placed the provisions on it. The Messenger of Allah stood, supplicated and blessed it. Then he called them with their vessels, and the people took from it until they had finished. The Messenger of Allah said: I testify that there is no deity except Allah and that I am the Messenger of Allah.",
"Bishr ibn Marhum überlieferte uns. Hatim ibn Ismail überlieferte uns, von Yazid ibn Abi Ubayd, von Salama (möge Allah mit ihm zufrieden sein), der sagte: Die Vorräte der Menschen wurden knapp und sie gerieten in Not. Sie kamen zum Propheten (Friede sei auf ihm) und baten um Erlaubnis, ihre Kamele zu schlachten, und er erlaubte es ihnen. Umar traf sie und sie berichteten ihm davon. Er sagte: Was wird euch nach euren Kamelen bleiben? Er trat beim Propheten (Friede sei auf ihm) ein und sagte: Gesandter Allahs, was wird ihnen nach ihren Kamelen bleiben? Der Gesandte Allahs sagte: Rufe unter den Menschen aus, damit sie ihre übrigen Vorräte bringen. Dafür wurde eine Lederdecke ausgebreitet, und sie legten die Vorräte darauf. Der Gesandte Allahs stand auf, bat Allah und segnete sie. Dann rief er sie mit ihren Gefäßen, und die Menschen schöpften davon, bis nichts mehr übrig war. Der Gesandte Allahs sagte: Ich bezeuge, dass es keinen Gott außer Allah gibt und dass ich der Gesandte Allahs bin."
],
"2485":[
"Muhammad ibn Yusuf narrated to us. Al-Awzai narrated to us. Abu an-Najashi narrated to us. I heard Rafi ibn Khadij (may Allah be pleased with him) say: We used to pray the afternoon prayer with the Prophet (peace be upon him), then slaughter a camel. It was divided into ten portions, and we ate cooked meat before the sun set.",
"Muhammad ibn Yusuf überlieferte uns. Al-Awzai überlieferte uns. Abu an-Nadschaschi überlieferte uns. Ich hörte Rafi ibn Chadidsch (möge Allah mit ihm zufrieden sein) sagen: Wir verrichteten mit dem Propheten (Friede sei auf ihm) das Nachmittagsgebet und schlachteten dann ein Kamel. Es wurde in zehn Teile geteilt, und wir aßen gegartes Fleisch, bevor die Sonne unterging."
],
"2486":[
"Muhammad ibn al-Ala narrated to us. Hammad ibn Usama narrated to us, from Burayd, from Abu Burda, from Abu Musa, who said: The Prophet (peace be upon him) said: When the Asharis run out of provisions during an expedition, or the food of their families in Medina becomes scarce, they gather whatever they have in one cloth and divide it equally among themselves in one vessel. They belong to me and I belong to them.",
"Muhammad ibn al-Ala überlieferte uns. Hammad ibn Usama überlieferte uns, von Burayd, von Abu Burda, von Abu Musa, der sagte: Der Prophet (Friede sei auf ihm) sagte: Wenn den Ascharis auf einem Feldzug die Vorräte ausgehen oder die Nahrung ihrer Familien in Medina knapp wird, sammeln sie alles, was sie haben, in einem Tuch und teilen es in einem Gefäß gleichmäßig unter sich. Sie gehören zu mir und ich gehöre zu ihnen."
],
"2487":[
"Muhammad ibn Abdullah ibn al-Muthanna said: My father narrated to me. Thumama ibn Abdullah ibn Anas narrated to me that Anas narrated to him that Abu Bakr (may Allah be pleased with him) wrote for him the obligatory charity that the Messenger of Allah (peace be upon him) prescribed. He said: When two partners have mixed property, they settle between themselves equally.",
"Muhammad ibn Abdullah ibn al-Muthanna sagte: Mein Vater berichtete mir. Thumama ibn Abdullah ibn Anas berichtete mir, dass Anas ihm berichtete, dass Abu Bakr (möge Allah mit ihm zufrieden sein) ihm die verpflichtende Almosenabgabe aufschrieb, die der Gesandte Allahs (Friede sei auf ihm) vorgeschrieben hatte. Er sagte: Wenn zwei Teilhaber gemeinsames Vieh besitzen, rechnen sie untereinander zu gleichen Teilen ab."
],
"2488":[
"Ali ibn al-Hakam al-Ansari narrated to us. Abu Awana narrated to us, from Sa'id ibn Masruq, from Abaya ibn Rifa'a ibn Rafi ibn Khadij, from his grandfather, who said: We were with the Prophet (peace be upon him) at Dhu al-Hulayfa. The people became hungry and caught camels and sheep. The Prophet was at the rear of the people. They hurried, slaughtered and set up the cooking pots. The Prophet ordered the pots to be overturned. Then he divided the animals, assigning ten sheep for one camel. One camel escaped. They pursued it but could not catch it. There were a few horses among the people, and one man shot it with an arrow, so Allah stopped it. Then he said: These animals can be wild like wild beasts. If one of them overcomes you, do this to it. My grandfather said: We expect, or fear, the enemy tomorrow, and we have no knives. May we slaughter with reeds? He said: Whatever makes the blood flow and Allah's name is mentioned over it, eat it, except teeth and claws. I will tell you about that: the tooth is a bone, and the claw is the knife of the Abyssinians.",
"Ali ibn al-Hakam al-Ansari überlieferte uns. Abu Awana überlieferte uns, von Sa'id ibn Masruq, von Abaya ibn Rifa'a ibn Rafi ibn Chadidsch, von seinem Großvater, der sagte: Wir waren mit dem Propheten (Friede sei auf ihm) in Dhul-Hulaifa. Die Menschen wurden hungrig und fingen Kamele und Schafe. Der Prophet war am Ende der Gruppe. Sie eilten voraus, schlachteten und stellten die Kochtöpfe auf. Der Prophet befahl, die Töpfe auszuschütten. Dann teilte er die Tiere auf und setzte zehn Schafe einem Kamel gleich. Ein Kamel entlief. Sie verfolgten es, konnten es aber nicht einholen. Unter den Menschen waren einige wenige Pferde, und ein Mann schoss mit einem Pfeil auf das Kamel, sodass Allah es anhielt. Dann sagte er: Diese Tiere können wie wilde Tiere davonlaufen. Wenn eines euch entkommt, dann verfahrt so mit ihm. Mein Großvater sagte: Wir erwarten oder fürchten morgen den Feind, und wir haben keine Messer. Dürfen wir mit Schilfrohr schlachten? Er sagte: Was das Blut fließen lässt und worüber Allahs Name genannt wird, davon esst, außer wenn es ein Zahn oder eine Klaue ist. Ich werde euch darüber berichten: Der Zahn ist ein Knochen, und die Klaue ist das Messer der Äthiopier."
],
"2489":[
"Khalid ibn Yahya narrated to us. Sufyan narrated to us. Jabala ibn Suhaym narrated to us. I heard Ibn Umar (may Allah be pleased with them both) say: The Prophet (peace be upon him) forbade a person to take two dates together, unless he asks his companions for permission.",
"Khalid ibn Yahya überlieferte uns. Sufyan überlieferte uns. Jabala ibn Suhaym überlieferte uns. Ich hörte Ibn Umar (möge Allah mit ihnen beiden zufrieden sein) sagen: Der Prophet (Friede sei auf ihm) verbot einem Menschen, zwei Datteln auf einmal zu nehmen, es sei denn, er bittet seine Gefährten um Erlaubnis."
],
"2490":[
"Abu al-Walid narrated to us. Shu'ba narrated to us, from Jabala, who said: We were in Medina and a year of hardship struck us. Ibn az-Zubayr used to provide us with dates. Ibn Umar passed by us and said: Do not take two together, for the Prophet (peace be upon him) forbade taking two together, unless one of you asks his brother for permission.",
"Abu al-Walid überlieferte uns. Shu'ba überlieferte uns, von Jabala, der sagte: Wir waren in Medina, und ein Jahr der Not traf uns. Ibn az-Zubayr pflegte uns mit Datteln zu versorgen. Ibn Umar ging an uns vorbei und sagte: Nehmt nicht zwei auf einmal, denn der Prophet (Friede sei auf ihm) verbot das Zusammennehmen, außer wenn einer von euch seinen Bruder um Erlaubnis bittet."
],
"2491":[
"Imran ibn Maysara narrated to us. Abd al-Warith narrated to us. Ayyub narrated to us, from Nafi, from Ibn Umar (may Allah be pleased with them both), who said: The Messenger of Allah (peace be upon him) said: Whoever frees his share in a slave, or his part in him, and has enough property to pay his fair value, the slave is free. Otherwise, only the portion he freed is free. The narrator said: I do not know whether the words 'only the portion he freed is free' are from Nafi or from the hadith of the Prophet (peace be upon him).",
"Imran ibn Maysara überlieferte uns. Abd al-Warith überlieferte uns. Ayyub überlieferte uns, von Nafi, von Ibn Umar (möge Allah mit ihnen beiden zufrieden sein), der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Wer seinen Anteil an einem Sklaven oder seinen Teil an ihm freilässt und genügend Vermögen besitzt, um seinen gerechten Wert zu bezahlen, der Sklave ist frei. Andernfalls ist nur der Anteil frei, den er freigelassen hat. Der Überlieferer sagte: Ich weiß nicht, ob die Worte „nur der Anteil, den er freigelassen hat, ist frei“ von Nafi stammen oder aus dem Hadith des Propheten (Friede sei auf ihm)."
],
"2492":[
"Bishr ibn Muhammad informed us. Abdullah informed us. Sa'id ibn Abi Aruba informed us, from Qatada, from an-Nadr ibn Anas, from Bashir ibn Nahik, from Abu Hurayra (may Allah be pleased with him), from the Prophet (peace be upon him), who said: Whoever frees a share of his owned slave must complete his freedom from his property. If he has no property, the slave is assessed at a fair value and is required to work to pay the remainder, without being overburdened.",
"Bishr ibn Muhammad berichtete uns. Abdullah berichtete uns. Sa'id ibn Abi Aruba berichtete uns, von Qatada, von an-Nadr ibn Anas, von Bashir ibn Nahik, von Abu Hurayra (möge Allah mit ihm zufrieden sein), vom Propheten (Friede sei auf ihm), der sagte: Wer einen Anteil an seinem Sklaven freilässt, muss dessen Freilassung aus seinem Vermögen vollenden. Wenn er kein Vermögen besitzt, wird der Sklave zu einem gerechten Wert geschätzt und muss den Rest durch Arbeit bezahlen, ohne dass ihm mehr auferlegt wird, als er tragen kann."
],
"2493":[
"Abu Nu'aym narrated to us. Zakariya narrated to us. He said: I heard Amir say: I heard an-Numan ibn Bashir (may Allah be pleased with them both) report from the Prophet (peace be upon him), who said: The example of the person who observes Allah's limits and the person who violates them is like people who drew lots for places on a ship. Some received the upper part and some the lower part. When those below needed water, they passed by those above them and said: If we make a hole in our portion, we will not harm those above us. If they leave them to do what they intend, all of them will perish; but if they restrain them, they will be saved, and all will be saved.",
"Abu Nu'aym überlieferte uns. Zakariya überlieferte uns. Er sagte: Ich hörte Amir sagen: Ich hörte an-Numan ibn Baschir (möge Allah mit ihnen beiden zufrieden sein) vom Propheten (Friede sei auf ihm) berichten, der sagte: Das Gleichnis dessen, der Allahs Grenzen einhält, und dessen, der sie verletzt, ist wie das Gleichnis von Menschen, die um Plätze auf einem Schiff losten. Einige erhielten den oberen Teil und andere den unteren. Wenn die Unteren Wasser brauchten, gingen sie an den Oberen vorbei und sagten: Wenn wir in unserem Anteil ein Loch machen, schaden wir denen über uns nicht. Wenn sie sie tun lassen, was sie beabsichtigen, werden alle zugrunde gehen. Wenn sie sie aber davon abhalten, werden sie gerettet, und alle werden gerettet."
],
"2494":[
"Abd al-Aziz ibn Abdullah al-Amiri al-Uwaysi narrated to us. Ibrahim ibn Sa'd narrated to us, from Salih, from Ibn Shihab. Urwa informed me that he asked Aisha (may Allah be pleased with her). Al-Layth also said: Yunus narrated to me, from Ibn Shihab, who said: Urwa ibn az-Zubayr informed me that he asked Aisha about Allah's words: If you fear that you will not deal fairly with the orphan girls, then marry whatever women seem good to you, two, three or four (Quran 4:3). She said: My nephew, this concerns an orphan girl in the care of her guardian who shares in his property. Her wealth and beauty please him, so he wants to marry her without giving her a fair dowry, giving her only what another man would give her. They were forbidden to marry such girls unless they dealt fairly with them and gave them the highest customary dowry. They were told to marry other women who were lawful and pleasing to them. Urwa said that Aisha then said: After this verse, people asked the Messenger of Allah (peace be upon him), and Allah revealed: They ask you for a ruling concerning women ... and you desire to marry them (Quran 4:127). The first verse recited in the Book was: If you fear that you will not deal fairly with the orphans, then marry whatever women seem good to you (Quran 4:3). Aisha said: The meaning of the other verse, and you desire to marry them, is that one of you desires to marry the orphan girl in his care when she has little wealth and beauty. They were forbidden to marry orphans whom they desired for their wealth and beauty except with fairness, because they had no desire for them otherwise.",
"Abd al-Aziz ibn Abdullah al-Amiri al-Uwaysi überlieferte uns. Ibrahim ibn Sa'd überlieferte uns, von Salih, von Ibn Schihab. Urwa berichtete mir, dass er Aischa (möge Allah mit ihr zufrieden sein) fragte. Al-Layth sagte ebenfalls: Yunus berichtete mir, von Ibn Schihab, der sagte: Urwa ibn az-Zubayr berichtete mir, dass er Aischa nach Allahs Worten fragte: Wenn ihr fürchtet, dass ihr den Waisenmädchen nicht gerecht werdet, dann heiratet, was euch an Frauen gut erscheint, zwei, drei oder vier (Quran 4:3). Sie sagte: Mein Neffe, damit ist ein Waisenmädchen gemeint, das sich in der Obhut seines Vormunds befindet und an dessen Vermögen beteiligt ist. Ihr Vermögen und ihre Schönheit gefallen ihm, und so will er sie heiraten, ohne ihr eine gerechte Morgengabe zu geben, indem er ihr nur das gibt, was ein anderer Mann ihr geben würde. Sie wurden daran gehindert, solche Mädchen zu heiraten, außer wenn sie ihnen gerecht wurden und ihnen die höchste übliche Morgengabe gaben. Ihnen wurde befohlen, andere Frauen zu heiraten, die ihnen erlaubt und angenehm waren. Urwa sagte, dass Aischa danach sagte: Nachdem dieser Vers offenbart worden war, fragten die Menschen den Gesandten Allahs (Friede sei auf ihm), und Allah offenbarte: Sie fragen dich nach einer Rechtsauskunft über die Frauen ... und ihr begehrt, sie zu heiraten (Quran 4:127). Der zuerst im Buch rezitierte Vers war: Wenn ihr fürchtet, dass ihr den Waisen nicht gerecht werdet, dann heiratet, was euch an Frauen gut erscheint (Quran 4:3). Aischa sagte: Die Bedeutung des anderen Verses, und ihr begehrt, sie zu heiraten, ist, dass einer von euch das Waisenmädchen in seiner Obhut heiraten will, wenn es wenig Vermögen und Schönheit besitzt. Ihnen wurde verboten, Waisenmädchen zu heiraten, deren Vermögen und Schönheit sie begehrten, außer mit Gerechtigkeit, weil sie sonst kein Interesse an ihnen hatten."
],
"2495":[
"Abdullah ibn Muhammad narrated to us. Hisham narrated to us. Ma'mar informed us, from az-Zuhri, from Abu Salama, from Jabir ibn Abdullah (may Allah be pleased with them both), who said: The Prophet (peace be upon him) established the right of pre-emption in every property that has not been divided. Once boundaries are fixed and roads are assigned, there is no right of pre-emption.",
"Abdullah ibn Muhammad überlieferte uns. Hisham überlieferte uns. Ma'mar berichtete uns, von az-Zuhri, von Abu Salama, von Jabir ibn Abdullah (möge Allah mit ihnen beiden zufrieden sein), der sagte: Der Prophet (Friede sei auf ihm) bestimmte das Vorkaufsrecht für alles, was noch nicht geteilt ist. Sobald Grenzen festgelegt und Wege zugewiesen sind, gibt es kein Vorkaufsrecht mehr."
],
"2496":[
"Musaddad narrated to us. Abd al-Wahid narrated to us. Ma'mar narrated to us, from az-Zuhri, from Abu Salama, from Jabir ibn Abdullah (may Allah be pleased with them both), who said: The Prophet (peace be upon him) judged that the right of pre-emption applies to everything not divided. Once boundaries are fixed and roads are assigned, there is no right of pre-emption.",
"Musaddad überlieferte uns. Abd al-Wahid überlieferte uns. Ma'mar überlieferte uns, von az-Zuhri, von Abu Salama, von Jabir ibn Abdullah (möge Allah mit ihnen beiden zufrieden sein), der sagte: Der Prophet (Friede sei auf ihm) entschied, dass das Vorkaufsrecht für alles gilt, was nicht geteilt ist. Sobald Grenzen festgelegt und Wege zugewiesen sind, gibt es kein Vorkaufsrecht."
],
"2497":[
"Amr ibn Ali narrated to us. Abu Asim narrated to us, from Uthman, meaning Ibn al-Aswad. Sulayman ibn Abi Muslim informed me. He said: I asked Abu al-Minhal about exchanging currency hand to hand. He said: I and a partner bought something partly hand to hand and partly deferred. Al-Bara ibn Azib came to us, so we asked him. He said: I and my partner Zayd ibn Arqam did that, and we asked the Prophet (peace be upon him) about it. He said: Whatever is hand to hand, take it; whatever is deferred, leave it.",
"Amr ibn Ali überlieferte uns. Abu Asim überlieferte uns, von Uthman, gemeint ist Ibn al-Aswad. Sulayman ibn Abi Muslim berichtete mir. Er sagte: Ich fragte Abu al-Minhal nach dem Währungstausch Hand zu Hand. Er sagte: Ich und ein Teilhaber kauften etwas, teils sofort und teils aufgeschoben. Al-Bara ibn Azib kam zu uns, und wir fragten ihn. Er sagte: Ich und mein Teilhaber Zayd ibn Arqam taten dasselbe, und wir fragten den Propheten (Friede sei auf ihm) danach. Er sagte: Was sofort ausgetauscht wird, nehmt; was aufgeschoben ist, lasst sein."
],
"2499":[
"Musa ibn Ismail narrated to us. Juwayriya ibn Asma narrated to us, from Nafi, from Abdullah (may Allah be pleased with him), who said: The Messenger of Allah (peace be upon him) gave Khaybar to the Jews on the condition that they work and cultivate it, and that they would have half of whatever it produced.",
"Musa ibn Ismail überlieferte uns. Juwayriya ibn Asma überlieferte uns, von Nafi, von Abdullah (möge Allah mit ihm zufrieden sein), der sagte: Der Gesandte Allahs (Friede sei auf ihm) überließ Chaibar den Juden unter der Bedingung, dass sie es bearbeiten und bebauen sollten und ihnen die Hälfte dessen gehörte, was daraus hervorgebracht wurde."
]
};
for(const item of input){const n=item.url.split(":").pop()!;if(!t[n])throw new Error("Missing "+n);}
const output=input.map((item:any)=>{const n=item.url.split(":").pop()!;return {id:item.id,n,en:t[n][0],de:t[n][1]};});
fs.writeFileSync("data/hadith-words-translations/codex-out-010.json",JSON.stringify(output,null,2)+"\n","utf8");
console.log("Wrote "+output.length+" translations");

