import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-next3.json','utf8'));
const tr:Record<string,{en:string;de:string}>={
'https://sunnah.com/muslim:407':{en:'Muhammad ibn Abdullah ibn Numayr narrated to us. Ruh and Abdullah ibn Nafi narrated to us. And Ishaq ibn Ibrahim narrated to us, and this is his wording. He said: Ruh informed us, from Malik ibn Anas, from Abdullah ibn Abi Bakr, from his father, from Amr ibn Sulaym, that Abu Humayd al-Saidi informed him that they said: O Messenger of Allah, how should we invoke blessings upon you? He said: Say: O Allah, bless Muhammad, his wives, and his offspring as You blessed the family of Ibrahim, and bless Muhammad, his wives, and his offspring as You blessed the family of Ibrahim. Indeed, You are Praiseworthy, Glorious.',de:'Muhammad ibn Abdullah ibn Numayr überlieferte uns. Ruh und Abdullah ibn Nafi überlieferten uns. Und Ishaq ibn Ibrahim überlieferte uns, und dies ist sein Wortlaut. Er sagte: Ruh berichtete uns, von Malik ibn Anas, von Abdullah ibn Abi Bakr, von dessen Vater, von Amr ibn Sulaym, dass Abu Humayd al-Saidi ihm berichtete, dass sie sagten: O Gesandter Allahs, wie sollen wir Segenswünsche für dich sprechen? Er sagte: Sagt: O Allah, segne Muhammad, seine Ehefrauen und seine Nachkommen, wie Du die Familie Ibrahims gesegnet hast, und segne Muhammad, seine Ehefrauen und seine Nachkommen, wie Du die Familie Ibrahims gesegnet hast. Wahrlich, Du bist lobenswert und ruhmreich.'},
'https://sunnah.com/muslim:408':{en:'Yahya ibn Ayyub, Qutayba, and Ibn Hujr narrated to us. They said: Ismail, who was Ibn Jafar, narrated to us, from al-Ala, from his father, from Abu Hurayra, that the Messenger of Allah (peace be upon him) said: Whoever invokes one blessing upon me, Allah blesses him ten times.',de:'Yahya ibn Ayyub, Qutayba und Ibn Hujr überlieferten uns. Sie sagten: Ismail, nämlich Ibn Jafar, überlieferte uns, von al-Ala, von dessen Vater, von Abu Hurayra, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Wer einen Segenswunsch für mich spricht, den segnet Allah dafür zehnmal.'},
'https://sunnah.com/muslim:409a':{en:'Yahya ibn Yahya said: I read to Malik, from Sumayy, from Abu Salih, from Abu Hurayra, that the Messenger of Allah (peace be upon him) said: When the imam says, “Allah hears whoever praises Him,” say, “O Allah, our Lord, to You belongs praise.” Whoever’s words coincide with the words of the angels will have his previous sins forgiven.',de:'Yahya ibn Yahya sagte: Ich las Malik vor, von Sumayy, von Abu Salih, von Abu Hurayra, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn der Imam sagt: „Allah hört den, der Ihn lobt“, sagt: „O Allah, unser Herr, Dir gebührt das Lob.“ Wem seine Worte mit den Worten der Engel übereinstimmen, dem werden seine früheren Sünden vergeben.'},
'https://sunnah.com/muslim:409b':{en:'Qutayba ibn Said narrated to us. Yaqob, meaning Ibn Abd al-Rahman, narrated to us, from Suhayl, from his father, from Abu Hurayra, from the Prophet (peace be upon him), with the meaning of Sumayy’s hadith.',de:'Qutayba ibn Said überlieferte uns. Yaqob, gemeint ist Ibn Abd al-Rahman, überlieferte uns, von Suhayl, von dessen Vater, von Abu Hurayra, vom Propheten (Friede sei auf ihm), mit der Bedeutung von Sumayys Hadith.'},
'https://sunnah.com/muslim:410a':{en:'Yahya ibn Yahya said: I read to Malik, from Ibn Shihab, from Said ibn al-Musayyab and Abu Salama ibn Abd al-Rahman, that they informed him from Abu Hurayra, that the Messenger of Allah (peace be upon him) said: When the imam says, “Amin,” say, “Amin.” Whoever’s saying of Amin coincides with the saying of the angels will have his previous sins forgiven. Ibn Shihab said: The Messenger of Allah (peace be upon him) used to say: Amin.',de:'Yahya ibn Yahya sagte: Ich las Malik vor, von Ibn Shihab, von Said ibn al-Musayyab und Abu Salama ibn Abd al-Rahman, die ihm von Abu Hurayra berichteten, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn der Imam „Amin“ sagt, sagt „Amin“. Wem sein Amin-Sagen mit dem Amin-Sagen der Engel übereinstimmt, dem werden seine früheren Sünden vergeben. Ibn Shihab sagte: Der Gesandte Allahs (Friede sei auf ihm) pflegte „Amin“ zu sagen.'},
'https://sunnah.com/muslim:410b':{en:'Harmala ibn Yahya informed us. Ibn Wahb informed us. Yunus informed me, from Ibn Shihab. Ibn al-Musayyab and Abu Salama ibn Abd al-Rahman informed him that Abu Hurayra said: I heard the Messenger of Allah (peace be upon him), with the same meaning as Malik’s hadith. It does not mention Ibn Shihab’s statement.',de:'Harmala ibn Yahya berichtete uns. Ibn Wahb berichtete uns. Yunus berichtete mir, von Ibn Shihab. Ibn al-Musayyab und Abu Salama ibn Abd al-Rahman berichteten ihm, dass Abu Hurayra sagte: Ich hörte den Gesandten Allahs (Friede sei auf ihm), mit derselben Bedeutung wie in Maliks Hadith. Die Aussage von Ibn Shihab wird nicht erwähnt.'},
'https://sunnah.com/muslim:410c':{en:'Harmala ibn Yahya narrated to me. Ibn Wahb narrated to me. Amr informed me that Abu Yunus related to him from Abu Hurayra that the Messenger of Allah (peace be upon him) said: When one of you says Amin in prayer and the angels in heaven say Amin, and one of them coincides with the other, his previous sins will be forgiven.',de:'Harmala ibn Yahya überlieferte mir. Ibn Wahb überlieferte mir. Amr berichtete mir, dass Abu Yunus ihm von Abu Hurayra überlieferte, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn einer von euch im Gebet „Amin“ sagt und die Engel im Himmel „Amin“ sagen und eines mit dem anderen übereinstimmt, werden ihm seine früheren Sünden vergeben.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]})); if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-250-part.json',JSON.stringify(out,null,2)); fs.writeFileSync('data/hadith-words-translations/codex-out-250-part.json',JSON.stringify(out,null,2)); console.log(`wrote ${out.length} staged translations`);
