import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:287c':{en:'Harmala ibn Yahya narrated it to me. Ibn Wahb informed us. Yunus ibn Yazid informed me that Ibn Shihab informed him. Ubaydullah ibn Abdullah ibn Utba ibn Masud informed me that Umm Qays bint Mihsan, one of the earliest emigrant women who pledged allegiance to the Messenger of Allah (peace be upon him), and the sister of Ukasha ibn Mihsan of Banu Asad ibn Khuzayma, told him: She brought a son of hers to the Messenger of Allah (peace be upon him) who had not yet reached the age of eating food. Ubaydullah said: She informed me that this son of hers urinated in the lap of the Messenger of Allah (peace be upon him), so the Messenger of Allah (peace be upon him) called for water and sprinkled it on his garment without washing it thoroughly.',de:'Harmala ibn Yahya überlieferte ihn mir. Ibn Wahb berichtete uns. Yunus ibn Yazid berichtete mir, dass Ibn Shihab ihm berichtete. Ubaydullah ibn Abdullah ibn Utba ibn Masud berichtete mir, dass Umm Qays bint Mihsan, eine der frühen Auswanderinnen, die dem Gesandten Allahs (Friede sei auf ihm) den Treueid leisteten, und die Schwester von Ukasha ibn Mihsan von den Banu Asad ibn Khuzayma, ihm erzählte: Sie brachte einen ihrer Söhne zum Gesandten Allahs (Friede sei auf ihm), der noch nicht alt genug war, Nahrung zu essen. Ubaydullah sagte: Sie berichtete mir, dass dieser ihr Sohn in den Schoß des Gesandten Allahs (Friede sei auf ihm) urinierte. Da ließ der Gesandte Allahs (Friede sei auf ihm) Wasser bringen und spritzte es auf sein Gewand, ohne es gründlich zu waschen.'},
'https://sunnah.com/muslim:287d':{en:'Yahya ibn Yahya al-Tamimi, Abu Bakr ibn Abi Shayba, Amr al-Naqid, Zuhayr ibn Harb, and Ibn Abi Umar narrated to us, and this is Zuhayr\'s wording. Yahya said: He informed us, while the others said: Sufyan ibn Uyayna narrated to us, from al-Zuhri, from Ubaydullah ibn Abdullah, from Umm Qays bint Mihsan, the sister of Ukasha ibn Mihsan, who said: I entered upon the Messenger of Allah (peace be upon him) with a son of mine who had not eaten food. He urinated on him, so he called for water and sprinkled it over him. She said: I also entered upon him with a son of mine on whom I had hung a talisman for a throat ailment. He said: Why do you strangle your children with this talisman? Use Indian costus, for it contains seven remedies. Among them is pleurisy: it is inhaled for a throat ailment and administered from the side of the mouth for pleurisy.',de:'Yahya ibn Yahya al-Tamimi, Abu Bakr ibn Abi Shayba, Amr al-Naqid, Zuhayr ibn Harb und Ibn Abi Umar überlieferten uns, und dies ist Zuhayrs Wortlaut. Yahya sagte: Er berichtete uns, während die anderen sagten: Sufyan ibn Uyayna überlieferte uns, von al-Zuhri, von Ubaydullah ibn Abdullah, von Umm Qays bint Mihsan, der Schwester von Ukasha ibn Mihsan, die sagte: Ich trat beim Gesandten Allahs (Friede sei auf ihm) mit einem Sohn von mir ein, der noch keine Nahrung gegessen hatte. Er urinierte auf ihn, da ließ er Wasser bringen und spritzte es über ihn. Sie sagte: Ich trat auch mit einem Sohn von mir bei ihm ein, dem ich wegen einer Halskrankheit einen Anhänger umgehängt hatte. Er sagte: Warum würgt ihr eure Kinder mit diesem Anhänger? Verwendet indische Kostuswurzel, denn sie enthält sieben Heilmittel. Eines davon ist Brustfellentzündung: Bei einer Halskrankheit wird sie eingesogen und bei Brustfellentzündung seitlich in den Mund eingegeben.'},
'https://sunnah.com/muslim:288a':{en:'Yahya ibn Yahya narrated to us. Khalid ibn Abdullah informed us, from Khalid, from Abu Ma\'shar, from Ibrahim, from Alqama and al-Aswad, that a man stayed with Aisha and woke up washing his garment. Aisha said: It would have been enough for you, if you saw it, to wash the place affected. If you did not see it, you could sprinkle water around it. I saw myself rubbing it from the garment of the Messenger of Allah (peace be upon him), and he prayed in it.',de:'Yahya ibn Yahya überlieferte uns. Khalid ibn Abdullah berichtete uns, von Khalid, von Abu Ma\'shar, von Ibrahim, von Alqama und al-Aswad, dass ein Mann bei Aisha übernachtete und am Morgen sein Gewand wusch. Aisha sagte: Es hätte dir genügt, wenn du es gesehen hättest, die betroffene Stelle zu waschen. Wenn du es nicht gesehen hättest, hättest du Wasser um sie herum spritzen können. Ich selbst sah, wie ich es aus dem Gewand des Gesandten Allahs (Friede sei auf ihm) herausrieb, und er betete darin.'},
'https://sunnah.com/muslim:288b':{en:'Umar ibn Hafs ibn Ghiyath narrated to us. My father narrated to us, from al-Amash, from Ibrahim, from al-Aswad and Hammam, from Aisha, regarding sexual fluid. She said: I used to rub it from the garment of the Messenger of Allah (peace be upon him).',de:'Umar ibn Hafs ibn Ghiyath überlieferte uns. Mein Vater überlieferte uns, von al-Amash, von Ibrahim, von al-Aswad und Hammam, von Aisha, über Samenflüssigkeit. Sie sagte: Ich pflegte sie aus dem Gewand des Gesandten Allahs (Friede sei auf ihm) herauszureiben.'},
'https://sunnah.com/muslim:288c':{en:'Qutayba ibn Said narrated to us. Hammad, meaning ibn Zayd, narrated to us, from Hisham ibn Hassan. Ishaq ibn Ibrahim also narrated to us: Abda ibn Sulayman informed us. Ibn Abi Aruba narrated to us. All of them narrated from Abu Ma\'shar. Abu Bakr ibn Abi Shayba also narrated to us: Hushaym narrated to us, from Mughira. Muhammad ibn Hatim narrated to me: Abd al-Rahman ibn Mahdi narrated to us, from Mahdi ibn Maymun, from Wasil al-Ahdab. Ibn Hatim also narrated to me: Ishaq ibn Mansur narrated to us. Israil narrated to us, from Mansur and Mughira. All of these narrated from Ibrahim, from al-Aswad, from Aisha, concerning scraping sexual fluid from the garment of the Messenger of Allah (peace be upon him), with a report like Khalid\'s hadith from Abu Ma\'shar.',de:'Qutayba ibn Said überlieferte uns. Hammad, gemeint ist ibn Zayd, überlieferte uns, von Hisham ibn Hassan. Auch Ishaq ibn Ibrahim überlieferte uns: Abda ibn Sulayman berichtete uns. Ibn Abi Aruba überlieferte uns. Alle überlieferten von Abu Ma\'shar. Auch Abu Bakr ibn Abi Shayba überlieferte uns: Hushaym überlieferte uns, von Mughira. Muhammad ibn Hatim überlieferte mir: Abd al-Rahman ibn Mahdi überlieferte uns, von Mahdi ibn Maymun, von Wasil al-Ahdab. Auch Ibn Hatim überlieferte mir: Ishaq ibn Mansur überlieferte uns. Israil überlieferte uns, von Mansur und Mughira. Alle diese überlieferten von Ibrahim, von al-Aswad, von Aisha, über das Abkratzen von Samenflüssigkeit aus dem Gewand des Gesandten Allahs (Friede sei auf ihm), mit einem Bericht wie dem Hadith von Khalid von Abu Ma\'shar.'},
'https://sunnah.com/muslim:288d':{en:'Muhammad ibn Hatim narrated to me. Ibn Uyayna narrated to us, from Mansur, from Ibrahim, from Hammam, from Aisha, with a report like theirs.',de:'Muhammad ibn Hatim überlieferte mir. Ibn Uyayna überlieferte uns, von Mansur, von Ibrahim, von Hammam, von Aisha, mit einem Bericht wie ihren.'},
'https://sunnah.com/muslim:289a':{en:'Abu Bakr ibn Abi Shayba narrated to us. Muhammad ibn Bishr narrated to us, from Amr ibn Maymun, who said: I asked Sulayman ibn Yasar about sexual fluid that gets on a man\'s garment: should he wash it or wash the garment? He said: Aisha informed me that the Messenger of Allah (peace be upon him) used to wash sexual fluid, then go to prayer wearing that garment, while I looked at the mark left by the washing on it.',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Muhammad ibn Bishr überlieferte uns, von Amr ibn Maymun, der sagte: Ich fragte Sulayman ibn Yasar über Samenflüssigkeit, die auf das Gewand eines Mannes gelangt: Soll er sie waschen oder das Gewand waschen? Er sagte: Aisha berichtete mir, dass der Gesandte Allahs (Friede sei auf ihm) die Samenflüssigkeit zu waschen pflegte und dann in diesem Gewand zum Gebet ging, während ich die Waschspur darauf sah.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-214-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-214-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
