import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:Record<string,{en:string;de:string}>={
'https://sunnah.com/muslim:355b':{en:'Ahmad ibn Isa narrated to me. Ibn Wahb narrated to us. Amr informed me, from Ibn Shihab, from Jafar ibn Amr ibn Umayya al-Damri, from his father, who said: I saw the Messenger of Allah (peace be upon him) cutting meat from a sheep’s shoulder and eating from it. Then he was called to prayer, so he stood, put down the knife, and prayed without performing wudu. Ibn Shihab said: Ali ibn Abdullah ibn Abbas narrated to me, from his father, from the Messenger of Allah (peace be upon him), with the same meaning.',de:'Ahmad ibn Isa überlieferte mir. Ibn Wahb überlieferte uns. Amr berichtete mir, von Ibn Shihab, von Jafar ibn Amr ibn Umayya al-Damri, von dessen Vater, der sagte: Ich sah den Gesandten Allahs (Friede sei auf ihm), wie er Fleisch von der Schulter eines Schafs schnitt und davon aß. Dann wurde er zum Gebet gerufen, worauf er aufstand, das Messer niederlegte und betete, ohne Wudu zu verrichten. Ibn Shihab sagte: Ali ibn Abdullah ibn Abbas überlieferte mir, von dessen Vater, vom Gesandten Allahs (Friede sei auf ihm), mit derselben Bedeutung.'},
'https://sunnah.com/muslim:356a':{en:'Amr said: Bukayr ibn al-Ashajj narrated to me, from Kurayb, the client of Ibn Abbas, from Maymuna, the wife of the Prophet (peace be upon him), that the Prophet (peace be upon him) ate a shoulder at her house, then prayed without performing wudu.',de:'Amr sagte: Bukayr ibn al-Ashajj überlieferte mir, von Kurayb, dem Schutzbefohlenen von Ibn Abbas, von Maymuna, der Ehefrau des Propheten (Friede sei auf ihm), dass der Prophet (Friede sei auf ihm) bei ihr eine Schulter aß und dann betete, ohne Wudu zu verrichten.'},
'https://sunnah.com/muslim:356b':{en:'Amr said: Jafar ibn Rabia narrated to me, from Yaqob ibn al-Ashajj, from Kurayb, the client of Ibn Abbas, from Maymuna, the wife of the Prophet (peace be upon him), with the same meaning.',de:'Amr sagte: Jafar ibn Rabia überlieferte mir, von Yaqob ibn al-Ashajj, von Kurayb, dem Schutzbefohlenen von Ibn Abbas, von Maymuna, der Ehefrau des Propheten (Friede sei auf ihm), mit derselben Bedeutung.'},
'https://sunnah.com/muslim:357':{en:'Amr said: Said ibn Abi Hilal narrated to me, from Abdullah ibn Ubayd Allah ibn Abi Rafi, from Abu Ghutfan, from Abu Rafi, who said: I testify that I used to roast the belly of a sheep for the Messenger of Allah (peace be upon him). Then he prayed without performing wudu.',de:'Amr sagte: Said ibn Abi Hilal überlieferte mir, von Abdullah ibn Ubayd Allah ibn Abi Rafi, von Abu Ghutfan, von Abu Rafi, der sagte: Ich bezeuge, dass ich für den Gesandten Allahs (Friede sei auf ihm) den Bauch eines Schafs zu braten pflegte. Dann betete er, ohne Wudu zu verrichten.'},
'https://sunnah.com/muslim:358a':{en:'Qutayba ibn Said narrated to us. Layth narrated to us, from Uqayl, from al-Zuhri, from Ubayd Allah ibn Abdullah, from Ibn Abbas, that the Prophet (peace be upon him) drank milk. Then he called for water, rinsed his mouth, and said: It contains fat.',de:'Qutayba ibn Said überlieferte uns. Layth überlieferte uns, von Uqayl, von al-Zuhri, von Ubayd Allah ibn Abdullah, von Ibn Abbas, dass der Prophet (Friede sei auf ihm) Milch trank. Dann ließ er Wasser bringen, spülte seinen Mund und sagte: Sie enthält Fett.'},
'https://sunnah.com/muslim:358b':{en:'Ahmad ibn Isa narrated to me. Ibn Wahb narrated to us, and Amr informed me. And Zuhayr ibn Harb narrated to me. Yahya ibn Said narrated to us, from al-Awzai. And Harmala ibn Yahya narrated to me. Ibn Wahb informed us. Yunus narrated to me. All of them narrated from Ibn Shihab, with the chain of Uqayl from al-Zuhri, with the same meaning.',de:'Ahmad ibn Isa überlieferte mir. Ibn Wahb überlieferte uns, und Amr berichtete mir. Und Zuhayr ibn Harb überlieferte mir. Yahya ibn Said überlieferte uns, von al-Awzai. Und Harmala ibn Yahya überlieferte mir. Ibn Wahb berichtete uns. Yunus überlieferte mir. Alle überlieferten von Ibn Shihab, mit der Überlieferungskette von Uqayl über al-Zuhri, mit derselben Bedeutung.'},
'https://sunnah.com/muslim:359a':{en:'Ali ibn Hujr narrated to me. Ismail ibn Jafar narrated to us. Muhammad ibn Amr ibn Halhala narrated to us, from Muhammad ibn Amr ibn Ata, from Ibn Abbas, that the Messenger of Allah (peace be upon him) gathered his clothes around himself and went out to prayer. He was brought a gift of bread and meat, ate three mouthfuls, then led the people in prayer, without touching water.',de:'Ali ibn Hujr überlieferte mir. Ismail ibn Jafar überlieferte uns. Muhammad ibn Amr ibn Halhala überlieferte uns, von Muhammad ibn Amr ibn Ata, von Ibn Abbas, dass der Gesandte Allahs (Friede sei auf ihm) seine Kleidung um sich raffte und zum Gebet hinausging. Ihm wurde ein Geschenk aus Brot und Fleisch gebracht. Er aß drei Bissen und leitete dann das Gebet für die Menschen, ohne Wasser zu berühren.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]})); if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-233-part.json',JSON.stringify(out,null,2)); fs.writeFileSync('data/hadith-words-translations/codex-out-233-part.json',JSON.stringify(out,null,2)); console.log(`wrote ${out.length} staged translations`);
