import fs from "node:fs";

type Raw = { id: string; url: string; text_original: string };
type Out = { id: string; n: number; en: string; de: string };

const input = "data/hadith-words-translations/codex-batch-027.json";
const output = "data/hadith-words-translations/codex-out-027.json";
const raw = JSON.parse(fs.readFileSync(input, "utf8")) as Raw[];

const t: Record<number, [string, string]> = {
  2856: [
    "Ishaq ibn Ibrahim narrated to me. He heard Yahya ibn Adam. Abu al-Ahwas narrated to us, from Abu Ishaq, from Amr ibn Maymun, from Muadh, may Allah be pleased with him, who said: I was riding behind the Prophet (peace be upon him) on a donkey called Ufair. He said: O Muadh, do you know Allah's right over His servants and the servants' right over Allah? I said: Allah and His Messenger know best. He said: Allah's right over the servants is that they worship Him and associate nothing with Him, and the servants' right over Allah is that He does not punish whoever associates nothing with Him. I said: O Messenger of Allah, should I not tell the people about it? He said: Do not tell them, lest they rely on it.",
    "Ishaq ibn Ibrahim berichtete mir. Er hörte Yahya ibn Adam. Abu al-Ahwas überlieferte uns, von Abu Ishaq, von Amr ibn Maymun, von Muadh, möge Allah mit ihm zufrieden sein, der sagte: Ich ritt hinter dem Propheten (Friede sei auf ihm) auf einem Esel namens Ufair. Er sagte: O Muadh, weißt du, welches Recht Allah über Seine Diener und welches Recht die Diener über Allah haben? Ich sagte: Allah und Sein Gesandter wissen es besser. Er sagte: Allahs Recht über die Diener ist, dass sie Ihn anbeten und Ihm nichts beigesellen, und das Recht der Diener über Allah ist, dass Er denjenigen nicht bestraft, der Ihm nichts beigesellt. Ich sagte: O Gesandter Allahs, soll ich den Menschen nicht davon berichten? Er sagte: Berichte es ihnen nicht, damit sie sich nicht darauf verlassen.",
  ],
  2857: [
    "Muhammad ibn Bashshar narrated to us. Ghundar narrated to us. Shu'ba narrated to us. I heard Qatada, from Anas ibn Malik, may Allah be pleased with him, who said: There was an alarm in Medina, so the Prophet (peace be upon him) borrowed a horse of ours called Mandub. He said: We saw no cause for alarm, and we found it to be a sea.",
    "Muhammad ibn Bashshar überlieferte uns. Ghundar überlieferte uns. Shu'ba überlieferte uns. Ich hörte Qatada, von Anas ibn Malik, möge Allah mit ihm zufrieden sein, der sagte: In Medina gab es einen Alarm, da lieh sich der Prophet (Friede sei auf ihm) ein Pferd von uns namens Mandub. Er sagte: Wir sahen keinen Grund zur Beunruhigung, und wir fanden es wie ein Meer.",
  ],
  2858: [
    "Abu al-Yaman informed us. Shu'ayb informed us, from al-Zuhri, who said: Salim ibn Abdullah informed me that Abdullah ibn Umar, may Allah be pleased with them, said: I heard the Prophet (peace be upon him) say: Bad luck is only in three things: the horse, the woman, and the house.",
    "Abu al-Yaman informierte uns. Shu'ayb informierte uns, von al-Zuhri, der sagte: Salim ibn Abdullah berichtete mir, dass Abdullah ibn Umar, möge Allah mit ihnen zufrieden sein, sagte: Ich hörte den Propheten (Friede sei auf ihm) sagen: Unglück gibt es nur in drei Dingen: im Pferd, in der Frau und im Haus.",
  ],
  2859: [
    "Abdullah ibn Maslama narrated to us, from Malik, from Abu Hazim ibn Dinar, from Sahl ibn Sa'd al-Sa'idi, may Allah be pleased with him, that the Messenger of Allah (peace be upon him) said: If there is anything in which bad luck lies, it is the woman, the horse, and the dwelling.",
    "Abdullah ibn Maslama überlieferte uns, von Malik, von Abu Hazim ibn Dinar, von Sahl ibn Sa'd al-Sa'idi, möge Allah mit ihm zufrieden sein, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn es überhaupt etwas gibt, in dem Unglück liegt, dann sind es die Frau, das Pferd und die Wohnung.",
  ],
  2860: [
    "Abdullah ibn Maslama narrated to us, from Malik, from Zayd ibn Aslam, from Abu Salih al-Samman, from Abu Hurayra, may Allah be pleased with him, that the Messenger of Allah (peace be upon him) said: Horses are for three: for one man they are a reward, for one man a protection, and against one man a burden. The one for whom they are a reward is a man who ties them in the cause of Allah and lets them run at length in a pasture or garden. Whatever they eat in that pasture or garden is good deeds for him. If they break their tether and climb a hill or two, their dung and tracks are good deeds for him. If they pass by a river and drink from it, even though he did not intend to water them, that is good deeds for him. Another man ties them out of pride, showing off, and opposition to the people of Islam, and they are a burden against him. The Messenger of Allah (peace be upon him) was asked about donkeys and said: Nothing has been revealed to me concerning them except this comprehensive, singular verse: (Quran 99:7-8) Whoever does an atom's weight of good will see it, and whoever does an atom's weight of evil will see it.",
    "Abdullah ibn Maslama überlieferte uns, von Malik, von Zayd ibn Aslam, von Abu Salih al-Samman, von Abu Hurayra, möge Allah mit ihm zufrieden sein, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Pferde sind für drei bestimmt: Für einen Mann sind sie eine Belohnung, für einen Mann ein Schutz und gegen einen Mann eine Last. Derjenige, für den sie eine Belohnung sind, ist ein Mann, der sie auf Allahs Weg anbindet und sie lange auf einer Weide oder in einem Garten laufen lässt. Was sie auf dieser Weide oder in diesem Garten fressen, sind gute Taten für ihn. Wenn sie ihr Seil durchtrennen und einen oder zwei Hügel hinaufsteigen, sind ihr Mist und ihre Spuren gute Taten für ihn. Wenn sie an einem Fluss vorbeikommen und daraus trinken, obwohl er nicht beabsichtigt hatte, sie zu tränken, ist das für ihn eine gute Tat. Ein anderer Mann bindet sie aus Stolz, Angeberei und Feindschaft gegen die Muslime an, und sie sind eine Last gegen ihn. Der Gesandte Allahs (Friede sei auf ihm) wurde nach Eseln gefragt und sagte: Über sie wurde mir nichts offenbart außer diesem umfassenden, einzigartigen Vers: (Quran 99:7-8) Wer das Gewicht eines Staubkorns an Gutem tut, wird es sehen, und wer das Gewicht eines Staubkorns an Bösem tut, wird es sehen.",
  ],
  2861: [
    "Muslim narrated to us. Abu Aqil narrated to us. Abu al-Mutawakkil al-Naji said: I went to Jabir ibn Abdullah al-Ansari and said: Tell me what you heard from the Messenger of Allah (peace be upon him). He said: I traveled with him on one of his journeys. Abu Aqil said: I do not know whether it was an expedition or an Umrah. When we approached, the Prophet (peace be upon him) said: Whoever wants to hurry to his family, let him hurry. Jabir said: We set out, and I was on a dark-gray camel of mine without a distinguishing mark, with the people behind me. While I was in that state, he came up behind me, and the Prophet (peace be upon him) said: Hold on, Jabir. He struck it once with his whip, and the camel leapt forward. He said: Will you sell the camel? I said: Yes. When we reached Medina and the Prophet (peace be upon him) entered the mosque among groups of his Companions, I came to him and tied the camel at the edge of the paved courtyard. I said: This is your camel. He came out and began walking around it, saying: The camel is ours. Then the Prophet (peace be upon him) sent some gold coins and said: Give them to Jabir. Then he said: Have you received the full price? I said: Yes. He said: The price and the camel are yours.",
    "Muslim überlieferte uns. Abu Aqil überlieferte uns. Abu al-Mutawakkil al-Naji sagte: Ich ging zu Jabir ibn Abdullah al-Ansari und sagte: Berichte mir, was du vom Gesandten Allahs (Friede sei auf ihm) gehört hast. Er sagte: Ich reiste auf einer seiner Reisen mit ihm. Abu Aqil sagte: Ich weiß nicht, ob es ein Feldzug oder eine Umra war. Als wir uns näherten, sagte der Prophet (Friede sei auf ihm): Wer zu seiner Familie eilen möchte, soll eilen. Jabir sagte: Wir zogen weiter, und ich saß auf meinem dunkelgrauen Kamel ohne besonderes Kennzeichen, während die Menschen hinter mir waren. Während ich so war, holte er mich ein, und der Prophet (Friede sei auf ihm) sagte zu mir: Halt dich fest, Jabir. Er schlug es einmal mit seiner Peitsche, und das Kamel sprang vor. Er sagte: Verkaufst du das Kamel? Ich sagte: Ja. Als wir Medina erreichten und der Prophet (Friede sei auf ihm) mit Gruppen seiner Gefährten die Moschee betrat, kam ich zu ihm und band das Kamel am Rand des gepflasterten Hofes an. Ich sagte: Das ist dein Kamel. Er kam heraus und ging um es herum, wobei er sagte: Das Kamel gehört uns. Dann schickte der Prophet (Friede sei auf ihm) einige Goldmünzen und sagte: Gib sie Jabir. Dann sagte er: Hast du den vollständigen Preis erhalten? Ich sagte: Ja. Er sagte: Der Preis und das Kamel gehören dir.",
  ],
  2862: [
    "Ahmad ibn Muhammad informed us. Abdullah informed us. Shu'ba informed us, from Qatada. I heard Anas ibn Malik, may Allah be pleased with him, say: There was an alarm in Medina, so the Prophet (peace be upon him) borrowed a horse from Abu Talha called Mandub, rode it, and said: We saw no cause for alarm, and we found it to be a sea.",
    "Ahmad ibn Muhammad informierte uns. Abdullah informierte uns. Shu'ba informierte uns, von Qatada. Ich hörte Anas ibn Malik, möge Allah mit ihm zufrieden sein, sagen: In Medina gab es einen Alarm, da lieh sich der Prophet (Friede sei auf ihm) ein Pferd von Abu Talha namens Mandub, bestieg es und sagte: Wir sahen keinen Grund zur Beunruhigung, und wir fanden es wie ein Meer.",
  ],
  2863: [
    "Ubayd ibn Isma'il narrated to us, from Abu Usama, from Ubaydullah, from Nafi, from Ibn Umar, may Allah be pleased with them, that the Messenger of Allah (peace be upon him) allotted two shares for a horse and one share for its rider. Malik said: Shares are allotted to horses, including packhorses, because of His saying: (Quran 16:8) And horses, mules, and donkeys for you to ride. No more than one horse is allotted a share.",
    "Ubayd ibn Isma'il überlieferte uns, von Abu Usama, von Ubaydullah, von Nafi, von Ibn Umar, möge Allah mit ihnen zufrieden sein, dass der Gesandte Allahs (Friede sei auf ihm) dem Pferd zwei Anteile und seinem Reiter einen Anteil zuteilte. Malik sagte: Pferden, einschließlich Lastpferden, werden Anteile zugeteilt, wegen Seiner Aussage: (Quran 16:8) Und Pferde, Maultiere und Esel, damit ihr auf ihnen reitet. Für mehr als ein Pferd wird kein Anteil zugeteilt.",
  ],
  2864: [
    "Qutayba narrated to us. Sahl ibn Yusuf narrated to us, from Shu'ba, from Abu Ishaq. A man said to al-Bara ibn Azib, may Allah be pleased with them: Did you flee from the Messenger of Allah (peace be upon him) on the day of Hunayn? He said: No, by Allah. The Messenger of Allah (peace be upon him) did not flee, but the quick ones among the people fled. Hawazin met them with arrows, and the Messenger of Allah (peace be upon him) was on his white mule, while Abu Sufyan held its bridle. The Prophet (peace be upon him) was saying: I am the Prophet, no lie; I am the son of Abd al-Muttalib.",
    "Qutayba überlieferte uns. Sahl ibn Yusuf überlieferte uns, von Shu'ba, von Abu Ishaq. Ein Mann sagte zu al-Bara ibn Azib, möge Allah mit ihnen zufrieden sein: Seid ihr am Tag von Hunayn vor dem Gesandten Allahs (Friede sei auf ihm) geflohen? Er sagte: Nein, bei Allah. Der Gesandte Allahs (Friede sei auf ihm) floh nicht, sondern die Schnellen unter den Menschen flohen. Hawazin empfing sie mit Pfeilen, und der Gesandte Allahs (Friede sei auf ihm) saß auf seinem weißen Maultier, während Abu Sufyan dessen Zügel hielt. Der Prophet (Friede sei auf ihm) sagte: Ich bin der Prophet, kein Lügner; ich bin der Sohn von Abd al-Muttalib.",
  ],
  2865: [
    "Ubayd ibn Isma'il narrated to me, from Abu Usama, from Ubaydullah, from Nafi, from Ibn Umar, may Allah be pleased with them, from the Prophet (peace be upon him): When he put his foot in the stirrup and his she-camel stood upright with him, he raised his voice with the pilgrimage declaration from beside the mosque of Dhu al-Hulayfa.",
    "Ubayd ibn Isma'il berichtete mir, von Abu Usama, von Ubaydullah, von Nafi, von Ibn Umar, möge Allah mit ihnen zufrieden sein, vom Propheten (Friede sei auf ihm): Wenn er seinen Fuß in den Steigbügel setzte und seine Kamelstute mit ihm aufrecht stand, sprach er neben der Moschee von Dhu al-Hulayfa die Pilgerformel laut aus.",
  ],
  2866: [
    "Amr ibn Awn narrated to us. Hammad narrated to us, from Thabit, from Anas, may Allah be pleased with him: The Prophet (peace be upon him) met them riding an unsaddled horse, with a sword around his neck.",
    "Amr ibn Awn überlieferte uns. Hammad überlieferte uns, von Thabit, von Anas, möge Allah mit ihm zufrieden sein: Der Prophet (Friede sei auf ihm) begegnete ihnen auf einem Pferd ohne Sattel, mit einem Schwert um den Hals.",
  ],
  2867: [
    "Abd al-A'la ibn Hammad narrated to us. Yazid ibn Zuray narrated to us. Sa'id narrated to us, from Qatada, from Anas ibn Malik, may Allah be pleased with him, that the people of Medina were alarmed once. The Prophet (peace be upon him) rode a horse belonging to Abu Talha that was cropping, or had been cropped. When he returned, he said: We found this horse of yours to be a sea. After that, it could not be raced.",
    "Abd al-A'la ibn Hammad überlieferte uns. Yazid ibn Zuray überlieferte uns. Sa'id überlieferte uns, von Qatada, von Anas ibn Malik, möge Allah mit ihm zufrieden sein, dass die Bewohner von Medina einmal erschraken. Der Prophet (Friede sei auf ihm) bestieg ein Pferd von Abu Talha, das gerade graste oder dessen Weide abgefressen war. Als er zurückkehrte, sagte er: Wir fanden dieses euer Pferd wie ein Meer. Danach konnte es nicht mehr übertroffen werden.",
  ],
  2868: [
    "Qabisa narrated to us. Sufyan narrated to us, from Ubaydullah, from Nafi, from Ibn Umar, may Allah be pleased with them, who said: The Prophet (peace be upon him) raced the trained horses from al-Hafya to Thaniyyat al-Wada, and he raced the untrained horses from the pass to the mosque of Banu Zurayq. Ibn Umar said: I was among those who raced. Abdullah said: Sufyan narrated to us. He said: Ubaydullah narrated to me. Sufyan said: Between al-Hafya and Thaniyyat al-Wada are five or six miles, and between the pass and the mosque of Banu Zurayq is one mile.",
    "Qabisa überlieferte uns. Sufyan überlieferte uns, von Ubaydullah, von Nafi, von Ibn Umar, möge Allah mit ihnen zufrieden sein, der sagte: Der Prophet (Friede sei auf ihm) ließ die trainierten Pferde von al-Hafya bis Thaniyyat al-Wada laufen und die nicht trainierten Pferde vom Pass bis zur Moschee von Banu Zurayq. Ibn Umar sagte: Ich gehörte zu denen, die liefen. Abdullah sagte: Sufyan überlieferte uns. Er sagte: Ubaydullah berichtete mir. Sufyan sagte: Zwischen al-Hafya und Thaniyyat al-Wada liegen fünf oder sechs Meilen, und zwischen dem Pass und der Moschee von Banu Zurayq liegt eine Meile.",
  ],
  2869: [
    "Ahmad ibn Yunus narrated to us. al-Layth narrated to us, from Nafi, from Abdullah, may Allah be pleased with him, that the Prophet (peace be upon him) raced the horses that had not been trained, and their course was from the pass to the mosque of Banu Zurayq. Abdullah ibn Umar used to race them. Abu Abdullah said: The course means the finish line; the course was made long for them.",
    "Ahmad ibn Yunus überlieferte uns. al-Layth überlieferte uns, von Nafi, von Abdullah, möge Allah mit ihm zufrieden sein, dass der Prophet (Friede sei auf ihm) die nicht trainierten Pferde um die Wette laufen ließ, und ihre Strecke verlief vom Pass bis zur Moschee von Banu Zurayq. Abdullah ibn Umar pflegte mit ihnen um die Wette zu laufen. Abu Abdullah sagte: Mit Strecke ist das Ziel gemeint; die Strecke wurde für sie verlängert.",
  ],
  2870: [
    "Abdullah ibn Muhammad narrated to us. Muawiya narrated to us. Abu Ishaq narrated to us, from Musa ibn Uqba, from Nafi, from Ibn Umar, may Allah be pleased with them, who said: The Messenger of Allah (peace be upon him) raced the trained horses, releasing them from al-Hafya, with their finish at Thaniyyat al-Wada. I asked Musa: How far was that? He said: Six or seven miles. He raced the untrained horses, releasing them from Thaniyyat al-Wada, with their finish at the mosque of Banu Zurayq. I asked: How far was that? He said: One mile or thereabout. Ibn Umar was among those who raced them.",
    "Abdullah ibn Muhammad überlieferte uns. Muawiya überlieferte uns. Abu Ishaq überlieferte uns, von Musa ibn Uqba, von Nafi, von Ibn Umar, möge Allah mit ihnen zufrieden sein, der sagte: Der Gesandte Allahs (Friede sei auf ihm) ließ die trainierten Pferde um die Wette laufen und ließ sie von al-Hafya los, mit dem Ziel bei Thaniyyat al-Wada. Ich fragte Musa: Wie weit war das? Er sagte: sechs oder sieben Meilen. Er ließ die nicht trainierten Pferde von Thaniyyat al-Wada los, mit dem Ziel bei der Moschee von Banu Zurayq. Ich fragte: Wie weit war das? Er sagte: eine Meile oder ungefähr so viel. Ibn Umar gehörte zu denen, die mit ihnen liefen.",
  ],
  2871: [
    "Abdullah ibn Muhammad narrated to us. Muawiya narrated to us. Abu Ishaq narrated to us, from Humayd, who said: I heard Anas, may Allah be pleased with him, say: The she-camel of the Prophet (peace be upon him) was called al-Adba.",
    "Abdullah ibn Muhammad überlieferte uns. Muawiya überlieferte uns. Abu Ishaq überlieferte uns, von Humayd, der sagte: Ich hörte Anas, möge Allah mit ihm zufrieden sein, sagen: Die Kamelstute des Propheten (Friede sei auf ihm) hieß al-Adba.",
  ],
  2872: [
    "Malik ibn Isma'il narrated to us. Zuhayr narrated to us, from Humayd, from Anas, may Allah be pleased with him, who said: The Prophet (peace be upon him) had a she-camel called al-Adba that was never beaten, or he said, hardly ever beaten. Then a desert Arab came on a young camel and beat it. This was difficult for the Muslims until he recognized it and said: It is Allah's right that nothing of this world rises except that He lowers it. Musa lengthened this narration from Hammad, from Thabit, from Anas, from the Prophet (peace be upon him).",
    "Malik ibn Isma'il überlieferte uns. Zuhayr überlieferte uns, von Humayd, von Anas, möge Allah mit ihm zufrieden sein, der sagte: Der Prophet (Friede sei auf ihm) hatte eine Kamelstute namens al-Adba, die nie besiegt wurde, oder er sagte: kaum je besiegt wurde. Dann kam ein Beduine auf einem jungen Kamel und besiegte sie. Das bedrückte die Muslime, bis er es erkannte und sagte: Es gehört zu Allahs Recht, dass nichts von dieser Welt sich erhebt, ohne dass Er es wieder senkt. Musa gab diese Überlieferung ausführlicher weiter, von Hammad, von Thabit, von Anas, vom Propheten (Friede sei auf ihm).",
  ],
  2873: [
    "Amr ibn Ali narrated to us. Yahya narrated to us. Sufyan narrated to us. He said: Abu Ishaq narrated to me. He said: I heard Amr ibn al-Harith say: The Prophet (peace be upon him) left nothing except his white mule, his weapons, and land that he had left as charity.",
    "Amr ibn Ali überlieferte uns. Yahya überlieferte uns. Sufyan überlieferte uns. Er sagte: Abu Ishaq berichtete mir. Er sagte: Ich hörte Amr ibn al-Harith sagen: Der Prophet (Friede sei auf ihm) hinterließ nichts außer seinem weißen Maultier, seinen Waffen und Land, das er als Almosen hinterlassen hatte.",
  ],
  2874: [
    "Muhammad ibn al-Muthanna narrated to us. Yahya ibn Sa'id narrated to us, from Sufyan. He said: Abu Ishaq narrated to me, from al-Bara, may Allah be pleased with him, that a man said to him: O Abu Umara, did you turn away on the day of Hunayn? He said: No, by Allah. The Prophet (peace be upon him) did not turn away, but the swift people did. Hawazin met them with arrows while the Prophet (peace be upon him) was on his white mule and Abu Sufyan ibn al-Harith held its bridle. The Prophet (peace be upon him) said: I am the Prophet, no lie; I am the son of Abd al-Muttalib.",
    "Muhammad ibn al-Muthanna überlieferte uns. Yahya ibn Sa'id überlieferte uns, von Sufyan. Er sagte: Abu Ishaq berichtete mir, von al-Bara, möge Allah mit ihm zufrieden sein, dass ein Mann zu ihm sagte: O Abu Umara, seid ihr am Tag von Hunayn zurückgewichen? Er sagte: Nein, bei Allah. Der Prophet (Friede sei auf ihm) wich nicht zurück, sondern die schnellen Menschen wichen zurück. Hawazin empfing sie mit Pfeilen, während der Prophet (Friede sei auf ihm) auf seinem weißen Maultier saß und Abu Sufyan ibn al-Harith dessen Zügel hielt. Der Prophet (Friede sei auf ihm) sagte: Ich bin der Prophet, kein Lügner; ich bin der Sohn von Abd al-Muttalib.",
  ],
  2875: [
    "Muhammad ibn Kathir informed us. Sufyan informed us, from Muawiya ibn Ishaq, from Aisha bint Talha, from Aisha, Mother of the Believers, may Allah be pleased with her, who said: I asked the Prophet (peace be upon him) for permission to fight. He said: Your jihad is Hajj. Abdullah ibn al-Walid said: Sufyan narrated to us from Muawiya with this wording.",
    "Muhammad ibn Kathir informierte uns. Sufyan informierte uns, von Muawiya ibn Ishaq, von Aisha bint Talha, von Aisha, der Mutter der Gläubigen, möge Allah mit ihr zufrieden sein, die sagte: Ich bat den Propheten (Friede sei auf ihm) um Erlaubnis zum Kämpfen. Er sagte: Euer Dschihad ist der Hajj. Abdullah ibn al-Walid sagte: Sufyan überlieferte uns von Muawiya mit diesem Wortlaut.",
  ],
  2876: [
    "Qabisa narrated to us. Sufyan narrated to us from Muawiya with this wording. And from Habib ibn Abi Amra, from Aisha bint Talha, from Aisha, Mother of the Believers, from the Prophet (peace be upon him): His wives asked him about jihad, and he said: What an excellent jihad Hajj is.",
    "Qabisa überlieferte uns. Sufyan überlieferte uns von Muawiya mit diesem Wortlaut. Und von Habib ibn Abi Amra, von Aisha bint Talha, von Aisha, der Mutter der Gläubigen, vom Propheten (Friede sei auf ihm): Seine Ehefrauen fragten ihn nach dem Dschihad, und er sagte: Wie vortrefflich der Dschihad, der Hajj, ist.",
  ],
  2877: [
    "Abdullah ibn Muhammad narrated to us. Muawiya ibn Amr narrated to us. Abu Ishaq narrated to us, from Abdullah ibn Abd al-Rahman al-Ansari, who said: I heard Anas, may Allah be pleased with him, say: The Messenger of Allah (peace be upon him) entered upon the daughter of Milhan and reclined with her. Then he laughed. She said: Why are you laughing, O Messenger of Allah? He said: People from my nation will ride the green sea in the cause of Allah; their likeness is that of kings on thrones. She said: O Messenger of Allah, ask Allah to make me one of them. He said: O Allah, make her one of them. Then he returned and laughed, and she said to him the same or something like it, and he said the same to her. She said: Ask Allah to make me one of them. He said: You are among the first, not among the last. Anas said: She married Ubadah ibn al-Samit and sailed the sea with the daughter of Qaraza. When she returned, she mounted her animal, but it stumbled with her, she fell from it, and died.",
    "Abdullah ibn Muhammad überlieferte uns. Muawiya ibn Amr überlieferte uns. Abu Ishaq überlieferte uns, von Abdullah ibn Abd al-Rahman al-Ansari, der sagte: Ich hörte Anas, möge Allah mit ihm zufrieden sein, sagen: Der Gesandte Allahs (Friede sei auf ihm) trat bei der Tochter von Milhan ein und lehnte sich bei ihr zurück. Dann lachte er. Sie sagte: Warum lachst du, o Gesandter Allahs? Er sagte: Menschen aus meiner Gemeinschaft werden auf dem grünen Meer auf Allahs Weg fahren; ihr Gleichnis ist das von Königen auf Thronen. Sie sagte: O Gesandter Allahs, bitte Allah, mich zu einer von ihnen zu machen. Er sagte: O Allah, mache sie zu einer von ihnen. Dann kam er wieder und lachte, und sie sagte zu ihm dasselbe oder etwas Ähnliches, worauf er ihr dasselbe sagte. Sie sagte: Bitte Allah, mich zu einer von ihnen zu machen. Er sagte: Du gehörst zu den Ersten und nicht zu den Letzten. Anas sagte: Sie heiratete Ubadah ibn al-Samit und fuhr mit der Tochter von Qaraza über das Meer. Als sie zurückkehrte, bestieg sie ihr Reittier, doch es stolperte mit ihr, sie fiel herab und starb.",
  ],
  2879: [
    "Hajjaj ibn Minhal narrated to us. Abdullah ibn Umar al-Numayri narrated to us. Yunus narrated to us. He said: I heard al-Zuhri say: I heard Urwa ibn al-Zubayr, Sa'id ibn al-Musayyab, Alqama ibn Waqqas, and Ubaydullah ibn Abdullah relating from the report of Aisha. Each related part of the report. She said: When the Prophet (peace be upon him) wanted to go out, he drew lots among his wives. Whichever one's lot came out, he took her with him. He drew lots among us on an expedition he made, and my lot came out, so I went out with the Prophet (peace be upon him) after the command of hijab had been revealed.",
    "Hajjaj ibn Minhal überlieferte uns. Abdullah ibn Umar al-Numayri überlieferte uns. Yunus überlieferte uns. Er sagte: Ich hörte al-Zuhri sagen: Ich hörte Urwa ibn al-Zubayr, Sa'id ibn al-Musayyab, Alqama ibn Waqqas und Ubaydullah ibn Abdullah von der Überlieferung Aishas berichten. Jeder von ihnen berichtete mir einen Teil. Sie sagte: Wenn der Prophet (Friede sei auf ihm) ausziehen wollte, loste er unter seinen Ehefrauen. Wessen Los gezogen wurde, die nahm der Prophet mit. Er loste bei einem Feldzug, den er unternahm, unter uns, und mein Los wurde gezogen. So zog ich mit dem Propheten (Friede sei auf ihm) aus, nachdem das Gebot des Schleiers offenbart worden war.",
  ],
  2880: [
    "Abu Ma'mar narrated to us. Abd al-Warith narrated to us. Abd al-Aziz narrated to us, from Anas, may Allah be pleased with him, who said: On the day of Uhud, when the people fled from the Prophet (peace be upon him), he said: I saw Aisha bint Abi Bakr and Umm Sulaym, both with their sleeves rolled up, and I could see their anklets. They were carrying water skins on their backs, or, according to another wording, transferring the water skins, pouring their contents into the mouths of the people, then returning, filling them, and coming back to pour them into the mouths of the people.",
    "Abu Ma'mar überlieferte uns. Abd al-Warith überlieferte uns. Abd al-Aziz überlieferte uns, von Anas, möge Allah mit ihm zufrieden sein, der sagte: Am Tag von Uhud, als die Menschen vor dem Propheten (Friede sei auf ihm) flohen, sagte er: Ich sah Aisha bint Abi Bakr und Umm Sulaym, beide mit hochgekrempelten Ärmeln, und ich konnte ihre Knöchel sehen. Sie trugen Wasserschläuche auf ihren Rücken, oder nach einer anderen Fassung trugen sie die Wasserschläuche hin und her, gossen ihren Inhalt in die Münder der Menschen, kehrten dann zurück, füllten sie und kamen wieder, um ihn in die Münder der Menschen zu gießen.",
  ],
  2881: [
    "Abdan informed us. Abdullah informed us. Yunus informed us, from Ibn Shihab. Tha'laba ibn Abi Malik said: Umar ibn al-Khattab, may Allah be pleased with him, distributed cloaks among women from the women of Medina. A good cloak remained, and some of those with him said: O Commander of the Believers, give this to the daughter of the Messenger of Allah (peace be upon him) who is with you, meaning Umm Kulthum bint Ali. Umar said: Umm Sulayt has more right. Umm Sulayt was one of the women of the Helpers who pledged allegiance to the Messenger of Allah (peace be upon him). Umar said: She used to carry water skins for us on the day of Uhud. Abu Abdullah said: The word means she sewed them.",
    "Abdan informierte uns. Abdullah informierte uns. Yunus informierte uns, von Ibn Shihab. Tha'laba ibn Abi Malik sagte: Umar ibn al-Khattab, möge Allah mit ihm zufrieden sein, verteilte Umhänge unter Frauen aus Medina. Ein guter Umhang blieb übrig, und einige der Anwesenden sagten: O Befehlshaber der Gläubigen, gib diesen der Tochter des Gesandten Allahs (Friede sei auf ihm), die bei dir ist, also Umm Kulthum bint Ali. Umar sagte: Umm Sulayt hat mehr Anspruch darauf. Umm Sulayt war eine der Frauen der Helfer, die dem Gesandten Allahs (Friede sei auf ihm) den Treueid geleistet hatten. Umar sagte: Sie pflegte uns am Tag von Uhud die Wasserschläuche zu tragen. Abu Abdullah sagte: Das Wort bedeutet, dass sie sie nähte.",
  ],
  2882: [
    "Ali ibn Abdullah narrated to us. Bishr ibn al-Mufaddal narrated to us. Khalid ibn Dhakwan narrated to us, from al-Rubayyi bint Muawwidh, who said: We were with the Prophet (peace be upon him), giving water, treating the wounded, and carrying the dead back to Medina.",
    "Ali ibn Abdullah überlieferte uns. Bishr ibn al-Mufaddal überlieferte uns. Khalid ibn Dhakwan überlieferte uns, von al-Rubayyi bint Muawwidh, die sagte: Wir waren beim Propheten (Friede sei auf ihm), gaben Wasser, behandelten die Verwundeten und brachten die Toten nach Medina zurück.",
  ],
  2883: [
    "Musaddad narrated to us. Bishr ibn al-Mufaddal narrated to us, from Khalid ibn Dhakwan, from al-Rubayyi bint Muawwidh, who said: We went on expeditions with the Prophet (peace be upon him), giving the people water, serving them, and carrying the wounded and the dead back to Medina.",
    "Musaddad überlieferte uns. Bishr ibn al-Mufaddal überlieferte uns, von Khalid ibn Dhakwan, von al-Rubayyi bint Muawwidh, die sagte: Wir zogen mit dem Propheten (Friede sei auf ihm) auf Feldzüge, gaben den Menschen Wasser, dienten ihnen und brachten die Verwundeten und die Toten nach Medina zurück.",
  ],
  2884: [
    "Muhammad ibn al-Ala narrated to us. Abu Usama narrated to us, from Burayd ibn Abdullah, from Abu Burda, from Abu Musa, may Allah be pleased with him, who said: Abu Amir was struck in the knee by an arrow. I came to him, and he said: Pull out this arrow. I pulled it out, and water spurted from it. I entered upon the Prophet (peace be upon him) and told him, so he said: O Allah, forgive Ubayd, Abu Amir.",
    "Muhammad ibn al-Ala überlieferte uns. Abu Usama überlieferte uns, von Burayd ibn Abdullah, von Abu Burda, von Abu Musa, möge Allah mit ihm zufrieden sein, der sagte: Abu Amir wurde von einem Pfeil im Knie getroffen. Ich kam zu ihm, und er sagte: Zieh diesen Pfeil heraus. Ich zog ihn heraus, und Wasser spritzte daraus. Ich ging zum Propheten (Friede sei auf ihm) und berichtete ihm, worauf er sagte: O Allah, vergib Ubayd, Abu Amir.",
  ],
  2885: [
    "Isma'il ibn Khalil informed us. Ali ibn Mushir informed us. Yahya ibn Sa'id informed us. Abdullah ibn Amir ibn Rabi'a informed us. He said: I heard Aisha, may Allah be pleased with her, say: The Prophet (peace be upon him) stayed awake, and when he reached Medina he said: I wish a righteous man from my Companions would guard me tonight. Then we heard the sound of weapons. He said: Who is that? He said: I am Sa'd ibn Abi Waqqas; I have come to guard you. Then the Prophet (peace be upon him) slept.",
    "Isma'il ibn Khalil informierte uns. Ali ibn Mushir informierte uns. Yahya ibn Sa'id informierte uns. Abdullah ibn Amir ibn Rabi'a informierte uns. Er sagte: Ich hörte Aisha, möge Allah mit ihr zufrieden sein, sagen: Der Prophet (Friede sei auf ihm) blieb wach, und als er Medina erreichte, sagte er: Ich wünschte, ein rechtschaffener Mann aus meinen Gefährten würde mich heute Nacht bewachen. Da hörten wir das Geräusch von Waffen. Er sagte: Wer ist das? Er sagte: Ich bin Sa'd ibn Abi Waqqas; ich bin gekommen, um dich zu bewachen. Dann schlief der Prophet (Friede sei auf ihm).",
  ],
  2886: [
    "Yahya ibn Yusuf informed us. Abu Bakr informed us, from Abu Husayn, from Abu Salih, from Abu Hurayra, may Allah be pleased with him, from the Prophet (peace be upon him), who said: Wretched is the servant of the dinar, the dirham, the fine cloth, and the striped cloak. If he is given, he is pleased, and if he is not given, he is displeased. Israel did not attribute this wording to the Prophet from Abu Husayn.",
    "Yahya ibn Yusuf informierte uns. Abu Bakr informierte uns, von Abu Husayn, von Abu Salih, von Abu Hurayra, möge Allah mit ihm zufrieden sein, vom Propheten (Friede sei auf ihm), der sagte: Elend ist der Diener des Dinars, des Dirhams, des feinen Stoffes und des gestreiften Mantels. Wenn ihm gegeben wird, ist er zufrieden, und wenn ihm nicht gegeben wird, ist er unzufrieden. Israel führte diesen Wortlaut von Abu Husayn nicht auf den Propheten zurück.",
  ],
};

const out: Out[] = raw.map((row) => {
  const n = Number(row.url.split(":").pop());
  const pair = t[n];
  if (!pair) throw new Error(`Missing translation for ${row.url}`);
  return { id: row.id, n, en: pair[0], de: pair[1] };
});

fs.writeFileSync(output, JSON.stringify(out, null, 2) + "\n", "utf8");
console.log(`wrote ${out.length} translations to ${output}`);
