import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:325a':{en:'Ubaydullah ibn Muadh narrated to us. My father narrated to us. Muhammad ibn al-Muthanna also narrated to us. Abd al-Rahman, meaning ibn Mahdi, narrated to us. They both said: Shuba narrated to us, from Abdullah ibn Abdullah ibn Jabr, who said: I heard Anas say: The Messenger of Allah (peace be upon him) used to perform ghusl with five makkuk and wudu with one makkuk. Ibn al-Muthanna said: with five makuk. Ibn Muadh said: from Abdullah ibn Abdullah, without mentioning ibn Jabr.',de:'Ubaydullah ibn Muadh überlieferte uns. Mein Vater überlieferte uns. Auch Muhammad ibn al-Muthanna überlieferte uns. Abd al-Rahman, gemeint ist ibn Mahdi, überlieferte uns. Sie beide sagten: Shuba überlieferte uns, von Abdullah ibn Abdullah ibn Jabr, der sagte: Ich hörte Anas sagen: Der Gesandte Allahs (Friede sei auf ihm) pflegte Ghusl mit fünf Makkuk und Wudu mit einem Makkuk zu verrichten. Ibn al-Muthanna sagte: mit fünf Makuk. Ibn Muadh sagte: von Abdullah ibn Abdullah, ohne ibn Jabr zu erwähnen.'},
'https://sunnah.com/muslim:325b':{en:'Qutayba ibn Said narrated to us. Waki narrated to us, from Misar, from Ibn Jabr, from Anas, who said: The Prophet (peace be upon him) used to perform wudu with a mudd and ghusl with a sa, up to five mudds.',de:'Qutayba ibn Said überlieferte uns. Waki überlieferte uns, von Misar, von Ibn Jabr, von Anas, der sagte: Der Prophet (Friede sei auf ihm) pflegte Wudu mit einem Mudd und Ghusl mit einem Sa, bis zu fünf Mudd, zu verrichten.'},
'https://sunnah.com/muslim:326a':{en:'Abu Kamil al-Jahdari and Amr ibn Ali narrated to us, both from Bishr ibn al-Mufaddal. Abu Kamil said: Bishr narrated to us. Abu Rayhana narrated to us, from Safina, who said: The Messenger of Allah (peace be upon him) was washed with a sa of water for major ritual impurity, and wudu was performed for him with a mudd.',de:'Abu Kamil al-Jahdari und Amr ibn Ali überlieferten uns, beide von Bishr ibn al-Mufaddal. Abu Kamil sagte: Bishr überlieferte uns. Abu Rayhana überlieferte uns, von Safina, der sagte: Für den Gesandten Allahs (Friede sei auf ihm) wurde wegen großer ritueller Unreinheit mit einem Sa Wasser Ghusl verrichtet, und für ihn wurde mit einem Mudd Wudu verrichtet.'},
'https://sunnah.com/muslim:326b':{en:'Abu Bakr ibn Abi Shayba narrated to us. Ibn Ulayya narrated to us. Ali ibn Hujr also narrated to me: Ismail narrated to us, from Abu Rayhana, from Safina, the companion of the Messenger of Allah (peace be upon him), who said: The Messenger of Allah (peace be upon him) used to perform ghusl with a sa and purify himself with a mudd. In Ibn Hujr\'s hadith it says: or he said, the mudd purifies him. He said: He had grown old, and I did not trust his report.',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Ibn Ulayya überlieferte uns. Auch Ali ibn Hujr überlieferte mir: Ismail überlieferte uns, von Abu Rayhana, von Safina, dem Gefährten des Gesandten Allahs (Friede sei auf ihm), der sagte: Der Gesandte Allahs (Friede sei auf ihm) pflegte Ghusl mit einem Sa und die Reinigung mit einem Mudd zu verrichten. In Ibn Hujrs Hadith heißt es: oder er sagte, der Mudd reinigt ihn. Er sagte: Er war alt geworden, und ich vertraute seiner Überlieferung nicht.'},
'https://sunnah.com/muslim:327a':{en:'Yahya ibn Yahya, Qutayba ibn Said, and Abu Bakr ibn Abi Shayba narrated to us. Yahya said: He informed us, while the other two said: Abu al-Ahwas narrated to us, from Abu Ishaq, from Sulayman ibn Surad, from Jubayr ibn Mutim, who said: They disputed about ghusl in the presence of the Messenger of Allah (peace be upon him). One of the people said: As for me, I wash my head this many times. The Messenger of Allah (peace be upon him) said: As for me, I pour three handfuls over my head.',de:'Yahya ibn Yahya, Qutayba ibn Said und Abu Bakr ibn Abi Shayba überlieferten uns. Yahya sagte: Er berichtete uns, während die beiden anderen sagten: Abu al-Ahwas überlieferte uns, von Abu Ishaq, von Sulayman ibn Surad, von Jubayr ibn Mutim, der sagte: In Gegenwart des Gesandten Allahs (Friede sei auf ihm) stritten sie über Ghusl. Einer der Leute sagte: Was mich betrifft, so wasche ich meinen Kopf so und so oft. Der Gesandte Allahs (Friede sei auf ihm) sagte: Was mich betrifft, so gieße ich drei Handvoll über meinen Kopf.'},
'https://sunnah.com/muslim:327b':{en:'Muhammad ibn Bashshar narrated to us. Muhammad ibn Jafar narrated to us. Shuba narrated to us, from Abu Ishaq, from Sulayman ibn Surad, from Jubayr ibn Mutim, from the Prophet (peace be upon him), that ghusl from major ritual impurity was mentioned in his presence, and he said: As for me, I pour three times over my head.',de:'Muhammad ibn Bashshar überlieferte uns. Muhammad ibn Jafar überlieferte uns. Shuba überlieferte uns, von Abu Ishaq, von Sulayman ibn Surad, von Jubayr ibn Mutim, vom Propheten (Friede sei auf ihm), dass in seiner Gegenwart Ghusl wegen großer ritueller Unreinheit erwähnt wurde und er sagte: Was mich betrifft, so gieße ich dreimal über meinen Kopf.'},
'https://sunnah.com/muslim:328':{en:'Yahya ibn Yahya and Ismail ibn Salim narrated to us. They said: Hushaym informed us, from Abu Bishr, from Abu Sufyan, from Jabir ibn Abdullah, that the delegation of Thaqif asked the Prophet (peace be upon him). They said: Our land is cold, so what about ghusl? He said: As for me, I pour three times over my head. Ibn Salim said in his narration: Hushaym narrated to us. Abu Bishr informed us, and he said: The delegation of Thaqif said: O Messenger of Allah.',de:'Yahya ibn Yahya und Ismail ibn Salim überlieferten uns. Sie sagten: Hushaym berichtete uns, von Abu Bishr, von Abu Sufyan, von Jabir ibn Abdullah, dass die Delegation von Thaqif den Propheten (Friede sei auf ihm) fragte. Sie sagten: Unser Land ist kalt, wie ist es dann mit Ghusl? Er sagte: Was mich betrifft, so gieße ich dreimal über meinen Kopf. Ibn Salim sagte in seiner Überlieferung: Hushaym überlieferte uns. Abu Bishr berichtete uns und sagte: Die Delegation von Thaqif sagte: O Gesandter Allahs.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-224-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-224-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
