import fs from "node:fs";

type Raw = { id: string; url: string; text_original: string };
type Out = { id: string; n: number; en: string; de: string };

const input = "data/hadith-words-translations/codex-batch-025.json";
const output = "data/hadith-words-translations/codex-out-025.json";
const raw = JSON.parse(fs.readFileSync(input, "utf8")) as Raw[];

const translations: Record<number, [string, string]> = {
  2794: [
    "Qabisa narrated to us. Sufyan narrated to us, from Abu Hazim, from Sahl ibn Sa'd, may Allah be pleased with him, from the Prophet (peace be upon him), who said: A morning journey and an evening journey in the cause of Allah are better than the world and everything in it.",
    "Qabisa überlieferte uns. Sufyan überlieferte uns, von Abu Hazim, von Sahl ibn Sa'd, möge Allah mit ihm zufrieden sein, vom Propheten (Friede sei auf ihm), der sagte: Eine Reise am Morgen und eine Reise am Abend auf Allahs Weg sind besser als die Welt und alles, was in ihr ist.",
  ],
  2795: [
    "Abdullah ibn Muhammad narrated to us. Muawiya ibn Amr narrated to us. Abu Ishaq narrated to us, from Humayd, who said: I heard Anas ibn Malik, may Allah be pleased with him, from the Prophet (peace be upon him), who said: No servant who has something better with Allah and dies would be pleased to return to the world and have the world and everything in it, except the martyr, because of what he sees of the virtue of martyrdom. He would be pleased to return to the world and be killed once more.",
    "Abdullah ibn Muhammad überlieferte uns. Muawiya ibn Amr überlieferte uns. Abu Ishaq überlieferte uns, von Humayd, der sagte: Ich hörte Anas ibn Malik, möge Allah mit ihm zufrieden sein, vom Propheten (Friede sei auf ihm), der sagte: Kein Diener, der bei Allah etwas Besseres hat und stirbt, würde sich wünschen, in die Welt zurückzukehren und die Welt und alles, was in ihr ist, zu besitzen, außer dem Märtyrer, wegen dessen, was er vom Vorzug des Märtyrertums sieht. Er würde sich wünschen, in die Welt zurückzukehren und noch einmal getötet zu werden.",
  ],
  2796: [
    "I heard Anas ibn Malik, from the Prophet (peace be upon him): A morning journey in the cause of Allah or an evening journey is better than the world and everything in it. The distance of one of your bows in Paradise, or the place of a whip, meaning its strap, is better than the world and everything in it. If a woman from the people of Paradise were to look upon the people of the earth, she would illuminate what is between them and fill it with fragrance, and her head-covering on her head is better than the world and everything in it.",
    "Ich hörte Anas ibn Malik vom Propheten (Friede sei auf ihm): Eine Reise am Morgen auf Allahs Weg oder eine Reise am Abend ist besser als die Welt und alles, was in ihr ist. Die Entfernung eines Bogens von euch im Paradies oder der Platz einer Peitsche, also ihres Riemens, ist besser als die Welt und alles, was in ihr ist. Wenn eine Frau aus den Bewohnern des Paradieses auf die Bewohner der Erde blicken würde, würde sie das, was zwischen ihnen ist, erhellen und es mit Duft erfüllen, und ihr Kopftuch auf ihrem Kopf ist besser als die Welt und alles, was in ihr ist.",
  ],
  2797: [
    "Abu al-Yaman narrated to us. Shu'ayb informed us, from al-Zuhri, who said: Sa'id ibn al-Musayyab informed me that Abu Hurayra, may Allah be pleased with him, said: I heard the Prophet (peace be upon him) say: By Him in whose hand is my soul, were it not that some men among the believers dislike staying behind me, and I cannot find what to carry them on, I would never stay behind a military expedition that goes out in the cause of Allah. By Him in whose hand is my soul, I would love to be killed in the cause of Allah, then brought to life, then killed, then brought to life, then killed, then brought to life, then killed.",
    "Abu al-Yaman überlieferte uns. Shu'ayb informierte uns, von al-Zuhri, der sagte: Sa'id ibn al-Musayyab berichtete mir, dass Abu Hurayra, möge Allah mit ihm zufrieden sein, sagte: Ich hörte den Propheten (Friede sei auf ihm) sagen: Bei Dem, in Dessen Hand meine Seele ist: Wenn nicht einige Männer unter den Gläubigen es ablehnten, hinter mir zurückzubleiben, und ich nicht fände, worauf ich sie tragen könnte, würde ich niemals hinter einem Heerzug zurückbleiben, der auf Allahs Weg auszieht. Bei Dem, in Dessen Hand meine Seele ist: Ich würde gern auf Allahs Weg getötet, dann wieder zum Leben erweckt, dann getötet, dann wieder zum Leben erweckt, dann getötet, dann wieder zum Leben erweckt und dann getötet werden.",
  ],
  2798: [
    "Yusuf ibn Ya'qub al-Saffar narrated to us. Isma'il ibn Ulayya narrated to us, from Ayyub, from Humayd ibn Hilal, from Anas ibn Malik, may Allah be pleased with him, who said: The Prophet (peace be upon him) gave a speech and said: Zayd took the banner and was struck down. Then Ja'far took it and was struck down. Then Abdullah ibn Rawaha took it and was struck down. Then Khalid ibn al-Walid took it without being appointed, and victory was given to him. He said: We would not be pleased that they were with us. Ayyub said, or he said: They would not be pleased that they were with us. His eyes were shedding tears.",
    "Yusuf ibn Ya'qub al-Saffar überlieferte uns. Isma'il ibn Ulayya überlieferte uns, von Ayyub, von Humayd ibn Hilal, von Anas ibn Malik, möge Allah mit ihm zufrieden sein, der sagte: Der Prophet (Friede sei auf ihm) hielt eine Ansprache und sagte: Zayd nahm das Banner und wurde niedergestreckt. Dann nahm Ja'far es und wurde niedergestreckt. Dann nahm Abdullah ibn Rawaha es und wurde niedergestreckt. Dann nahm Khalid ibn al-Walid es, ohne dazu ernannt worden zu sein, und ihm wurde der Sieg gegeben. Er sagte: Wir würden nicht wünschen, dass sie bei uns wären. Ayyub sagte, oder er sagte: Sie würden nicht wünschen, dass sie bei uns wären. Seine Augen vergossen Tränen.",
  ],
  2799: [
    "Abdullah ibn Yusuf narrated to us. He said: al-Layth narrated to me. Yahya narrated to us, from Muhammad ibn Yahya ibn Hibban, from Anas ibn Malik, from his maternal aunt Umm Haram bint Milhan, who said: One day the Prophet (peace be upon him) slept near me, then he woke smiling. I said: What has made you laugh? He said: Some people from my nation were shown to me, sailing on this green sea, like kings on thrones. She said: Supplicate to Allah to make me one of them. So he supplicated for her. Then he slept a second time and did the same, and she said the same as before, so he answered her in the same way. She said: Supplicate to Allah to make me one of them. He said: You are among the first ones. She then went out with her husband, Ubadah ibn al-Samit, as a fighter, when the Muslims first sailed the sea with Muawiya. When they returned from their expedition and stopped in Syria, an animal was brought near her for her to ride, but it threw her down and she died.",
    "Abdullah ibn Yusuf überlieferte uns. Er sagte: al-Layth berichtete mir. Yahya überlieferte uns, von Muhammad ibn Yahya ibn Hibban, von Anas ibn Malik, von seiner Tante mütterlicherseits Umm Haram bint Milhan, die sagte: Eines Tages schlief der Prophet (Friede sei auf ihm) in meiner Nähe, dann wachte er lächelnd auf. Ich sagte: Was bringt dich zum Lachen? Er sagte: Mir wurden einige Menschen aus meiner Gemeinschaft gezeigt, die auf diesem grünen Meer fahren wie Könige auf Thronen. Sie sagte: Bitte Allah, mich zu einer von ihnen zu machen. Da bat er für sie. Dann schlief er ein zweites Mal und tat dasselbe, und sie sagte dasselbe wie zuvor, worauf er ihr ebenso antwortete. Sie sagte: Bitte Allah, mich zu einer von ihnen zu machen. Er sagte: Du gehörst zu den Ersten. Dann zog sie mit ihrem Ehemann Ubadah ibn al-Samit als Kämpferin aus, als die Muslime mit Muawiya zum ersten Mal über das Meer fuhren. Als sie von ihrem Feldzug zurückkehrten und sich in Syrien niederließen, wurde ihr ein Reittier gebracht, damit sie aufstieg, doch es warf sie ab und sie starb.",
  ],
  2801: [
    "Hafs ibn Umar al-Hawdi narrated to us. Hammam narrated to us, from Ishaq, from Anas, may Allah be pleased with him, who said: The Prophet (peace be upon him) sent some men from Banu Sulaym to Banu Amir, seventy in number. When they arrived, my maternal uncle said to them: I will go ahead of you. If they grant me protection so that I can convey to them the message of the Messenger of Allah (peace be upon him), then that is well; otherwise, stay close behind me. He went ahead, and they granted him protection. While he was speaking to them about the Prophet (peace be upon him), they signaled to a man among them, who stabbed him and pierced him through. He said: Allah is the Greatest! I have won, by the Lord of the Ka'bah. Then they turned upon the rest of his companions and killed them, except for a lame man who climbed the mountain. Hammam said: I think another man was with him. Gabriel, peace be upon him, informed the Prophet (peace be upon him) that they had met their Lord, and He was pleased with them and made them pleased. We used to recite: Convey to our people that we have met our Lord, and He was pleased with us and made us pleased. Then this was abrogated later, and he supplicated against them for forty mornings, against Ri'l, Dhakwan, Banu Lihyan, and Banu Usayya, who disobeyed Allah and His Messenger (peace be upon him).",
    "Hafs ibn Umar al-Hawdi überlieferte uns. Hammam überlieferte uns, von Ishaq, von Anas, möge Allah mit ihm zufrieden sein, der sagte: Der Prophet (Friede sei auf ihm) sandte einige Männer von Banu Sulaym zu Banu Amir, siebzig an der Zahl. Als sie ankamen, sagte mein Onkel mütterlicherseits zu ihnen: Ich gehe euch voraus. Wenn sie mir Schutz gewähren, damit ich ihnen die Botschaft des Gesandten Allahs (Friede sei auf ihm) übermitteln kann, dann ist es gut; andernfalls bleibt nahe hinter mir. Er ging voraus, und sie gewährten ihm Schutz. Während er mit ihnen über den Propheten (Friede sei auf ihm) sprach, deuteten sie auf einen Mann unter ihnen, der ihn stach und durchbohrte. Er sagte: Allah ist der Größte! Ich habe gewonnen, beim Herrn der Kaaba. Dann wandten sie sich gegen die übrigen seiner Gefährten und töteten sie, außer einem lahmen Mann, der den Berg hinaufstieg. Hammam sagte: Ich glaube, dass ein anderer Mann bei ihm war. Gabriel, Friede sei auf ihm, teilte dem Propheten (Friede sei auf ihm) mit, dass sie ihrem Herrn begegnet waren, Der mit ihnen zufrieden war und sie zufrieden machte. Wir pflegten zu rezitieren: Übermittelt unserem Volk, dass wir unserem Herrn begegnet sind und Er mit uns zufrieden war und uns zufrieden machte. Später wurde dies aufgehoben, und er sprach vierzig Morgen lang ein Bittgebet gegen sie, gegen Ri'l, Dhakwan, Banu Lihyan und Banu Usayya, die Allah und Seinem Gesandten (Friede sei auf ihm) ungehorsam waren.",
  ],
  2802: [
    "Musa ibn Isma'il narrated to us. Abu Awana narrated to us, from al-Aswad ibn Qays, from Jundub ibn Sufyan, that the Messenger of Allah (peace be upon him) was in one of the battles and his finger was bleeding. He said: You are only a finger that has bled, and what you have suffered is in the cause of Allah.",
    "Musa ibn Isma'il überlieferte uns. Abu Awana überlieferte uns, von al-Aswad ibn Qays, von Jundub ibn Sufyan, dass der Gesandte Allahs (Friede sei auf ihm) bei einem der Feldzüge war und sein Finger blutete. Er sagte: Du bist nur ein Finger, der geblutet hat, und was du erlitten hast, ist auf Allahs Weg.",
  ],
  2803: [
    "Abdullah ibn Yusuf narrated to us. Malik informed us, from Abu al-Zinad, from al-A'raj, from Abu Hurayra, may Allah be pleased with him, that the Messenger of Allah (peace be upon him) said: By Him in whose hand is my soul, no one is wounded in the cause of Allah, and Allah knows best who is wounded in His cause, except that he will come on the Day of Resurrection with the color being the color of blood and the scent being the scent of musk.",
    "Abdullah ibn Yusuf überlieferte uns. Malik informierte uns, von Abu al-Zinad, von al-A'raj, von Abu Hurayra, möge Allah mit ihm zufrieden sein, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Bei Dem, in Dessen Hand meine Seele ist: Niemand wird auf Allahs Weg verwundet, und Allah weiß am besten, wer auf Seinem Weg verwundet wird, ohne dass er am Tag der Auferstehung kommt, wobei die Farbe die Farbe des Blutes und der Duft der Duft von Moschus ist.",
  ],
  2804: [
    "Yahya ibn Bukayr narrated to us. al-Layth narrated to us. He said: Yunus narrated to me, from Ibn Shihab, from Ubaydullah ibn Abdullah, that Abdullah ibn Abbas informed him that Abu Sufyan informed him that Heraclius said to him: I asked you how your fighting with him was, and you claimed that the war between you was alternating, with victory sometimes for one side and sometimes for the other. Such are the messengers: they are tested, then the outcome is theirs.",
    "Yahya ibn Bukayr überlieferte uns. al-Layth überlieferte uns. Er sagte: Yunus berichtete mir, von Ibn Shihab, von Ubaydullah ibn Abdullah, dass Abdullah ibn Abbas ihm berichtete, dass Abu Sufyan ihm berichtete, dass Heraklius zu ihm sagte: Ich fragte dich, wie euer Kampf gegen ihn war, und du behauptetest, dass der Krieg zwischen euch wechselte, wobei der Sieg manchmal auf der einen und manchmal auf der anderen Seite war. So ergeht es den Gesandten: Sie werden geprüft, dann gehört ihnen der Ausgang.",
  ],
  2805: [
    "Muhammad ibn Sa'id al-Khuza'i narrated to us. Abd al-A'la narrated to us, from Humayd, who said: I asked Anas. Amr ibn Zurara narrated to us. Ziyad narrated to us. He said: Humayd al-Tawil narrated to me, from Anas, may Allah be pleased with him, who said: My uncle Anas ibn al-Nadr was absent from the Battle of Badr. He said: O Messenger of Allah, I was absent from the first battle in which you fought the polytheists. If Allah lets me witness a battle against the polytheists, Allah will certainly see what I do. When the day of Uhud came and the Muslims turned away, he said: O Allah, I apologize to You for what these people have done, meaning his companions, and I disassociate myself before You from what these people have done, meaning the polytheists. Then he advanced, and Sa'd ibn Mu'adh met him. He said: O Sa'd ibn Mu'adh, Paradise! By the Lord of al-Nadr, I smell it beyond Uhud. Sa'd said: I could not do what he did, O Messenger of Allah. Anas said: We found on him more than eighty wounds from sword strikes, spear thrusts, or arrows. We found that he had been killed and that the polytheists had mutilated him. No one could recognize him except his sister by her fingertips. Anas said: We used to think, or believe, that this verse was revealed about him and others like him: (Quran 33:23) Among the believers are men who were true to what they pledged to Allah, until the end of the verse. He also said: His sister, whose name was al-Rubayyi, broke the front tooth of a woman, so the Messenger of Allah (peace be upon him) ordered retaliation. Anas said: O Messenger of Allah, by Him who sent you with the truth, her front tooth will not be broken. They accepted compensation and abandoned retaliation. The Messenger of Allah (peace be upon him) said: Among Allah's servants are those who, if they swear an oath by Allah, Allah fulfills it for them.",
    "Muhammad ibn Sa'id al-Khuza'i überlieferte uns. Abd al-A'la überlieferte uns, von Humayd, der sagte: Ich fragte Anas. Amr ibn Zurara überlieferte uns. Ziyad überlieferte uns. Er sagte: Humayd al-Tawil berichtete mir, von Anas, möge Allah mit ihm zufrieden sein, der sagte: Mein Onkel Anas ibn al-Nadr war beim Kampf von Badr abwesend. Er sagte: O Gesandter Allahs, ich war beim ersten Kampf abwesend, in dem du gegen die Götzendiener gekämpft hast. Wenn Allah mich einen Kampf gegen die Götzendiener erleben lässt, wird Allah gewiss sehen, was ich tue. Als der Tag von Uhud kam und die Muslime sich zurückzogen, sagte er: O Allah, ich entschuldige mich bei Dir für das, was diese Leute getan haben, also seine Gefährten, und ich sage mich vor Dir los von dem, was diese Leute getan haben, also die Götzendiener. Dann rückte er vor, und Sa'd ibn Mu'adh begegnete ihm. Er sagte: O Sa'd ibn Mu'adh, das Paradies! Beim Herrn al-Nadrs, ich rieche es jenseits von Uhud. Sa'd sagte: Ich konnte nicht tun, was er tat, o Gesandter Allahs. Anas sagte: Wir fanden an ihm mehr als achtzig Wunden durch Schwerthiebe, Speerstiche oder Pfeile. Wir fanden, dass er getötet worden war und dass die Götzendiener ihn verstümmelt hatten. Niemand konnte ihn erkennen außer seiner Schwester an ihren Fingerspitzen. Anas sagte: Wir pflegten zu glauben oder anzunehmen, dass dieser Vers über ihn und seinesgleichen offenbart worden war: (Quran 33:23) Unter den Gläubigen sind Männer, die wahr gemacht haben, was sie Allah gelobt hatten, bis zum Ende des Verses. Er sagte auch: Seine Schwester, die al-Rubayyi genannt wurde, brach einer Frau einen Schneidezahn ab, worauf der Gesandte Allahs (Friede sei auf ihm) Vergeltung anordnete. Anas sagte: O Gesandter Allahs, bei Dem, Der dich mit der Wahrheit gesandt hat, ihr Schneidezahn wird nicht abgebrochen werden. Sie akzeptierten eine Entschädigung und ließen die Vergeltung fallen. Der Gesandte Allahs (Friede sei auf ihm) sagte: Unter Allahs Dienern gibt es solche, die, wenn sie bei Allah schwören, dass Allah ihren Schwur erfüllt.",
  ],
  2807: [
    "Abu al-Yaman informed us. Shu'ayb informed us, from al-Zuhri. Isma'il narrated to me. He said: My brother narrated to me, from Sulayman, I think from Muhammad ibn Abi Atiq, from Ibn Shihab, from Kharija ibn Zayd, that Zayd ibn Thabit, may Allah be pleased with him, said: I copied the sheets into the written copies of the Quran, and I missed a verse from Surat al-Ahzab that I had heard the Messenger of Allah (peace be upon him) recite. I found it only with Khuzayma ibn Thabit al-Ansari, whose testimony the Messenger of Allah (peace be upon him) made equal to the testimony of two men. It is His saying: (Quran 33:23) Among the believers are men who were true to what they pledged to Allah.",
    "Abu al-Yaman informierte uns. Shu'ayb informierte uns, von al-Zuhri. Isma'il berichtete mir. Er sagte: Mein Bruder berichtete mir, von Sulayman, ich glaube von Muhammad ibn Abi Atiq, von Ibn Shihab, von Kharija ibn Zayd, dass Zayd ibn Thabit, möge Allah mit ihm zufrieden sein, sagte: Ich übertrug die Blätter in die niedergeschriebenen Exemplare des Quran, und mir fehlte ein Vers aus der Sura al-Ahzab, den ich den Gesandten Allahs (Friede sei auf ihm) hatte rezitieren hören. Ich fand ihn nur bei Khuzayma ibn Thabit al-Ansari, dessen Zeugnis der Gesandte Allahs (Friede sei auf ihm) dem Zeugnis zweier Männer gleichstellte. Es ist Seine Aussage: (Quran 33:23) Unter den Gläubigen sind Männer, die wahr gemacht haben, was sie Allah gelobt hatten.",
  ],
  2808: [
    "Muhammad ibn Abd al-Rahim narrated to us. Shubaba ibn Sawwar al-Fazari narrated to us. Israel narrated to us, from Abu Ishaq, who said: I heard al-Bara, may Allah be pleased with him, say: A man wearing iron armor came to the Prophet (peace be upon him) and said: Should I fight and embrace Islam? He said: Embrace Islam, then fight. So he embraced Islam and then fought, and he was killed. The Messenger of Allah (peace be upon him) said: He did little and received a great reward.",
    "Muhammad ibn Abd al-Rahim überlieferte uns. Shubaba ibn Sawwar al-Fazari überlieferte uns. Israel überlieferte uns, von Abu Ishaq, der sagte: Ich hörte al-Bara, möge Allah mit ihm zufrieden sein, sagen: Ein Mann in eiserner Rüstung kam zum Propheten (Friede sei auf ihm) und sagte: Soll ich kämpfen und den Islam annehmen? Er sagte: Nimm den Islam an, dann kämpfe. Da nahm er den Islam an und kämpfte, und er wurde getötet. Der Gesandte Allahs (Friede sei auf ihm) sagte: Er tat wenig und erhielt eine große Belohnung.",
  ],
  2809: [
    "Muhammad ibn Abdullah narrated to us. Husayn ibn Muhammad Abu Ahmad narrated to us. Shayban narrated to us, from Qatada. Anas ibn Malik narrated to us that Umm al-Rubayyi bint al-Bara, who was the mother of Haritha ibn Suraqa, came to the Prophet (peace be upon him) and said: O Prophet of Allah, will you not tell me about Haritha? He was killed on the day of Badr by a stray arrow. If he is in Paradise, I will be patient, and if he is otherwise, I will strive in weeping for him. He said: O Umm Haritha, they are gardens in Paradise, and your son has reached the highest Firdaws.",
    "Muhammad ibn Abdullah überlieferte uns. Husayn ibn Muhammad Abu Ahmad überlieferte uns. Shayban überlieferte uns, von Qatada. Anas ibn Malik überlieferte uns, dass Umm al-Rubayyi bint al-Bara, die Mutter von Haritha ibn Suraqa, zum Propheten (Friede sei auf ihm) kam und sagte: O Prophet Allahs, willst du mir nicht von Haritha erzählen? Er wurde am Tag von Badr von einem verirrten Pfeil getroffen und getötet. Wenn er im Paradies ist, werde ich geduldig sein, und wenn es anders ist, werde ich mich im Weinen um ihn bemühen. Er sagte: O Umm Haritha, es sind Gärten im Paradies, und dein Sohn hat das höchste Firdaws erreicht.",
  ],
  2810: [
    "Sulayman ibn Harb narrated to us. Shu'ba narrated to us, from Amr, from Abu Wa'il, from Abu Musa, may Allah be pleased with him, who said: A man came to the Prophet (peace be upon him) and said: One man fights for the spoils, another fights for fame, and another fights so that his position may be seen. Which of them is in the cause of Allah? He said: Whoever fights so that the word of Allah is supreme is in the cause of Allah.",
    "Sulayman ibn Harb überlieferte uns. Shu'ba überlieferte uns, von Amr, von Abu Wa'il, von Abu Musa, möge Allah mit ihm zufrieden sein, der sagte: Ein Mann kam zum Propheten (Friede sei auf ihm) und sagte: Ein Mann kämpft wegen der Beute, ein anderer kämpft wegen des Ruhms, und ein anderer kämpft, damit man seine Stellung sieht. Wer von ihnen ist auf Allahs Weg? Er sagte: Wer kämpft, damit das Wort Allahs das höchste ist, der ist auf Allahs Weg.",
  ],
  2811: [
    "Ishaq informed us. Muhammad ibn al-Mubarak informed us. Yahya ibn Hamza narrated to us. He said: Yazid ibn Abi Maryam narrated to me. Abaya ibn Rafi ibn Khadij informed us. He said: Abu Abs, namely Abd al-Rahman ibn Jabr, informed me that the Messenger of Allah (peace be upon him) said: No servant's feet become dusty in the cause of Allah and then the Fire touches him.",
    "Ishaq informierte uns. Muhammad ibn al-Mubarak informierte uns. Yahya ibn Hamza überlieferte uns. Er sagte: Yazid ibn Abi Maryam berichtete mir. Abaya ibn Rafi ibn Khadij informierte uns. Er sagte: Abu Abs, nämlich Abd al-Rahman ibn Jabr, berichtete mir, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Die Füße keines Dieners werden auf Allahs Weg staubig, ohne dass ihn danach das Feuer berührt.",
  ],
  2812: [
    "Ibrahim ibn Musa narrated to us. Abd al-Wahhab informed us. Khalid narrated to us, from Ikrima, that Ibn Abbas said to him and to Ali ibn Abdullah: Go to Abu Sa'id and listen to his hadith. So we went to him while he and his brother were watering a garden belonging to them. When he saw us, he came, folded his legs, and sat down. He said: We used to carry the bricks of the mosque one brick at a time, while Ammar used to carry them two at a time. The Prophet (peace be upon him) passed by him, wiped the dust from his head, and said: Alas for Ammar! The rebellious group will kill him. Ammar calls them to Allah, while they call him to the Fire.",
    "Ibrahim ibn Musa überlieferte uns. Abd al-Wahhab informierte uns. Khalid überlieferte uns, von Ikrima, dass Ibn Abbas zu ihm und zu Ali ibn Abdullah sagte: Geht zu Abu Sa'id und hört seinen Hadith. Da gingen wir zu ihm, während er und sein Bruder einen ihnen gehörenden Garten bewässerten. Als er uns sah, kam er, setzte sich mit angezogenen Beinen hin und sagte: Wir pflegten die Ziegel der Moschee einen Ziegel nach dem anderen zu tragen, während Ammar sie zwei nach dem anderen trug. Der Prophet (Friede sei auf ihm) kam an ihm vorbei, wischte den Staub von seinem Kopf und sagte: Wehe Ammar! Die aufrührerische Gruppe wird ihn töten. Ammar ruft sie zu Allah, während sie ihn zum Feuer rufen.",
  ],
  2813: [
    "Muhammad narrated to us. Abda informed us, from Hisham ibn Urwa, from his father, from Aisha, may Allah be pleased with her, that when the Messenger of Allah (peace be upon him) returned on the day of the Trench, put down his weapons, and took a bath, Gabriel came to him with dust covering his head and said: You have put down your weapons? By Allah, I have not put them down. The Messenger of Allah (peace be upon him) said: Where then? He said: There, and he pointed toward Banu Qurayza. Aisha said: The Messenger of Allah (peace be upon him) went out to them.",
    "Muhammad überlieferte uns. Abda informierte uns, von Hisham ibn Urwa, von seinem Vater, von Aisha, möge Allah mit ihr zufrieden sein, dass der Gesandte Allahs (Friede sei auf ihm), als er am Tag des Grabens zurückkehrte, seine Waffen niederlegte und ein Bad nahm, Gabriel zu ihm kam, während Staub seinen Kopf bedeckte, und sagte: Du hast deine Waffen niedergelegt? Bei Allah, ich habe sie nicht niedergelegt. Der Gesandte Allahs (Friede sei auf ihm) sagte: Wohin dann? Er sagte: Dorthin, und er deutete auf Banu Qurayza. Aisha sagte: Der Gesandte Allahs (Friede sei auf ihm) zog zu ihnen hinaus.",
  ],
  2814: [
    "Isma'il ibn Abdullah narrated to us. He said: Malik narrated to me, from Ishaq ibn Abdullah ibn Abi Talha, from Anas ibn Malik, may Allah be pleased with him, who said: The Messenger of Allah (peace be upon him) supplicated against those who killed the companions at Bi'r Ma'una for thirty mornings, against Ri'l, Dhakwan, and Usayya, who disobeyed Allah and His Messenger. Anas said: Quran was revealed concerning those who were killed at Bi'r Ma'una. We recited it, then it was abrogated later: Convey to our people that we have met our Lord, and He was pleased with us and we were pleased with Him.",
    "Isma'il ibn Abdullah überlieferte uns. Er sagte: Malik berichtete mir, von Ishaq ibn Abdullah ibn Abi Talha, von Anas ibn Malik, möge Allah mit ihm zufrieden sein, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sprach dreißig Morgen lang ein Bittgebet gegen jene, die die Gefährten bei Bi'r Ma'una getötet hatten, gegen Ri'l, Dhakwan und Usayya, die Allah und Seinem Gesandten ungehorsam waren. Anas sagte: Über diejenigen, die bei Bi'r Ma'una getötet worden waren, wurde Quran offenbart. Wir rezitierten ihn, dann wurde er später aufgehoben: Übermittelt unserem Volk, dass wir unserem Herrn begegnet sind, dass Er mit uns zufrieden war und wir mit Ihm zufrieden waren.",
  ],
  2815: [
    "Ali ibn Abdullah narrated to us. Sufyan narrated to us, from Amr, who heard Jabir ibn Abdullah, may Allah be pleased with them, say: Some people drank wine in the morning on the day of Uhud, then they were killed as martyrs. Sufyan was asked: At the end of that day? He said: This is not in it.",
    "Ali ibn Abdullah überlieferte uns. Sufyan überlieferte uns, von Amr, der Jabir ibn Abdullah, möge Allah mit ihnen zufrieden sein, sagen hörte: Einige Menschen tranken am Morgen des Tages von Uhud Wein und wurden dann als Märtyrer getötet. Sufyan wurde gefragt: Am Ende dieses Tages? Er sagte: Das steht darin nicht.",
  ],
  2816: [
    "Sadaqa ibn al-Fadl narrated to us. He said: Ibn Uyayna informed us. He said: I heard Muhammad ibn al-Munkadir hear Jabir say: My father was brought to the Prophet (peace be upon him), after he had been mutilated, and was placed before him. I went to uncover his face, but my people forbade me. The Prophet heard the voice of a wailing woman, and it was said: The daughter of Amr, or the sister of Amr. He said: Why is she weeping? Or: Do not weep. The angels have continued to shade him with their wings. I said to Sadaqa: Was this so until he was lifted? He said: Perhaps he said that.",
    "Sadaqa ibn al-Fadl überlieferte uns. Er sagte: Ibn Uyayna informierte uns. Er sagte: Ich hörte Muhammad ibn al-Munkadir Jabir sagen hören: Mein Vater wurde zum Propheten (Friede sei auf ihm) gebracht, nachdem er verstümmelt worden war, und vor ihn gelegt. Ich wollte sein Gesicht aufdecken, doch mein Volk hinderte mich daran. Der Prophet hörte die Stimme einer klagenden Frau, und es wurde gesagt: Die Tochter von Amr oder die Schwester von Amr. Er sagte: Warum weint sie? Oder: Weine nicht. Die Engel beschatten ihn weiterhin mit ihren Flügeln. Ich sagte zu Sadaqa: War es so, bis er emporgehoben wurde? Er sagte: Vielleicht sagte er das.",
  ],
  2817: [
    "Muhammad ibn Bashshar narrated to us. Ghundar narrated to us. Shu'ba narrated to us. He said: I heard Qatada say: I heard Anas ibn Malik, may Allah be pleased with him, from the Prophet (peace be upon him), who said: No one enters Paradise and wishes to return to the world while having everything on earth, except the martyr. He wishes to return to the world and be killed ten times, because of the honor he sees.",
    "Muhammad ibn Bashshar überlieferte uns. Ghundar überlieferte uns. Shu'ba überlieferte uns. Er sagte: Ich hörte Qatada sagen: Ich hörte Anas ibn Malik, möge Allah mit ihm zufrieden sein, vom Propheten (Friede sei auf ihm), der sagte: Niemand betritt das Paradies und wünscht sich, in die Welt zurückzukehren, während er alles besitzt, was auf der Erde ist, außer dem Märtyrer. Er wünscht sich, in die Welt zurückzukehren und zehnmal getötet zu werden, wegen der Ehre, die er sieht.",
  ],
  2818: [
    "Abdullah ibn Muhammad narrated to us. Muawiya ibn Amr narrated to us. Abu Ishaq narrated to us, from Musa ibn Uqba, from Salim Abu al-Nadr, the freedman of Umar ibn Ubaydullah, who was his secretary. He said: Abdullah ibn Abi Awfa, may Allah be pleased with them, wrote to him that the Messenger of Allah (peace be upon him) said: Know that Paradise is beneath the shade of swords. Al-Uwaysi followed this narration from Ibn Abi al-Zinad, from Musa ibn Uqba.",
    "Abdullah ibn Muhammad überlieferte uns. Muawiya ibn Amr überlieferte uns. Abu Ishaq überlieferte uns, von Musa ibn Uqba, von Salim Abu al-Nadr, dem Freigelassenen von Umar ibn Ubaydullah, der dessen Schreiber war. Er sagte: Abdullah ibn Abi Awfa, möge Allah mit ihnen zufrieden sein, schrieb ihm, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Wisst, dass das Paradies unter dem Schatten der Schwerter liegt. al-Uwaysi überlieferte diese Überlieferung ebenfalls von Ibn Abi al-Zinad, von Musa ibn Uqba.",
  ],
  2819: [
    "Al-Layth said: Ja'far ibn Rabi'a narrated to me, from Abd al-Rahman ibn Hurmuz, who said: I heard Abu Hurayra, may Allah be pleased with him, from the Messenger of Allah (peace be upon him), who said: Sulayman ibn Dawud, peace be upon them, said: Tonight I will go around to one hundred women, or ninety-nine, each of whom will give birth to a horseman who will fight in the cause of Allah. His companion said to him: If Allah wills. But he did not say: If Allah wills. None of them conceived except one woman, who gave birth to half a man. By Him in whose hand is the soul of Muhammad, had he said: If Allah wills, they would all have fought in the cause of Allah as horsemen.",
    "Al-Layth sagte: Ja'far ibn Rabi'a berichtete mir, von Abd al-Rahman ibn Hurmuz, der sagte: Ich hörte Abu Hurayra, möge Allah mit ihm zufrieden sein, vom Gesandten Allahs (Friede sei auf ihm), der sagte: Sulayman ibn Dawud, Friede sei auf ihnen, sagte: Heute Nacht werde ich zu hundert Frauen, oder neunundneunzig, gehen, von denen jede einen Reiter gebären wird, der auf Allahs Weg kämpft. Sein Gefährte sagte zu ihm: Wenn Allah will. Doch er sagte nicht: Wenn Allah will. Keine von ihnen empfing außer einer Frau, die einen halben Mann gebar. Bei Dem, in Dessen Hand die Seele Muhammads ist: Hätte er gesagt: Wenn Allah will, hätten sie alle als Reiter auf Allahs Weg gekämpft.",
  ],
  2820: [
    "Ahmad ibn Abd al-Malik ibn Waqid narrated to us. Hammad ibn Zayd narrated to us, from Thabit, from Anas, may Allah be pleased with him, who said: The Prophet (peace be upon him) was the finest of people, the bravest of people, and the most generous of people. The people of Medina were alarmed, and the Prophet (peace be upon him) had gone ahead of them on a horse. He said: We found it to be a sea.",
    "Ahmad ibn Abd al-Malik ibn Waqid überlieferte uns. Hammad ibn Zayd überlieferte uns, von Thabit, von Anas, möge Allah mit ihm zufrieden sein, der sagte: Der Prophet (Friede sei auf ihm) war der schönste, der mutigste und der großzügigste aller Menschen. Die Bewohner von Medina erschraken, und der Prophet (Friede sei auf ihm) war ihnen auf einem Pferd vorausgeeilt. Er sagte: Wir fanden es wie ein Meer.",
  ],
  2821: [
    "Abu al-Yaman informed us. Shu'ayb informed us, from al-Zuhri, who said: Umar ibn Muhammad ibn Jubayr ibn Mut'im informed me that Muhammad ibn Jubayr said: Jubayr ibn Mut'im informed me that while he was traveling with the Messenger of Allah (peace be upon him), with the people accompanying him, on his return from Hunayn, the people clung to him, asking him, until they forced him toward a thorn tree, whose thorns caught his cloak. The Prophet (peace be upon him) stopped and said: Give me my cloak. If I had as many camels as the number of these thorn trees, I would divide them among you. Then you would not find me stingy, lying, or cowardly.",
    "Abu al-Yaman informierte uns. Shu'ayb informierte uns, von al-Zuhri, der sagte: Umar ibn Muhammad ibn Jubayr ibn Mut'im berichtete mir, dass Muhammad ibn Jubayr sagte: Jubayr ibn Mut'im berichtete mir, dass er mit dem Gesandten Allahs (Friede sei auf ihm) und den Menschen, die ihn begleiteten, von Hunayn zurückkehrte. Die Menschen hielten sich an ihm fest und baten ihn, bis sie ihn zu einem Dornbaum drängten, dessen Dornen seinen Mantel erfassten. Der Prophet (Friede sei auf ihm) blieb stehen und sagte: Gebt mir meinen Mantel. Wenn ich so viele Kamele hätte wie die Anzahl dieser Dornbäume, würde ich sie unter euch verteilen. Dann würdet ihr mich weder geizig noch lügnerisch noch feige finden.",
  ],
  2822: [
    "Musa ibn Isma'il narrated to us. Abu Awana narrated to us. Abd al-Malik ibn Umayr narrated to us. I heard Amr ibn Maymun al-Awdi say: Sa'd used to teach his sons these words as a teacher teaches boys writing, and he would say: The Messenger of Allah (peace be upon him) used to seek refuge from them after the prayer: O Allah, I seek refuge in You from cowardice. I seek refuge in You from being returned to the lowest stage of life. I seek refuge in You from the trial of the world. I seek refuge in You from the punishment of the grave. I related this to Mus'ab, and he affirmed it.",
    "Musa ibn Isma'il überlieferte uns. Abu Awana überlieferte uns. Abd al-Malik ibn Umayr überlieferte uns. Ich hörte Amr ibn Maymun al-Awdi sagen: Sa'd pflegte seinen Söhnen diese Worte beizubringen, wie ein Lehrer den Jungen das Schreiben beibringt, und er sagte: Der Gesandte Allahs (Friede sei auf ihm) pflegte nach dem Gebet bei ihnen Zuflucht zu suchen: O Allah, ich suche Zuflucht bei Dir vor Feigheit. Ich suche Zuflucht bei Dir davor, in das hinfälligste Lebensalter zurückgebracht zu werden. Ich suche Zuflucht bei Dir vor der Prüfung der Welt. Ich suche Zuflucht bei Dir vor der Strafe des Grabes. Ich erzählte dies Mus'ab, und er bestätigte es.",
  ],
  2823: [
    "Musaddad narrated to us. Mu'tamir narrated to us. He said: I heard my father say: I heard Anas ibn Malik, may Allah be pleased with him, say: The Prophet (peace be upon him) used to say: O Allah, I seek refuge in You from incapacity, laziness, cowardice, and old age. I seek refuge in You from the trial of life and death. I seek refuge in You from the punishment of the grave.",
    "Musaddad überlieferte uns. Mu'tamir überlieferte uns. Er sagte: Ich hörte meinen Vater sagen: Ich hörte Anas ibn Malik, möge Allah mit ihm zufrieden sein, sagen: Der Prophet (Friede sei auf ihm) pflegte zu sagen: O Allah, ich suche Zuflucht bei Dir vor Unfähigkeit, Faulheit, Feigheit und hohem Alter. Ich suche Zuflucht bei Dir vor der Prüfung des Lebens und des Todes. Ich suche Zuflucht bei Dir vor der Strafe des Grabes.",
  ],
  2824: [
    "Qutayba ibn Sa'id narrated to us. Hatim narrated to us, from Muhammad ibn Yusuf, from al-Sa'ib ibn Yazid, who said: I accompanied Talha ibn Ubaydullah, Sa'd, al-Miqdad ibn al-Aswad, and Abd al-Rahman ibn Awf, may Allah be pleased with them. I did not hear any of them narrate from the Messenger of Allah (peace be upon him), except that I heard Talha narrate about the day of Uhud.",
    "Qutayba ibn Sa'id überlieferte uns. Hatim überlieferte uns, von Muhammad ibn Yusuf, von al-Sa'ib ibn Yazid, der sagte: Ich begleitete Talha ibn Ubaydullah, Sa'd, al-Miqdad ibn al-Aswad und Abd al-Rahman ibn Awf, möge Allah mit ihnen zufrieden sein. Ich hörte keinen von ihnen vom Gesandten Allahs (Friede sei auf ihm) überliefern, außer dass ich Talha über den Tag von Uhud überliefern hörte.",
  ],
  2825: [
    "Amr ibn Ali narrated to us. Yahya narrated to us. Sufyan narrated to us. He said: Mansur narrated to me, from Mujahid, from Tawus, from Ibn Abbas, may Allah be pleased with them, that the Prophet (peace be upon him) said on the day of the Conquest: There is no emigration after the Conquest, but there is jihad and intention. When you are called to mobilize, then mobilize.",
    "Amr ibn Ali überlieferte uns. Yahya überlieferte uns. Sufyan überlieferte uns. Er sagte: Mansur berichtete mir, von Mujahid, von Tawus, von Ibn Abbas, möge Allah mit ihnen zufrieden sein, dass der Prophet (Friede sei auf ihm) am Tag der Eroberung sagte: Nach der Eroberung gibt es keine Auswanderung mehr, aber es gibt Dschihad und die Absicht. Wenn ihr zum Ausrücken aufgerufen werdet, dann rückt aus.",
  ],
};

const out: Out[] = raw.map((row) => {
  const n = Number(row.url.split(":").pop());
  const pair = translations[n];
  if (!pair) throw new Error(`Missing translation for ${row.url}`);
  return { id: row.id, n, en: pair[0], de: pair[1] };
});

fs.writeFileSync(output, JSON.stringify(out, null, 2) + "\n", "utf8");
console.log(`wrote ${out.length} translations to ${output}`);
