import fs from 'node:fs';

const rows: any[] = JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json', 'utf8'));
const tr: Record<string, { en: string; de: string }> = {
  'https://sunnah.com/muslim:337': {
    en: 'Ishaq ibn Ibrahim al-Hanzali narrated to us. Musa al-Qari informed us. Zaidah narrated to us, from al-Amash, from Salim ibn Abi al-Jad, from Kurayb, from Ibn Abbas, from Maymunah, who said: I prepared water for the Prophet (peace be upon him) and screened him, so he performed ghusl.',
    de: 'Ishaq ibn Ibrahim al-Hanzali überlieferte uns. Musa al-Qari berichtete uns. Zaidah überlieferte uns, von al-Amash, von Salim ibn Abi al-Jad, von Kurayb, von Ibn Abbas, von Maymunah, die sagte: Ich bereitete dem Propheten (Friede sei auf ihm) Wasser vor und schirmte ihn ab, und so verrichtete er den Ghusl.'
  },
  'https://sunnah.com/muslim:338a': {
    en: 'Abu Bakr ibn Abi Shaiba narrated to us. Zaid ibn al-Hubab narrated to us, from al-Dahhak ibn Uthman, who said: Zaid ibn Aslam informed me, from Abd al-Rahman ibn Abi Said al-Khudri, from his father, that the Messenger of Allah (peace be upon him) said: A man must not look at the private parts of another man, nor a woman at the private parts of another woman. A man must not lie with another man under one garment, nor may a woman lie with another woman under one garment.',
    de: 'Abu Bakr ibn Abi Shaiba überlieferte uns. Zaid ibn al-Hubab überlieferte uns, von al-Dahhak ibn Uthman, der sagte: Zaid ibn Aslam berichtete mir, von Abd al-Rahman ibn Abi Said al-Khudri, von dessen Vater, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Ein Mann darf nicht auf die Scham eines anderen Mannes blicken, und eine Frau darf nicht auf die Scham einer anderen Frau blicken. Ein Mann darf nicht mit einem anderen Mann unter einem einzigen Gewand liegen, und eine Frau darf nicht mit einer anderen Frau unter einem einzigen Gewand liegen.'
  },
  'https://sunnah.com/muslim:338b': {
    en: 'Harun ibn Abdullah and Muhammad ibn Rafi narrated it to me. They said: Ibn Abi Fudayk narrated to us. al-Dahhak ibn Uthman informed us with this chain, and they said: Instead of private parts, he said: the nakedness of a man and the nakedness of a woman.',
    de: 'Harun ibn Abdullah und Muhammad ibn Rafi überlieferten ihn mir. Sie sagten: Ibn Abi Fudayk überlieferte uns. al-Dahhak ibn Uthman berichtete uns mit dieser Überlieferungskette, und sie sagten: Statt Scham sagte er: die Blöße eines Mannes und die Blöße einer Frau.'
  },
  'https://sunnah.com/muslim:339': {
    en: 'Muhammad ibn Rafi narrated to us. Abd al-Razzaq narrated to us. Mamar narrated to us, from Hammam ibn Munabbih, who said: This is what Abu Hurayra narrated to us, from Muhammad, the Messenger of Allah (peace be upon him). He mentioned some hadiths, among them that the Messenger of Allah (peace be upon him) said: The Children of Israel used to perform ghusl naked, looking at one another’s private parts, while Musa (peace be upon him) used to perform ghusl alone. They said: By Allah, nothing prevents Musa from performing ghusl with us except that he has a swollen testicle. He said: Once he went to perform ghusl and placed his garment on a stone, but the stone ran off with his garment. He said: Musa chased after it, saying, “My garment, stone! My garment, stone!” until the Children of Israel looked at Musa’s private parts. They said: By Allah, Musa has no defect. Then the stone stood still so that it could be seen. He said: He took his garment and began striking the stone. Abu Hurayra said: By Allah, there are six or seven marks on the stone from Musa’s striking it.',
    de: 'Muhammad ibn Rafi überlieferte uns. Abd al-Razzaq überlieferte uns. Mamar überlieferte uns, von Hammam ibn Munabbih, der sagte: Das ist, was Abu Hurayra uns von Muhammad, dem Gesandten Allahs (Friede sei auf ihm), überlieferte. Er erwähnte einige Hadithe, darunter, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Die Kinder Israels pflegten nackt den Ghusl zu verrichten und einander auf die Scham zu blicken, während Musa (Friede sei auf ihm) den Ghusl allein zu verrichten pflegte. Sie sagten: Bei Allah, nichts hindert Musa daran, mit uns den Ghusl zu verrichten, außer dass er einen geschwollenen Hoden hat. Er sagte: Einmal ging er zum Ghusl, legte sein Gewand auf einen Stein, doch der Stein lief mit seinem Gewand davon. Er sagte: Musa eilte ihm nach und sagte: „Mein Gewand, o Stein! Mein Gewand, o Stein!“ bis die Kinder Israels auf Musas Scham blickten. Sie sagten: Bei Allah, Musa hat keinen Makel. Dann blieb der Stein stehen, sodass man ihn sehen konnte. Er sagte: Er nahm sein Gewand und begann, auf den Stein einzuschlagen. Abu Hurayra sagte: Bei Allah, auf dem Stein sind sechs oder sieben Spuren von Musas Schlägen.'
  },
  'https://sunnah.com/muslim:339b': {
    en: 'Muhammad ibn Rafi narrated to me. Abd al-Razzaq narrated to us. Mamar informed us, from Hammam ibn Munabbih, who said: This is what Abu Hurayra narrated to us, from the Messenger of Allah (peace be upon him). He mentioned some hadiths, among them that the Messenger of Allah (peace be upon him) said: The Children of Israel used to perform ghusl naked, looking at one another’s private parts, while Musa (peace be upon him) used to perform ghusl alone. They said: By Allah, nothing prevents Musa from performing ghusl with us except that he has a swollen testicle. He said: Once he went to perform ghusl and placed his garment on a stone, but the stone ran off with his garment. He said: Musa chased after it, saying, “My garment, stone! My garment, stone!” until the Children of Israel looked at Musa’s private parts and said: By Allah, Musa has no defect. Then the stone stood still so that it could be seen. He said: He took his garment and began striking the stone. Abu Hurayra said: By Allah, there are six or seven marks on the stone from Musa’s striking it, peace be upon him.',
    de: 'Muhammad ibn Rafi überlieferte mir. Abd al-Razzaq überlieferte uns. Mamar berichtete uns, von Hammam ibn Munabbih, der sagte: Das ist, was Abu Hurayra uns vom Gesandten Allahs (Friede sei auf ihm) überlieferte. Er erwähnte einige Hadithe, darunter, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Die Kinder Israels pflegten nackt den Ghusl zu verrichten und einander auf die Scham zu blicken, während Musa (Friede sei auf ihm) den Ghusl allein zu verrichten pflegte. Sie sagten: Bei Allah, nichts hindert Musa daran, mit uns den Ghusl zu verrichten, außer dass er einen geschwollenen Hoden hat. Er sagte: Einmal ging er zum Ghusl, legte sein Gewand auf einen Stein, doch der Stein lief mit seinem Gewand davon. Er sagte: Musa eilte ihm nach und sagte: „Mein Gewand, o Stein! Mein Gewand, o Stein!“ bis die Kinder Israels auf Musas Scham blickten und sagten: Bei Allah, Musa hat keinen Makel. Dann blieb der Stein stehen, sodass man ihn sehen konnte. Er sagte: Er nahm sein Gewand und begann, auf den Stein einzuschlagen. Abu Hurayra sagte: Bei Allah, auf dem Stein sind sechs oder sieben Spuren von Musas Schlägen, Friede sei auf ihm.'
  },
  'https://sunnah.com/muslim:339c': {
    en: 'Yahya ibn Habib al-Harithy narrated to us. Yazid ibn Zuray narrated to us. Khalid al-Haddha narrated to us, from Abdullah ibn Shaqiq, who said: Abu Hurayra informed us. He said: Musa (peace be upon him) was a very modest man. He was not seen undressed. The Children of Israel said: He has a swollen testicle. He said: He performed ghusl at a small water source, placed his garment on a stone, and the stone went off running. He followed it with his staff, striking it and saying, “My garment, o stone! My garment, o stone!” until it came to a gathering of the Children of Israel. Then this verse was revealed: O you who believe, do not be like those who harmed Musa, and Allah cleared him of what they said, and he was honored in the sight of Allah (Quran 33:69).',
    de: 'Yahya ibn Habib al-Harithy überlieferte uns. Yazid ibn Zuray überlieferte uns. Khalid al-Hadhdha überlieferte uns, von Abdullah ibn Shaqiq, der sagte: Abu Hurayra berichtete uns. Er sagte: Musa (Friede sei auf ihm) war ein sehr schamhafter Mann. Man sah ihn nicht unbekleidet. Die Kinder Israels sagten: Er hat einen geschwollenen Hoden. Er sagte: Er verrichtete den Ghusl an einer kleinen Wasserstelle, legte sein Gewand auf einen Stein, und der Stein lief davon. Er folgte ihm mit seinem Stock und schlug auf ihn ein, wobei er sagte: „Mein Gewand, o Stein! Mein Gewand, o Stein!“ bis er zu einer Versammlung der Kinder Israels kam. Dann wurde dieser Vers offenbart: O ihr, die ihr glaubt, seid nicht wie diejenigen, die Musa verletzten, und Allah sprach ihn von dem frei, was sie sagten, und er war bei Allah angesehen (Quran 33:69).'
  },
  'https://sunnah.com/muslim:340a': {
    en: 'Ishaq ibn Ibrahim al-Hanzali and Muhammad ibn Hatim ibn Maymun both narrated from Muhammad ibn Bakr. He said: Ibn Jurayj informed us. And Ishaq ibn Mansur and Muhammad ibn Rafi narrated to me, with the wording belonging to both of them. Ishaq said: He informed us, while Ibn Rafi said: Abd al-Razzaq narrated to us. Ibn Jurayj informed us. Amr ibn Dinar informed me that he heard Jabir ibn Abdullah say: When the Kaaba was built, the Prophet (peace be upon him) and Abbas went carrying stones. Abbas said to the Prophet (peace be upon him): Put your lower garment on your shoulder to protect you from the stones. He did so, fell to the ground, and his eyes gazed toward the sky. Then he stood and said: “My lower garment, my lower garment.” He tied his lower garment around himself. Ibn Rafi said in his narration: “around your neck,” and he did not say: “on your shoulder.”',
    de: 'Ishaq ibn Ibrahim al-Hanzali und Muhammad ibn Hatim ibn Maymun überlieferten beide von Muhammad ibn Bakr. Er sagte: Ibn Jurayj berichtete uns. Und Ishaq ibn Mansur und Muhammad ibn Rafi überlieferten mir, wobei der Wortlaut von beiden stammt. Ishaq sagte: Er berichtete uns, während Ibn Rafi sagte: Abd al-Razzaq überlieferte uns. Ibn Jurayj berichtete uns. Amr ibn Dinar berichtete mir, dass er Jabir ibn Abdullah sagen hörte: Als die Kaaba gebaut wurde, gingen der Prophet (Friede sei auf ihm) und Abbas und trugen Steine. Abbas sagte zum Propheten (Friede sei auf ihm): Lege dein Untergewand über deine Schulter, damit es dich vor den Steinen schützt. Er tat es, fiel zu Boden, und seine Augen blickten zum Himmel. Dann stand er auf und sagte: „Mein Untergewand, mein Untergewand.“ Er band sein Untergewand um sich. Ibn Rafi sagte in seiner Überlieferung: „um deinen Hals“, und er sagte nicht: „über deine Schulter.“'
  }
};

const out = rows.filter((r) => tr[r.url]).map((r) => ({ ...r, ...tr[r.url] }));
if (out.length !== 7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-229-part.json', JSON.stringify(out, null, 2));
fs.writeFileSync('data/hadith-words-translations/codex-out-229-part.json', JSON.stringify(out, null, 2));
console.log(`wrote ${out.length} staged translations`);
