import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-208.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:267a':{en:'Yahya ibn Yahya narrated to us. Abd al-Rahman ibn Mahdi informed us, from Hammam, from Yahya ibn Abi Kathir, from Abdullah ibn Abi Qatada, from his father, who said: The Messenger of Allah (peace be upon him) said: None of you should hold his private part with his right hand while urinating, wipe himself with his right hand after relieving himself, or breathe into the vessel.',de:'Yahya ibn Yahya überlieferte uns. Abd al-Rahman ibn Mahdi berichtete uns, von Hammam, von Yahya ibn Abi Kathir, von Abdullah ibn Abi Qatada, von dessen Vater, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Keiner von euch soll sein Geschlechtsteil beim Urinieren mit der rechten Hand halten, sich nach dem Erleichtern mit der rechten Hand abwischen oder in das Gefäß atmen.'},
'https://sunnah.com/muslim:267b':{en:'Yahya ibn Yahya narrated to us. Waki narrated to us, from Hisham al-Dastuwai, from Yahya ibn Abi Kathir, from Abdullah ibn Abi Qatada, from his father, who said: The Messenger of Allah (peace be upon him) said: When one of you enters the place of relieving himself, let him not touch his private part with his right hand.',de:'Yahya ibn Yahya überlieferte uns. Waki überlieferte uns, von Hisham al-Dastuwai, von Yahya ibn Abi Kathir, von Abdullah ibn Abi Qatada, von dessen Vater, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Wenn einer von euch den Ort zum Erleichtern betritt, soll er sein Geschlechtsteil nicht mit der rechten Hand berühren.'},
'https://sunnah.com/muslim:267c':{en:'Ibn Abi Umar narrated to us. Al-Thaqafi narrated to us, from Ayyub, from Yahya ibn Abi Kathir, from Abdullah ibn Abi Qatada, from Abu Qatada, that the Prophet (peace be upon him) forbade breathing into the vessel, touching the private part with the right hand, and cleaning oneself with the right hand.',de:'Ibn Abi Umar überlieferte uns. Al-Thaqafi überlieferte uns, von Ayyub, von Yahya ibn Abi Kathir, von Abdullah ibn Abi Qatada, von Abu Qatada, dass der Prophet (Friede sei auf ihm) verbot, in das Gefäß zu atmen, das Geschlechtsteil mit der rechten Hand zu berühren und sich mit der rechten Hand zu reinigen.'},
'https://sunnah.com/muslim:267d':{en:'Ibn Abi Umar narrated to us. Al-Thaqafi narrated to us, from Ayyub, from Yahya ibn Abi Kathir, from Abdullah ibn Abi Qatada, from his father, that the Prophet (peace be upon him) forbade breathing into the vessel.',de:'Ibn Abi Umar überlieferte uns. Al-Thaqafi überlieferte uns, von Ayyub, von Yahya ibn Abi Kathir, von Abdullah ibn Abi Qatada, von dessen Vater, dass der Prophet (Friede sei auf ihm) verbot, in das Gefäß zu atmen.'},
'https://sunnah.com/muslim:268a':{en:'Yahya ibn Yahya al-Tamimi narrated to us. Abu al-Ahwas informed us, from Ashath, from his father, from Masruq, from Aisha, who said: The Messenger of Allah (peace be upon him) used to love starting with the right in his purification when he purified himself, in combing his hair when he combed it, and in putting on his shoes when he put them on.',de:'Yahya ibn Yahya al-Tamimi überlieferte uns. Abu al-Ahwas berichtete uns, von Ashath, von dessen Vater, von Masruq, von Aisha, die sagte: Der Gesandte Allahs (Friede sei auf ihm) liebte es, bei seiner Reinigung mit der rechten Seite zu beginnen, wenn er sich reinigte, beim Kämmen, wenn er sich kämmte, und beim Anziehen seiner Schuhe, wenn er sie anzog.'},
'https://sunnah.com/muslim:268b':{en:'Ubaydullah ibn Muadh narrated to us. My father narrated to us. Shu\'ba narrated to us, from Ashath, from his father, from Masruq, from Aisha, who said: The Messenger of Allah (peace be upon him) used to love beginning with the right in all his affairs: in putting on his sandals, combing his hair, and purification.',de:'Ubaydullah ibn Muadh überlieferte uns. Mein Vater überlieferte uns. Shu\'ba überlieferte uns, von Ashath, von dessen Vater, von Masruq, von Aisha, die sagte: Der Gesandte Allahs (Friede sei auf ihm) liebte es, in all seinen Angelegenheiten mit der rechten Seite zu beginnen: beim Anziehen seiner Sandalen, beim Kämmen seiner Haare und bei der Reinigung.'},
'https://sunnah.com/muslim:269':{en:'Yahya ibn Ayyub, Qutayba, and Ibn Hujr narrated to us, all from Ismail ibn Jafar. Ibn Ayyub said: Ismail narrated to us. Al-Ala informed me, from his father, from Abu Hurayra, that the Messenger of Allah (peace be upon him) said: Beware of the two things that bring curses. They asked: What are the two things that bring curses, O Messenger of Allah? He said: The one who relieves himself on people\'s path or in their shade.',de:'Yahya ibn Ayyub, Qutayba und Ibn Hujr überlieferten uns, alle von Ismail ibn Jafar. Ibn Ayyub sagte: Ismail überlieferte uns. Al-Ala berichtete mir, von dessen Vater, von Abu Hurayra, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Hütet euch vor den beiden Dingen, die Flüche hervorrufen. Sie fragten: Was sind die beiden Dinge, die Flüche hervorrufen, o Gesandter Allahs? Er sagte: Derjenige, der sich auf dem Weg der Menschen oder in ihrem Schatten erleichtert.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-208-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-208-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
