import fs from "node:fs";

const rows = JSON.parse(fs.readFileSync("data/hadith-words-translations/codex-batch-156.json", "utf8"));
const t: Record<string, [string, string]> = {};
const add = (n: string, en: string, de: string) => { t[n] = [en, de]; };

add("5183", "Yahya ibn Bukayr narrated to us. He said: Ya'qub ibn Abd al-Rahman al-Qari narrated to us, from Abu Hazim, who said: I heard Sahl ibn Sa'd say that Abu Usayd al-Sa'idi invited the Prophet, peace be upon him, to his wedding. His wife was serving them on that day, and she was the bride. She said: Do you know what she prepared for the Messenger of Allah, peace be upon him? She prepared dates for him soaked overnight in a vessel.", "Yahya ibn Bukayr überlieferte uns. Er sagte: Ya'qub ibn Abd ar-Rahman al-Qari überlieferte uns, von Abu Hazim, der sagte: Ich hörte Sahl ibn Sa'd sagen, dass Abu Usayd al-Sa'idi den Propheten, Friede sei auf ihm, zu seiner Hochzeit einlud. Seine Frau bediente sie an jenem Tag, und sie war die Braut. Sie sagte: Wisst ihr, was sie für den Gesandten Allahs, Friede sei auf ihm, vorbereitet hatte? Sie hatte für ihn Datteln in einem Gefäß über Nacht eingeweicht.");
add("5184", "Abd al-Aziz ibn Abd Allah narrated to us. He said: Malik narrated to me, from Abu al-Zinad, from al-A'raj, from Abu Hurayra, that the Messenger of Allah, peace be upon him, said: A woman is like a rib. If you try to straighten her, you will break her; and if you enjoy her, you enjoy her while there is crookedness in her.", "Abd al-Aziz ibn Abd Allah überlieferte uns. Er sagte: Malik überlieferte mir, von Abu az-Zinad, von al-A'raj, von Abu Hurayra, dass der Gesandte Allahs, Friede sei auf ihm, sagte: Die Frau ist wie eine Rippe. Wenn du versuchst, sie gerade zu machen, wirst du sie brechen; und wenn du Freude an ihr hast, hast du Freude an ihr, während sie eine Krümmung aufweist.");
add("5185", "Ishaq ibn Nasr narrated to us. Husayn al-Ju'fi narrated to us, from Za'ida, from Maysara, from Abu Hazim, from Abu Hurayra, from the Prophet, peace be upon him, who said: Whoever believes in Allah and the Last Day, let him not harm his neighbor. And treat women well, for they were created from a rib. The most crooked part of the rib is its upper part. If you try to straighten it, you will break it, and if you leave it, it will remain crooked. So treat women well.", "Ishaq ibn Nasr überlieferte uns. Husayn al-Ju'fi überlieferte uns, von Za'ida, von Maysara, von Abu Hazim, von Abu Hurayra, vom Propheten, Friede sei auf ihm, der sagte: Wer an Allah und den Letzten Tag glaubt, der soll seinem Nachbarn keinen Schaden zufügen. Und behandelt die Frauen gut, denn sie wurden aus einer Rippe erschaffen. Der am stärksten gekrümmte Teil der Rippe ist ihr oberer Teil. Wenn du versuchst, sie gerade zu machen, wirst du sie brechen, und wenn du sie lässt, wird sie gekrümmt bleiben. So behandelt die Frauen gut.");
add("5187", "Abu Nu'aym narrated to us. Sufyan narrated to us, from Abd Allah ibn Dinar, from Ibn Umar, who said: In the time of the Prophet, peace be upon him, we used to avoid speaking at length and being overly familiar with our women, out of fear that something might be revealed concerning us. When the Prophet, peace be upon him, passed away, we spoke and became familiar with them.", "Abu Nu'aym überlieferte uns. Sufyan überlieferte uns, von Abd Allah ibn Dinar, von Ibn Umar, der sagte: Zur Zeit des Propheten, Friede sei auf ihm, vermieden wir es, lange zu sprechen und mit unseren Frauen allzu vertraut zu sein, aus Angst, dass etwas über uns offenbart werden könnte. Als der Prophet, Friede sei auf ihm, verstorben war, sprachen wir und wurden mit ihnen vertraut.");
add("5188", "Abu al-Nu'man narrated to us. Hammad ibn Zayd narrated to us, from Ayyub, from Nafi', from Abd Allah, who said: The Prophet, peace be upon him, said: Each of you is a shepherd, and each of you is responsible. The imam is a shepherd and is responsible. A man is a shepherd over his household and is responsible. A woman is a guardian over her husband's home and is responsible. A servant is a shepherd over his master's property and is responsible. Indeed, each of you is a shepherd, and each of you is responsible.", "Abu an-Nu'man überlieferte uns. Hammad ibn Zayd überlieferte uns, von Ayyub, von Nafi', von Abd Allah, der sagte: Der Prophet, Friede sei auf ihm, sagte: Jeder von euch ist ein Hirte, und jeder von euch ist verantwortlich. Der Imam ist ein Hirte und ist verantwortlich. Der Mann ist ein Hirte über seine Familie und ist verantwortlich. Die Frau ist eine Hüterin über das Haus ihres Mannes und ist verantwortlich. Der Diener ist ein Hirte über das Vermögen seines Herrn und ist verantwortlich. Wahrlich, jeder von euch ist ein Hirte, und jeder von euch ist verantwortlich.");

const out = rows.map((r: any) => { const n = String(r.url).split(":").pop()!; if (!t[n]) throw new Error(`missing ${n}`); return { id: r.id, n, en: t[n][0], de: t[n][1] }; });
fs.writeFileSync("data/hadith-words-translations/codex-out-156.json", JSON.stringify(out, null, 2) + "\n");
console.log(`wrote ${out.length} translations`);
