import fs from 'node:fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-current.json','utf8'));
const tr:any={
'https://sunnah.com/muslim:317a':{en:'Ali ibn Hujr al-Sadi narrated to me. Isa ibn Yunus narrated to me. Al-Amash narrated to us, from Salim ibn Abi al-Jad, from Kurayb, from Ibn Abbas, who said: My maternal aunt Maymuna told me: I brought the vessel for the Messenger of Allah (peace be upon him) to perform ghusl from major ritual impurity. He washed his hands two or three times, then put his hand into the vessel. He poured water over his private part and washed it with his left hand. Then he struck his left hand on the ground and rubbed it vigorously. Then he performed the wudu for prayer. He poured three handfuls, each filling his palm, over his head, then washed the rest of his body. Then he moved away from that place and washed his feet. I brought him a towel, but he returned it.',de:'Ali ibn Hujr al-Sadi überlieferte mir. Isa ibn Yunus überlieferte mir. Al-Amash überlieferte uns, von Salim ibn Abi al-Jad, von Kurayb, von Ibn Abbas, der sagte: Meine Tante mütterlicherseits Maymuna erzählte mir: Ich brachte dem Gesandten Allahs (Friede sei auf ihm) das Gefäß, um wegen großer ritueller Unreinheit Ghusl zu verrichten. Er wusch seine Hände zwei- oder dreimal, steckte dann seine Hand in das Gefäß, goss Wasser über sein Geschlechtsteil und wusch es mit seiner linken Hand. Dann schlug er seine linke Hand auf den Boden und rieb sie kräftig. Danach verrichtete er die Wudu für das Gebet. Er goss drei Handvoll, jede eine volle Handfläche, über seinen Kopf und wusch dann den übrigen Körper. Danach entfernte er sich von dieser Stelle und wusch seine Füße. Ich brachte ihm ein Handtuch, aber er gab es zurück.'},
'https://sunnah.com/muslim:317b':{en:'Muhammad ibn al-Sabbah, Abu Bakr ibn Abi Shayba, Abu Kurayb, al-Ashajj, and Ishaq all narrated to us, from Waki. Yahya ibn Yahya and Abu Kurayb also narrated it to us: Abu Muawiya narrated to us. Both narrated from al-Amash with this chain. Their hadiths do not mention pouring three handfuls over the head. Waki\'s hadith describes the complete wudu and mentions rinsing the mouth and drawing water into the nose, while Abu Muawiya\'s hadith does not mention the towel.',de:'Muhammad ibn al-Sabbah, Abu Bakr ibn Abi Shayba, Abu Kurayb, al-Ashajj und Ishaq überlieferten uns, alle von Waki. Auch Yahya ibn Yahya und Abu Kurayb überlieferten ihn uns: Abu Muawiya überlieferte uns. Beide überlieferten von al-Amash mit dieser Überlieferungskette. Ihre Hadithe erwähnen nicht das Gießen von drei Handvoll über den Kopf. Der Hadith von Waki beschreibt die vollständige Wudu und erwähnt das Spülen des Mundes und das Ziehen von Wasser in die Nase, während der Hadith von Abu Muawiya das Handtuch nicht erwähnt.'},
'https://sunnah.com/muslim:317c':{en:'Abu Bakr ibn Abi Shayba narrated to us. Abdullah ibn Idris narrated to us, from al-Amash, from Salim, from Kurayb, from Ibn Abbas, from Maymuna, that the Prophet (peace be upon him) was brought a towel but did not use it. Instead, he began saying this with the water, meaning that he shook it off.',de:'Abu Bakr ibn Abi Shayba überlieferte uns. Abdullah ibn Idris überlieferte uns, von al-Amash, von Salim, von Kurayb, von Ibn Abbas, von Maymuna, dass dem Propheten (Friede sei auf ihm) ein Handtuch gebracht wurde, er es aber nicht benutzte. Stattdessen begann er dies mit dem Wasser zu tun, gemeint ist, dass er es abschüttelte.'},
'https://sunnah.com/muslim:318':{en:'Muhammad ibn al-Muthanna al-Anazi narrated to us. Abu Asim narrated to me, from Hanzala ibn Abi Sufyan, from al-Qasim, from Aisha, who said: When the Messenger of Allah (peace be upon him) performed ghusl from major ritual impurity, he called for something like a milk vessel. He took water in his cupped hand, began with the right side of his head, then the left, and then took water in both hands and poured it over his head.',de:'Muhammad ibn al-Muthanna al-Anazi überlieferte uns. Abu Asim überlieferte mir, von Hanzala ibn Abi Sufyan, von al-Qasim, von Aisha, die sagte: Wenn der Gesandte Allahs (Friede sei auf ihm) wegen großer ritueller Unreinheit Ghusl verrichtete, ließ er etwas bringen, das einem Milchgefäß glich. Er nahm Wasser in seine hohle Hand, begann mit der rechten Seite seines Kopfes, dann mit der linken, nahm danach Wasser in beide Hände und goss es über seinen Kopf.'},
'https://sunnah.com/muslim:319a':{en:'Yahya ibn Yahya narrated to us. He said: I read to Malik, from Ibn Shihab, from Urwa ibn al-Zubayr, from Aisha, that the Messenger of Allah (peace be upon him) used to perform ghusl from major ritual impurity from a vessel that was al-Faraq.',de:'Yahya ibn Yahya überlieferte uns. Er sagte: Ich las Malik vor, von Ibn Shihab, von Urwa ibn al-Zubayr, von Aisha, dass der Gesandte Allahs (Friede sei auf ihm) wegen großer ritueller Unreinheit aus einem Gefäß Ghusl zu verrichten pflegte, das al-Faraq war.'},
'https://sunnah.com/muslim:319b':{en:'Qutayba ibn Said narrated to us. Layth narrated to us. Ibn Rumh also narrated to us: al-Layth informed us. Qutayba ibn Said, Abu Bakr ibn Abi Shayba, Amr al-Naqid, and Zuhayr ibn Harb also narrated to us. They said: Sufyan narrated to us. Both narrated from al-Zuhri, from Urwa, from Aisha, who said: The Messenger of Allah (peace be upon him) used to perform ghusl in a vessel that was al-Faraq, and I and he used to perform ghusl from the same vessel. In Sufyan\'s hadith it says: from one vessel. Qutayba said: Sufyan said: al-Faraq is three sa of measure.',de:'Qutayba ibn Said überlieferte uns. Layth überlieferte uns. Auch Ibn Rumh überlieferte uns: al-Layth berichtete uns. Auch Qutayba ibn Said, Abu Bakr ibn Abi Shayba, Amr al-Naqid und Zuhayr ibn Harb überlieferten uns. Sie sagten: Sufyan überlieferte uns. Beide überlieferten von al-Zuhri, von Urwa, von Aisha, die sagte: Der Gesandte Allahs (Friede sei auf ihm) pflegte in einem Gefäß Ghusl zu verrichten, das al-Faraq war, und ich und er pflegten aus demselben Gefäß Ghusl zu verrichten. In Sufyans Hadith heißt es: aus einem Gefäß. Qutayba sagte: Sufyan sagte: al-Faraq beträgt drei Sa Maß.'},
'https://sunnah.com/muslim:320':{en:'Ubaydullah ibn Muadh al-Anbari narrated to me. He said: My father narrated to us. Shuba narrated to us, from Abu Bakr ibn Hafs, from Abu Salama ibn Abd al-Rahman, who said: I entered upon Aisha with her foster-brother. He asked her about the Prophet\'s (peace be upon him) ghusl from major ritual impurity. She called for a vessel holding about one sa, performed ghusl, with a screen between us and her, and poured water over her head three times. He said: The wives of the Prophet (peace be upon him) used to cut their hair until it was like a الوفرة hairstyle.',de:'Ubaydullah ibn Muadh al-Anbari überlieferte mir. Er sagte: Mein Vater überlieferte uns. Shuba überlieferte uns, von Abu Bakr ibn Hafs, von Abu Salama ibn Abd al-Rahman, der sagte: Ich trat mit ihrem Milchbruder bei Aisha ein. Er fragte sie über den Ghusl des Propheten (Friede sei auf ihm) wegen großer ritueller Unreinheit. Sie ließ ein Gefäß bringen, das ungefähr ein Sa fasste, verrichtete Ghusl, während sich zwischen uns und ihr ein Vorhang befand, und goss dreimal Wasser über ihren Kopf. Er sagte: Die Ehefrauen des Propheten (Friede sei auf ihm) pflegten ihr Haar zu kürzen, bis es wie eine Wufra-Frisur war.'}
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,...tr[r.url]}));
if(out.length!==7) throw new Error(`expected 7 got ${out.length}`);
fs.writeFileSync('data/hadith-words-translations/codex-batch-222-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-222-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
