import fs from 'fs';
const rows:any[]=JSON.parse(fs.readFileSync('data/hadith-words-translations/codex-batch-191.json','utf8'));
const tr:Record<string,[string,string]>={
'https://sunnah.com/muslim:198a':[ `Yunus ibn Abd al-A'la narrated to me. Abdullah ibn Wahb informed us. He said: Malik ibn Anas informed me, from Ibn Shihab, from Abu Salama ibn Abd al-Rahman, from Abu Hurayra, that the Messenger of Allah (peace be upon him) said: Every prophet has a supplication that he makes, and I want to reserve my supplication as intercession for my community on the Day of Resurrection.`, `Yunus ibn Abd al-A'la überlieferte mir. Abd Allah ibn Wahb berichtete uns. Er sagte: Malik ibn Anas berichtete mir, von Ibn Schihab, von Abu Salama ibn Abd ar-Rahman, von Abu Hurayra, dass der Gesandte Allahs (Friede sei auf ihm) sagte: Jeder Prophet hat ein Bittgebet, das er spricht, und ich möchte mein Bittgebet als Fürsprache für meine Gemeinschaft am Tag der Auferstehung aufbewahren.`],
'https://sunnah.com/muslim:198b':[ `Zuhayr ibn Harb and Abd ibn Humayd narrated to me. Zuhayr said: Yaqub ibn Ibrahim narrated to us. Ibn Shihab's nephew narrated to us, from his uncle. Abu Salama ibn Abd al-Rahman informed me that Abu Hurayra said: The Messenger of Allah (peace be upon him) said: Every prophet has a supplication, and I want, if Allah wills, to reserve my supplication as intercession for my community on the Day of Resurrection.`, `Zuhayr ibn Harb und Abd ibn Humayd überlieferten mir. Zuhayr sagte: Yaqub ibn Ibrahim überlieferte uns. Der Neffe von Ibn Schihab überlieferte uns, von seinem Onkel. Abu Salama ibn Abd ar-Rahman berichtete mir, dass Abu Hurayra sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Jeder Prophet hat ein Bittgebet, und ich möchte, wenn Allah will, mein Bittgebet als Fürsprache für meine Gemeinschaft am Tag der Auferstehung aufbewahren.`],
'https://sunnah.com/muslim:198c':[ `Zuhayr ibn Harb and Abd ibn Humayd narrated to me. Zuhayr said: Yaqub ibn Ibrahim narrated to us. Ibn Shihab's nephew narrated to us, from his uncle. Amr ibn Abi Sufyan ibn Asid ibn Jariya al-Thaqafi narrated to me something similar, from Abu Hurayra, from the Messenger of Allah (peace be upon him).`, `Zuhayr ibn Harb und Abd ibn Humayd überlieferten mir. Zuhayr sagte: Yaqub ibn Ibrahim überlieferte uns. Der Neffe von Ibn Schihab überlieferte uns, von seinem Onkel. Amr ibn Abi Sufyan ibn Asid ibn Dschariya ath-Thaqafi überlieferte mir etwas Ähnliches, von Abu Hurayra, vom Gesandten Allahs (Friede sei auf ihm).`],
'https://sunnah.com/muslim:198d':[ `Harmala ibn Yahya narrated to me. Ibn Wahb informed us. Yunus informed me, from Ibn Shihab, that Amr ibn Abi Sufyan ibn Asid ibn Jariya al-Thaqafi informed him that Abu Hurayra said to Ka'b al-Ahbar: The Prophet of Allah (peace be upon him) said: Every prophet has a supplication that he makes, and I want, if Allah wills, to reserve my supplication as intercession for my community on the Day of Resurrection. Ka'b said to Abu Hurayra: Did you hear this from the Messenger of Allah (peace be upon him)? Abu Hurayra said: Yes.`, `Harmala ibn Yahya überlieferte mir. Ibn Wahb berichtete uns. Yunus berichtete mir, von Ibn Schihab, dass Amr ibn Abi Sufyan ibn Asid ibn Dschariya ath-Thaqafi ihm berichtete, dass Abu Hurayra zu Ka'b al-Ahbar sagte: Der Prophet Allahs (Friede sei auf ihm) sagte: Jeder Prophet hat ein Bittgebet, das er spricht, und ich möchte, wenn Allah will, mein Bittgebet als Fürsprache für meine Gemeinschaft am Tag der Auferstehung aufbewahren. Ka'b sagte zu Abu Hurayra: Hast du dies vom Gesandten Allahs (Friede sei auf ihm) gehört? Abu Hurayra sagte: Ja.`],
'https://sunnah.com/muslim:199a':[ `Abu Bakr ibn Abi Shayba and Abu Kurayb narrated to us, and this is Abu Kurayb's wording. They said: Abu Muawiya narrated to us, from al-A'mash, from Abu Salih, from Abu Hurayra, who said: The Messenger of Allah (peace be upon him) said: Every prophet has an answered supplication. Every prophet hastened his supplication, but I have reserved my supplication as intercession for my community on the Day of Resurrection. If Allah wills, it will reach whoever of my community dies without associating anything with Allah.`, `Abu Bakr ibn Abi Schayba und Abu Kuraib überlieferten uns, und dies ist der Wortlaut von Abu Kuraib. Sie sagten: Abu Mu'awiya überlieferte uns, von al-A'masch, von Abu Salih, von Abu Hurayra, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Jeder Prophet hat ein erhörtes Bittgebet. Jeder Prophet beeilte sich mit seinem Bittgebet, doch ich habe mein Bittgebet als Fürsprache für meine Gemeinschaft am Tag der Auferstehung aufbewahrt. Wenn Allah will, wird es jeden aus meiner Gemeinschaft erreichen, der stirbt, ohne Allah irgendetwas beizugesellen.`],
'https://sunnah.com/muslim:199b':[ `Qutayba ibn Sa'id narrated to us. Jarir narrated to us, from Imara, meaning Ibn al-Qa'qa', from Abu Zur'a, from Abu Hurayra, who said: The Messenger of Allah (peace be upon him) said: Every prophet has an answered supplication with which he calls, and it is answered and granted to him. I have reserved my supplication as intercession for my community on the Day of Resurrection.`, `Qutayba ibn Sa'id überlieferte uns. Jarir überlieferte uns, von Imara, das heißt Ibn al-Qa'qa', von Abu Zur'a, von Abu Hurayra, der sagte: Der Gesandte Allahs (Friede sei auf ihm) sagte: Jeder Prophet hat ein erhörtes Bittgebet, mit dem er bittet, und es wird für ihn erhört und ihm gewährt. Ich habe mein Bittgebet als Fürsprache für meine Gemeinschaft am Tag der Auferstehung aufbewahrt.`],
'https://sunnah.com/muslim:199c':[ `Ubayd Allah ibn Muadh al-Anbari narrated to us. My father narrated to us. Shu'ba narrated to us, from Muhammad, meaning Ibn Ziyad. He said: I heard Abu Hurayra say: The Messenger of Allah (peace be upon him) said: Every prophet made a supplication for his community, and it was answered for him. I want, if Allah wills, to delay my supplication as intercession for my community on the Day of Resurrection.`, `Ubayd Allah ibn Mu'adh al-Anbari überlieferte uns. Mein Vater überlieferte uns. Schu'ba überlieferte uns, von Muhammad, das heißt Ibn Ziyad. Er sagte: Ich hörte Abu Hurayra sagen: Der Gesandte Allahs (Friede sei auf ihm) sagte: Jeder Prophet sprach ein Bittgebet für seine Gemeinschaft, und es wurde für ihn erhört. Ich möchte, wenn Allah will, mein Bittgebet als Fürsprache für meine Gemeinschaft am Tag der Auferstehung aufschieben.`]
};
const out=rows.filter(r=>tr[r.url]).map(r=>({...r,en:tr[r.url][0],de:tr[r.url][1]}));
fs.writeFileSync('data/hadith-words-translations/codex-batch-191-part.json',JSON.stringify(out,null,2));
fs.writeFileSync('data/hadith-words-translations/codex-out-191-part.json',JSON.stringify(out,null,2));
console.log(`wrote ${out.length} staged translations`);
