-- Phase 2 seed: approved scholars (plan 3b) and the 12 Hard questions topics (titles and questions only).

insert into public.scholars (id, name_ar, name_en, name_de, website, sort) values
  ('ibn-baz', 'عبد العزيز بن باز', 'Shaykh Abdul-Aziz ibn Baz', 'Scheich Abdul-Aziz ibn Baz', 'https://binbaz.org.sa', 1),
  ('ibn-uthaymeen', 'محمد بن صالح العثيمين', 'Shaykh Muhammad ibn Salih al-Uthaymeen', 'Scheich Muhammad ibn Salih al-Uthaymeen', 'https://binothaimeen.net', 2),
  ('al-albani', 'محمد ناصر الدين الألباني', 'Shaykh Muhammad Nasir al-Din al-Albani', 'Scheich Muhammad Nasir al-Din al-Albani', 'https://al-albany.com', 3),
  ('al-fawzan', 'صالح الفوزان', 'Shaykh Salih al-Fawzan', 'Scheich Salih al-Fawzan', 'https://al-fuzan.com', 4),
  ('al-abbad', 'عبد المحسن العباد', 'Shaykh Abdul-Muhsin al-Abbad', 'Scheich Abdul-Muhsin al-Abbad', 'https://al-abbaad.com', 5),
  ('al-badr', 'عبد الرزاق البدر', 'Shaykh Abdur-Razzaq al-Badr', 'Scheich Abdur-Razzaq al-Badr', 'https://al-badr.net', 6),
  ('al-madkhali', 'ربيع المدخلي', 'Shaykh Rabee al-Madkhali', 'Scheich Rabee al-Madkhali', 'https://rabee.net', 7),
  ('al-wadii', 'مقبل بن هادي الوادعي', 'Shaykh Muqbil ibn Hadi al-Wadi''i', 'Scheich Muqbil ibn Hadi al-Wadi''i', 'https://muqbel.net', 8),
  ('an-najmi', 'أحمد النجمي', 'Shaykh Ahmad an-Najmi', 'Scheich Ahmad an-Najmi', 'https://alnajmi.net', 9),
  ('ar-ruhayli', 'سليمان الرحيلي', 'Shaykh Sulayman ar-Ruhayli', 'Scheich Sulayman ar-Ruhayli', 'https://sualruhaily.com', 10),
  ('al-usaymi', 'صالح العصيمي', 'Shaykh Salih al-Usaymi', 'Scheich Salih al-Usaymi', 'https://j-eman.net', 11),
  ('al-ghudayyan', 'عبد الله الغديان', 'Shaykh Abdullah al-Ghudayyan', 'Scheich Abdullah al-Ghudayyan', 'https://algodayan.com', 12),
  ('al-barrak', 'عبد الرحمن البراك', 'Shaykh Abdur-Rahman al-Barrak', 'Scheich Abdur-Rahman al-Barrak', 'https://sh-albarrak.com', 13),
  ('al-ash-shaykh', 'صالح آل الشيخ', 'Shaykh Salih Al al-Shaykh', 'Scheich Salih Al al-Shaykh', 'https://saleh.af.org.sa', 14),
  ('al-ajmi', 'دغش العجمي', 'Shaykh Dagash al-Ajmi', 'Scheich Dagash al-Ajmi', 'https://kalelm.com', 15),
  ('raslan', 'محمد سعيد رسلان', 'Shaykh Muhammad Sa''id Raslan', 'Scheich Muhammad Sa''id Raslan', 'https://rslan.com', 16),
  ('al-anizi', 'عزيز بن فرحان العنزي', 'Shaykh Aziz ibn Farhan al-Anizi', 'Scheich Aziz ibn Farhan al-Anizi', 'https://azizfarhan.com', 17),
  ('ash-shuwayr', 'الشويعر', 'Shaykh ash-Shuwayr', 'Scheich ash-Shuwayr', 'https://shuwaier.com', 18),
  ('al-hajiri', 'محمد رمزان الهاجري', 'Shaykh Muhammad Ramzan al-Hajiri', 'Scheich Muhammad Ramzan al-Hajiri', 'https://mohammed-ramzan.com', 19);

insert into public.topics (id, category, sort, popular_rank) values
  ('purpose', 'belief', 1, 1),
  ('who-created', 'belief', 2, null),
  ('suffering', 'belief', 3, 3),
  ('doubt', 'belief', 4, null),
  ('faith-reason', 'science', 5, null),
  ('evolution', 'science', 6, null),
  ('quran-preserved', 'preservation', 7, 2),
  ('hadith-late', 'preservation', 8, null),
  ('women-spiritual', 'women', 9, null),
  ('inheritance', 'women', 10, null),
  ('never-heard', 'history', 11, null),
  ('sword', 'history', 12, 4);

insert into public.topic_texts (topic_id, lang, title, question) values
  ('purpose', 'ar', 'لماذا أنا هنا؟', 'ما الغاية من الحياة في الإسلام؟'),
  ('purpose', 'en', 'Why am I here?', 'What is the purpose of life in Islam?'),
  ('purpose', 'de', 'Warum bin ich hier?', 'Was ist der Sinn des Lebens im Islam?'),
  ('who-created', 'ar', 'من خلق الله؟', 'إذا كان لكل شيء خالق، فمن خلق الله؟'),
  ('who-created', 'en', 'Who made God?', 'If everything has a creator, who created God?'),
  ('who-created', 'de', 'Wer hat Gott erschaffen?', 'Wenn alles einen Schöpfer hat, wer hat dann Gott erschaffen?'),
  ('suffering', 'ar', 'لماذا يوجد الألم؟', 'إذا كان الله رحيمًا، فلماذا يوجد الألم والمعاناة؟'),
  ('suffering', 'en', 'Why is there suffering?', 'If God is good, why is there suffering?'),
  ('suffering', 'de', 'Warum gibt es Leid?', 'Wenn Gott gut ist, warum gibt es dann Leid?'),
  ('doubt', 'ar', 'الشك والإيمان', 'عندي شكوك. هل هذا يجعلني مسلمًا سيئًا؟'),
  ('doubt', 'en', 'Doubt and faith', 'I have doubts. Does that make me a bad Muslim?'),
  ('doubt', 'de', 'Zweifel und Glaube', 'Ich habe Zweifel. Bin ich deshalb ein schlechter Muslim?'),
  ('faith-reason', 'ar', 'الإيمان والعقل', 'هل يطلب الإسلام منا أن نؤمن إيمانًا أعمى؟'),
  ('faith-reason', 'en', 'Faith and reason', 'Does Islam ask us to believe blindly?'),
  ('faith-reason', 'de', 'Glaube und Vernunft', 'Verlangt der Islam, blind zu glauben?'),
  ('evolution', 'ar', 'التطور وآدم', 'ماذا يقول الإسلام عن التطور وخلق آدم؟'),
  ('evolution', 'en', 'Evolution and Adam', 'What does Islam say about evolution and the creation of Adam?'),
  ('evolution', 'de', 'Evolution und Adam', 'Was sagt der Islam über Evolution und die Erschaffung Adams?'),
  ('quran-preserved', 'ar', 'هل حُفظ القرآن؟', 'كيف نعرف أن القرآن لم يُحرَّف؟'),
  ('quran-preserved', 'en', 'Was the Quran preserved?', 'How do we know the Quran was not changed?'),
  ('quran-preserved', 'de', 'Wurde der Koran bewahrt?', 'Woher wissen wir, dass der Koran nicht verändert wurde?'),
  ('hadith-late', 'ar', 'متى دُوّن الحديث؟', 'هل دُوّن الحديث بعد النبي بمئتي سنة فقط؟'),
  ('hadith-late', 'en', 'When were hadith written?', 'Were hadith only written down 200 years after the Prophet?'),
  ('hadith-late', 'de', 'Wann wurden Hadithe aufgeschrieben?', 'Wurden Hadithe erst 200 Jahre nach dem Propheten aufgeschrieben?'),
  ('women-spiritual', 'ar', 'الرجل والمرأة عند الله', 'هل الرجل والمرأة سواء عند الله في الإسلام؟'),
  ('women-spiritual', 'en', 'Men and women before God', 'Are men and women equal before God in Islam?'),
  ('women-spiritual', 'de', 'Mann und Frau vor Gott', 'Sind Männer und Frauen im Islam vor Gott gleich?'),
  ('inheritance', 'ar', 'الميراث', 'لماذا ترث المرأة أحيانًا أقل من الرجل؟'),
  ('inheritance', 'en', 'Inheritance', 'Why does a woman sometimes inherit less than a man?'),
  ('inheritance', 'de', 'Erbrecht', 'Warum erbt eine Frau manchmal weniger als ein Mann?'),
  ('never-heard', 'ar', 'من لم تبلغه الدعوة', 'ما حكم من لم يسمع بالإسلام؟'),
  ('never-heard', 'en', 'Those who never heard', 'What happens to people who never heard of Islam?'),
  ('never-heard', 'de', 'Wer nie davon hörte', 'Was geschieht mit Menschen, die nie vom Islam gehört haben?'),
  ('sword', 'ar', 'هل انتشر الإسلام بالسيف؟', 'هل انتشر الإسلام بالسيف؟'),
  ('sword', 'en', 'Spread by the sword?', 'Was Islam spread by the sword?'),
  ('sword', 'de', 'Mit dem Schwert verbreitet?', 'Wurde der Islam mit dem Schwert verbreitet?');

insert into public.topic_related (topic_id, related_id, sort) values
  ('purpose', 'who-created', 1),
  ('purpose', 'suffering', 2),
  ('who-created', 'purpose', 1),
  ('who-created', 'faith-reason', 2),
  ('suffering', 'purpose', 1),
  ('suffering', 'never-heard', 2),
  ('doubt', 'faith-reason', 1),
  ('doubt', 'who-created', 2),
  ('faith-reason', 'evolution', 1),
  ('faith-reason', 'doubt', 2),
  ('evolution', 'faith-reason', 1),
  ('evolution', 'who-created', 2),
  ('quran-preserved', 'hadith-late', 1),
  ('hadith-late', 'quran-preserved', 1),
  ('women-spiritual', 'inheritance', 1),
  ('inheritance', 'women-spiritual', 1),
  ('never-heard', 'suffering', 1),
  ('never-heard', 'sword', 2),
  ('sword', 'never-heard', 1);

